export interface ApplicationSyncOptions {
  /**
   * The size of the item batch to decrypt and render upon application load.
   */
  loadBatchSize: number

  sleepBetweenBatches: number

  /**
   * LAZY-DECRYPT / METADATA-RETENTION (feature flag, DEFAULT OFF).
   *
   * When enabled, cold-load decrypts each item to extract a small metadata projection and then
   * DISCARDS the bulky body (note `text`), keeping only a content-stripped ("lite") payload
   * resident in memory. Full content is re-hydrated on demand at the four consumer points
   * (editor open, markdown export, search-index build, revisions/links). This dramatically
   * lowers resident heap, enabling ~100k notes without the renderer OOM-crashing.
   *
   * With the flag OFF, behavior is byte-identical to today: no lite payloads are ever created
   * and the entire lazy-decrypt machinery is dormant.
   */
  lazyDecryptEnabled: boolean
}

export interface ApplicationDisplayOptions {
  allowNoteSelectionStatePersistence: boolean
  allowMultipleSelection: boolean
}

export interface ApplicationOptionalConfiguratioOptions {
  /**
   * URL for WebSocket providing permissions and roles information.
   */
  webSocketUrl?: string

  /**
   * Amount sync calls allowed per minute.
   */
  syncCallsThresholdPerMinute?: number

  /**
   * 3rd party library function for prompting U2F authenticator device registration
   *
   * @param registrationOptions - Registration options generated by the server
   * @returns authenticator device response
   */
  u2fAuthenticatorRegistrationPromptFunction?: (
    registrationOptions: Record<string, unknown>,
  ) => Promise<Record<string, unknown>>

  /**
   * 3rd party library function for prompting U2F authenticator device authentication
   *
   * @param registrationOptions - Registration options generated by the server
   * @returns authenticator device response
   */
  u2fAuthenticatorVerificationPromptFunction?: (
    authenticationOptions: Record<string, unknown>,
  ) => Promise<Record<string, unknown>>
}
