import type { LocaleResource } from './en'

// العربية (ar). Right-to-left language; the document `dir` is set to `rtl`
// when this locale is active (see Internationalization/i18n.ts).
const ar: LocaleResource = {
  common: {
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    confirm: 'تأكيد',
    close: 'إغلاق',
    edit: 'تحرير',
    rename: 'إعادة تسمية',
    duplicate: 'تكرار',
    remove: 'إزالة',
    open: 'فتح',
    create: 'إنشاء',
    add: 'إضافة',
    done: 'تم',
    back: 'رجوع',
    next: 'التالي',
    search: 'بحث',
    clear: 'مسح',
    loading: 'جارٍ التحميل…',
    copy: 'نسخ',
    copied: 'تم النسخ',
    download: 'تنزيل',
    upload: 'رفع',
    export: 'تصدير',
    import: 'استيراد',
    yes: 'نعم',
    no: 'لا',
    enabled: 'مُفعّل',
    disabled: 'مُعطّل',
    on: 'تشغيل',
    off: 'إيقاف',
    learnMore: 'معرفة المزيد',
    options: 'خيارات',
    settings: 'الإعدادات',
    preferences: 'التفضيلات',
    help: 'مساعدة',
    pin: 'تثبيت',
    unpin: 'إلغاء التثبيت',
    star: 'إضافة نجمة',
    unstar: 'إزالة النجمة',
    archive: 'أرشفة',
    unarchive: 'إلغاء الأرشفة',
    restore: 'استعادة',
    moveToTrash: 'نقل إلى المهملات',
    deletePermanently: 'حذف نهائي',
    protect: 'حماية',
    unprotect: 'إلغاء الحماية',
  },
  navigation: {
    notes: 'الملاحظات',
    allNotes: 'كل الملاحظات',
    files: 'الملفات',
    starred: 'المميّزة بنجمة',
    archived: 'المؤرشفة',
    trash: 'المهملات',
    untagged: 'بدون موضوع',
    conflicts: 'التعارضات',
    views: 'العروض',
    smartViews: 'العروض الذكية',
    tags: 'المواضيع',
    folders: 'المجلدات',
    favorites: 'المفضلة',
    dashboard: 'لوحة التحكم',
    createNewNote: 'إنشاء ملاحظة جديدة',
    createNewTag: 'إنشاء موضوع جديد',
    createNewFolder: 'إنشاء مجلد جديد',
    createNewSmartView: 'إنشاء عرض ذكي جديد',
    searchTags: 'البحث في المواضيع…',
    noTagsFound: 'لم يتم العثور على مواضيع. جرّب بحثًا آخر.',
    noSmartViewsFound: 'لم يتم العثور على عروض ذكية. جرّب بحثًا آخر.',
    collapseTagsPanel: 'طي لوحة المواضيع',
    expandTagsPanel: 'توسيع لوحة المواضيع',
    goToItemsList: 'الانتقال إلى قائمة العناصر',
    goToAccountMenu: 'الانتقال إلى قائمة الحساب',
    openPreferences: 'فتح التفضيلات',
  },
  account: {
    account: 'الحساب',
    signIn: 'تسجيل الدخول',
    signOut: 'تسجيل الخروج',
    signUp: 'إنشاء حساب',
    register: 'إنشاء حساب',
    you: 'أنت',
    encryptionOn: 'التشفير من طرف إلى طرف مُفعّل',
    notSignedIn: 'لم تقم بتسجيل الدخول',
    signInOrRegister: 'سجّل الدخول أو أنشئ حسابًا لمزامنة ملاحظاتك',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    confirmPassword: 'تأكيد كلمة المرور',
    syncNow: 'المزامنة الآن',
    lastSynced: 'آخر مزامنة',
    importData: 'استيراد',
    switchWorkspace: 'تبديل مساحة العمل',
    lockApplication: 'قفل التطبيق',
    helpAndFeedback: 'المساعدة والملاحظات',
  },
  preferences: {
    title: 'التفضيلات',
    general: 'عام',
    account: 'الحساب',
    security: 'الأمان',
    appearance: 'المظهر',
    backups: 'النسخ الاحتياطية',
    listed: 'Listed',
    plugins: 'الإضافات',
    whatsNew: 'ما الجديد',
    helpAndFeedback: 'المساعدة والملاحظات',
    language: 'اللغة',
    languageTitle: 'اللغة',
    languageDescription: 'اختر اللغة المستخدمة في واجهة التطبيق. يعود التطبيق إلى الإنجليزية لكل ما لم تتم ترجمته بعد.',
    languageChanged: 'تم تحديث اللغة',
    defaults: 'الإعدادات الافتراضية',
    tools: 'الأدوات',
    spellcheck: 'التدقيق الإملائي',
    labs: 'المختبرات',
  },
}

export default ar
