import type { LocaleResource } from './en'

// العربية (ar). Right-to-left language; the document `dir` is set to `rtl`
// when this locale is active (see Internationalization/i18n.ts).
const ar: LocaleResource = {
  common: {
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    confirm: 'تأكيد',
    close: 'إغلاق',
    edit: 'تحرير',
    rename: 'إعادة تسمية',
    duplicate: 'تكرار',
    remove: 'إزالة',
    open: 'فتح',
    create: 'إنشاء',
    add: 'إضافة',
    done: 'تم',
    back: 'رجوع',
    next: 'التالي',
    search: 'بحث',
    clear: 'مسح',
    loading: 'جارٍ التحميل…',
    copy: 'نسخ',
    copied: 'تم النسخ',
    download: 'تنزيل',
    upload: 'رفع',
    export: 'تصدير',
    import: 'استيراد',
    yes: 'نعم',
    no: 'لا',
    enabled: 'مُفعّل',
    disabled: 'مُعطّل',
    on: 'تشغيل',
    off: 'إيقاف',
    learnMore: 'معرفة المزيد',
    options: 'خيارات',
    settings: 'الإعدادات',
    preferences: 'التفضيلات',
    help: 'مساعدة',
    pin: 'تثبيت',
    unpin: 'إلغاء التثبيت',
    star: 'إضافة نجمة',
    unstar: 'إزالة النجمة',
    archive: 'أرشفة',
    unarchive: 'إلغاء الأرشفة',
    restore: 'استعادة',
    moveToTrash: 'نقل إلى المهملات',
    deletePermanently: 'حذف نهائي',
    protect: 'حماية',
    unprotect: 'إلغاء الحماية',
  },
  navigation: {
    notes: 'الملاحظات',
    allNotes: 'كل الملاحظات',
    files: 'الملفات',
    starred: 'المميّزة بنجمة',
    archived: 'المؤرشفة',
    trash: 'المهملات',
    untagged: 'بدون موضوع',
    conflicts: 'التعارضات',
    views: 'العروض',
    smartViews: 'العروض الذكية',
    tags: 'المواضيع',
    folders: 'المجلدات',
    favorites: 'المفضلة',
    dashboard: 'لوحة التحكم',
    createNewNote: 'إنشاء ملاحظة جديدة',
    createNewTag: 'إنشاء موضوع جديد',
    createNewFolder: 'إنشاء مجلد جديد',
    createNewSmartView: 'إنشاء عرض ذكي جديد',
    searchTags: 'البحث في المواضيع…',
    noTagsFound: 'لم يتم العثور على مواضيع. جرّب بحثًا آخر.',
    noSmartViewsFound: 'لم يتم العثور على عروض ذكية. جرّب بحثًا آخر.',
    collapseTagsPanel: 'طي لوحة المواضيع',
    expandTagsPanel: 'توسيع لوحة المواضيع',
    goToItemsList: 'الانتقال إلى قائمة العناصر',
    goToAccountMenu: 'الانتقال إلى قائمة الحساب',
    openPreferences: 'فتح التفضيلات',
  },
  account: {
    account: 'الحساب',
    signIn: 'تسجيل الدخول',
    signOut: 'تسجيل الخروج',
    signUp: 'إنشاء حساب',
    register: 'إنشاء حساب',
    you: 'أنت',
    encryptionOn: 'التشفير من طرف إلى طرف مُفعّل',
    notSignedIn: 'لم تقم بتسجيل الدخول',
    signInOrRegister: 'سجّل الدخول أو أنشئ حسابًا لمزامنة ملاحظاتك',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    confirmPassword: 'تأكيد كلمة المرور',
    syncNow: 'المزامنة الآن',
    lastSynced: 'آخر مزامنة',
    importData: 'استيراد',
    switchWorkspace: 'تبديل مساحة العمل',
    lockApplication: 'قفل التطبيق',
    helpAndFeedback: 'المساعدة والملاحظات',
  },
  preferences: {
    title: 'التفضيلات',
    general: 'عام',
    account: 'الحساب',
    security: 'الأمان',
    appearance: 'المظهر',
    backups: 'النسخ الاحتياطية',
    listed: 'Listed',
    plugins: 'الإضافات',
    whatsNew: 'ما الجديد',
    helpAndFeedback: 'المساعدة والملاحظات',
    language: 'اللغة',
    languageTitle: 'اللغة',
    languageDescription: 'اختر اللغة المستخدمة في واجهة التطبيق. يعود التطبيق إلى الإنجليزية لكل ما لم تتم ترجمته بعد.',
    languageChanged: 'تم تحديث اللغة',
    defaults: 'الإعدادات الافتراضية',
    tools: 'الأدوات',
    spellcheck: 'التدقيق الإملائي',
    labs: 'المختبرات',
  },
  editor: {
    cut: 'قص',
    copy: 'نسخ',
    paste: 'لصق',
    moreCutOptions: 'المزيد من خيارات القص',
    moreCopyOptions: 'المزيد من خيارات النسخ',
    morePasteOptions: 'المزيد من خيارات اللصق',
    tableOfContents: 'جدول المحتويات',
    selectAll: 'تحديد الكل',
    selectAllText: 'تحديد النص فقط',
    deselectAll: 'إلغاء تحديد الكل',
    search: 'بحث',
    undo: 'تراجع',
    redo: 'إعادة',
    undoHistory: 'سجل التراجع',
    redoHistory: 'سجل الإعادة',
    undoHistoryEmpty: 'سجل التراجع — لا شيء للتراجع عنه بعد',
    undoHistoryAvailable: 'سجل التراجع — ارجع عدة خطوات دفعة واحدة',
    redoHistoryEmpty: 'سجل الإعادة — لا شيء لإعادته',
    redoHistoryAvailable: 'سجل الإعادة — تقدّم عدة خطوات دفعة واحدة',
    formattingOptions: 'خيارات التنسيق',
    bold: 'عريض',
    italic: 'مائل',
    underline: 'تسطير',
    strikethrough: 'يتوسطه خط',
    inlineCode: 'رمز مضمّن',
    link: 'رابط',
    formatPainter: 'ناسخ التنسيق — انسخ التنسيق (انقر نقرًا مزدوجًا للإبقاء عليه مفعّلًا)',
    textStyle: 'نمط النص',
    textColor: 'لون النص',
    highlightColor: 'لون التمييز',
    typography: 'الطباعة — التوكيد والمخطط وتباعد الأحرف والكلمات',
    typographyTitle: 'الطباعة',
    fontSize: 'حجم الخط',
    chooseFontSize: 'اختيار حجم الخط',
    decreaseFontSize: 'تصغير حجم الخط',
    increaseFontSize: 'تكبير حجم الخط',
    fontFamily: 'عائلة الخط',
    customFontFamily: 'مخصّص',
    bulletedList: 'قائمة نقطية',
    numberedList: 'قائمة رقمية',
    checkList: 'قائمة مهام',
    quote: 'اقتباس',
    codeBlock: 'كتلة رمز',
    changeCase: 'تغيير حالة الأحرف',
    sortAndDedupeLines: 'فرز الأسطر وإزالة المكرر',
    alignment: 'المحاذاة',
    paragraphLayout: 'تخطيط الفقرة — تباعد الأسطر والفقرات والمسافة البادئة والتظليل',
    paragraphLayoutTitle: 'تخطيط الفقرة',
    listStyleMarker: 'نمط القائمة — علامة النقاط والأرقام',
    formattingMarks: 'علامات التنسيق',
    insert: 'إدراج',
    insertRowAbove: 'إدراج صف أعلى',
    insertRowBelow: 'إدراج صف أسفل',
    insertColumnLeft: 'إدراج عمود يسار',
    insertColumnRight: 'إدراج عمود يمين',
    deleteRow: 'حذف الصف',
    deleteColumn: 'حذف العمود',
    toggleRowHeader: 'تبديل رأس الصف',
    toggleColumnHeader: 'تبديل رأس العمود',
    deleteTable: 'حذف الجدول',
    rows: 'الصفوف',
    columns: 'الأعمدة',
    cells: 'الخلايا',
    table: 'الجدول',
    block: 'الكتلة',
    alignLeft: 'محاذاة لليسار',
    alignCenter: 'محاذاة للوسط',
    alignRight: 'محاذاة لليمين',
    editLink: 'تحرير الرابط',
    removeLink: 'إزالة الرابط',
    zoomIntoBlock: 'التكبير داخل الكتلة',
    blockStyle: 'نمط الكتلة',
    heading1: 'عنوان 1',
    heading2: 'عنوان 2',
    heading3: 'عنوان 3',
    normalText: 'نص عادي',
    moreFormatting: 'المزيد من التنسيق',
    createNoteFromSelectionTitle: 'إنشاء ملاحظة جديدة من التحديد',
    createNoteFromSelectionDescription:
      'ينشئ ملاحظة جديدة تحتوي على التحديد الحالي ويستبدل التحديد برابط إلى الملاحظة الجديدة.',
    dismissKeyboard: 'إخفاء لوحة المفاتيح',
    tableOfContentsLower: 'جدول المحتويات',
    noHeadingsFound: 'لم يتم العثور على عناوين',
    textFormattingOptions: 'خيارات تنسيق النص',
    highlight: 'تمييز',
    subscript: 'منخفض',
    superscript: 'مرتفع',
    clearFormatting: 'مسح التنسيق',
    normal: 'عادي',
    smartChecklist: 'قائمة مهام ذكية',
    restoreCompletedTasks: 'استعادة المهام المكتملة',
    completeAllChecklistItems: 'تعليم كل العناصر كمكتملة',
    completeAllChecklistItemsDescription: 'يعلّم كل عنصر في قائمة المهام التي يوجد بها المؤشر أو التحديد كمكتمل.',
    completeSelectedChecklistItems: 'تعليم العناصر المحددة كمكتملة',
    uncompleteSelectedChecklistItems: 'تعليم العناصر المحددة كغير مكتملة',
    noChecklistItemsSelected: 'ضع المؤشر في قائمة مهام أو حدّد عناصر لاستخدام هذا الإجراء.',
    leftAlign: 'محاذاة لليسار',
    centerAlign: 'محاذاة للوسط',
    rightAlign: 'محاذاة لليمين',
    justify: 'ضبط',
    searchBlocksPlaceholder: 'البحث في الوحدات…',
    searchBlocksToInsert: 'البحث عن وحدات لإدراجها',
    clearSearch: 'مسح البحث',
    noBlocksMatch: 'لا تطابق أي وحدات “{{query}}”',
    customizeToolbar: 'تخصيص شريط الأدوات',
    custom: 'مخصّص',
    clear: 'مسح',
    textColorSwatch: 'لون النص {{color}}',
    highlightColorSwatch: 'لون التمييز {{color}}',
    textShadingSwatch: 'تظليل النص {{color}}',
    noTextShading: 'بدون تظليل نص',
    uppercase: 'أحرف كبيرة',
    lowercase: 'أحرف صغيرة',
    camelCase: 'camelCase',
    sortLines: 'فرز الأسطر',
    deduplicate: 'إزالة التكرار',
    multiKeySort: 'فرز متعدد المفاتيح (الأول، الثاني، الثالث)…',
    sortAndDeduplicateLines: 'فرز الأسطر وإزالة التكرار',
    emphasisMarks: 'علامات التوكيد',
    outlineTextStroke: 'مخطط (حد النص)',
    letterSpacingKerning: 'تباعد الأحرف (التقنين)',
    wordSpacing: 'تباعد الكلمات',
    clearTypography: 'مسح الطباعة',
    spacingTight: 'ضيّق',
    spacingNormal: 'عادي',
    spacingWide: 'واسع',
    spacingWider: 'أوسع',
    spacingWidest: 'الأوسع',
    undoMultipleSteps: 'التراجع عن عدة خطوات',
    redoMultipleSteps: 'إعادة عدة خطوات',
    emptyHistoryPreview: '(فارغ)',
    pasteOptions: 'خيارات اللصق',
    copyOptions: 'خيارات النسخ',
    cutOptions: 'خيارات القص',
    pasteWithoutFormatting: 'لصق بدون تنسيق',
    pasteClean: 'لصق نظيف (إزالة الأحرف المخفية)',
    keepSourceFormatting: 'الإبقاء على تنسيق المصدر',
    matchDestinationFormatting: 'مطابقة تنسيق الوجهة',
    pasteAsImage: 'لصق كصورة',
    copyWithoutFormatting: 'نسخ بدون تنسيق',
    copyTextOnly: 'نسخ النص فقط',
    copyImagesOnly: 'نسخ الصور فقط',
    cutWithoutFormatting: 'قص بدون تنسيق',
    cutTextOnly: 'قص النص فقط',
    cutImagesOnly: 'قص الصور فقط',
    lineSpacing: 'تباعد الأسطر',
    spaceBefore: 'مسافة قبل',
    spaceAfter: 'مسافة بعد',
    indentation: 'المسافة البادئة',
    none: 'بلا',
    increaseLeft: 'زيادة من اليسار',
    decreaseLeft: 'إنقاص من اليسار',
    increaseRight: 'زيادة من اليمين',
    decreaseRight: 'إنقاص من اليمين',
    firstLine: 'السطر الأول',
    noFirstLine: 'بدون سطر أول',
    textShading: 'تظليل النص',
    listStyle: 'نمط القائمة',
    bulleted: 'نقطية',
    numbered: 'رقمية',
    bulletedListMarkers: 'نمط علامة النقاط',
    numberedListMarkers: 'نمط الترقيم',
    multilevelList: 'قائمة متعددة المستويات',
    multilevelListHint: 'اختر علامة لكل مستوى تداخل',
    multilevelLevelDefault: 'افتراضي',
    level: 'المستوى',
    apply: 'تطبيق',
    insertTable: 'إدراج جدول',
    insertImageFromUrl: 'إدراج صورة من رابط',
    sortLinesModalTitle: 'فرز الأسطر',
    blockPicker: 'منتقي الوحدات',
    blockParagraph: 'فقرة',
    blockCallout: 'مربع تنبيه',
    blockDivider: 'فاصل',
    blockCollapsible: 'قابل للطي',
    blockImageFromUrl: 'صورة من رابط',
    blockUploadFile: 'رفع ملف',
    blockDrawing: 'رسم',
    blockQrCode: 'رمز QR',
    blockTable: 'جدول',
    blockKanbanBoard: 'لوحة Kanban',
    blockCalendar: 'تقويم',
    blockTimeline: 'خط زمني',
    blockDataTable: 'جدول بيانات',
    blockSqlQuery: 'استعلام SQL',
    blockMermaidDiagram: 'مخطط Mermaid',
    blockGanttChart: 'مخطط Gantt',
    blockTimingDiagram: 'مخطط التوقيت',
    blockMusicStaff: 'مدرّج موسيقي',
    blockTradingViewChart: 'مخطط TradingView',
    blockStockChart: 'مخطط الأسهم',
    blockEmbed: 'تضمين',
    blockEmbedWebsite: 'تضمين موقع',
    blockTweet: 'تغريدة',
    blockEquation: 'معادلة',
    blockInlineEquation: 'معادلة مضمّنة',
    blockFootnote: 'حاشية سفلية',
    blockBookmark: 'إشارة مرجعية',
    blockGeneratePassword: 'إنشاء كلمة مرور آمنة تشفيريًا',
    blockClock: 'ساعة',
    blockCurrentDateTime: 'التاريخ والوقت الحالي',
    blockCurrentTime: 'الوقت الحالي',
    blockCurrentDate: 'التاريخ الحالي',
    blockCategoryBasic: 'أساسي',
    blockCategoryLists: 'القوائم',
    blockCategoryMedia: 'الوسائط',
    blockCategoryDataTables: 'البيانات والجداول',
    blockCategoryDiagramsCharts: 'المخططات والرسوم البيانية',
    blockCategoryFinance: 'المالية',
    blockCategoryEmbeds: 'التضمينات',
    blockCategoryAdvanced: 'متقدم',
  },
  files: {
    dropToUploadTooltip: 'أفلِت ملفاتك لرفعها وربطها بالملف الحالي',
    fileAriaLabel: 'ملف',
    fileReadonly: 'هذا الملف للقراءة فقط',
    fileInformationPanel: 'لوحة معلومات الملف',
    details: 'التفاصيل',
    selectedFilesCount: '{{count}} ملفات محددة',
    actionsPerformedOnSelected: 'ستُطبَّق الإجراءات على جميع الملفات المحددة.',
    cancelMultipleSelection: 'إلغاء التحديد المتعدد',
    fileOptions: 'خيارات الملف',
    fileContextMenu: 'قائمة سياق الملف',
    fileOptionsMenu: 'قائمة خيارات الملف',
    fileOptionsPanel: 'لوحة خيارات الملف',
    noFilesSelected: 'لم يتم تحديد أي ملفات',
    detachFromNote: 'فصل عن الملاحظة',
    attachToNote: 'إرفاق بالملاحظة',
    passwordProtect: 'حماية بكلمة مرور',
    downloadSeparately: 'تنزيل منفصل',
    downloadAsArchive: 'تنزيل كأرشيف',
    failedToDownloadArchive: 'تعذّر تنزيل الملفات كأرشيف',
    fileId: 'معرّف الملف:',
    size: 'الحجم:',
    totalSize: 'الحجم الإجمالي:',
    backedUpOn: 'تم النسخ الاحتياطي في {{date}}',
    configureFileBackups: 'تكوين النسخ الاحتياطي للملفات',
    fileNotBackedUpLocally: 'الملف غير منسوخ احتياطيًا محليًا',
    noFoldersYet: 'لا توجد مجلدات بعد',
    moveToFolder: 'نقل إلى مجلد',
    folderSelectionMenu: 'قائمة اختيار المجلد',
    noFolder: 'بدون مجلد',
    fileProtected: 'هذا الملف محمي.',
    authenticateToView: 'قم بالمصادقة لعرض هذا الملف.',
    addPasscodeToView: 'أضِف رمز مرور أو أنشئ حسابًا لطلب المصادقة عند عرض هذا الملف.',
    openAccountMenu: 'فتح قائمة الحساب',
    authenticate: 'مصادقة',
    viewFile: 'عرض الملف',
    loading: 'جارٍ التحميل...',
    fileCannotBePreviewed: 'لا يمكن معاينة هذا الملف.',
    errorLoadingFile: 'حدث خطأ أثناء تحميل الملف. حاول مرة أخرى، أو نزّل الملف وافتحه باستخدام تطبيق آخر.',
    tryAgain: 'حاول مرة أخرى',
    downloadToView: 'لعرض هذا الملف، نزّله وافتحه باستخدام تطبيق آخر.',
    fileInformation: 'معلومات الملف',
    type: 'النوع:',
    decryptedSize: 'الحجم بعد فك التشفير:',
    encryptedSize: 'الحجم المشفّر:',
    created: 'تاريخ الإنشاء:',
    lastModified: 'آخر تعديل:',
    done: 'تم',
    showFileOptions: 'إظهار خيارات الملف',
    showFileInfo: 'إظهار معلومات الملف',
    hideFileInfo: 'إخفاء معلومات الملف',
    showLinksSection: 'إظهار قسم الروابط',
    hideLinksSection: 'إخفاء قسم الروابط',
    submit: 'إرسال',
    renameFile: 'إعادة تسمية الملف',
    showLinkedItems: 'إظهار العناصر المرتبطة',
    closeModal: 'إغلاق النافذة',
    filePreviewModal: 'نافذة معاينة الملف',
    leftAlign: 'محاذاة لليسار',
    centerAlign: 'محاذاة للوسط',
    rightAlign: 'محاذاة لليمين',
    videoCannotBePreviewed: 'لا يمكن معاينة هذا الفيديو.',
    audioCannotBePlayed: 'لا يمكن تشغيل هذا الصوت.',
    downloadToListen: 'للاستماع إلى هذا الملف، نزّله وافتحه باستخدام تطبيق آخر.',
    externalAppOnly: 'لا يمكن معاينة هذا الملف إلا في تطبيق خارجي',
    openFilePreview: 'فتح معاينة الملف',
    loadingPdfViewer: 'جارٍ تحميل عارض PDF...',
    zoomOut: 'تصغير',
    zoomIn: 'تكبير',
    resetToActualSize: 'إعادة التعيين إلى الحجم الفعلي',
    resetTo100: 'إعادة التعيين إلى 100%',
    fitToScreen: 'ملاءمة الشاشة',
    unableToRenderPdf: 'تعذّر عرض ملف PDF هذا.',
    pdfCorruptedOrProtected: 'قد يكون الملف تالفًا أو محميًا بكلمة مرور.',
    loadingPdf: 'جارٍ تحميل PDF...',
    previousPage: 'الصفحة السابقة',
    pageNumber: 'رقم الصفحة',
    nextPage: 'الصفحة التالية',
    fitWidth: 'ملاءمة العرض',
    searchInDocumentShortcut: 'البحث في المستند (Ctrl/Cmd+F)',
    searchInDocument: 'البحث في المستند',
    copyLinkToPage: 'نسخ رابط إلى الصفحة {{page}}',
    copyLinkToThisPage: 'نسخ رابط إلى هذه الصفحة',
    copyLinkToSelectedText: 'نسخ رابط إلى النص المحدد',
    cancelOcr: 'إلغاء التعرّف الضوئي على الحروف',
    preparingOcr: 'جارٍ تحضير التعرّف الضوئي...',
    ocrProgress: 'التعرّف الضوئي على الصفحة {{current}} / {{total}} ({{percent}}%)',
    ocrCachedReRunTooltip:
      'تم استخراج النص بالفعل (مخزّن مؤقتًا). أعِد تشغيل التعرّف الضوئي في متصفحك (يبقى على جهازك).',
    ocrExtractedReRunTooltip: 'تم استخراج النص. أعِد تشغيل التعرّف الضوئي في متصفحك (يبقى على جهازك).',
    ocrExtractTooltip:
      'استخرج النص من الصفحات الممسوحة ضوئيًا باستخدام التعرّف الضوئي. يعمل في متصفحك؛ لا شيء يغادر جهازك (بطيء؛ يُنزّل بيانات اللغة).',
    extractTextWithOcrBrowser: 'استخراج النص بالتعرّف الضوئي في متصفحك',
    reRunOcrBrowser: 'إعادة تشغيل التعرّف الضوئي (المتصفح)',
    extractTextOcr: 'استخراج النص (التعرّف الضوئي)',
    serverOcrTooltip:
      'شغّل التعرّف الضوئي على الخادم. يؤدي هذا إلى إرسال صور صفحات ملف PDF هذا إلى الخادم ويترك التشفير من طرف إلى طرف — يمكن للخادم قراءة ذلك المحتوى. يُبقي التعرّف الضوئي في المتصفح كل شيء على جهازك.',
    runOcrOnServerAria: 'تشغيل التعرّف الضوئي على الخادم (يرسل صور الصفحات إلى الخادم؛ يترك التشفير من طرف إلى طرف)',
    runOcrOnServer: 'تشغيل التعرّف الضوئي على الخادم',
    copyAllExtractedText: 'نسخ كل النص المستخرَج',
    copyExtractedTextAria: 'نسخ النص المستخرَج',
    findInDocument: 'البحث في المستند',
    matchCase: 'مطابقة حالة الأحرف',
    noResults: 'لا نتائج',
    matchOfTotal: '{{current}} من {{total}}',
    previousMatch: 'المطابقة السابقة',
    nextMatch: 'المطابقة التالية',
    closeSearch: 'إغلاق البحث',
    serverOcrDisclosurePrefix: 'التعرّف الضوئي على الخادم متاح لحسابك. يرسل صور صفحات ملف PDF هذا إلى الخادم و',
    serverOcrDisclosureBold: 'يترك التشفير من طرف إلى طرف',
    serverOcrDisclosureSuffix:
      ' — يمكن للخادم (وأي شخص يتحكم فيه) قراءة ذلك المحتوى. يُبقي التعرّف الضوئي في المتصفح كل شيء على جهازك. الافتراضي هو التعرّف الضوئي في المتصفح.',
    ocrRunningServer:
      'التعرّف الضوئي على الخادم: يجري رفع صور صفحات ملف PDF هذا إلى الخادم، مما يترك التشفير من طرف إلى طرف — يمكن للخادم قراءة ذلك المحتوى. (يُبقي التعرّف الضوئي في المتصفح كل شيء على جهازك.)',
    ocrRunningBrowser:
      'يعمل التعرّف الضوئي في متصفحك على هذا الجهاز (تبقى ملفاتك مشفّرة من طرف إلى طرف). وهو بطيء ويُنزّل بيانات اللغة عند أول استخدام.',
    ocrDoneServer:
      'انتهى التعرّف الضوئي على الخادم. أُرسِلت صور الصفحات إلى الخادم (وقد ترك ذلك التشفير من طرف إلى طرف). تختلف الدقة حسب جودة المسح؛ أصبح النص المستخرَج الآن قابلًا للبحث والنسخ، وهو مخزّن مؤقتًا على هذا الجهاز.',
    ocrDoneBrowser:
      'انتهى التعرّف الضوئي. تختلف الدقة حسب جودة المسح؛ أصبح النص المستخرَج الآن قابلًا للبحث والنسخ، وهو مخزّن مؤقتًا على هذا الجهاز.',
    copiedExtractedText: 'تم نسخ النص المستخرَج',
    copiedLinkToPage: 'تم نسخ الرابط إلى الصفحة {{page}}',
    copiedLinkToSelectedText: 'تم نسخ الرابط إلى النص المحدد',
    serverOcrFailed: 'فشل التعرّف الضوئي على الخادم: {{message}}',
    ocrUnknownError: 'خطأ غير معروف',
    ocrFailed: 'فشل التعرّف الضوئي. ربما فشل تنزيل بيانات اللغة.',
  },
  notes: {
    notesAndFiles: 'الملاحظات والملفات',
    selectAllItems: 'تحديد كل العناصر',
    selectedCount: '{{count}} محدد',
    cancelMultipleSelection: 'إلغاء التحديد المتعدد',
    noFilesInFolder: 'لا توجد ملفات في هذا المجلد.',
    noItems: 'لا توجد عناصر.',
    loading: 'جارٍ التحميل...',
    uploadFileWithShortcut: 'رفع ملف {{shortcut}}',
    createNoteInTopicWithShortcut: 'إنشاء ملاحظة جديدة في الموضوع المحدد {{shortcut}}',
    dropFilesToUpload: 'أفلِت ملفاتك لرفعها وربطها بالموضوع "{{title}}"',
    noFilesYet: 'ليس لديك أي ملفات بعد',
    filesAttachedAppearHere: 'تظهر الملفات المرفقة بملاحظاتك هنا. يمكنك أيضًا رفع الملفات مباشرةً من هذه الصفحة.',
    uploadFiles: 'رفع الملفات',
    syncing: 'جارٍ المزامنة...',
    loadingItemsProgress: 'جارٍ تحميل {{current}}/{{total}} عنصر...',
    potentiallyOutOfSync: 'ربما غير متزامن',
    openDisplayOptionsMenu: 'فتح قائمة خيارات العرض',
    displayOptionsMenu: 'قائمة خيارات العرض',
    displayOptions: 'خيارات العرض',
    expandTopicsPanel: 'توسيع لوحة المواضيع',
    collapseNotesPanel: 'طي لوحة الملاحظات',
    addItem: 'إضافة عنصر',
    uploadFolder: 'رفع مجلد',
    takePhoto: 'التقاط صورة',
    recordVideo: 'تسجيل فيديو',
    searchPlaceholder: 'بحث...',
    notesListOptionsMenu: 'قائمة خيارات قائمة الملاحظات',
    preferencesFor: 'تفضيلات',
    global: 'عام',
    reset: 'إعادة تعيين',
    upgradeForPerTopicPreferences: 'قم بالترقية للحصول على تفضيلات لكل موضوع',
    perTopicPreferencesMessageWithDaily:
      'أنشئ سير عمل قوية وتخطيطات تنظيمية بفضل تفضيلات العرض لكل موضوع وتخطيط تقويم دفتر الملاحظات اليومي الجديد كليًا.',
    perTopicPreferencesMessage: 'أنشئ سير عمل قوية وتخطيطات تنظيمية بفضل تفضيلات العرض لكل موضوع.',
    sortBy: 'الفرز حسب',
    relevanceBestMatch: 'الصلة (أفضل تطابق)',
    dateModified: 'تاريخ التعديل',
    creationDate: 'تاريخ الإنشاء',
    title: 'العنوان',
    customDragToReorder: 'مخصّص (اسحب لإعادة الترتيب)',
    view: 'عرض',
    showNotePreview: 'إظهار معاينة الملاحظة',
    showDate: 'إظهار التاريخ',
    showTags: 'إظهار المواضيع',
    showIcon: 'إظهار الأيقونة',
    other: 'أخرى',
    showPinned: 'إظهار المثبّتة',
    showProtected: 'إظهار المحمية',
    showArchived: 'إظهار المؤرشفة',
    showTrashed: 'إظهار المحذوفة',
    dailyNotebook: 'دفتر الملاحظات اليومي',
    labs: 'Labs',
    dailyNotebookDescription: 'دوّن ملاحظات جديدة يوميًا بتخطيط قائم على التقويم',
    tableView: 'عرض الجدول',
    tableViewDescription: 'عرض الملاحظات والملفات في الموضوع الحالي بتخطيط جدولي',
    newNoteDefaults: 'الإعدادات الافتراضية للملاحظة الجديدة',
    noteType: 'نوع الملاحظة',
    selectDefaultNoteType: 'اختر نوع الملاحظة الافتراضي',
    titleFormat: 'تنسيق العنوان',
    selectTitleFormat: 'اختر تنسيق عنوان الملاحظة',
    customFormatPlaceholder: 'مثال: YYYY-MM-DD',
    preview: 'معاينة: ',
    useBracketsToEscape: '. استخدم ',
    toEscapeFormatting: ' لتجاوز التنسيق.',
    protected: 'محمية',
    modified: 'مُعدّلة',
    now: 'الآن',
    editingDisabled: 'التحرير مُعطّل',
    trashed: 'محذوفة',
    archived: 'مؤرشفة',
    files: 'الملفات',
    starred: 'مميّزة بنجمة',
    fileBackedUpLocally: 'الملف منسوخ احتياطيًا محليًا',
    conflictedCopy: 'نسخة متعارضة',
    allFiles: 'كل الملفات',
    noFolder: 'بدون مجلد',
    folderNamePlaceholder: 'اسم المجلد',
    createNewFolder: 'إنشاء مجلد جديد',
    newFolder: 'مجلد جديد',
    currentStreak: 'التتابع الحالي',
    dayWithCount_zero: 'يوم',
    dayWithCount_one: 'يوم',
    dayWithCount_two: 'يومان',
    dayWithCount_few: 'أيام',
    dayWithCount_many: 'يومًا',
    dayWithCount_other: 'يوم',
  },
  auth: {
    unableToComputePrivateUsername: 'تعذّر حساب اسم المستخدم الخاص.',
    advancedOptions: 'خيارات متقدمة',
    privateUsernameMode: 'وضع اسم المستخدم الخاص',
    username: 'اسم المستخدم',
    useStrictSignIn: 'استخدام تسجيل الدخول الصارم',
    useRecoveryCode: 'استخدام رمز الاسترداد',
    recoveryCode: 'رمز الاسترداد',
    deleteLocalDataTitle: 'حذف البيانات المحلية؟',
    noMergeWarning:
      'لقد اخترت عدم دمج بياناتك المحلية. إذا تابعت، فسيتم حذف ملاحظاتك ومواضيعك المحلية نهائيًا واستبدالها ببيانات من حسابك. لا يمكن التراجع عن هذا الإجراء.',
    noMergeConfirmQuestion: 'هل أنت متأكد أنك تريد المتابعة دون الدمج؟',
    deleteLocalDataAndContinue: 'حذف البيانات المحلية والمتابعة',
    passwordResetWarningPart1: 'نظرًا لأن ملاحظاتك مشفّرة باستخدام كلمة مرورك،',
    passwordResetWarningHighlight: 'لا يوفّر Standard Red Notes خيارًا لإعادة تعيين كلمة المرور',
    passwordResetWarningPart2: '. إذا نسيت كلمة مرورك، فستفقد الوصول إلى بياناتك نهائيًا.',
    confirmPassword: 'تأكيد كلمة المرور',
    creatingAccount: 'جارٍ إنشاء الحساب...',
    createAccountAndSignIn: 'إنشاء حساب وتسجيل الدخول',
    staySignedIn: 'إبقائي مسجّلاً للدخول',
    goBack: 'رجوع',
    humanVerification: 'التحقق البشري',
    confirmPasswordTitle: 'تأكيد كلمة المرور',
    createAccount: 'إنشاء حساب',
    workspaceNameOptional: 'اسم مساحة العمل (اختياري)',
    generalAccountMenuLabel: 'قائمة الحساب العامة',
    signedInAs: 'أنت مسجّل الدخول باسم:',
    syncing: 'جارٍ المزامنة...',
    lastSynced: 'آخر مزامنة:',
    offlineSignInPrompt:
      'أنت غير متصل. سجّل الدخول لمزامنة ملاحظاتك وتفضيلاتك عبر جميع أجهزتك وتفعيل التشفير من طرف إلى طرف.',
    offline: 'غير متصل',
    accountSettings: 'إعدادات الحساب',
    createFreeAccount: 'إنشاء حساب مجاني',
    documentation: 'التوثيق',
    keyboardShortcuts: 'اختصارات لوحة المفاتيح',
    commandPalette: 'لوحة الأوامر',
    signOutWorkspace: 'تسجيل الخروج من مساحة العمل',
    mergeLocalData: 'دمج البيانات المحلية ({{count}} ملاحظة وموضوع)',
    mergeLocalDataTooltip:
      'إذا لم يتم تحديده، فسيتم حذف ملاحظاتك ومواضيعك المحلية نهائيًا واستبدالها ببيانات من حسابك.',
    homeServerNotRunning: 'الخادم المنزلي غير مُشغّل. يُرجى فتح التفضيلات وعلامة تبويب الخادم المنزلي لتشغيله.',
    serverDefault: 'افتراضي',
    serverCustom: 'مخصّص',
    serverHomeServer: 'الخادم المنزلي',
    syncServer: 'خادم المزامنة',
    signingIn: 'جارٍ تسجيل الدخول...',
    syncUnreachable: 'تعذّر الوصول إلى المزامنة',
    syncUnreachableMessage: 'همم... يبدو أننا لا نستطيع مزامنة حسابك. السبب: {{reason}}',
    workspaceSwitcherMenuLabel: 'قائمة تبديل مساحة العمل',
    signOutAllWorkspacesConfirm: 'هل أنت متأكد أنك تريد تسجيل الخروج من جميع مساحات العمل على هذا الجهاز؟',
    signOutAll: 'تسجيل الخروج من الكل',
    addAnotherWorkspace: 'إضافة مساحة عمل أخرى',
    signOutAllWorkspaces: 'تسجيل الخروج من جميع مساحات العمل',
    deleteAccountTitle: 'حذف الحساب؟',
    deleteMyAccountForGood: 'حذف حسابي نهائيًا',
    dataNotBackedUp: 'البيانات غير منسوخة احتياطيًا',
    signInOrRegisterToSync: 'سجّل الدخول أو أنشئ حسابًا لمزامنة ملاحظاتك إلى أجهزتك الأخرى بالتشفير من طرف إلى طرف.',
    openAccountMenu: 'فتح قائمة الحساب',
    ignoreWarning: 'تجاهل التحذير',
    waitingForSecurityKey: 'في انتظار مفتاح الأمان...',
    authenticationSuccessful: 'تمت المصادقة بنجاح!',
    insertSecurityKeyPrompt: 'أدخِل مفتاح الأمان الخاص بجهازك، ثم اضغط الزر أدناه للمصادقة.',
    authenticate: 'مصادقة',
  },
  search: {
    placeholder: 'بحث...',
    protectedContents: 'المحتويات المحمية',
    archived: 'المؤرشفة',
    trashed: 'المحذوفة',
    aiUnavailable: 'إعادة الترتيب بالذكاء الاصطناعي غير متاحة أو لم تُرجِع أي نتيجة.',
    aiUnavailableTooltip: 'البحث السياقي بالذكاء الاصطناعي غير متاح.',
    aiTypeQueryFirst: 'اكتب استعلام بحث أولاً.',
    aiTooltip:
      'أعِد ترتيب أفضل النتائج حسب الصلة الدلالية باستخدام مزوّد الذكاء الاصطناعي الذي أعددته. ' +
      'يرسل عناوين تلك المرشحات ومقتطفات قصيرة منها، بالإضافة إلى استعلامك، إلى المزوّد.',
    aiSearchWithAi: 'البحث بالذكاء الاصطناعي',
    aiRanking: 'جارٍ الترتيب…',
    aiRankedByRelevance: 'مرتّب حسب صلة الذكاء الاصطناعي',
    aiPrivacyNotice:
      'يرسل عناوين ومقتطفات أفضل النتائج واستعلامك إلى مزوّد الذكاء الاصطناعي لديك. سيطّلع عليها مزوّدو السحابة — ' +
      'أما النموذج المحلي فيُبقيها على جهازك.',
    advancedFilters: 'عوامل تصفية البحث المتقدمة',
    filters: 'عوامل التصفية',
    noteTypeAny: 'أي نوع',
    noteTypePlainText: 'نص عادي',
    noteTypeRichText: 'نص منسّق',
    noteTypeSuper: 'Super',
    noteTypeMarkdown: 'Markdown',
    noteTypeCode: 'رمز',
    noteTypeTask: 'مهمة',
    noteTypeSpreadsheet: 'جدول بيانات',
    flagProtected: 'محمية',
    flagPinned: 'مثبّتة',
    flagArchived: 'مؤرشفة',
    flagStarred: 'مميّزة بنجمة',
    flagTrashed: 'محذوفة',
    topicsLabel: 'المواضيع (مفصولة بفواصل)',
    topicsPlaceholder: 'عمل، شخصي',
    noteTypeLabel: 'نوع الملاحظة',
    searchInLabel: 'البحث في',
    searchInTitleAndContent: 'العنوان والمحتوى',
    modifiedWithinLabel: 'عُدّلت خلال',
    datePreset: 'آخر {{label}}',
    createdAfterLabel: 'أُنشئت بعد',
    createdBeforeLabel: 'أُنشئت قبل',
    updatedAfterLabel: 'حُدّثت بعد',
    updatedBeforeLabel: 'حُدّثت قبل',
    statusLabel: 'الحالة',
    hasAttachments: 'تحتوي على مرفقات',
    caseSensitive: 'حساس لحالة الأحرف',
    clearAllFilters: 'مسح كل عوامل التصفية',
  },
  sharing: {
    vaultSelectionMenu: 'قائمة اختيار الخزنة',
    vaultOptionsMenu: 'قائمة خيارات الخزنة',
    vaultOptions: 'خيارات الخزنة',
    noVaultsFound: 'لم يتم العثور على خزائن',
    moveToVault: 'نقل إلى الخزنة',
    moveOutOfVault: 'نقل خارج {{name}}',
    vaultsFallbackName: 'خزائن',
    editVault: 'تحرير الخزنة',
    lockVault: 'قفل الخزنة',
    unlockVault: 'فتح الخزنة',
    openVaultSettings: 'فتح إعدادات الخزنة',
    selectionModeMultiple: 'متعدد',
    selectionModeOne: 'واحد',
    lastEditedBy: 'آخر تعديل بواسطة',
    sharedBy: 'تمت المشاركة بواسطة',
    sharedByContact: 'تمت المشاركة بواسطة جهة اتصال',
    vaultName: 'اسم الخزنة',
    sharedInVault: 'تمت المشاركة في الخزنة',
    copiedToClipboard: 'تم النسخ إلى الحافظة',
    failedToCopyToClipboard: 'تعذّر النسخ إلى الحافظة',
    copyExampleToClipboard: 'نسخ المثال إلى الحافظة',
    copiedExclaim: 'تم النسخ!',
    shareUnavailableTitle: 'المشاركة غير متاحة',
    shareUnavailableMessage: 'لم يعد رابط المشاركة هذا متاحًا.',
    invalidLinkTitle: 'رابط غير صالح',
    invalidLinkMessage: 'رابط المشاركة هذا غير صالح أو المفتاح مفقود.',
    selfDestructTitle: 'تدمّر هذه الملاحظة نفسها بعد العرض',
    oneTimeViewConsumed: 'أنت تقرأ رابط عرض لمرة واحدة. لقد تم استهلاكه الآن ولا يمكن إعادة فتحه',
    oneTimeViewExpiresClause_zero: '، وتنتهي صلاحيته بالكامل بعد {{count}} دقيقة من أول فتح',
    oneTimeViewExpiresClause_one: '، وتنتهي صلاحيته بالكامل بعد {{count}} دقيقة من أول فتح',
    oneTimeViewExpiresClause_two: '، وتنتهي صلاحيته بالكامل بعد {{count}} دقيقتين من أول فتح',
    oneTimeViewExpiresClause_few: '، وتنتهي صلاحيته بالكامل بعد {{count}} دقائق من أول فتح',
    oneTimeViewExpiresClause_many: '، وتنتهي صلاحيته بالكامل بعد {{count}} دقيقة من أول فتح',
    oneTimeViewExpiresClause_other: '، وتنتهي صلاحيته بالكامل بعد {{count}} دقيقة من أول فتح',
    linkExpires_zero: 'تنتهي صلاحية هذا الرابط بعد {{count}} دقيقة من أول فتح له.',
    linkExpires_one: 'تنتهي صلاحية هذا الرابط بعد {{count}} دقيقة من أول فتح له.',
    linkExpires_two: 'تنتهي صلاحية هذا الرابط بعد {{count}} دقيقتين من أول فتح له.',
    linkExpires_few: 'تنتهي صلاحية هذا الرابط بعد {{count}} دقائق من أول فتح له.',
    linkExpires_many: 'تنتهي صلاحية هذا الرابط بعد {{count}} دقيقة من أول فتح له.',
    linkExpires_other: 'تنتهي صلاحية هذا الرابط بعد {{count}} دقيقة من أول فتح له.',
    untitled: 'بدون عنوان',
    tagHasNoNotes: 'لا يحتوي هذا الموضوع على ملاحظات.',
    publicReadOnlyFooter: 'هذا رابط مشاركة عام للقراءة فقط. تم فك تشفير المحتوى في متصفحك.',
    confidentialWatermark: 'سري · {{datetime}}',
    contentHiddenTitle: 'المحتوى مخفي',
    contentHiddenMessage: 'أعِد التركيز إلى هذه النافذة لعرض المحتوى المشترك.',
  },
}

export default ar
