import type { LocaleResource } from './en'

const de: LocaleResource = {
  common: {
    save: 'Speichern',
    cancel: 'Abbrechen',
    delete: 'Löschen',
    confirm: 'Bestätigen',
    close: 'Schließen',
    edit: 'Bearbeiten',
    rename: 'Umbenennen',
    duplicate: 'Duplizieren',
    remove: 'Entfernen',
    open: 'Öffnen',
    create: 'Erstellen',
    add: 'Hinzufügen',
    done: 'Fertig',
    back: 'Zurück',
    next: 'Weiter',
    search: 'Suchen',
    clear: 'Löschen',
    loading: 'Wird geladen…',
    copy: 'Kopieren',
    copied: 'Kopiert',
    download: 'Herunterladen',
    upload: 'Hochladen',
    export: 'Exportieren',
    import: 'Importieren',
    yes: 'Ja',
    no: 'Nein',
    enabled: 'Aktiviert',
    disabled: 'Deaktiviert',
    on: 'Ein',
    off: 'Aus',
    learnMore: 'Mehr erfahren',
    options: 'Optionen',
    settings: 'Einstellungen',
    preferences: 'Einstellungen',
    help: 'Hilfe',
    pin: 'Anheften',
    unpin: 'Lösen',
    star: 'Markieren',
    unstar: 'Markierung entfernen',
    archive: 'Archivieren',
    unarchive: 'Aus Archiv holen',
    restore: 'Wiederherstellen',
    moveToTrash: 'In den Papierkorb verschieben',
    deletePermanently: 'Endgültig löschen',
    protect: 'Schützen',
    unprotect: 'Schutz aufheben',
  },
  navigation: {
    notes: 'Notizen',
    allNotes: 'Alle Notizen',
    files: 'Dateien',
    starred: 'Markiert',
    archived: 'Archiviert',
    trash: 'Papierkorb',
    untagged: 'Ohne Schlagwort',
    conflicts: 'Konflikte',
    views: 'Ansichten',
    smartViews: 'Intelligente Ansichten',
    tags: 'Schlagwörter',
    folders: 'Ordner',
    favorites: 'Favoriten',
    dashboard: 'Übersicht',
    createNewNote: 'Neue Notiz erstellen',
    createNewTag: 'Neues Schlagwort erstellen',
    createNewFolder: 'Neuen Ordner erstellen',
    createNewSmartView: 'Neue intelligente Ansicht erstellen',
    searchTags: 'Schlagwörter suchen…',
    noTagsFound: 'Keine Schlagwörter gefunden. Versuchen Sie eine andere Suche.',
    noSmartViewsFound: 'Keine intelligenten Ansichten gefunden. Versuchen Sie eine andere Suche.',
    collapseTagsPanel: 'Schlagwort-Bereich einklappen',
    expandTagsPanel: 'Schlagwort-Bereich ausklappen',
    goToItemsList: 'Zur Elementliste',
    goToAccountMenu: 'Zum Kontomenü',
    openPreferences: 'Einstellungen öffnen',
  },
  account: {
    account: 'Konto',
    signIn: 'Anmelden',
    signOut: 'Abmelden',
    signUp: 'Registrieren',
    register: 'Registrieren',
    you: 'Sie',
    encryptionOn: 'Ende-zu-Ende-Verschlüsselung aktiv',
    notSignedIn: 'Sie sind nicht angemeldet',
    signInOrRegister: 'Melden Sie sich an oder registrieren Sie sich, um Ihre Notizen zu synchronisieren',
    email: 'E-Mail',
    password: 'Passwort',
    confirmPassword: 'Passwort bestätigen',
    syncNow: 'Jetzt synchronisieren',
    lastSynced: 'Zuletzt synchronisiert',
    importData: 'Importieren',
    switchWorkspace: 'Arbeitsbereich wechseln',
    lockApplication: 'Anwendung sperren',
    helpAndFeedback: 'Hilfe & Feedback',
  },
  preferences: {
    title: 'Einstellungen',
    general: 'Allgemein',
    account: 'Konto',
    security: 'Sicherheit',
    appearance: 'Darstellung',
    backups: 'Sicherungen',
    listed: 'Listed',
    plugins: 'Erweiterungen',
    whatsNew: 'Neuigkeiten',
    helpAndFeedback: 'Hilfe & Feedback',
    language: 'Sprache',
    languageTitle: 'Sprache',
    languageDescription:
      'Wählen Sie die Sprache der Benutzeroberfläche. Für noch nicht übersetzte Inhalte wird Englisch verwendet.',
    languageChanged: 'Sprache aktualisiert',
    defaults: 'Standardwerte',
    tools: 'Werkzeuge',
    spellcheck: 'Rechtschreibprüfung',
    labs: 'Labs',
  },
}

export default de
