import type { LocaleResource } from './en'

const es: LocaleResource = {
  common: {
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    confirm: 'Confirmar',
    close: 'Cerrar',
    edit: 'Editar',
    rename: 'Renombrar',
    duplicate: 'Duplicar',
    remove: 'Quitar',
    open: 'Abrir',
    create: 'Crear',
    add: 'Añadir',
    done: 'Listo',
    back: 'Atrás',
    next: 'Siguiente',
    search: 'Buscar',
    clear: 'Borrar',
    loading: 'Cargando…',
    copy: 'Copiar',
    copied: 'Copiado',
    download: 'Descargar',
    upload: 'Subir',
    export: 'Exportar',
    import: 'Importar',
    yes: 'Sí',
    no: 'No',
    enabled: 'Activado',
    disabled: 'Desactivado',
    on: 'Encendido',
    off: 'Apagado',
    learnMore: 'Más información',
    options: 'Opciones',
    settings: 'Ajustes',
    preferences: 'Preferencias',
    help: 'Ayuda',
    pin: 'Fijar',
    unpin: 'Desfijar',
    star: 'Destacar',
    unstar: 'Quitar destacado',
    archive: 'Archivar',
    unarchive: 'Desarchivar',
    restore: 'Restaurar',
    moveToTrash: 'Mover a la papelera',
    deletePermanently: 'Eliminar permanentemente',
    protect: 'Proteger',
    unprotect: 'Desproteger',
  },
  navigation: {
    notes: 'Notas',
    allNotes: 'Todas las notas',
    files: 'Archivos',
    starred: 'Destacadas',
    archived: 'Archivadas',
    trash: 'Papelera',
    untagged: 'Sin etiqueta',
    conflicts: 'Conflictos',
    views: 'Vistas',
    smartViews: 'Vistas inteligentes',
    tags: 'Etiquetas',
    folders: 'Carpetas',
    favorites: 'Favoritos',
    dashboard: 'Panel',
    createNewNote: 'Crear una nota nueva',
    createNewTag: 'Crear una etiqueta nueva',
    createNewFolder: 'Crear una carpeta nueva',
    createNewSmartView: 'Crear una vista inteligente nueva',
    searchTags: 'Buscar etiquetas…',
    noTagsFound: 'No se encontraron etiquetas. Prueba con otra búsqueda.',
    noSmartViewsFound: 'No se encontraron vistas inteligentes. Prueba con otra búsqueda.',
    collapseTagsPanel: 'Contraer el panel de etiquetas',
    expandTagsPanel: 'Expandir el panel de etiquetas',
    goToItemsList: 'Ir a la lista de elementos',
    goToAccountMenu: 'Ir al menú de la cuenta',
    openPreferences: 'Abrir preferencias',
  },
  account: {
    account: 'Cuenta',
    signIn: 'Iniciar sesión',
    signOut: 'Cerrar sesión',
    signUp: 'Registrarse',
    register: 'Registrarse',
    you: 'Tú',
    encryptionOn: 'Cifrado de extremo a extremo activado',
    notSignedIn: 'No has iniciado sesión',
    signInOrRegister: 'Inicia sesión o regístrate para sincronizar tus notas',
    email: 'Correo electrónico',
    password: 'Contraseña',
    confirmPassword: 'Confirmar contraseña',
    syncNow: 'Sincronizar ahora',
    lastSynced: 'Última sincronización',
    importData: 'Importar',
    switchWorkspace: 'Cambiar de espacio de trabajo',
    lockApplication: 'Bloquear la aplicación',
    helpAndFeedback: 'Ayuda y comentarios',
  },
  preferences: {
    title: 'Preferencias',
    general: 'General',
    account: 'Cuenta',
    security: 'Seguridad',
    appearance: 'Apariencia',
    backups: 'Copias de seguridad',
    listed: 'Listed',
    plugins: 'Complementos',
    whatsNew: 'Novedades',
    helpAndFeedback: 'Ayuda y comentarios',
    language: 'Idioma',
    languageTitle: 'Idioma',
    languageDescription:
      'Elige el idioma utilizado en toda la interfaz de la aplicación. La aplicación usa el inglés para lo que aún no está traducido.',
    languageChanged: 'Idioma actualizado',
    defaults: 'Valores predeterminados',
    tools: 'Herramientas',
    spellcheck: 'Corrección ortográfica',
    labs: 'Laboratorios',
  },
}

export default es
