import type { LocaleResource } from './en'

const es: LocaleResource = {
  common: {
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    confirm: 'Confirmar',
    close: 'Cerrar',
    edit: 'Editar',
    rename: 'Renombrar',
    duplicate: 'Duplicar',
    remove: 'Quitar',
    open: 'Abrir',
    create: 'Crear',
    add: 'Añadir',
    done: 'Listo',
    back: 'Atrás',
    next: 'Siguiente',
    search: 'Buscar',
    clear: 'Borrar',
    loading: 'Cargando…',
    copy: 'Copiar',
    copied: 'Copiado',
    download: 'Descargar',
    upload: 'Subir',
    export: 'Exportar',
    import: 'Importar',
    yes: 'Sí',
    no: 'No',
    enabled: 'Activado',
    disabled: 'Desactivado',
    on: 'Encendido',
    off: 'Apagado',
    learnMore: 'Más información',
    options: 'Opciones',
    settings: 'Ajustes',
    preferences: 'Preferencias',
    help: 'Ayuda',
    pin: 'Fijar',
    unpin: 'Desfijar',
    star: 'Destacar',
    unstar: 'Quitar destacado',
    archive: 'Archivar',
    unarchive: 'Desarchivar',
    restore: 'Restaurar',
    moveToTrash: 'Mover a la papelera',
    deletePermanently: 'Eliminar permanentemente',
    protect: 'Proteger',
    unprotect: 'Desproteger',
  },
  navigation: {
    notes: 'Notas',
    allNotes: 'Todas las notas',
    files: 'Archivos',
    starred: 'Destacadas',
    archived: 'Archivadas',
    trash: 'Papelera',
    untagged: 'Sin tema',
    conflicts: 'Conflictos',
    views: 'Vistas',
    smartViews: 'Vistas inteligentes',
    tags: 'Temas',
    folders: 'Carpetas',
    favorites: 'Favoritos',
    dashboard: 'Panel',
    createNewNote: 'Crear una nota nueva',
    createNewTag: 'Crear un tema nuevo',
    createNewFolder: 'Crear una carpeta nueva',
    createNewSmartView: 'Crear una vista inteligente nueva',
    searchTags: 'Buscar temas…',
    noTagsFound: 'No se encontraron temas. Prueba con otra búsqueda.',
    noSmartViewsFound: 'No se encontraron vistas inteligentes. Prueba con otra búsqueda.',
    collapseTagsPanel: 'Contraer el panel de temas',
    expandTagsPanel: 'Expandir el panel de temas',
    goToItemsList: 'Ir a la lista de elementos',
    goToAccountMenu: 'Ir al menú de la cuenta',
    openPreferences: 'Abrir preferencias',
  },
  account: {
    account: 'Cuenta',
    signIn: 'Iniciar sesión',
    signOut: 'Cerrar sesión',
    signUp: 'Registrarse',
    register: 'Registrarse',
    you: 'Tú',
    encryptionOn: 'Cifrado de extremo a extremo activado',
    notSignedIn: 'No has iniciado sesión',
    signInOrRegister: 'Inicia sesión o regístrate para sincronizar tus notas',
    email: 'Correo electrónico',
    password: 'Contraseña',
    confirmPassword: 'Confirmar contraseña',
    syncNow: 'Sincronizar ahora',
    lastSynced: 'Última sincronización',
    importData: 'Importar',
    switchWorkspace: 'Cambiar de espacio de trabajo',
    lockApplication: 'Bloquear la aplicación',
    helpAndFeedback: 'Ayuda y comentarios',
  },
  preferences: {
    title: 'Preferencias',
    general: 'General',
    account: 'Cuenta',
    security: 'Seguridad',
    appearance: 'Apariencia',
    backups: 'Copias de seguridad',
    listed: 'Listed',
    plugins: 'Complementos',
    whatsNew: 'Novedades',
    helpAndFeedback: 'Ayuda y comentarios',
    language: 'Idioma',
    languageTitle: 'Idioma',
    languageDescription:
      'Elige el idioma utilizado en toda la interfaz de la aplicación. La aplicación usa el inglés para lo que aún no está traducido.',
    languageChanged: 'Idioma actualizado',
    defaults: 'Valores predeterminados',
    tools: 'Herramientas',
    spellcheck: 'Corrección ortográfica',
    labs: 'Laboratorios',
  },
  editor: {
    cut: 'Cortar',
    copy: 'Copiar',
    paste: 'Pegar',
    moreCutOptions: 'Más opciones de cortar',
    moreCopyOptions: 'Más opciones de copiar',
    morePasteOptions: 'Más opciones de pegar',
    tableOfContents: 'Tabla de contenidos',
    selectAll: 'Seleccionar todo',
    selectAllText: 'Seleccionar solo el texto',
    deselectAll: 'Deseleccionar todo',
    search: 'Buscar',
    undo: 'Deshacer',
    redo: 'Rehacer',
    undoHistory: 'Historial de deshacer',
    redoHistory: 'Historial de rehacer',
    undoHistoryEmpty: 'Historial de deshacer — nada que deshacer todavía',
    undoHistoryAvailable: 'Historial de deshacer — retrocede varios pasos a la vez',
    redoHistoryEmpty: 'Historial de rehacer — nada que rehacer',
    redoHistoryAvailable: 'Historial de rehacer — avanza varios pasos a la vez',
    formattingOptions: 'Opciones de formato',
    bold: 'Negrita',
    italic: 'Cursiva',
    underline: 'Subrayado',
    strikethrough: 'Tachado',
    inlineCode: 'Código en línea',
    link: 'Enlace',
    formatPainter: 'Copiar formato — copia el formato (doble clic para mantenerlo activo)',
    textStyle: 'Estilo de texto',
    textColor: 'Color del texto',
    highlightColor: 'Color de resaltado',
    typography: 'Tipografía — énfasis, contorno, espaciado de letras y palabras',
    typographyTitle: 'Tipografía',
    fontSize: 'Tamaño de fuente',
    chooseFontSize: 'Elegir el tamaño de fuente',
    decreaseFontSize: 'Reducir el tamaño de fuente',
    increaseFontSize: 'Aumentar el tamaño de fuente',
    fontFamily: 'Familia de fuentes',
    customFontFamily: 'Personalizada',
    bulletedList: 'Lista con viñetas',
    numberedList: 'Lista numerada',
    checkList: 'Lista de tareas',
    quote: 'Cita',
    codeBlock: 'Bloque de código',
    changeCase: 'Cambiar mayúsculas y minúsculas',
    sortAndDedupeLines: 'Ordenar y eliminar líneas duplicadas',
    alignment: 'Alineación',
    paragraphLayout: 'Diseño de párrafo — espaciado de líneas y párrafos, sangría, sombreado',
    paragraphLayoutTitle: 'Diseño de párrafo',
    listStyleMarker: 'Estilo de lista — marcador de viñeta y numeración',
    formattingMarks: 'Marcas de formato',
    insert: 'Insertar',
    insertRowAbove: 'Insertar fila arriba',
    insertRowBelow: 'Insertar fila abajo',
    insertColumnLeft: 'Insertar columna a la izquierda',
    insertColumnRight: 'Insertar columna a la derecha',
    deleteRow: 'Eliminar fila',
    deleteColumn: 'Eliminar columna',
    toggleRowHeader: 'Alternar encabezado de fila',
    toggleColumnHeader: 'Alternar encabezado de columna',
    deleteTable: 'Eliminar tabla',
    rows: 'Filas',
    columns: 'Columnas',
    cells: 'Celdas',
    table: 'Tabla',
    block: 'Bloque',
    alignLeft: 'Alinear a la izquierda',
    alignCenter: 'Centrar',
    alignRight: 'Alinear a la derecha',
    editLink: 'Editar enlace',
    removeLink: 'Quitar enlace',
    zoomIntoBlock: 'Ampliar el bloque',
    blockStyle: 'Estilo de bloque',
    heading1: 'Encabezado 1',
    heading2: 'Encabezado 2',
    heading3: 'Encabezado 3',
    normalText: 'Texto normal',
    moreFormatting: 'Más formato',
    createNoteFromSelectionTitle: 'Crear una nota nueva a partir de la selección',
    createNoteFromSelectionDescription:
      'Crea una nota nueva con la selección actual y reemplaza la selección con un enlace a la nueva nota.',
    dismissKeyboard: 'Ocultar el teclado',
    tableOfContentsLower: 'Tabla de contenidos',
    noHeadingsFound: 'No se encontraron encabezados',
    textFormattingOptions: 'Opciones de formato de texto',
    highlight: 'Resaltar',
    subscript: 'Subíndice',
    superscript: 'Superíndice',
    clearFormatting: 'Borrar formato',
    normal: 'Normal',
    smartChecklist: 'Lista de tareas inteligente',
    restoreCompletedTasks: 'Restaurar tareas completadas',
    leftAlign: 'Alinear a la izquierda',
    centerAlign: 'Centrar',
    rightAlign: 'Alinear a la derecha',
    justify: 'Justificar',
    searchBlocksPlaceholder: 'Buscar bloques…',
    searchBlocksToInsert: 'Buscar bloques para insertar',
    clearSearch: 'Borrar búsqueda',
    noBlocksMatch: 'Ningún bloque coincide con «{{query}}»',
    customizeToolbar: 'Personalizar la barra de herramientas',
    custom: 'Personalizado',
    clear: 'Borrar',
    textColorSwatch: 'Color del texto {{color}}',
    highlightColorSwatch: 'Color de resaltado {{color}}',
    textShadingSwatch: 'Sombreado del texto {{color}}',
    noTextShading: 'Sin sombreado del texto',
    uppercase: 'MAYÚSCULAS',
    lowercase: 'minúsculas',
    camelCase: 'camelCase',
    sortLines: 'Ordenar líneas',
    deduplicate: 'Eliminar duplicados',
    multiKeySort: 'Ordenación por varias claves (1.ª, 2.ª, 3.ª)…',
    sortAndDeduplicateLines: 'Ordenar y eliminar líneas duplicadas',
    emphasisMarks: 'Marcas de énfasis',
    outlineTextStroke: 'Contorno (trazo del texto)',
    letterSpacingKerning: 'Espaciado de letras (kerning)',
    wordSpacing: 'Espaciado de palabras',
    clearTypography: 'Borrar tipografía',
    spacingTight: 'Estrecho',
    spacingNormal: 'Normal',
    spacingWide: 'Amplio',
    spacingWider: 'Más amplio',
    spacingWidest: 'El más amplio',
    undoMultipleSteps: 'Deshacer varios pasos',
    redoMultipleSteps: 'Rehacer varios pasos',
    emptyHistoryPreview: '(vacío)',
    pasteOptions: 'Opciones de pegado',
    copyOptions: 'Opciones de copia',
    cutOptions: 'Opciones de corte',
    pasteWithoutFormatting: 'Pegar sin formato',
    pasteClean: 'Pegar limpio (eliminar caracteres ocultos)',
    keepSourceFormatting: 'Mantener el formato de origen',
    matchDestinationFormatting: 'Adaptar al formato de destino',
    pasteAsImage: 'Pegar como imagen',
    copyWithoutFormatting: 'Copiar sin formato',
    copyTextOnly: 'Copiar solo el texto',
    copyImagesOnly: 'Copiar solo las imágenes',
    cutWithoutFormatting: 'Cortar sin formato',
    cutTextOnly: 'Cortar solo el texto',
    cutImagesOnly: 'Cortar solo las imágenes',
    lineSpacing: 'Espaciado de líneas',
    spaceBefore: 'Espacio antes',
    spaceAfter: 'Espacio después',
    indentation: 'Sangría',
    none: 'Ninguna',
    increaseLeft: 'Aumentar a la izquierda',
    decreaseLeft: 'Reducir a la izquierda',
    increaseRight: 'Aumentar a la derecha',
    decreaseRight: 'Reducir a la derecha',
    firstLine: 'Primera línea',
    noFirstLine: 'Sin primera línea',
    textShading: 'Sombreado del texto',
    listStyle: 'Estilo de lista',
    bulleted: 'Con viñetas',
    numbered: 'Numerada',
    bulletedListMarkers: 'Estilo de marcador de viñeta',
    numberedListMarkers: 'Estilo de numeración',
    multilevelList: 'Lista multinivel',
    multilevelListHint: 'Elige un marcador por nivel de anidamiento',
    multilevelLevelDefault: 'Predeterminado',
    level: 'Nivel',
    apply: 'Aplicar',
    insertTable: 'Insertar tabla',
    insertImageFromUrl: 'Insertar imagen desde URL',
    sortLinesModalTitle: 'Ordenar líneas',
    blockPicker: 'Selector de bloques',
    blockParagraph: 'Párrafo',
    blockCallout: 'Nota destacada',
    blockDivider: 'Divisor',
    blockCollapsible: 'Contraíble',
    blockImageFromUrl: 'Imagen desde URL',
    blockUploadFile: 'Subir archivo',
    blockDrawing: 'Dibujo',
    blockQrCode: 'Código QR',
    blockTable: 'Tabla',
    blockKanbanBoard: 'Tablero Kanban',
    blockCalendar: 'Calendario',
    blockTimeline: 'Cronología',
    blockDataTable: 'Tabla de datos',
    blockSqlQuery: 'Consulta SQL',
    blockMermaidDiagram: 'Diagrama Mermaid',
    blockGanttChart: 'Diagrama de Gantt',
    blockTimingDiagram: 'Diagrama de tiempos',
    blockMusicStaff: 'Pentagrama musical',
    blockTradingViewChart: 'Gráfico de TradingView',
    blockStockChart: 'Gráfico de acciones',
    blockEmbed: 'Insertar contenido',
    blockEmbedWebsite: 'Insertar sitio web',
    blockTweet: 'Tweet',
    blockEquation: 'Ecuación',
    blockInlineEquation: 'Ecuación en línea',
    blockFootnote: 'Nota al pie',
    blockBookmark: 'Marcador',
    blockGeneratePassword: 'Generar una contraseña criptográficamente segura',
    blockClock: 'Reloj',
    blockCurrentDateTime: 'Fecha y hora actuales',
    blockCurrentTime: 'Hora actual',
    blockCurrentDate: 'Fecha actual',
    blockCategoryBasic: 'Básico',
    blockCategoryLists: 'Listas',
    blockCategoryMedia: 'Multimedia',
    blockCategoryDataTables: 'Datos y tablas',
    blockCategoryDiagramsCharts: 'Diagramas y gráficos',
    blockCategoryFinance: 'Finanzas',
    blockCategoryEmbeds: 'Contenido insertado',
    blockCategoryAdvanced: 'Avanzado',
  },
  files: {
    dropToUploadTooltip: 'Suelta los archivos para subirlos y vincularlos al archivo actual',
    fileAriaLabel: 'Archivo',
    fileReadonly: 'Este archivo es de solo lectura',
    fileInformationPanel: 'Panel de información del archivo',
    details: 'Detalles',
    selectedFilesCount: '{{count}} archivos seleccionados',
    actionsPerformedOnSelected: 'Las acciones se aplicarán a todos los archivos seleccionados.',
    cancelMultipleSelection: 'Cancelar la selección múltiple',
    fileOptions: 'Opciones del archivo',
    fileContextMenu: 'Menú contextual del archivo',
    fileOptionsMenu: 'Menú de opciones del archivo',
    fileOptionsPanel: 'Panel de opciones del archivo',
    noFilesSelected: 'No hay archivos seleccionados',
    detachFromNote: 'Desvincular de la nota',
    attachToNote: 'Adjuntar a la nota',
    passwordProtect: 'Proteger con contraseña',
    downloadSeparately: 'Descargar por separado',
    downloadAsArchive: 'Descargar como archivo comprimido',
    failedToDownloadArchive: 'No se pudieron descargar los archivos como archivo comprimido',
    fileId: 'ID del archivo:',
    size: 'Tamaño:',
    totalSize: 'Tamaño total:',
    backedUpOn: 'Copia de seguridad realizada el {{date}}',
    configureFileBackups: 'Configurar las copias de seguridad de archivos',
    fileNotBackedUpLocally: 'El archivo no tiene copia de seguridad local',
    noFoldersYet: 'Aún no hay carpetas',
    moveToFolder: 'Mover a una carpeta',
    folderSelectionMenu: 'Menú de selección de carpetas',
    noFolder: 'Sin carpeta',
    fileProtected: 'Este archivo está protegido.',
    authenticateToView: 'Autentícate para ver este archivo.',
    addPasscodeToView: 'Añade un código de acceso o crea una cuenta para requerir autenticación al ver este archivo.',
    openAccountMenu: 'Abrir el menú de la cuenta',
    authenticate: 'Autenticar',
    viewFile: 'Ver archivo',
    loading: 'Cargando...',
    fileCannotBePreviewed: 'Este archivo no se puede previsualizar.',
    errorLoadingFile: 'Se produjo un error al cargar el archivo. Inténtalo de nuevo o descarga el archivo y ábrelo con otra aplicación.',
    tryAgain: 'Intentar de nuevo',
    downloadToView: 'Para ver este archivo, descárgalo y ábrelo con otra aplicación.',
    fileInformation: 'Información del archivo',
    type: 'Tipo:',
    decryptedSize: 'Tamaño descifrado:',
    encryptedSize: 'Tamaño cifrado:',
    created: 'Creado:',
    lastModified: 'Última modificación:',
    done: 'Listo',
    showFileOptions: 'Mostrar las opciones del archivo',
    showFileInfo: 'Mostrar la información del archivo',
    hideFileInfo: 'Ocultar la información del archivo',
    showLinksSection: 'Mostrar la sección de enlaces',
    hideLinksSection: 'Ocultar la sección de enlaces',
    submit: 'Enviar',
    renameFile: 'Renombrar archivo',
    showLinkedItems: 'Mostrar elementos vinculados',
    closeModal: 'Cerrar la ventana',
    filePreviewModal: 'Ventana de vista previa del archivo',
    leftAlign: 'Alinear a la izquierda',
    centerAlign: 'Centrar',
    rightAlign: 'Alinear a la derecha',
    videoCannotBePreviewed: 'Este vídeo no se puede previsualizar.',
    audioCannotBePlayed: 'Este audio no se puede reproducir.',
    downloadToListen: 'Para escuchar este archivo, descárgalo y ábrelo con otra aplicación.',
    externalAppOnly: 'Este archivo solo se puede previsualizar en una aplicación externa',
    openFilePreview: 'Abrir la vista previa del archivo',
    loadingPdfViewer: 'Cargando el visor de PDF...',
    zoomOut: 'Alejar',
    zoomIn: 'Acercar',
    resetToActualSize: 'Restablecer al tamaño real',
    resetTo100: 'Restablecer al 100 %',
    fitToScreen: 'Ajustar a la pantalla',
    unableToRenderPdf: 'No se puede representar este PDF.',
    pdfCorruptedOrProtected: 'El archivo puede estar dañado o protegido con contraseña.',
    loadingPdf: 'Cargando PDF...',
    previousPage: 'Página anterior',
    pageNumber: 'Número de página',
    nextPage: 'Página siguiente',
    fitWidth: 'Ajustar al ancho',
    searchInDocumentShortcut: 'Buscar en el documento (Ctrl/Cmd+F)',
    searchInDocument: 'Buscar en el documento',
    copyLinkToPage: 'Copiar el enlace a la página {{page}}',
    copyLinkToThisPage: 'Copiar el enlace a esta página',
    copyLinkToSelectedText: 'Copiar el enlace al texto seleccionado',
    cancelOcr: 'Cancelar OCR',
    preparingOcr: 'Preparando OCR...',
    ocrProgress: 'OCR página {{current}} / {{total}} ({{percent}} %)',
    ocrCachedReRunTooltip: 'Texto ya extraído (en caché). Vuelve a ejecutar el OCR en tu navegador (permanece en tu dispositivo).',
    ocrExtractedReRunTooltip: 'Texto extraído. Vuelve a ejecutar el OCR en tu navegador (permanece en tu dispositivo).',
    ocrExtractTooltip: 'Extrae texto de páginas escaneadas con OCR. Se ejecuta en tu navegador; nada sale de tu dispositivo (lento; descarga datos de idioma).',
    extractTextWithOcrBrowser: 'Extraer texto con OCR en tu navegador',
    reRunOcrBrowser: 'Volver a ejecutar el OCR (navegador)',
    extractTextOcr: 'Extraer texto (OCR)',
    serverOcrTooltip:
      'Ejecuta el OCR en el SERVIDOR. Esto envía las imágenes de las páginas de este PDF al servidor y ABANDONA el cifrado de extremo a extremo — el servidor puede leer ese contenido. El OCR en el navegador mantiene todo en tu dispositivo.',
    runOcrOnServerAria: 'Ejecutar el OCR en el servidor (envía las imágenes de las páginas al servidor; abandona el cifrado de extremo a extremo)',
    runOcrOnServer: 'Ejecutar el OCR en el servidor',
    copyAllExtractedText: 'Copiar todo el texto extraído',
    copyExtractedTextAria: 'Copiar el texto extraído',
    findInDocument: 'Buscar en el documento',
    matchCase: 'Coincidir mayúsculas y minúsculas',
    noResults: 'Sin resultados',
    matchOfTotal: '{{current}} de {{total}}',
    previousMatch: 'Coincidencia anterior',
    nextMatch: 'Coincidencia siguiente',
    closeSearch: 'Cerrar la búsqueda',
    serverOcrDisclosurePrefix: 'El OCR en el servidor está disponible para tu cuenta. Envía las imágenes de las páginas de este PDF al servidor y',
    serverOcrDisclosureBold: 'abandona el cifrado de extremo a extremo',
    serverOcrDisclosureSuffix:
      ' — el servidor (y quien lo controle) puede leer ese contenido. El OCR en el navegador mantiene todo en tu dispositivo. La opción predeterminada es el OCR en el navegador.',
    ocrRunningServer:
      'OCR en el servidor: las imágenes de las páginas de este PDF se están subiendo al servidor, lo que ABANDONA el cifrado de extremo a extremo — el servidor puede leer ese contenido. (El OCR en el navegador mantiene todo en tu dispositivo.)',
    ocrRunningBrowser:
      'El OCR se ejecuta en tu navegador en este dispositivo (tus archivos permanecen cifrados de extremo a extremo). Es lento y descarga datos de idioma la primera vez que se usa.',
    ocrDoneServer:
      'El OCR en el servidor ha finalizado. Las imágenes de las páginas se enviaron al servidor (esto abandonó el cifrado de extremo a extremo). La precisión varía según la calidad del escaneo; el texto extraído ahora se puede buscar y copiar, y se almacena en caché en este dispositivo.',
    ocrDoneBrowser:
      'El OCR ha finalizado. La precisión varía según la calidad del escaneo; el texto extraído ahora se puede buscar y copiar, y se almacena en caché en este dispositivo.',
    copiedExtractedText: 'Texto extraído copiado',
    copiedLinkToPage: 'Enlace a la página {{page}} copiado',
    copiedLinkToSelectedText: 'Enlace al texto seleccionado copiado',
    serverOcrFailed: 'El OCR en el servidor falló: {{message}}',
    ocrUnknownError: 'error desconocido',
    ocrFailed: 'El OCR falló. Es posible que los datos de idioma no se hayan descargado.',
  },
  notes: {
    notesAndFiles: 'Notas y archivos',
    selectAllItems: 'Seleccionar todos los elementos',
    selectedCount: '{{count}} seleccionados',
    cancelMultipleSelection: 'Cancelar la selección múltiple',
    noFilesInFolder: 'No hay archivos en esta carpeta.',
    noItems: 'No hay elementos.',
    loading: 'Cargando...',
    uploadFileWithShortcut: 'Subir archivo {{shortcut}}',
    createNoteInTopicWithShortcut: 'Crear una nota nueva en el tema seleccionado {{shortcut}}',
    dropFilesToUpload: 'Suelta los archivos para subirlos y vincularlos al tema "{{title}}"',
    noFilesYet: 'Aún no tienes ningún archivo',
    filesAttachedAppearHere:
      'Los archivos adjuntos a tus notas aparecen aquí. También puedes subir archivos directamente desde esta página.',
    uploadFiles: 'Subir archivos',
    syncing: 'Sincronizando...',
    loadingItemsProgress: 'Cargando {{current}}/{{total}} elementos...',
    potentiallyOutOfSync: 'Posiblemente sin sincronizar',
    openDisplayOptionsMenu: 'Abrir el menú de opciones de visualización',
    displayOptionsMenu: 'Menú de opciones de visualización',
    displayOptions: 'Opciones de visualización',
    expandTopicsPanel: 'Expandir el panel de temas',
    collapseNotesPanel: 'Contraer el panel de notas',
    addItem: 'Añadir elemento',
    uploadFolder: 'Subir carpeta',
    takePhoto: 'Hacer foto',
    recordVideo: 'Grabar vídeo',
    searchPlaceholder: 'Buscar...',
    notesListOptionsMenu: 'Menú de opciones de la lista de notas',
    preferencesFor: 'Preferencias para',
    global: 'Global',
    reset: 'Restablecer',
    upgradeForPerTopicPreferences: 'Mejora tu plan para tener preferencias por tema',
    perTopicPreferencesMessageWithDaily:
      'Crea flujos de trabajo potentes y diseños organizativos con preferencias de visualización por tema y el nuevo diseño de calendario Daily Notebook.',
    perTopicPreferencesMessage:
      'Crea flujos de trabajo potentes y diseños organizativos con preferencias de visualización por tema.',
    sortBy: 'Ordenar por',
    relevanceBestMatch: 'Relevancia (mejor coincidencia)',
    dateModified: 'Fecha de modificación',
    creationDate: 'Fecha de creación',
    title: 'Título',
    customDragToReorder: 'Personalizado (arrastra para reordenar)',
    view: 'Ver',
    showNotePreview: 'Mostrar la vista previa de la nota',
    showDate: 'Mostrar la fecha',
    showTags: 'Mostrar los temas',
    showIcon: 'Mostrar el icono',
    other: 'Otros',
    showPinned: 'Mostrar las fijadas',
    showProtected: 'Mostrar las protegidas',
    showArchived: 'Mostrar las archivadas',
    showTrashed: 'Mostrar las de la papelera',
    dailyNotebook: 'Daily Notebook',
    labs: 'Labs',
    dailyNotebookDescription: 'Captura notas nuevas a diario con un diseño basado en un calendario',
    tableView: 'Vista de tabla',
    tableViewDescription: 'Muestra las notas y los archivos del tema actual en un diseño de tabla',
    newNoteDefaults: 'Valores predeterminados de nota nueva',
    noteType: 'Tipo de nota',
    selectDefaultNoteType: 'Selecciona el tipo de nota predeterminado',
    titleFormat: 'Formato del título',
    selectTitleFormat: 'Selecciona el formato del título de la nota',
    customFormatPlaceholder: 'p. ej. AAAA-MM-DD',
    preview: 'Vista previa: ',
    useBracketsToEscape: '. Usa ',
    toEscapeFormatting: ' para escapar el formato.',
    protected: 'Protegida',
    modified: 'Modificada',
    now: 'Ahora',
    editingDisabled: 'Edición desactivada',
    trashed: 'En la papelera',
    archived: 'Archivada',
    files: 'Archivos',
    starred: 'Destacada',
    fileBackedUpLocally: 'El archivo tiene copia de seguridad local',
    conflictedCopy: 'Copia en conflicto',
    allFiles: 'Todos los archivos',
    noFolder: 'Sin carpeta',
    folderNamePlaceholder: 'Nombre de la carpeta',
    createNewFolder: 'Crear una carpeta nueva',
    newFolder: 'Carpeta nueva',
    currentStreak: 'Racha actual',
    dayWithCount_one: 'Día',
    dayWithCount_many: 'Días',
    dayWithCount_other: 'Días',
  },
  auth: {
    unableToComputePrivateUsername: 'No se pudo calcular el nombre de usuario privado.',
    advancedOptions: 'Opciones avanzadas',
    privateUsernameMode: 'Modo de nombre de usuario privado',
    username: 'Nombre de usuario',
    useStrictSignIn: 'Usar inicio de sesión estricto',
    useRecoveryCode: 'Usar código de recuperación',
    recoveryCode: 'Código de recuperación',
    deleteLocalDataTitle: '¿Eliminar los datos locales?',
    noMergeWarning:
      'Has elegido no combinar tus datos locales. Si continúas, tus notas y temas locales se eliminarán permanentemente y se reemplazarán con los datos de tu cuenta. Esta acción no se puede deshacer.',
    noMergeConfirmQuestion: '¿Seguro que quieres continuar sin combinar?',
    deleteLocalDataAndContinue: 'Eliminar los datos locales y continuar',
    passwordResetWarningPart1: 'Como tus notas están cifradas con tu contraseña,',
    passwordResetWarningHighlight: 'Standard Red Notes no tiene opción de restablecimiento de contraseña',
    passwordResetWarningPart2: '. Si olvidas tu contraseña, perderás permanentemente el acceso a tus datos.',
    confirmPassword: 'Confirmar contraseña',
    creatingAccount: 'Creando la cuenta...',
    createAccountAndSignIn: 'Crear cuenta e iniciar sesión',
    staySignedIn: 'Mantener la sesión iniciada',
    goBack: 'Volver',
    humanVerification: 'Verificación humana',
    confirmPasswordTitle: 'Confirmar contraseña',
    createAccount: 'Crear cuenta',
    workspaceNameOptional: 'Nombre del espacio de trabajo (opcional)',
    generalAccountMenuLabel: 'Menú general de la cuenta',
    signedInAs: 'Has iniciado sesión como:',
    syncing: 'Sincronizando...',
    lastSynced: 'Última sincronización:',
    offlineSignInPrompt:
      'Estás sin conexión. Inicia sesión para sincronizar tus notas y preferencias en todos tus dispositivos y habilitar el cifrado de extremo a extremo.',
    offline: 'Sin conexión',
    accountSettings: 'Configuración de la cuenta',
    createFreeAccount: 'Crear una cuenta gratuita',
    documentation: 'Documentación',
    keyboardShortcuts: 'Atajos de teclado',
    commandPalette: 'Paleta de comandos',
    signOutWorkspace: 'Cerrar sesión del espacio de trabajo',
    mergeLocalData: 'Combinar datos locales ({{count}} notas y temas)',
    mergeLocalDataTooltip:
      'Si no se marca, tus notas y temas locales se eliminarán permanentemente y se reemplazarán con los datos de tu cuenta.',
    homeServerNotRunning:
      'El servidor doméstico no está en ejecución. Abre las preferencias y la pestaña del servidor doméstico para iniciarlo.',
    serverDefault: 'Predeterminado',
    serverCustom: 'Personalizado',
    serverHomeServer: 'Servidor doméstico',
    syncServer: 'Servidor de sincronización',
    signingIn: 'Iniciando sesión...',
    syncUnreachable: 'Sincronización inaccesible',
    syncUnreachableMessage: 'Mmm... parece que no podemos sincronizar tu cuenta. El motivo: {{reason}}',
    workspaceSwitcherMenuLabel: 'Menú de cambio de espacio de trabajo',
    signOutAllWorkspacesConfirm: '¿Seguro que quieres cerrar la sesión de todos los espacios de trabajo en este dispositivo?',
    signOutAll: 'Cerrar todas las sesiones',
    addAnotherWorkspace: 'Añadir otro espacio de trabajo',
    signOutAllWorkspaces: 'Cerrar la sesión de todos los espacios de trabajo',
    deleteAccountTitle: '¿Eliminar la cuenta?',
    deleteMyAccountForGood: 'Eliminar mi cuenta definitivamente',
    dataNotBackedUp: 'Datos sin copia de seguridad',
    signInOrRegisterToSync:
      'Inicia sesión o regístrate para sincronizar tus notas con tus otros dispositivos con cifrado de extremo a extremo.',
    openAccountMenu: 'Abrir el menú de la cuenta',
    ignoreWarning: 'Ignorar la advertencia',
    waitingForSecurityKey: 'Esperando la llave de seguridad...',
    authenticationSuccessful: '¡Autenticación correcta!',
    insertSecurityKeyPrompt: 'Inserta tu llave de seguridad de hardware y luego pulsa el botón de abajo para autenticarte.',
    authenticate: 'Autenticar',
  },
  search: {
    placeholder: 'Buscar...',
    protectedContents: 'Contenido protegido',
    archived: 'Archivadas',
    trashed: 'En la papelera',
    aiUnavailable: 'La reordenación con IA no está disponible o no devolvió ningún resultado.',
    aiUnavailableTooltip: 'La búsqueda contextual con IA no está disponible.',
    aiTypeQueryFirst: 'Escribe primero una consulta de búsqueda.',
    aiTooltip:
      'Reordena los mejores resultados por relevancia semántica usando tu proveedor de IA configurado. ' +
      'Envía los títulos y fragmentos cortos de esos candidatos, junto con tu consulta, al proveedor.',
    aiSearchWithAi: 'Buscar con IA',
    aiRanking: 'Clasificando…',
    aiRankedByRelevance: 'Ordenado por relevancia según la IA',
    aiPrivacyNotice:
      'Envía los títulos y fragmentos de los mejores resultados y tu consulta a tu proveedor de IA. Los proveedores en la nube los verán ' +
      '— un modelo local lo mantiene en el dispositivo.',
    advancedFilters: 'Filtros de búsqueda avanzados',
    filters: 'Filtros',
    noteTypeAny: 'Cualquier tipo',
    noteTypePlainText: 'Texto sin formato',
    noteTypeRichText: 'Texto enriquecido',
    noteTypeSuper: 'Super',
    noteTypeMarkdown: 'Markdown',
    noteTypeCode: 'Código',
    noteTypeTask: 'Tarea',
    noteTypeSpreadsheet: 'Hoja de cálculo',
    flagProtected: 'Protegida',
    flagPinned: 'Fijada',
    flagArchived: 'Archivada',
    flagStarred: 'Destacada',
    flagTrashed: 'En la papelera',
    topicsLabel: 'Temas (separados por comas)',
    topicsPlaceholder: 'trabajo, personal',
    noteTypeLabel: 'Tipo de nota',
    searchInLabel: 'Buscar en',
    searchInTitleAndContent: 'Título y contenido',
    modifiedWithinLabel: 'Modificada en los últimos',
    datePreset: 'Últimos {{label}}',
    createdAfterLabel: 'Creada después de',
    createdBeforeLabel: 'Creada antes de',
    updatedAfterLabel: 'Actualizada después de',
    updatedBeforeLabel: 'Actualizada antes de',
    statusLabel: 'Estado',
    hasAttachments: 'Tiene adjuntos',
    caseSensitive: 'Distingue mayúsculas y minúsculas',
    clearAllFilters: 'Borrar todos los filtros',
  },
  sharing: {
    vaultSelectionMenu: 'Menú de selección de bóvedas',
    vaultOptionsMenu: 'Menú de opciones de la bóveda',
    vaultOptions: 'Opciones de la bóveda',
    noVaultsFound: 'No se encontraron bóvedas',
    moveToVault: 'Mover a una bóveda',
    moveOutOfVault: 'Sacar de {{name}}',
    vaultsFallbackName: 'bóvedas',
    editVault: 'Editar bóveda',
    lockVault: 'Bloquear bóveda',
    unlockVault: 'Desbloquear bóveda',
    openVaultSettings: 'Abrir la configuración de la bóveda',
    selectionModeMultiple: 'Múltiple',
    selectionModeOne: 'Una',
    lastEditedBy: 'Última edición de',
    sharedBy: 'Compartido por',
    sharedByContact: 'Compartido por el contacto',
    vaultName: 'Nombre de la bóveda',
    sharedInVault: 'Compartido en la bóveda',
    copiedToClipboard: 'Copiado al portapapeles',
    failedToCopyToClipboard: 'No se pudo copiar al portapapeles',
    copyExampleToClipboard: 'Copiar el ejemplo al portapapeles',
    copiedExclaim: '¡Copiado!',
    shareUnavailableTitle: 'Compartición no disponible',
    shareUnavailableMessage: 'Este enlace compartido ya no está disponible.',
    invalidLinkTitle: 'Enlace no válido',
    invalidLinkMessage: 'Este enlace compartido no es válido o falta la clave.',
    selfDestructTitle: 'Esta nota se autodestruye después de verla',
    oneTimeViewConsumed: 'Estás leyendo un enlace de visualización única. Ya se ha consumido y no se puede volver a abrir',
    oneTimeViewExpiresClause_one: ', y caduca por completo {{count}} minuto después de la primera apertura',
    oneTimeViewExpiresClause_many: ', y caduca por completo {{count}} minutos después de la primera apertura',
    oneTimeViewExpiresClause_other: ', y caduca por completo {{count}} minutos después de la primera apertura',
    linkExpires_one: 'Este enlace caduca {{count}} minuto después de abrirse por primera vez.',
    linkExpires_many: 'Este enlace caduca {{count}} minutos después de abrirse por primera vez.',
    linkExpires_other: 'Este enlace caduca {{count}} minutos después de abrirse por primera vez.',
    untitled: 'Sin título',
    tagHasNoNotes: 'Este tema no tiene notas.',
    publicReadOnlyFooter: 'Este es un enlace compartido público y de solo lectura. El contenido se descifró en tu navegador.',
    confidentialWatermark: 'Confidencial · {{datetime}}',
    contentHiddenTitle: 'Contenido oculto',
    contentHiddenMessage: 'Vuelve a poner el foco en esta ventana para ver el contenido compartido.',
  },
}

export default es
