import type { LocaleResource } from './en'

const fr: LocaleResource = {
  common: {
    save: 'Enregistrer',
    cancel: 'Annuler',
    delete: 'Supprimer',
    confirm: 'Confirmer',
    close: 'Fermer',
    edit: 'Modifier',
    rename: 'Renommer',
    duplicate: 'Dupliquer',
    remove: 'Retirer',
    open: 'Ouvrir',
    create: 'Créer',
    add: 'Ajouter',
    done: 'Terminé',
    back: 'Retour',
    next: 'Suivant',
    search: 'Rechercher',
    clear: 'Effacer',
    loading: 'Chargement…',
    copy: 'Copier',
    copied: 'Copié',
    download: 'Télécharger',
    upload: 'Téléverser',
    export: 'Exporter',
    import: 'Importer',
    yes: 'Oui',
    no: 'Non',
    enabled: 'Activé',
    disabled: 'Désactivé',
    on: 'Activé',
    off: 'Désactivé',
    learnMore: 'En savoir plus',
    options: 'Options',
    settings: 'Paramètres',
    preferences: 'Préférences',
    help: 'Aide',
    pin: 'Épingler',
    unpin: 'Désépingler',
    star: 'Mettre en favori',
    unstar: 'Retirer des favoris',
    archive: 'Archiver',
    unarchive: 'Désarchiver',
    restore: 'Restaurer',
    moveToTrash: 'Mettre à la corbeille',
    deletePermanently: 'Supprimer définitivement',
    protect: 'Protéger',
    unprotect: 'Déprotéger',
  },
  navigation: {
    notes: 'Notes',
    allNotes: 'Toutes les notes',
    files: 'Fichiers',
    starred: 'Favoris',
    archived: 'Archivées',
    trash: 'Corbeille',
    untagged: 'Sans sujet',
    conflicts: 'Conflits',
    views: 'Vues',
    smartViews: 'Vues intelligentes',
    tags: 'Sujets',
    folders: 'Dossiers',
    favorites: 'Favoris',
    dashboard: 'Tableau de bord',
    createNewNote: 'Créer une nouvelle note',
    createNewTag: 'Créer un nouveau sujet',
    createNewFolder: 'Créer un nouveau dossier',
    createNewSmartView: 'Créer une nouvelle vue intelligente',
    searchTags: 'Rechercher des sujets…',
    noTagsFound: 'Aucun sujet trouvé. Essayez une autre recherche.',
    noSmartViewsFound: 'Aucune vue intelligente trouvée. Essayez une autre recherche.',
    collapseTagsPanel: 'Réduire le panneau des sujets',
    expandTagsPanel: 'Développer le panneau des sujets',
    goToItemsList: 'Aller à la liste des éléments',
    goToAccountMenu: 'Aller au menu du compte',
    openPreferences: 'Ouvrir les préférences',
  },
  account: {
    account: 'Compte',
    signIn: 'Se connecter',
    signOut: 'Se déconnecter',
    signUp: "S'inscrire",
    register: "S'inscrire",
    you: 'Vous',
    encryptionOn: 'Chiffrement de bout en bout activé',
    notSignedIn: 'Vous n’êtes pas connecté',
    signInOrRegister: 'Connectez-vous ou inscrivez-vous pour synchroniser vos notes',
    email: 'Adresse e-mail',
    password: 'Mot de passe',
    confirmPassword: 'Confirmer le mot de passe',
    syncNow: 'Synchroniser maintenant',
    lastSynced: 'Dernière synchronisation',
    importData: 'Importer',
    switchWorkspace: 'Changer d’espace de travail',
    lockApplication: 'Verrouiller l’application',
    helpAndFeedback: 'Aide et commentaires',
  },
  preferences: {
    title: 'Préférences',
    general: 'Général',
    account: 'Compte',
    security: 'Sécurité',
    appearance: 'Apparence',
    backups: 'Sauvegardes',
    listed: 'Listed',
    plugins: 'Extensions',
    whatsNew: 'Nouveautés',
    helpAndFeedback: 'Aide et commentaires',
    language: 'Langue',
    languageTitle: 'Langue',
    languageDescription:
      "Choisissez la langue utilisée dans toute l'interface de l'application. L'application utilise l'anglais pour ce qui n'est pas encore traduit.",
    languageChanged: 'Langue mise à jour',
    defaults: 'Valeurs par défaut',
    tools: 'Outils',
    spellcheck: 'Vérification orthographique',
    labs: 'Laboratoires',
  },
}

export default fr
