import type { LocaleResource } from './en'

const it: LocaleResource = {
  common: {
    save: 'Salva',
    cancel: 'Annulla',
    delete: 'Elimina',
    confirm: 'Conferma',
    close: 'Chiudi',
    edit: 'Modifica',
    rename: 'Rinomina',
    duplicate: 'Duplica',
    remove: 'Rimuovi',
    open: 'Apri',
    create: 'Crea',
    add: 'Aggiungi',
    done: 'Fatto',
    back: 'Indietro',
    next: 'Avanti',
    search: 'Cerca',
    clear: 'Cancella',
    loading: 'Caricamento…',
    copy: 'Copia',
    copied: 'Copiato',
    download: 'Scarica',
    upload: 'Carica',
    export: 'Esporta',
    import: 'Importa',
    yes: 'Sì',
    no: 'No',
    enabled: 'Attivato',
    disabled: 'Disattivato',
    on: 'Attivo',
    off: 'Disattivo',
    learnMore: 'Scopri di più',
    options: 'Opzioni',
    settings: 'Impostazioni',
    preferences: 'Preferenze',
    help: 'Aiuto',
    pin: 'Fissa',
    unpin: 'Sblocca',
    star: 'Aggiungi a speciali',
    unstar: 'Rimuovi da speciali',
    archive: 'Archivia',
    unarchive: 'Rimuovi dall’archivio',
    restore: 'Ripristina',
    moveToTrash: 'Sposta nel cestino',
    deletePermanently: 'Elimina definitivamente',
    protect: 'Proteggi',
    unprotect: 'Rimuovi protezione',
  },
  navigation: {
    notes: 'Note',
    allNotes: 'Tutte le note',
    files: 'File',
    starred: 'Speciali',
    archived: 'Archiviate',
    trash: 'Cestino',
    untagged: 'Senza argomento',
    conflicts: 'Conflitti',
    views: 'Viste',
    smartViews: 'Viste intelligenti',
    tags: 'Argomenti',
    folders: 'Cartelle',
    favorites: 'Preferiti',
    dashboard: 'Pannello',
    createNewNote: 'Crea una nuova nota',
    createNewTag: 'Crea un nuovo argomento',
    createNewFolder: 'Crea una nuova cartella',
    createNewSmartView: 'Crea una nuova vista intelligente',
    searchTags: 'Cerca argomenti…',
    noTagsFound: 'Nessun argomento trovato. Prova un’altra ricerca.',
    noSmartViewsFound: 'Nessuna vista intelligente trovata. Prova un’altra ricerca.',
    collapseTagsPanel: 'Comprimi pannello argomenti',
    expandTagsPanel: 'Espandi pannello argomenti',
    goToItemsList: 'Vai all’elenco degli elementi',
    goToAccountMenu: 'Vai al menu dell’account',
    openPreferences: 'Apri preferenze',
  },
  account: {
    account: 'Account',
    signIn: 'Accedi',
    signOut: 'Esci',
    signUp: 'Registrati',
    register: 'Registrati',
    you: 'Tu',
    encryptionOn: 'Crittografia end-to-end attiva',
    notSignedIn: 'Non hai effettuato l’accesso',
    signInOrRegister: 'Accedi o registrati per sincronizzare le tue note',
    email: 'E-mail',
    password: 'Password',
    confirmPassword: 'Conferma password',
    syncNow: 'Sincronizza ora',
    lastSynced: 'Ultima sincronizzazione',
    importData: 'Importa',
    switchWorkspace: 'Cambia area di lavoro',
    lockApplication: 'Blocca l’applicazione',
    helpAndFeedback: 'Aiuto e feedback',
  },
  preferences: {
    title: 'Preferenze',
    general: 'Generali',
    account: 'Account',
    security: 'Sicurezza',
    appearance: 'Aspetto',
    backups: 'Backup',
    listed: 'Listed',
    plugins: 'Plugin',
    whatsNew: 'Novità',
    helpAndFeedback: 'Aiuto e feedback',
    language: 'Lingua',
    languageTitle: 'Lingua',
    languageDescription:
      'Scegli la lingua usata nell’interfaccia dell’app. L’app usa l’inglese per ciò che non è ancora tradotto.',
    languageChanged: 'Lingua aggiornata',
    defaults: 'Valori predefiniti',
    tools: 'Strumenti',
    spellcheck: 'Controllo ortografico',
    labs: 'Laboratori',
  },
  editor: {
    cut: 'Taglia',
    copy: 'Copia',
    paste: 'Incolla',
    moreCutOptions: 'Altre opzioni di taglio',
    moreCopyOptions: 'Altre opzioni di copia',
    morePasteOptions: 'Altre opzioni di incolla',

    tableOfContents: 'Indice',
    selectAll: 'Seleziona tutto',
    selectAllText: 'Seleziona solo il testo',
    deselectAll: 'Deseleziona tutto',
    search: 'Cerca',
    undo: 'Annulla',
    redo: 'Ripeti',
    undoHistory: 'Cronologia annullamenti',
    redoHistory: 'Cronologia ripetizioni',
    undoHistoryEmpty: 'Cronologia annullamenti — niente da annullare',
    undoHistoryAvailable: 'Cronologia annullamenti — torna indietro di più passaggi in una volta',
    redoHistoryEmpty: 'Cronologia ripetizioni — niente da ripetere',
    redoHistoryAvailable: 'Cronologia ripetizioni — vai avanti di più passaggi in una volta',

    formattingOptions: 'Opzioni di formattazione',
    bold: 'Grassetto',
    italic: 'Corsivo',
    underline: 'Sottolineato',
    strikethrough: 'Barrato',
    inlineCode: 'Codice inline',
    link: 'Collegamento',
    formatPainter: 'Copia formato — copia la formattazione (doppio clic per mantenerlo attivo)',
    textStyle: 'Stile del testo',
    textColor: 'Colore del testo',
    highlightColor: 'Colore evidenziazione',
    typography: 'Tipografia — enfasi, contorno, spaziatura tra lettere e parole',
    typographyTitle: 'Tipografia',

    fontSize: 'Dimensione carattere',
    chooseFontSize: 'Scegli la dimensione del carattere',
    decreaseFontSize: 'Riduci dimensione carattere',
    increaseFontSize: 'Aumenta dimensione carattere',
    fontFamily: 'Famiglia di caratteri',
    customFontFamily: 'Personalizzato',

    bulletedList: 'Elenco puntato',
    numberedList: 'Elenco numerato',
    checkList: 'Elenco di controllo',
    quote: 'Citazione',
    codeBlock: 'Blocco di codice',
    changeCase: 'Cambia maiuscole/minuscole',
    sortAndDedupeLines: 'Ordina ed elimina righe duplicate',
    alignment: 'Allineamento',
    paragraphLayout: 'Layout paragrafo — spaziatura righe e paragrafi, rientro, sfondo',
    paragraphLayoutTitle: 'Layout paragrafo',
    listStyleMarker: 'Stile elenco — indicatore punto e numero',
    formattingMarks: 'Segni di formattazione',
    insert: 'Inserisci',

    insertRowAbove: 'Inserisci riga sopra',
    insertRowBelow: 'Inserisci riga sotto',
    insertColumnLeft: 'Inserisci colonna a sinistra',
    insertColumnRight: 'Inserisci colonna a destra',
    deleteRow: 'Elimina riga',
    deleteColumn: 'Elimina colonna',
    toggleRowHeader: 'Attiva/disattiva intestazione riga',
    toggleColumnHeader: 'Attiva/disattiva intestazione colonna',
    deleteTable: 'Elimina tabella',

    rows: 'Righe',
    columns: 'Colonne',
    cells: 'Celle',
    table: 'Tabella',
    block: 'Blocco',

    alignLeft: 'Allinea a sinistra',
    alignCenter: 'Allinea al centro',
    alignRight: 'Allinea a destra',

    editLink: 'Modifica collegamento',
    removeLink: 'Rimuovi collegamento',

    zoomIntoBlock: 'Zoom sul blocco',

    blockStyle: 'Stile del blocco',
    heading1: 'Titolo 1',
    heading2: 'Titolo 2',
    heading3: 'Titolo 3',
    normalText: 'Testo normale',
    moreFormatting: 'Altra formattazione',

    createNoteFromSelectionTitle: 'Crea una nuova nota dalla selezione',
    createNoteFromSelectionDescription:
      'Crea una nuova nota contenente la selezione corrente e sostituisce la selezione con un collegamento alla nuova nota.',

    dismissKeyboard: 'Nascondi tastiera',

    tableOfContentsLower: 'Indice',
    noHeadingsFound: 'Nessun titolo trovato',
    textFormattingOptions: 'Opzioni di formattazione testo',
    highlight: 'Evidenzia',
    subscript: 'Pedice',
    superscript: 'Apice',
    clearFormatting: 'Cancella formattazione',
    normal: 'Normale',
    smartChecklist: 'Elenco di controllo intelligente',
    restoreCompletedTasks: 'Ripristina attività completate',
    leftAlign: 'Allinea a sinistra',
    centerAlign: 'Allinea al centro',
    rightAlign: 'Allinea a destra',
    justify: 'Giustifica',

    searchBlocksPlaceholder: 'Cerca blocchi…',
    searchBlocksToInsert: 'Cerca blocchi da inserire',
    clearSearch: 'Cancella ricerca',
    noBlocksMatch: 'Nessun blocco corrisponde a “{{query}}”',
    customizeToolbar: 'Personalizza barra degli strumenti',

    custom: 'Personalizzato',
    clear: 'Cancella',
    textColorSwatch: 'Colore del testo {{color}}',
    highlightColorSwatch: 'Colore evidenziazione {{color}}',
    textShadingSwatch: 'Sfondo del testo {{color}}',
    noTextShading: 'Nessuno sfondo del testo',

    uppercase: 'MAIUSCOLO',
    lowercase: 'minuscolo',
    camelCase: 'camelCase',

    sortLines: 'Ordina righe',
    deduplicate: 'Elimina duplicati',
    multiKeySort: 'Ordinamento a più chiavi (1ª, 2ª, 3ª)…',
    sortAndDeduplicateLines: 'Ordina ed elimina righe duplicate',

    emphasisMarks: 'Segni di enfasi',
    outlineTextStroke: 'Contorno (traccia del testo)',
    letterSpacingKerning: 'Spaziatura lettere (crenatura)',
    wordSpacing: 'Spaziatura parole',
    clearTypography: 'Cancella tipografia',
    spacingTight: 'Stretta',
    spacingNormal: 'Normale',
    spacingWide: 'Ampia',
    spacingWider: 'Più ampia',
    spacingWidest: 'Massima',

    undoMultipleSteps: 'Annulla più passaggi',
    redoMultipleSteps: 'Ripeti più passaggi',
    emptyHistoryPreview: '(vuota)',

    pasteOptions: 'Opzioni di incolla',
    copyOptions: 'Opzioni di copia',
    cutOptions: 'Opzioni di taglio',
    pasteWithoutFormatting: 'Incolla senza formattazione',
    pasteClean: 'Incolla pulito (rimuovi caratteri nascosti)',
    keepSourceFormatting: 'Mantieni la formattazione di origine',
    matchDestinationFormatting: 'Adatta alla formattazione di destinazione',
    pasteAsImage: 'Incolla come immagine',
    copyWithoutFormatting: 'Copia senza formattazione',
    copyTextOnly: 'Copia solo il testo',
    copyImagesOnly: 'Copia solo le immagini',
    cutWithoutFormatting: 'Taglia senza formattazione',
    cutTextOnly: 'Taglia solo il testo',
    cutImagesOnly: 'Taglia solo le immagini',

    lineSpacing: 'Interlinea',
    spaceBefore: 'Spazio prima',
    spaceAfter: 'Spazio dopo',
    indentation: 'Rientro',
    none: 'Nessuno',
    increaseLeft: 'Aumenta a sinistra',
    decreaseLeft: 'Riduci a sinistra',
    increaseRight: 'Aumenta a destra',
    decreaseRight: 'Riduci a destra',
    firstLine: 'Prima riga',
    noFirstLine: 'Nessuna prima riga',
    textShading: 'Sfondo del testo',

    listStyle: 'Stile elenco',
    bulleted: 'Puntato',
    numbered: 'Numerato',
    bulletedListMarkers: 'Stile indicatore punto',
    numberedListMarkers: 'Stile numerazione',
    multilevelList: 'Elenco multilivello',
    multilevelListHint: 'Scegli un indicatore per ogni livello di annidamento',
    multilevelLevelDefault: 'Predefinito',
    level: 'Livello',
    apply: 'Applica',

    insertTable: 'Inserisci tabella',
    insertImageFromUrl: 'Inserisci immagine da URL',
    sortLinesModalTitle: 'Ordina righe',

    blockPicker: 'Selettore blocchi',

    blockParagraph: 'Paragrafo',
    blockCallout: 'Riquadro',
    blockDivider: 'Divisore',
    blockCollapsible: 'Comprimibile',
    blockImageFromUrl: 'Immagine da URL',
    blockUploadFile: 'Carica file',
    blockDrawing: 'Disegno',
    blockQrCode: 'Codice QR',
    blockTable: 'Tabella',
    blockKanbanBoard: 'Bacheca Kanban',
    blockCalendar: 'Calendario',
    blockTimeline: 'Sequenza temporale',
    blockDataTable: 'Tabella dati',
    blockSqlQuery: 'Query SQL',
    blockMermaidDiagram: 'Diagramma Mermaid',
    blockGanttChart: 'Diagramma di Gantt',
    blockTimingDiagram: 'Diagramma di temporizzazione',
    blockMusicStaff: 'Pentagramma musicale',
    blockTradingViewChart: 'Grafico TradingView',
    blockStockChart: 'Grafico azionario',
    blockEmbed: 'Incorpora',
    blockEmbedWebsite: 'Incorpora sito web',
    blockTweet: 'Tweet',
    blockEquation: 'Equazione',
    blockInlineEquation: 'Equazione inline',
    blockFootnote: 'Nota a piè di pagina',
    blockBookmark: 'Segnalibro',
    blockGeneratePassword: 'Genera password crittograficamente sicura',
    blockClock: 'Orologio',
    blockCurrentDateTime: 'Data e ora correnti',
    blockCurrentTime: 'Ora corrente',
    blockCurrentDate: 'Data corrente',

    blockCategoryBasic: 'Base',
    blockCategoryLists: 'Elenchi',
    blockCategoryMedia: 'Contenuti multimediali',
    blockCategoryDataTables: 'Dati e tabelle',
    blockCategoryDiagramsCharts: 'Diagrammi e grafici',
    blockCategoryFinance: 'Finanza',
    blockCategoryEmbeds: 'Incorporamenti',
    blockCategoryAdvanced: 'Avanzate',
  },
  files: {
    dropToUploadTooltip: 'Trascina i tuoi file per caricarli e collegarli al file corrente',
    fileAriaLabel: 'File',
    fileReadonly: 'Questo file è di sola lettura',
    fileInformationPanel: 'Pannello informazioni file',
    details: 'Dettagli',

    selectedFilesCount: '{{count}} file selezionati',
    actionsPerformedOnSelected: 'Le azioni verranno eseguite su tutti i file selezionati.',
    cancelMultipleSelection: 'Annulla selezione multipla',

    fileOptions: 'Opzioni file',
    fileContextMenu: 'Menu contestuale file',
    fileOptionsMenu: 'Menu opzioni file',
    fileOptionsPanel: 'Pannello opzioni file',

    noFilesSelected: 'Nessun file selezionato',
    detachFromNote: 'Scollega dalla nota',
    attachToNote: 'Allega alla nota',
    passwordProtect: 'Proteggi con password',
    downloadSeparately: 'Scarica separatamente',
    downloadAsArchive: 'Scarica come archivio',
    failedToDownloadArchive: 'Impossibile scaricare i file come archivio',
    fileId: 'ID file:',
    size: 'Dimensione:',
    totalSize: 'Dimensione totale:',

    backedUpOn: 'Backup eseguito il {{date}}',
    configureFileBackups: 'Configura backup dei file',
    fileNotBackedUpLocally: 'File senza backup locale',

    noFoldersYet: 'Ancora nessuna cartella',
    moveToFolder: 'Sposta nella cartella',
    folderSelectionMenu: 'Menu selezione cartella',
    noFolder: 'Nessuna cartella',

    fileProtected: 'Questo file è protetto.',
    authenticateToView: 'Autenticati per visualizzare questo file.',
    addPasscodeToView: 'Aggiungi un codice di accesso o crea un account per richiedere l\'autenticazione alla visualizzazione di questo file.',
    openAccountMenu: 'Apri menu account',
    authenticate: 'Autenticati',
    viewFile: 'Visualizza file',
    loading: 'Caricamento...',

    fileCannotBePreviewed: 'Impossibile visualizzare l\'anteprima di questo file.',
    errorLoadingFile: 'Si è verificato un errore durante il caricamento del file. Riprova oppure scarica il file e aprilo con un\'altra applicazione.',
    tryAgain: 'Riprova',
    downloadToView: 'Per visualizzare questo file, scaricalo e aprilo con un\'altra applicazione.',

    fileInformation: 'Informazioni file',
    type: 'Tipo:',
    decryptedSize: 'Dimensione decrittata:',
    encryptedSize: 'Dimensione crittata:',
    created: 'Creato:',
    lastModified: 'Ultima modifica:',

    done: 'Fatto',
    showFileOptions: 'Mostra opzioni file',
    showFileInfo: 'Mostra informazioni file',
    hideFileInfo: 'Nascondi informazioni file',
    showLinksSection: 'Mostra sezione collegamenti',
    hideLinksSection: 'Nascondi sezione collegamenti',
    submit: 'Invia',
    renameFile: 'Rinomina file',
    showLinkedItems: 'Mostra elementi collegati',
    closeModal: 'Chiudi finestra',
    filePreviewModal: 'Finestra anteprima file',

    leftAlign: 'Allinea a sinistra',
    centerAlign: 'Allinea al centro',
    rightAlign: 'Allinea a destra',

    videoCannotBePreviewed: 'Impossibile visualizzare l\'anteprima di questo video.',

    audioCannotBePlayed: 'Impossibile riprodurre questo audio.',
    downloadToListen: 'Per ascoltare questo file, scaricalo e aprilo con un\'altra applicazione.',

    externalAppOnly: 'Questo file può essere visualizzato in anteprima solo in un\'app esterna',
    openFilePreview: 'Apri anteprima file',
    loadingPdfViewer: 'Caricamento visualizzatore PDF...',

    zoomOut: 'Riduci zoom',
    zoomIn: 'Aumenta zoom',
    resetToActualSize: 'Ripristina dimensione reale',
    resetTo100: 'Ripristina al 100%',
    fitToScreen: 'Adatta allo schermo',

    unableToRenderPdf: 'Impossibile visualizzare questo PDF.',
    pdfCorruptedOrProtected: 'Il file potrebbe essere danneggiato o protetto da password.',
    loadingPdf: 'Caricamento PDF...',
    previousPage: 'Pagina precedente',
    pageNumber: 'Numero di pagina',
    nextPage: 'Pagina successiva',
    fitWidth: 'Adatta larghezza',
    searchInDocumentShortcut: 'Cerca nel documento (Ctrl/Cmd+F)',
    searchInDocument: 'Cerca nel documento',
    copyLinkToPage: 'Copia collegamento alla pagina {{page}}',
    copyLinkToThisPage: 'Copia collegamento a questa pagina',
    copyLinkToSelectedText: 'Copia collegamento al testo selezionato',
    cancelOcr: 'Annulla OCR',
    preparingOcr: 'Preparazione OCR...',
    ocrProgress: 'OCR pagina {{current}} / {{total}} ({{percent}}%)',
    ocrCachedReRunTooltip: 'Testo già estratto (in cache). Riesegui l\'OCR nel browser (rimane sul dispositivo).',
    ocrExtractedReRunTooltip: 'Testo estratto. Riesegui l\'OCR nel browser (rimane sul dispositivo).',
    ocrExtractTooltip: 'Estrai il testo dalle pagine scansionate con l\'OCR. Viene eseguito nel browser; nulla lascia il tuo dispositivo (lento; scarica i dati della lingua).',
    extractTextWithOcrBrowser: 'Estrai testo con OCR nel browser',
    reRunOcrBrowser: 'Riesegui OCR (browser)',
    extractTextOcr: 'Estrai testo (OCR)',
    serverOcrTooltip:
      'Esegui l\'OCR sul SERVER. Questo invia le immagini delle pagine di questo PDF al server e ABBANDONA la crittografia end-to-end — il server può leggere quel contenuto. L\'OCR nel browser mantiene tutto sul tuo dispositivo.',
    runOcrOnServerAria: 'Esegui l\'OCR sul server (invia le immagini delle pagine al server; abbandona la crittografia end-to-end)',
    runOcrOnServer: 'Esegui OCR sul server',
    copyAllExtractedText: 'Copia tutto il testo estratto',
    copyExtractedTextAria: 'Copia testo estratto',
    findInDocument: 'Trova nel documento',
    matchCase: 'Maiuscole/minuscole',
    noResults: 'Nessun risultato',
    matchOfTotal: '{{current}} di {{total}}',
    previousMatch: 'Corrispondenza precedente',
    nextMatch: 'Corrispondenza successiva',
    closeSearch: 'Chiudi ricerca',
    serverOcrDisclosurePrefix: 'L\'OCR sul server è disponibile per il tuo account. Invia le immagini delle pagine di questo PDF al server e',
    serverOcrDisclosureBold: 'abbandona la crittografia end-to-end',
    serverOcrDisclosureSuffix:
      ' — il server (e chiunque lo controlli) può leggere quel contenuto. L\'OCR nel browser mantiene tutto sul tuo dispositivo. L\'impostazione predefinita è l\'OCR nel browser.',
    ocrRunningServer:
      'OCR sul server: le immagini delle pagine di questo PDF vengono caricate sul server, il che ABBANDONA la crittografia end-to-end — il server può leggere quel contenuto. (L\'OCR nel browser mantiene tutto sul tuo dispositivo.)',
    ocrRunningBrowser:
      'L\'OCR viene eseguito nel browser su questo dispositivo (i tuoi file restano crittografati end-to-end). È lento e scarica i dati della lingua al primo utilizzo.',
    ocrDoneServer:
      'OCR sul server completato. Le immagini delle pagine sono state inviate al server (questo ha abbandonato la crittografia end-to-end). La precisione varia in base alla qualità della scansione; il testo estratto è ora ricercabile e copiabile ed è memorizzato nella cache su questo dispositivo.',
    ocrDoneBrowser:
      'OCR completato. La precisione varia in base alla qualità della scansione; il testo estratto è ora ricercabile e copiabile ed è memorizzato nella cache su questo dispositivo.',

    copiedExtractedText: 'Testo estratto copiato',
    copiedLinkToPage: 'Collegamento alla pagina {{page}} copiato',
    copiedLinkToSelectedText: 'Collegamento al testo selezionato copiato',

    serverOcrFailed: 'OCR sul server non riuscito: {{message}}',
    ocrUnknownError: 'errore sconosciuto',
    ocrFailed: 'OCR non riuscito. Potrebbe non essere stato possibile scaricare i dati della lingua.',
  },
  notes: {
    notesAndFiles: 'Note e file',
    selectAllItems: 'Seleziona tutti gli elementi',
    selectedCount: '{{count}} selezionati',
    cancelMultipleSelection: 'Annulla selezione multipla',
    noFilesInFolder: 'Nessun file in questa cartella.',
    noItems: 'Nessun elemento.',
    loading: 'Caricamento...',
    uploadFileWithShortcut: 'Carica file {{shortcut}}',
    createNoteInTopicWithShortcut: 'Crea una nuova nota nell\'argomento selezionato {{shortcut}}',
    dropFilesToUpload: 'Trascina i tuoi file per caricarli e collegarli all\'argomento "{{title}}"',

    noFilesYet: 'Non hai ancora nessun file',
    filesAttachedAppearHere:
      'I file allegati alle tue note appaiono qui. Puoi anche caricare file direttamente da questa pagina.',
    uploadFiles: 'Carica file',

    syncing: 'Sincronizzazione...',
    loadingItemsProgress: 'Caricamento di {{current}}/{{total}} elementi...',
    potentiallyOutOfSync: 'Potenzialmente non sincronizzato',
    openDisplayOptionsMenu: 'Apri menu opzioni di visualizzazione',
    displayOptionsMenu: 'Menu opzioni di visualizzazione',
    displayOptions: 'Opzioni di visualizzazione',
    expandTopicsPanel: 'Espandi pannello argomenti',
    collapseNotesPanel: 'Comprimi pannello note',

    addItem: 'Aggiungi elemento',
    uploadFolder: 'Carica cartella',
    takePhoto: 'Scatta foto',
    recordVideo: 'Registra video',

    searchPlaceholder: 'Cerca...',

    notesListOptionsMenu: 'Menu opzioni elenco note',
    preferencesFor: 'Preferenze per',
    global: 'Globale',
    reset: 'Reimposta',
    upgradeForPerTopicPreferences: 'Esegui l\'upgrade per le preferenze per argomento',
    perTopicPreferencesMessageWithDaily:
      'Crea potenti flussi di lavoro e layout organizzativi con le preferenze di visualizzazione per argomento e il nuovissimo layout calendario Daily Notebook.',
    perTopicPreferencesMessage:
      'Crea potenti flussi di lavoro e layout organizzativi con le preferenze di visualizzazione per argomento.',
    sortBy: 'Ordina per',
    relevanceBestMatch: 'Pertinenza (migliore corrispondenza)',
    dateModified: 'Data modifica',
    creationDate: 'Data creazione',
    title: 'Titolo',
    customDragToReorder: 'Personalizzato (trascina per riordinare)',
    view: 'Visualizza',
    showNotePreview: 'Mostra anteprima nota',
    showDate: 'Mostra data',
    showTags: 'Mostra argomenti',
    showIcon: 'Mostra icona',
    other: 'Altro',
    showPinned: 'Mostra fissati',
    showProtected: 'Mostra protetti',
    showArchived: 'Mostra archiviati',
    showTrashed: 'Mostra nel cestino',
    dailyNotebook: 'Daily Notebook',
    labs: 'Labs',
    dailyNotebookDescription: 'Acquisisci nuove note ogni giorno con un layout basato sul calendario',
    tableView: 'Vista tabella',
    tableViewDescription: 'Mostra le note e i file dell\'argomento corrente in un layout a tabella',
    newNoteDefaults: 'Valori predefiniti nuova nota',

    noteType: 'Tipo di nota',
    selectDefaultNoteType: 'Seleziona il tipo di nota predefinito',
    titleFormat: 'Formato titolo',
    selectTitleFormat: 'Seleziona il formato per il titolo della nota',
    customFormatPlaceholder: 'es. YYYY-MM-DD',
    preview: 'Anteprima: ',
    useBracketsToEscape: '. Usa ',
    toEscapeFormatting: ' per ignorare la formattazione.',

    protected: 'Protetta',
    modified: 'Modificata',
    now: 'Ora',

    editingDisabled: 'Modifica disattivata',
    trashed: 'Nel cestino',
    archived: 'Archiviata',
    files: 'File',
    starred: 'Speciale',
    fileBackedUpLocally: 'Il file ha un backup locale',

    conflictedCopy: 'Copia in conflitto',

    allFiles: 'Tutti i file',
    noFolder: 'Nessuna cartella',
    folderNamePlaceholder: 'Nome cartella',
    createNewFolder: 'Crea una nuova cartella',
    newFolder: 'Nuova cartella',

    currentStreak: 'Serie attuale',
    dayWithCount_one: 'Giorno',
    dayWithCount_many: 'Giorni',
    dayWithCount_other: 'Giorni',
  },
  auth: {
    unableToComputePrivateUsername: 'Impossibile calcolare il nome utente privato.',
    advancedOptions: 'Opzioni avanzate',
    privateUsernameMode: 'Modalità nome utente privato',
    username: 'Nome utente',
    useStrictSignIn: 'Usa accesso rigoroso',
    useRecoveryCode: 'Usa codice di recupero',
    recoveryCode: 'Codice di recupero',

    deleteLocalDataTitle: 'Eliminare i dati locali?',
    noMergeWarning:
      'Hai scelto di non unire i tuoi dati locali. Se procedi, le tue note e i tuoi argomenti locali verranno eliminati definitivamente e sostituiti con i dati del tuo account. Questa azione non può essere annullata.',
    noMergeConfirmQuestion: 'Sei sicuro di voler continuare senza unire?',
    deleteLocalDataAndContinue: 'Elimina i dati locali e continua',

    passwordResetWarningPart1: 'Poiché le tue note sono crittografate con la tua password,',
    passwordResetWarningHighlight: 'Standard Red Notes non dispone di un\'opzione di reimpostazione della password',
    passwordResetWarningPart2: '. Se dimentichi la password, perderai definitivamente l\'accesso ai tuoi dati.',
    confirmPassword: 'Conferma password',
    creatingAccount: 'Creazione account...',
    createAccountAndSignIn: 'Crea account e accedi',
    staySignedIn: 'Resta connesso',
    goBack: 'Torna indietro',
    humanVerification: 'Verifica umana',
    confirmPasswordTitle: 'Conferma password',

    createAccount: 'Crea account',
    workspaceNameOptional: 'Nome area di lavoro (facoltativo)',

    generalAccountMenuLabel: 'Menu generale account',
    signedInAs: 'Hai effettuato l\'accesso come:',
    syncing: 'Sincronizzazione...',
    lastSynced: 'Ultima sincronizzazione:',
    offlineSignInPrompt:
      'Sei offline. Accedi per sincronizzare le tue note e preferenze su tutti i tuoi dispositivi e abilitare la crittografia end-to-end.',
    offline: 'Offline',
    accountSettings: 'Impostazioni account',
    createFreeAccount: 'Crea un account gratuito',
    documentation: 'Documentazione',
    keyboardShortcuts: 'Scorciatoie da tastiera',
    commandPalette: 'Riquadro comandi',
    signOutWorkspace: 'Esci dall\'area di lavoro',

    mergeLocalData: 'Unisci dati locali ({{count}} note e argomenti)',
    mergeLocalDataTooltip:
      'Se deselezionato, le tue note e i tuoi argomenti locali verranno eliminati definitivamente e sostituiti con i dati del tuo account.',

    homeServerNotRunning:
      'Il server locale non è in esecuzione. Apri le preferenze e la scheda del server locale per avviarlo.',
    serverDefault: 'Predefinito',
    serverCustom: 'Personalizzato',
    serverHomeServer: 'Home Server',
    syncServer: 'Server di sincronizzazione',

    signingIn: 'Accesso in corso...',

    syncUnreachable: 'Sincronizzazione non raggiungibile',
    syncUnreachableMessage: 'Hmm...non riusciamo a sincronizzare il tuo account. Il motivo: {{reason}}',

    workspaceSwitcherMenuLabel: 'Menu selezione area di lavoro',
    signOutAllWorkspacesConfirm: 'Sei sicuro di voler uscire da tutte le aree di lavoro su questo dispositivo?',
    signOutAll: 'Esci da tutte',
    addAnotherWorkspace: 'Aggiungi un\'altra area di lavoro',
    signOutAllWorkspaces: 'Esci da tutte le aree di lavoro',

    deleteAccountTitle: 'Eliminare l\'account?',
    deleteMyAccountForGood: 'Elimina definitivamente il mio account',

    dataNotBackedUp: 'Dati senza backup',
    signInOrRegisterToSync:
      'Accedi o registrati per sincronizzare le tue note sugli altri dispositivi con crittografia end-to-end.',
    openAccountMenu: 'Apri menu Account',
    ignoreWarning: 'Ignora avviso',

    waitingForSecurityKey: 'In attesa della chiave di sicurezza...',
    authenticationSuccessful: 'Autenticazione riuscita!',
    insertSecurityKeyPrompt: 'Inserisci la tua chiave di sicurezza hardware, quindi premi il pulsante qui sotto per autenticarti.',
    authenticate: 'Autenticati',
  },
  search: {
    placeholder: 'Cerca...',

    protectedContents: 'Contenuti protetti',
    archived: 'Archiviati',
    trashed: 'Nel cestino',

    aiUnavailable: 'La riclassificazione AI non è disponibile o non ha restituito risultati.',
    aiUnavailableTooltip: 'La ricerca contestuale AI non è disponibile.',
    aiTypeQueryFirst: 'Digita prima una query di ricerca.',
    aiTooltip:
      'Riclassifica i migliori risultati per pertinenza semantica utilizzando il provider AI configurato. ' +
      'Invia i titoli e brevi estratti di quei candidati, insieme alla tua query, al provider.',
    aiSearchWithAi: 'Cerca con l\'AI',
    aiRanking: 'Classificazione…',
    aiRankedByRelevance: 'Classificati per pertinenza AI',
    aiPrivacyNotice:
      'Invia i titoli e gli estratti dei migliori risultati e la tua query al tuo provider AI. I provider cloud li vedranno — ' +
      'un modello locale li mantiene sul dispositivo.',

    advancedFilters: 'Filtri di ricerca avanzati',
    filters: 'Filtri',
    noteTypeAny: 'Qualsiasi tipo',
    noteTypePlainText: 'Testo semplice',
    noteTypeRichText: 'Testo formattato',
    noteTypeSuper: 'Super',
    noteTypeMarkdown: 'Markdown',
    noteTypeCode: 'Codice',
    noteTypeTask: 'Attività',
    noteTypeSpreadsheet: 'Foglio di calcolo',
    flagProtected: 'Protetta',
    flagPinned: 'Fissata',
    flagArchived: 'Archiviata',
    flagStarred: 'Speciale',
    flagTrashed: 'Nel cestino',
    topicsLabel: 'Argomenti (separati da virgola)',
    topicsPlaceholder: 'lavoro, personale',
    noteTypeLabel: 'Tipo di nota',
    searchInLabel: 'Cerca in',
    searchInTitleAndContent: 'Titolo e contenuto',
    modifiedWithinLabel: 'Modificato entro',
    datePreset: 'Ultimi {{label}}',
    createdAfterLabel: 'Creato dopo',
    createdBeforeLabel: 'Creato prima',
    updatedAfterLabel: 'Aggiornato dopo',
    updatedBeforeLabel: 'Aggiornato prima',
    statusLabel: 'Stato',
    hasAttachments: 'Ha allegati',
    caseSensitive: 'Distingui maiuscole/minuscole',
    clearAllFilters: 'Cancella tutti i filtri',
  },
  sharing: {
    vaultSelectionMenu: 'Menu selezione cassaforte',
    vaultOptionsMenu: 'Menu opzioni cassaforte',
    vaultOptions: 'Opzioni cassaforte',
    noVaultsFound: 'Nessuna cassaforte trovata',
    moveToVault: 'Sposta nella cassaforte',
    moveOutOfVault: 'Sposta fuori da {{name}}',
    vaultsFallbackName: 'casseforti',
    editVault: 'Modifica cassaforte',
    lockVault: 'Blocca cassaforte',
    unlockVault: 'Sblocca cassaforte',
    openVaultSettings: 'Apri impostazioni cassaforte',
    selectionModeMultiple: 'Multipla',
    selectionModeOne: 'Una',
    lastEditedBy: 'Ultima modifica di',
    sharedBy: 'Condiviso da',
    sharedByContact: 'Condiviso dal contatto',
    vaultName: 'Nome cassaforte',
    sharedInVault: 'Condiviso nella cassaforte',
    copiedToClipboard: 'Copiato negli appunti',
    failedToCopyToClipboard: 'Impossibile copiare negli appunti',
    copyExampleToClipboard: 'Copia esempio negli appunti',
    copiedExclaim: 'Copiato!',
    shareUnavailableTitle: 'Condivisione non disponibile',
    shareUnavailableMessage: 'Questo link di condivisione non è più disponibile.',
    invalidLinkTitle: 'Link non valido',
    invalidLinkMessage: 'Questo link di condivisione non è valido o la chiave è mancante.',
    selfDestructTitle: 'Questa nota si autodistrugge dopo la visualizzazione',
    oneTimeViewConsumed: 'Stai leggendo un link a visualizzazione singola. È stato ora consumato e non può essere riaperto',
    oneTimeViewExpiresClause_one: ', e scade completamente {{count}} minuto dalla prima apertura',
    oneTimeViewExpiresClause_many: ', e scade completamente {{count}} minuti dalla prima apertura',
    oneTimeViewExpiresClause_other: ', e scade completamente {{count}} minuti dalla prima apertura',
    linkExpires_one: 'Questo link scade {{count}} minuto dopo la prima apertura.',
    linkExpires_many: 'Questo link scade {{count}} minuti dopo la prima apertura.',
    linkExpires_other: 'Questo link scade {{count}} minuti dopo la prima apertura.',
    untitled: 'Senza titolo',
    tagHasNoNotes: 'Questo argomento non ha note.',
    publicReadOnlyFooter: 'Questo è un link condiviso pubblico e di sola lettura. Il contenuto è stato decrittato nel tuo browser.',
    confidentialWatermark: 'Riservato · {{datetime}}',
    contentHiddenTitle: 'Contenuto nascosto',
    contentHiddenMessage: 'Riporta il focus su questa finestra per visualizzare il contenuto condiviso.',
  },
}

export default it
