import type { LocaleResource } from './en'

const it: LocaleResource = {
  common: {
    save: 'Salva',
    cancel: 'Annulla',
    delete: 'Elimina',
    confirm: 'Conferma',
    close: 'Chiudi',
    edit: 'Modifica',
    rename: 'Rinomina',
    duplicate: 'Duplica',
    remove: 'Rimuovi',
    open: 'Apri',
    create: 'Crea',
    add: 'Aggiungi',
    done: 'Fatto',
    back: 'Indietro',
    next: 'Avanti',
    search: 'Cerca',
    clear: 'Cancella',
    loading: 'Caricamento…',
    copy: 'Copia',
    copied: 'Copiato',
    download: 'Scarica',
    upload: 'Carica',
    export: 'Esporta',
    import: 'Importa',
    yes: 'Sì',
    no: 'No',
    enabled: 'Attivato',
    disabled: 'Disattivato',
    on: 'Attivo',
    off: 'Disattivo',
    learnMore: 'Scopri di più',
    options: 'Opzioni',
    settings: 'Impostazioni',
    preferences: 'Preferenze',
    help: 'Aiuto',
    pin: 'Fissa',
    unpin: 'Sblocca',
    star: 'Aggiungi a speciali',
    unstar: 'Rimuovi da speciali',
    archive: 'Archivia',
    unarchive: 'Rimuovi dall’archivio',
    restore: 'Ripristina',
    moveToTrash: 'Sposta nel cestino',
    deletePermanently: 'Elimina definitivamente',
    protect: 'Proteggi',
    unprotect: 'Rimuovi protezione',
  },
  navigation: {
    notes: 'Note',
    allNotes: 'Tutte le note',
    files: 'File',
    starred: 'Speciali',
    archived: 'Archiviate',
    trash: 'Cestino',
    untagged: 'Senza etichetta',
    conflicts: 'Conflitti',
    views: 'Viste',
    smartViews: 'Viste intelligenti',
    tags: 'Etichette',
    folders: 'Cartelle',
    favorites: 'Preferiti',
    dashboard: 'Pannello',
    createNewNote: 'Crea una nuova nota',
    createNewTag: 'Crea una nuova etichetta',
    createNewFolder: 'Crea una nuova cartella',
    createNewSmartView: 'Crea una nuova vista intelligente',
    searchTags: 'Cerca etichette…',
    noTagsFound: 'Nessuna etichetta trovata. Prova un’altra ricerca.',
    noSmartViewsFound: 'Nessuna vista intelligente trovata. Prova un’altra ricerca.',
    collapseTagsPanel: 'Comprimi pannello etichette',
    expandTagsPanel: 'Espandi pannello etichette',
    goToItemsList: 'Vai all’elenco degli elementi',
    goToAccountMenu: 'Vai al menu dell’account',
    openPreferences: 'Apri preferenze',
  },
  account: {
    account: 'Account',
    signIn: 'Accedi',
    signOut: 'Esci',
    signUp: 'Registrati',
    register: 'Registrati',
    you: 'Tu',
    encryptionOn: 'Crittografia end-to-end attiva',
    notSignedIn: 'Non hai effettuato l’accesso',
    signInOrRegister: 'Accedi o registrati per sincronizzare le tue note',
    email: 'E-mail',
    password: 'Password',
    confirmPassword: 'Conferma password',
    syncNow: 'Sincronizza ora',
    lastSynced: 'Ultima sincronizzazione',
    importData: 'Importa',
    switchWorkspace: 'Cambia area di lavoro',
    lockApplication: 'Blocca l’applicazione',
    helpAndFeedback: 'Aiuto e feedback',
  },
  preferences: {
    title: 'Preferenze',
    general: 'Generali',
    account: 'Account',
    security: 'Sicurezza',
    appearance: 'Aspetto',
    backups: 'Backup',
    listed: 'Listed',
    plugins: 'Plugin',
    whatsNew: 'Novità',
    helpAndFeedback: 'Aiuto e feedback',
    language: 'Lingua',
    languageTitle: 'Lingua',
    languageDescription:
      'Scegli la lingua usata nell’interfaccia dell’app. L’app usa l’inglese per ciò che non è ancora tradotto.',
    languageChanged: 'Lingua aggiornata',
    defaults: 'Valori predefiniti',
    tools: 'Strumenti',
    spellcheck: 'Controllo ortografico',
    labs: 'Laboratori',
  },
}

export default it
