import type { LocaleResource } from './en'

const ja: LocaleResource = {
  common: {
    save: '保存',
    cancel: 'キャンセル',
    delete: '削除',
    confirm: '確認',
    close: '閉じる',
    edit: '編集',
    rename: '名前を変更',
    duplicate: '複製',
    remove: '削除',
    open: '開く',
    create: '作成',
    add: '追加',
    done: '完了',
    back: '戻る',
    next: '次へ',
    search: '検索',
    clear: 'クリア',
    loading: '読み込み中…',
    copy: 'コピー',
    copied: 'コピーしました',
    download: 'ダウンロード',
    upload: 'アップロード',
    export: 'エクスポート',
    import: 'インポート',
    yes: 'はい',
    no: 'いいえ',
    enabled: '有効',
    disabled: '無効',
    on: 'オン',
    off: 'オフ',
    learnMore: '詳細',
    options: 'オプション',
    settings: '設定',
    preferences: '環境設定',
    help: 'ヘルプ',
    pin: 'ピン留め',
    unpin: 'ピン留めを解除',
    star: 'スターを付ける',
    unstar: 'スターを外す',
    archive: 'アーカイブ',
    unarchive: 'アーカイブ解除',
    restore: '復元',
    moveToTrash: 'ゴミ箱に移動',
    deletePermanently: '完全に削除',
    protect: '保護',
    unprotect: '保護を解除',
  },
  navigation: {
    notes: 'ノート',
    allNotes: 'すべてのノート',
    files: 'ファイル',
    starred: 'スター付き',
    archived: 'アーカイブ済み',
    trash: 'ゴミ箱',
    untagged: 'トピックなし',
    conflicts: '競合',
    views: 'ビュー',
    smartViews: 'スマートビュー',
    tags: 'トピック',
    folders: 'フォルダ',
    favorites: 'お気に入り',
    dashboard: 'ダッシュボード',
    createNewNote: '新しいノートを作成',
    createNewTag: '新しいトピックを作成',
    createNewFolder: '新しいフォルダを作成',
    createNewSmartView: '新しいスマートビューを作成',
    searchTags: 'トピックを検索…',
    noTagsFound: 'トピックが見つかりません。別の検索をお試しください。',
    noSmartViewsFound: 'スマートビューが見つかりません。別の検索をお試しください。',
    collapseTagsPanel: 'トピックパネルを折りたたむ',
    expandTagsPanel: 'トピックパネルを展開',
    goToItemsList: '項目リストへ移動',
    goToAccountMenu: 'アカウントメニューへ移動',
    openPreferences: '環境設定を開く',
  },
  account: {
    account: 'アカウント',
    signIn: 'サインイン',
    signOut: 'サインアウト',
    signUp: '登録',
    register: '登録',
    you: 'あなた',
    encryptionOn: 'エンドツーエンド暗号化が有効',
    notSignedIn: 'サインインしていません',
    signInOrRegister: 'ノートを同期するにはサインインまたは登録してください',
    email: 'メールアドレス',
    password: 'パスワード',
    confirmPassword: 'パスワードを確認',
    syncNow: '今すぐ同期',
    lastSynced: '最終同期',
    importData: 'インポート',
    switchWorkspace: 'ワークスペースを切り替え',
    lockApplication: 'アプリをロック',
    helpAndFeedback: 'ヘルプとフィードバック',
  },
  preferences: {
    title: '環境設定',
    general: '一般',
    account: 'アカウント',
    security: 'セキュリティ',
    appearance: '外観',
    backups: 'バックアップ',
    listed: 'Listed',
    plugins: 'プラグイン',
    whatsNew: '新着情報',
    helpAndFeedback: 'ヘルプとフィードバック',
    language: '言語',
    languageTitle: '言語',
    languageDescription:
      'アプリのインターフェース全体で使用する言語を選択します。未翻訳の項目は英語で表示されます。',
    languageChanged: '言語を更新しました',
    defaults: '既定値',
    tools: 'ツール',
    spellcheck: 'スペルチェック',
    labs: 'ラボ',
  },
}

export default ja
