import type { LocaleResource } from './en'

const ja: LocaleResource = {
  common: {
    save: '保存',
    cancel: 'キャンセル',
    delete: '削除',
    confirm: '確認',
    close: '閉じる',
    edit: '編集',
    rename: '名前を変更',
    duplicate: '複製',
    remove: '削除',
    open: '開く',
    create: '作成',
    add: '追加',
    done: '完了',
    back: '戻る',
    next: '次へ',
    search: '検索',
    clear: 'クリア',
    loading: '読み込み中…',
    copy: 'コピー',
    copied: 'コピーしました',
    download: 'ダウンロード',
    upload: 'アップロード',
    export: 'エクスポート',
    import: 'インポート',
    yes: 'はい',
    no: 'いいえ',
    enabled: '有効',
    disabled: '無効',
    on: 'オン',
    off: 'オフ',
    learnMore: '詳細',
    options: 'オプション',
    settings: '設定',
    preferences: '環境設定',
    help: 'ヘルプ',
    pin: 'ピン留め',
    unpin: 'ピン留めを解除',
    star: 'スターを付ける',
    unstar: 'スターを外す',
    archive: 'アーカイブ',
    unarchive: 'アーカイブ解除',
    restore: '復元',
    moveToTrash: 'ゴミ箱に移動',
    deletePermanently: '完全に削除',
    protect: '保護',
    unprotect: '保護を解除',
  },
  navigation: {
    notes: 'ノート',
    allNotes: 'すべてのノート',
    files: 'ファイル',
    starred: 'スター付き',
    archived: 'アーカイブ済み',
    trash: 'ゴミ箱',
    untagged: 'トピックなし',
    conflicts: '競合',
    views: 'ビュー',
    smartViews: 'スマートビュー',
    tags: 'トピック',
    folders: 'フォルダ',
    favorites: 'お気に入り',
    dashboard: 'ダッシュボード',
    createNewNote: '新しいノートを作成',
    createNewTag: '新しいトピックを作成',
    createNewFolder: '新しいフォルダを作成',
    createNewSmartView: '新しいスマートビューを作成',
    searchTags: 'トピックを検索…',
    noTagsFound: 'トピックが見つかりません。別の検索をお試しください。',
    noSmartViewsFound: 'スマートビューが見つかりません。別の検索をお試しください。',
    collapseTagsPanel: 'トピックパネルを折りたたむ',
    expandTagsPanel: 'トピックパネルを展開',
    goToItemsList: '項目リストへ移動',
    goToAccountMenu: 'アカウントメニューへ移動',
    openPreferences: '環境設定を開く',
  },
  account: {
    account: 'アカウント',
    signIn: 'サインイン',
    signOut: 'サインアウト',
    signUp: '登録',
    register: '登録',
    you: 'あなた',
    encryptionOn: 'エンドツーエンド暗号化が有効',
    notSignedIn: 'サインインしていません',
    signInOrRegister: 'ノートを同期するにはサインインまたは登録してください',
    email: 'メールアドレス',
    password: 'パスワード',
    confirmPassword: 'パスワードを確認',
    syncNow: '今すぐ同期',
    lastSynced: '最終同期',
    importData: 'インポート',
    switchWorkspace: 'ワークスペースを切り替え',
    lockApplication: 'アプリをロック',
    helpAndFeedback: 'ヘルプとフィードバック',
  },
  preferences: {
    title: '環境設定',
    general: '一般',
    account: 'アカウント',
    security: 'セキュリティ',
    appearance: '外観',
    backups: 'バックアップ',
    listed: 'Listed',
    plugins: 'プラグイン',
    whatsNew: '新着情報',
    helpAndFeedback: 'ヘルプとフィードバック',
    language: '言語',
    languageTitle: '言語',
    languageDescription: 'アプリのインターフェース全体で使用する言語を選択します。未翻訳の項目は英語で表示されます。',
    languageChanged: '言語を更新しました',
    defaults: '既定値',
    tools: 'ツール',
    spellcheck: 'スペルチェック',
    labs: 'ラボ',
  },
  editor: {
    cut: '切り取り',
    copy: 'コピー',
    paste: '貼り付け',
    moreCutOptions: '切り取りのその他のオプション',
    moreCopyOptions: 'コピーのその他のオプション',
    morePasteOptions: '貼り付けのその他のオプション',

    tableOfContents: '目次',
    selectAll: 'すべて選択',
    selectAllText: 'テキストのみをすべて選択',
    deselectAll: '選択を解除',
    search: '検索',
    undo: '元に戻す',
    redo: 'やり直す',
    undoHistory: '元に戻す履歴',
    redoHistory: 'やり直す履歴',
    undoHistoryEmpty: '元に戻す履歴 — 元に戻す操作はまだありません',
    undoHistoryAvailable: '元に戻す履歴 — 一度に複数ステップ戻る',
    redoHistoryEmpty: 'やり直す履歴 — やり直す操作はありません',
    redoHistoryAvailable: 'やり直す履歴 — 一度に複数ステップ進む',

    formattingOptions: '書式設定オプション',
    bold: '太字',
    italic: '斜体',
    underline: '下線',
    strikethrough: '取り消し線',
    inlineCode: 'インラインコード',
    link: 'リンク',
    formatPainter: '書式のコピー — 書式をコピー（ダブルクリックで固定）',
    textStyle: 'テキストスタイル',
    textColor: '文字色',
    highlightColor: 'ハイライト色',
    typography: 'タイポグラフィ — 強調、アウトライン、文字・単語間隔',
    typographyTitle: 'タイポグラフィ',

    fontSize: 'フォントサイズ',
    chooseFontSize: 'フォントサイズを選択',
    decreaseFontSize: 'フォントサイズを小さくする',
    increaseFontSize: 'フォントサイズを大きくする',
    fontFamily: 'フォント',
    customFontFamily: 'カスタム',

    bulletedList: '箇条書きリスト',
    numberedList: '番号付きリスト',
    checkList: 'チェックリスト',
    quote: '引用',
    codeBlock: 'コードブロック',
    changeCase: '大文字・小文字を変更',
    sortAndDedupeLines: '行を並べ替えて重複を削除',
    alignment: '配置',
    paragraphLayout: '段落レイアウト — 行・段落の間隔、インデント、網かけ',
    paragraphLayoutTitle: '段落レイアウト',
    listStyleMarker: 'リストスタイル — 箇条書き・番号のマーカー',
    formattingMarks: '編集記号',
    insert: '挿入',

    insertRowAbove: '上に行を挿入',
    insertRowBelow: '下に行を挿入',
    insertColumnLeft: '左に列を挿入',
    insertColumnRight: '右に列を挿入',
    deleteRow: '行を削除',
    deleteColumn: '列を削除',
    toggleRowHeader: '行ヘッダーを切り替え',
    toggleColumnHeader: '列ヘッダーを切り替え',
    deleteTable: 'テーブルを削除',

    rows: '行',
    columns: '列',
    cells: 'セル',
    table: 'テーブル',
    block: 'ブロック',

    alignLeft: '左揃え',
    alignCenter: '中央揃え',
    alignRight: '右揃え',

    editLink: 'リンクを編集',
    removeLink: 'リンクを削除',

    zoomIntoBlock: 'ブロックにズーム',

    blockStyle: 'ブロックスタイル',
    heading1: '見出し1',
    heading2: '見出し2',
    heading3: '見出し3',
    normalText: '標準テキスト',
    moreFormatting: 'その他の書式設定',

    createNoteFromSelectionTitle: '選択範囲から新しいノートを作成',
    createNoteFromSelectionDescription:
      '選択範囲を含む新しいノートを作成し、選択範囲を新しいノートへのリンクに置き換えます。',

    dismissKeyboard: 'キーボードを閉じる',

    tableOfContentsLower: '目次',
    noHeadingsFound: '見出しが見つかりません',
    textFormattingOptions: 'テキスト書式設定オプション',
    highlight: 'ハイライト',
    subscript: '下付き文字',
    superscript: '上付き文字',
    clearFormatting: '書式をクリア',
    normal: '標準',
    smartChecklist: 'スマートチェックリスト',
    restoreCompletedTasks: '完了したタスクを復元',
    completeAllChecklistItems: 'すべての項目を完了にする',
    completeAllChecklistItemsDescription: 'カーソルまたは選択範囲があるチェックリストのすべての項目を完了にします。',
    completeSelectedChecklistItems: '選択した項目を完了にする',
    uncompleteSelectedChecklistItems: '選択した項目を未完了にする',
    noChecklistItemsSelected: 'チェックリストにカーソルを置くか、チェックリストの項目を選択してください。',
    leftAlign: '左揃え',
    centerAlign: '中央揃え',
    rightAlign: '右揃え',
    justify: '両端揃え',

    searchBlocksPlaceholder: 'ブロックを検索…',
    searchBlocksToInsert: '挿入するブロックを検索',
    clearSearch: '検索をクリア',
    noBlocksMatch: '「{{query}}」に一致するブロックがありません',
    customizeToolbar: 'ツールバーをカスタマイズ',

    custom: 'カスタム',
    clear: 'クリア',
    textColorSwatch: '文字色 {{color}}',
    highlightColorSwatch: 'ハイライト色 {{color}}',
    textShadingSwatch: '文字の網かけ {{color}}',
    noTextShading: '文字の網かけなし',

    uppercase: '大文字',
    lowercase: '小文字',
    camelCase: 'キャメルケース',

    sortLines: '行を並べ替え',
    deduplicate: '重複を削除',
    multiKeySort: '複数キーで並べ替え（1番目、2番目、3番目）…',
    sortAndDeduplicateLines: '行を並べ替えて重複を削除',

    emphasisMarks: '圏点',
    outlineTextStroke: 'アウトライン（文字の輪郭）',
    letterSpacingKerning: '文字間隔（カーニング）',
    wordSpacing: '単語間隔',
    clearTypography: 'タイポグラフィをクリア',
    spacingTight: '狭い',
    spacingNormal: '標準',
    spacingWide: '広い',
    spacingWider: 'より広い',
    spacingWidest: '最も広い',

    undoMultipleSteps: '複数ステップ元に戻す',
    redoMultipleSteps: '複数ステップやり直す',
    emptyHistoryPreview: '（空）',

    pasteOptions: '貼り付けオプション',
    copyOptions: 'コピーオプション',
    cutOptions: '切り取りオプション',
    pasteWithoutFormatting: '書式なしで貼り付け',
    pasteClean: 'クリーン貼り付け（隠し文字を除去）',
    keepSourceFormatting: 'コピー元の書式を保持',
    matchDestinationFormatting: '貼り付け先の書式に合わせる',
    pasteAsImage: '画像として貼り付け',
    copyWithoutFormatting: '書式なしでコピー',
    copyTextOnly: 'テキストのみをコピー',
    copyImagesOnly: '画像のみをコピー',
    cutWithoutFormatting: '書式なしで切り取り',
    cutTextOnly: 'テキストのみを切り取り',
    cutImagesOnly: '画像のみを切り取り',

    lineSpacing: '行間',
    spaceBefore: '前の間隔',
    spaceAfter: '後の間隔',
    indentation: 'インデント',
    none: 'なし',
    increaseLeft: '左を増やす',
    decreaseLeft: '左を減らす',
    increaseRight: '右を増やす',
    decreaseRight: '右を減らす',
    firstLine: '最初の行',
    noFirstLine: '最初の行なし',
    textShading: '文字の網かけ',

    listStyle: 'リストスタイル',
    bulleted: '箇条書き',
    numbered: '番号付き',
    bulletedListMarkers: '箇条書きマーカーのスタイル',
    numberedListMarkers: '番号付けのスタイル',
    multilevelList: '複数レベルのリスト',
    multilevelListHint: 'ネストレベルごとにマーカーを選択',
    multilevelLevelDefault: '既定',
    level: 'レベル',
    apply: '適用',

    insertTable: 'テーブルを挿入',
    insertImageFromUrl: 'URLから画像を挿入',
    sortLinesModalTitle: '行を並べ替え',

    blockPicker: 'ブロックピッカー',

    blockParagraph: '段落',
    blockCallout: 'コールアウト',
    blockDivider: '区切り線',
    blockCollapsible: '折りたたみ',
    blockImageFromUrl: 'URLからの画像',
    blockUploadFile: 'ファイルをアップロード',
    blockDrawing: '描画',
    blockQrCode: 'QRコード',
    blockTable: 'テーブル',
    blockKanbanBoard: 'カンバンボード',
    blockCalendar: 'カレンダー',
    blockTimeline: 'タイムライン',
    blockDataTable: 'データテーブル',
    blockSqlQuery: 'SQLクエリ',
    blockMermaidDiagram: 'Mermaid図',
    blockGanttChart: 'ガントチャート',
    blockTimingDiagram: 'タイミング図',
    blockMusicStaff: '五線譜',
    blockTradingViewChart: 'TradingViewチャート',
    blockStockChart: '株価チャート',
    blockEmbed: '埋め込み',
    blockEmbedWebsite: 'ウェブサイトを埋め込み',
    blockTweet: 'ツイート',
    blockEquation: '数式',
    blockInlineEquation: 'インライン数式',
    blockFootnote: '脚注',
    blockBookmark: 'ブックマーク',
    blockGeneratePassword: '暗号学的に安全なパスワードを生成',
    blockClock: '時計',
    blockCurrentDateTime: '現在の日付と時刻',
    blockCurrentTime: '現在の時刻',
    blockCurrentDate: '現在の日付',

    blockCategoryBasic: '基本',
    blockCategoryLists: 'リスト',
    blockCategoryMedia: 'メディア',
    blockCategoryDataTables: 'データとテーブル',
    blockCategoryDiagramsCharts: '図とチャート',
    blockCategoryFinance: '金融',
    blockCategoryEmbeds: '埋め込み',
    blockCategoryAdvanced: '詳細',
  },
  files: {
    dropToUploadTooltip: 'ファイルをドロップしてアップロードし、現在のファイルにリンクします',
    fileAriaLabel: 'ファイル',
    fileReadonly: 'このファイルは読み取り専用です',
    fileInformationPanel: 'ファイル情報パネル',
    details: '詳細',

    selectedFilesCount: '{{count}}件のファイルを選択中',
    actionsPerformedOnSelected: '選択したすべてのファイルに対して操作が実行されます。',
    cancelMultipleSelection: '複数選択をキャンセル',

    fileOptions: 'ファイルオプション',
    fileContextMenu: 'ファイルのコンテキストメニュー',
    fileOptionsMenu: 'ファイルオプションメニュー',
    fileOptionsPanel: 'ファイルオプションパネル',

    noFilesSelected: 'ファイルが選択されていません',
    detachFromNote: 'ノートから切り離す',
    attachToNote: 'ノートに添付',
    passwordProtect: 'パスワードで保護',
    downloadSeparately: '個別にダウンロード',
    downloadAsArchive: 'アーカイブとしてダウンロード',
    failedToDownloadArchive: 'ファイルをアーカイブとしてダウンロードできませんでした',
    fileId: 'ファイルID:',
    size: 'サイズ:',
    totalSize: '合計サイズ:',

    backedUpOn: '{{date}}にバックアップ済み',
    configureFileBackups: 'ファイルバックアップを設定',
    fileNotBackedUpLocally: 'ファイルはローカルにバックアップされていません',

    noFoldersYet: 'フォルダはまだありません',
    moveToFolder: 'フォルダに移動',
    folderSelectionMenu: 'フォルダ選択メニュー',
    noFolder: 'フォルダなし',

    fileProtected: 'このファイルは保護されています。',
    authenticateToView: 'このファイルを表示するには認証してください。',
    addPasscodeToView: 'このファイルの表示に認証を必要とするには、パスコードを追加するかアカウントを作成してください。',
    openAccountMenu: 'アカウントメニューを開く',
    authenticate: '認証',
    viewFile: 'ファイルを表示',
    loading: '読み込み中...',

    fileCannotBePreviewed: 'このファイルはプレビューできません。',
    errorLoadingFile:
      'ファイルの読み込み中にエラーが発生しました。もう一度お試しいただくか、ファイルをダウンロードして別のアプリケーションで開いてください。',
    tryAgain: 'もう一度試す',
    downloadToView: 'このファイルを表示するには、ダウンロードして別のアプリケーションで開いてください。',

    fileInformation: 'ファイル情報',
    type: '種類:',
    decryptedSize: '復号後のサイズ:',
    encryptedSize: '暗号化後のサイズ:',
    created: '作成日:',
    lastModified: '最終更新日:',

    done: '完了',
    showFileOptions: 'ファイルオプションを表示',
    showFileInfo: 'ファイル情報を表示',
    hideFileInfo: 'ファイル情報を非表示',
    showLinksSection: 'リンクセクションを表示',
    hideLinksSection: 'リンクセクションを非表示',
    submit: '送信',
    renameFile: 'ファイル名を変更',
    showLinkedItems: 'リンクされた項目を表示',
    closeModal: 'モーダルを閉じる',
    filePreviewModal: 'ファイルプレビューモーダル',

    leftAlign: '左揃え',
    centerAlign: '中央揃え',
    rightAlign: '右揃え',

    videoCannotBePreviewed: 'この動画はプレビューできません。',

    audioCannotBePlayed: 'このオーディオは再生できません。',
    downloadToListen: 'このファイルを再生するには、ダウンロードして別のアプリケーションで開いてください。',

    externalAppOnly: 'このファイルは外部アプリでのみプレビューできます',
    openFilePreview: 'ファイルプレビューを開く',
    loadingPdfViewer: 'PDFビューアを読み込み中...',

    zoomOut: 'ズームアウト',
    zoomIn: 'ズームイン',
    resetToActualSize: '実際のサイズにリセット',
    resetTo100: '100%にリセット',
    fitToScreen: '画面に合わせる',

    unableToRenderPdf: 'このPDFを表示できません。',
    pdfCorruptedOrProtected: 'ファイルが破損しているか、パスワードで保護されている可能性があります。',
    loadingPdf: 'PDFを読み込み中...',
    previousPage: '前のページ',
    pageNumber: 'ページ番号',
    nextPage: '次のページ',
    fitWidth: '幅に合わせる',
    searchInDocumentShortcut: 'ドキュメント内を検索（Ctrl/Cmd+F）',
    searchInDocument: 'ドキュメント内を検索',
    copyLinkToPage: '{{page}}ページへのリンクをコピー',
    copyLinkToThisPage: 'このページへのリンクをコピー',
    copyLinkToSelectedText: '選択したテキストへのリンクをコピー',
    cancelOcr: 'OCRをキャンセル',
    preparingOcr: 'OCRを準備中...',
    ocrProgress: 'OCR {{current}} / {{total}}ページ（{{percent}}%）',
    ocrCachedReRunTooltip:
      'テキストは抽出済みです（キャッシュ）。ブラウザでOCRを再実行します（デバイス上に留まります）。',
    ocrExtractedReRunTooltip: 'テキストを抽出しました。ブラウザでOCRを再実行します（デバイス上に留まります）。',
    ocrExtractTooltip:
      'OCRでスキャンページからテキストを抽出します。ブラウザで実行され、デバイスから何も送信されません（低速、言語データをダウンロードします）。',
    extractTextWithOcrBrowser: 'ブラウザでOCRを使ってテキストを抽出',
    reRunOcrBrowser: 'OCRを再実行（ブラウザ）',
    extractTextOcr: 'テキストを抽出（OCR）',
    serverOcrTooltip:
      'サーバー上でOCRを実行します。このPDFのページ画像をサーバーに送信し、エンドツーエンド暗号化から外れます — サーバーがその内容を読み取れます。ブラウザOCRはすべてをデバイス上に保持します。',
    runOcrOnServerAria: 'サーバー上でOCRを実行（ページ画像をサーバーに送信、エンドツーエンド暗号化から外れます）',
    runOcrOnServer: 'サーバーでOCRを実行',
    copyAllExtractedText: '抽出したテキストをすべてコピー',
    copyExtractedTextAria: '抽出したテキストをコピー',
    findInDocument: 'ドキュメント内を検索',
    matchCase: '大文字・小文字を区別',
    noResults: '結果がありません',
    matchOfTotal: '{{total}}件中{{current}}件',
    previousMatch: '前の一致',
    nextMatch: '次の一致',
    closeSearch: '検索を閉じる',
    serverOcrDisclosurePrefix: 'サーバーOCRはお使いのアカウントで利用できます。このPDFのページ画像をサーバーに送信し、',
    serverOcrDisclosureBold: 'エンドツーエンド暗号化から外れます',
    serverOcrDisclosureSuffix:
      ' — サーバー（およびそれを管理する者）がその内容を読み取れます。ブラウザOCRはすべてをデバイス上に保持します。既定はブラウザOCRです。',
    ocrRunningServer:
      'サーバーOCR: このPDFのページ画像がサーバーにアップロードされており、エンドツーエンド暗号化から外れます — サーバーがその内容を読み取れます。（ブラウザOCRはすべてをデバイス上に保持します。）',
    ocrRunningBrowser:
      'OCRはこのデバイスのブラウザで実行されます（ファイルはエンドツーエンドで暗号化されたままです）。低速で、初回使用時に言語データをダウンロードします。',
    ocrDoneServer:
      'サーバーOCRが完了しました。ページ画像はサーバーに送信されました（これによりエンドツーエンド暗号化から外れました）。精度はスキャン品質により異なります。抽出したテキストは検索・コピー可能になり、このデバイスにキャッシュされます。',
    ocrDoneBrowser:
      'OCRが完了しました。精度はスキャン品質により異なります。抽出したテキストは検索・コピー可能になり、このデバイスにキャッシュされます。',

    copiedExtractedText: '抽出したテキストをコピーしました',
    copiedLinkToPage: '{{page}}ページへのリンクをコピーしました',
    copiedLinkToSelectedText: '選択したテキストへのリンクをコピーしました',

    serverOcrFailed: 'サーバーOCRに失敗しました: {{message}}',
    ocrUnknownError: '不明なエラー',
    ocrFailed: 'OCRに失敗しました。言語データのダウンロードに失敗した可能性があります。',
  },
  notes: {
    notesAndFiles: 'ノートとファイル',
    selectAllItems: 'すべての項目を選択',
    selectedCount: '{{count}}件選択中',
    cancelMultipleSelection: '複数選択をキャンセル',
    noFilesInFolder: 'このフォルダにファイルはありません。',
    noItems: '項目がありません。',
    loading: '読み込み中...',
    uploadFileWithShortcut: 'ファイルをアップロード {{shortcut}}',
    createNoteInTopicWithShortcut: '選択したトピックに新しいノートを作成 {{shortcut}}',
    dropFilesToUpload: 'ファイルをドロップしてアップロードし、トピック「{{title}}」にリンクします',

    noFilesYet: 'ファイルはまだありません',
    filesAttachedAppearHere:
      'ノートに添付したファイルがここに表示されます。このページから直接ファイルをアップロードすることもできます。',
    uploadFiles: 'ファイルをアップロード',

    syncing: '同期中...',
    loadingItemsProgress: '{{total}}件中{{current}}件を読み込み中...',
    potentiallyOutOfSync: '同期されていない可能性があります',
    openDisplayOptionsMenu: '表示オプションメニューを開く',
    displayOptionsMenu: '表示オプションメニュー',
    displayOptions: '表示オプション',
    expandTopicsPanel: 'トピックパネルを展開',
    collapseNotesPanel: 'ノートパネルを折りたたむ',

    addItem: '項目を追加',
    uploadFolder: 'フォルダをアップロード',
    takePhoto: '写真を撮る',
    recordVideo: '動画を録画',

    searchPlaceholder: '検索...',

    notesListOptionsMenu: 'ノートリストオプションメニュー',
    preferencesFor: '環境設定の対象:',
    global: 'グローバル',
    reset: 'リセット',
    upgradeForPerTopicPreferences: 'トピックごとの環境設定にアップグレード',
    perTopicPreferencesMessageWithDaily:
      'トピックごとの表示設定と、全く新しいデイリーノートのカレンダーレイアウトで、強力なワークフローと整理レイアウトを作成できます。',
    perTopicPreferencesMessage: 'トピックごとの表示設定で、強力なワークフローと整理レイアウトを作成できます。',
    sortBy: '並べ替え',
    relevanceBestMatch: '関連度（最適な一致）',
    dateModified: '更新日',
    creationDate: '作成日',
    title: 'タイトル',
    customDragToReorder: 'カスタム（ドラッグして並べ替え）',
    view: '表示',
    showNotePreview: 'ノートのプレビューを表示',
    showDate: '日付を表示',
    showTags: 'トピックを表示',
    showIcon: 'アイコンを表示',
    other: 'その他',
    showPinned: 'ピン留めを表示',
    showProtected: '保護された項目を表示',
    showArchived: 'アーカイブ済みを表示',
    showTrashed: 'ゴミ箱の項目を表示',
    dailyNotebook: 'デイリーノート',
    labs: 'Labs',
    dailyNotebookDescription: 'カレンダーベースのレイアウトで毎日新しいノートを記録',
    tableView: 'テーブル表示',
    tableViewDescription: '現在のトピックのノートとファイルをテーブルレイアウトで表示',
    newNoteDefaults: '新規ノートの既定値',

    noteType: 'ノートの種類',
    selectDefaultNoteType: '既定のノートの種類を選択',
    titleFormat: 'タイトル形式',
    selectTitleFormat: 'ノートのタイトルの形式を選択',
    customFormatPlaceholder: '例: YYYY-MM-DD',
    preview: 'プレビュー: ',
    useBracketsToEscape: '. 使用 ',
    toEscapeFormatting: ' 書式をエスケープします。',

    protected: '保護済み',
    modified: '更新',
    now: '今',

    editingDisabled: '編集無効',
    trashed: 'ゴミ箱',
    archived: 'アーカイブ済み',
    files: 'ファイル',
    starred: 'スター付き',
    fileBackedUpLocally: 'ファイルはローカルにバックアップされています',

    conflictedCopy: '競合したコピー',

    allFiles: 'すべてのファイル',
    noFolder: 'フォルダなし',
    folderNamePlaceholder: 'フォルダ名',
    createNewFolder: '新しいフォルダを作成',
    newFolder: '新しいフォルダ',

    currentStreak: '現在の連続記録',
    dayWithCount_other: '日',
  },
  auth: {
    unableToComputePrivateUsername: 'プライベートユーザー名を計算できません。',
    advancedOptions: '詳細オプション',
    privateUsernameMode: 'プライベートユーザー名モード',
    username: 'ユーザー名',
    useStrictSignIn: '厳格なサインインを使用',
    useRecoveryCode: 'リカバリーコードを使用',
    recoveryCode: 'リカバリーコード',

    deleteLocalDataTitle: 'ローカルデータを削除しますか?',
    noMergeWarning:
      'ローカルデータをマージしないことを選択しました。続行すると、ローカルのノートとトピックは完全に削除され、アカウントのデータに置き換えられます。この操作は元に戻せません。',
    noMergeConfirmQuestion: 'マージせずに続行してもよろしいですか?',
    deleteLocalDataAndContinue: 'ローカルデータを削除して続行',

    passwordResetWarningPart1: 'ノートはパスワードを使って暗号化されているため、',
    passwordResetWarningHighlight: 'Standard Red Notesにはパスワードのリセット機能がありません',
    passwordResetWarningPart2: '。パスワードを忘れると、データへのアクセスを永久に失います。',
    confirmPassword: 'パスワードを確認',
    creatingAccount: 'アカウントを作成中...',
    createAccountAndSignIn: 'アカウントを作成してサインイン',
    staySignedIn: 'サインインを維持',
    goBack: '戻る',
    humanVerification: '本人確認',
    confirmPasswordTitle: 'パスワードを確認',

    createAccount: 'アカウントを作成',
    workspaceNameOptional: 'ワークスペース名（任意）',

    generalAccountMenuLabel: '一般アカウントメニュー',
    signedInAs: 'サインイン中:',
    syncing: '同期中...',
    lastSynced: '最終同期:',
    offlineSignInPrompt:
      'オフラインです。サインインすると、すべてのデバイス間でノートと環境設定を同期し、エンドツーエンド暗号化を有効にできます。',
    offline: 'オフライン',
    accountSettings: 'アカウント設定',
    createFreeAccount: '無料アカウントを作成',
    documentation: 'ドキュメント',
    keyboardShortcuts: 'キーボードショートカット',
    commandPalette: 'コマンドパレット',
    signOutWorkspace: 'ワークスペースからサインアウト',

    mergeLocalData: 'ローカルデータをマージ（{{count}}件のノートとトピック）',
    mergeLocalDataTooltip:
      'チェックを外すと、ローカルのノートとトピックは完全に削除され、アカウントのデータに置き換えられます。',

    homeServerNotRunning:
      'ホームサーバーが実行されていません。環境設定を開き、ホームサーバータブから起動してください。',
    serverDefault: '既定',
    serverCustom: 'カスタム',
    serverHomeServer: 'ホームサーバー',
    syncServer: '同期サーバー',

    signingIn: 'サインイン中...',

    syncUnreachable: '同期に到達できません',
    syncUnreachableMessage: 'うーん…アカウントを同期できないようです。原因: {{reason}}',

    workspaceSwitcherMenuLabel: 'ワークスペース切り替えメニュー',
    signOutAllWorkspacesConfirm: 'このデバイス上のすべてのワークスペースからサインアウトしてもよろしいですか?',
    signOutAll: 'すべてサインアウト',
    addAnotherWorkspace: '別のワークスペースを追加',
    signOutAllWorkspaces: 'すべてのワークスペースからサインアウト',

    deleteAccountTitle: 'アカウントを削除しますか?',
    deleteMyAccountForGood: 'アカウントを完全に削除',

    dataNotBackedUp: 'データはバックアップされていません',
    signInOrRegisterToSync:
      'サインインまたは登録して、エンドツーエンド暗号化でノートを他のデバイスに同期してください。',
    openAccountMenu: 'アカウントメニューを開く',
    ignoreWarning: '警告を無視',

    waitingForSecurityKey: 'セキュリティキーを待機中...',
    authenticationSuccessful: '認証に成功しました!',
    insertSecurityKeyPrompt: 'ハードウェアセキュリティキーを挿入し、下のボタンを押して認証してください。',
    authenticate: '認証',
  },
  search: {
    placeholder: '検索...',

    protectedContents: '保護されたコンテンツ',
    archived: 'アーカイブ済み',
    trashed: 'ゴミ箱',

    aiUnavailable: 'AIによる再ランク付けは利用できないか、結果が返されませんでした。',
    aiUnavailableTooltip: 'AIコンテキスト検索は利用できません。',
    aiTypeQueryFirst: '先に検索クエリを入力してください。',
    aiTooltip:
      '設定したAIプロバイダーを使用して、上位の結果を意味的な関連度で再ランク付けします。' +
      'それらの候補のタイトルと短いスニペット、およびクエリをプロバイダーに送信します。',
    aiSearchWithAi: 'AIで検索',
    aiRanking: 'ランク付け中…',
    aiRankedByRelevance: 'AIの関連度で並べ替え済み',
    aiPrivacyNotice:
      '上位の結果のタイトルとスニペット、およびクエリをAIプロバイダーに送信します。クラウドプロバイダーはそれらを' +
      '参照できます — ローカルモデルはデバイス上に保持します。',

    advancedFilters: '詳細検索フィルター',
    filters: 'フィルター',
    noteTypeAny: 'すべての種類',
    noteTypePlainText: 'プレーンテキスト',
    noteTypeRichText: 'リッチテキスト',
    noteTypeSuper: 'Super',
    noteTypeMarkdown: 'Markdown',
    noteTypeCode: 'コード',
    noteTypeTask: 'タスク',
    noteTypeSpreadsheet: 'スプレッドシート',
    flagProtected: '保護済み',
    flagPinned: 'ピン留め',
    flagArchived: 'アーカイブ済み',
    flagStarred: 'スター付き',
    flagTrashed: 'ゴミ箱',
    topicsLabel: 'トピック（カンマ区切り）',
    topicsPlaceholder: '仕事, プライベート',
    noteTypeLabel: 'ノートの種類',
    searchInLabel: '検索対象',
    searchInTitleAndContent: 'タイトルと内容',
    modifiedWithinLabel: '更新期間',
    datePreset: '過去{{label}}',
    createdAfterLabel: '作成日（以降）',
    createdBeforeLabel: '作成日（以前）',
    updatedAfterLabel: '更新日（以降）',
    updatedBeforeLabel: '更新日（以前）',
    statusLabel: 'ステータス',
    hasAttachments: '添付ファイルあり',
    caseSensitive: '大文字・小文字を区別',
    clearAllFilters: 'すべてのフィルターをクリア',
  },
  sharing: {
    vaultSelectionMenu: 'ボールト選択メニュー',
    vaultOptionsMenu: 'ボールトオプションメニュー',
    vaultOptions: 'ボールトオプション',
    noVaultsFound: 'ボールトが見つかりません',
    moveToVault: 'ボールトに移動',
    moveOutOfVault: '{{name}}から移動',
    vaultsFallbackName: 'ボールト',
    editVault: 'ボールトを編集',
    lockVault: 'ボールトをロック',
    unlockVault: 'ボールトのロックを解除',
    openVaultSettings: 'ボールト設定を開く',
    selectionModeMultiple: '複数',
    selectionModeOne: '1件',
    lastEditedBy: '最終編集者',
    sharedBy: '共有者',
    sharedByContact: '連絡先による共有',
    vaultName: 'ボールト名',
    sharedInVault: 'ボールトで共有中',
    copiedToClipboard: 'クリップボードにコピーしました',
    failedToCopyToClipboard: 'クリップボードへのコピーに失敗しました',
    copyExampleToClipboard: '例をクリップボードにコピー',
    copiedExclaim: 'コピーしました!',
    shareUnavailableTitle: '共有は利用できません',
    shareUnavailableMessage: 'この共有リンクは利用できなくなりました。',
    invalidLinkTitle: '無効なリンク',
    invalidLinkMessage: 'この共有リンクは無効か、キーが見つかりません。',
    selfDestructTitle: 'このノートは閲覧後に自動消去されます',
    oneTimeViewConsumed: 'あなたは一度きりの閲覧リンクを読んでいます。このリンクは消費され、再度開くことはできません',
    oneTimeViewExpiresClause_other: '。また、最初に開いてから{{count}}分後に完全に期限切れになります',
    linkExpires_other: 'このリンクは最初に開いてから{{count}}分後に期限切れになります。',
    untitled: '無題',
    tagHasNoNotes: 'このトピックにはノートがありません。',
    publicReadOnlyFooter: 'これは公開の読み取り専用共有リンクです。内容はお使いのブラウザで復号されました。',
    confidentialWatermark: '社外秘 · {{datetime}}',
    contentHiddenTitle: 'コンテンツは非表示です',
    contentHiddenMessage: '共有コンテンツを表示するには、このウィンドウにフォーカスを戻してください。',
  },
}

export default ja
