import type { LocaleResource } from './en'

const ko: LocaleResource = {
  common: {
    save: '저장',
    cancel: '취소',
    delete: '삭제',
    confirm: '확인',
    close: '닫기',
    edit: '편집',
    rename: '이름 변경',
    duplicate: '복제',
    remove: '제거',
    open: '열기',
    create: '만들기',
    add: '추가',
    done: '완료',
    back: '뒤로',
    next: '다음',
    search: '검색',
    clear: '지우기',
    loading: '불러오는 중…',
    copy: '복사',
    copied: '복사됨',
    download: '다운로드',
    upload: '업로드',
    export: '내보내기',
    import: '가져오기',
    yes: '예',
    no: '아니요',
    enabled: '사용',
    disabled: '사용 안 함',
    on: '켜짐',
    off: '꺼짐',
    learnMore: '자세히 알아보기',
    options: '옵션',
    settings: '설정',
    preferences: '환경설정',
    help: '도움말',
    pin: '고정',
    unpin: '고정 해제',
    star: '별표 표시',
    unstar: '별표 해제',
    archive: '보관',
    unarchive: '보관 해제',
    restore: '복원',
    moveToTrash: '휴지통으로 이동',
    deletePermanently: '영구 삭제',
    protect: '보호',
    unprotect: '보호 해제',
  },
  navigation: {
    notes: '노트',
    allNotes: '모든 노트',
    files: '파일',
    starred: '별표 표시됨',
    archived: '보관됨',
    trash: '휴지통',
    untagged: '주제 없음',
    conflicts: '충돌',
    views: '보기',
    smartViews: '스마트 보기',
    tags: '주제',
    folders: '폴더',
    favorites: '즐겨찾기',
    dashboard: '대시보드',
    createNewNote: '새 노트 만들기',
    createNewTag: '새 주제 만들기',
    createNewFolder: '새 폴더 만들기',
    createNewSmartView: '새 스마트 보기 만들기',
    searchTags: '주제 검색…',
    noTagsFound: '주제를 찾을 수 없습니다. 다른 검색어를 시도하세요.',
    noSmartViewsFound: '스마트 보기를 찾을 수 없습니다. 다른 검색어를 시도하세요.',
    collapseTagsPanel: '주제 패널 접기',
    expandTagsPanel: '주제 패널 펼치기',
    goToItemsList: '항목 목록으로 이동',
    goToAccountMenu: '계정 메뉴로 이동',
    openPreferences: '환경설정 열기',
  },
  account: {
    account: '계정',
    signIn: '로그인',
    signOut: '로그아웃',
    signUp: '회원가입',
    register: '회원가입',
    you: '나',
    encryptionOn: '종단 간 암호화 사용 중',
    notSignedIn: '로그인하지 않았습니다',
    signInOrRegister: '노트를 동기화하려면 로그인하거나 가입하세요',
    email: '이메일',
    password: '비밀번호',
    confirmPassword: '비밀번호 확인',
    syncNow: '지금 동기화',
    lastSynced: '마지막 동기화',
    importData: '가져오기',
    switchWorkspace: '작업 공간 전환',
    lockApplication: '앱 잠금',
    helpAndFeedback: '도움말 및 피드백',
  },
  preferences: {
    title: '환경설정',
    general: '일반',
    account: '계정',
    security: '보안',
    appearance: '모양',
    backups: '백업',
    listed: 'Listed',
    plugins: '플러그인',
    whatsNew: '새로운 기능',
    helpAndFeedback: '도움말 및 피드백',
    language: '언어',
    languageTitle: '언어',
    languageDescription: '앱 인터페이스 전체에서 사용할 언어를 선택하세요. 아직 번역되지 않은 항목은 영어로 표시됩니다.',
    languageChanged: '언어가 업데이트되었습니다',
    defaults: '기본값',
    tools: '도구',
    spellcheck: '맞춤법 검사',
    labs: '실험실',
  },
}

export default ko
