import type { LocaleResource } from './en'

const nl: LocaleResource = {
  common: {
    save: 'Opslaan',
    cancel: 'Annuleren',
    delete: 'Verwijderen',
    confirm: 'Bevestigen',
    close: 'Sluiten',
    edit: 'Bewerken',
    rename: 'Naam wijzigen',
    duplicate: 'Dupliceren',
    remove: 'Verwijderen',
    open: 'Openen',
    create: 'Aanmaken',
    add: 'Toevoegen',
    done: 'Klaar',
    back: 'Terug',
    next: 'Volgende',
    search: 'Zoeken',
    clear: 'Wissen',
    loading: 'Laden…',
    copy: 'Kopiëren',
    copied: 'Gekopieerd',
    download: 'Downloaden',
    upload: 'Uploaden',
    export: 'Exporteren',
    import: 'Importeren',
    yes: 'Ja',
    no: 'Nee',
    enabled: 'Ingeschakeld',
    disabled: 'Uitgeschakeld',
    on: 'Aan',
    off: 'Uit',
    learnMore: 'Meer informatie',
    options: 'Opties',
    settings: 'Instellingen',
    preferences: 'Voorkeuren',
    help: 'Help',
    pin: 'Vastmaken',
    unpin: 'Losmaken',
    star: 'Markeren',
    unstar: 'Markering verwijderen',
    archive: 'Archiveren',
    unarchive: 'Uit archief halen',
    restore: 'Herstellen',
    moveToTrash: 'Naar prullenbak verplaatsen',
    deletePermanently: 'Permanent verwijderen',
    protect: 'Beveiligen',
    unprotect: 'Beveiliging opheffen',
  },
  navigation: {
    notes: 'Notities',
    allNotes: 'Alle notities',
    files: 'Bestanden',
    starred: 'Gemarkeerd',
    archived: 'Gearchiveerd',
    trash: 'Prullenbak',
    untagged: 'Zonder label',
    conflicts: 'Conflicten',
    views: 'Weergaven',
    smartViews: 'Slimme weergaven',
    tags: 'Labels',
    folders: 'Mappen',
    favorites: 'Favorieten',
    dashboard: 'Dashboard',
    createNewNote: 'Een nieuwe notitie maken',
    createNewTag: 'Een nieuw label maken',
    createNewFolder: 'Een nieuwe map maken',
    createNewSmartView: 'Een nieuwe slimme weergave maken',
    searchTags: 'Labels zoeken…',
    noTagsFound: 'Geen labels gevonden. Probeer een andere zoekopdracht.',
    noSmartViewsFound: 'Geen slimme weergaven gevonden. Probeer een andere zoekopdracht.',
    collapseTagsPanel: 'Labelpaneel inklappen',
    expandTagsPanel: 'Labelpaneel uitklappen',
    goToItemsList: 'Ga naar itemlijst',
    goToAccountMenu: 'Ga naar accountmenu',
    openPreferences: 'Voorkeuren openen',
  },
  account: {
    account: 'Account',
    signIn: 'Aanmelden',
    signOut: 'Afmelden',
    signUp: 'Registreren',
    register: 'Registreren',
    you: 'Jij',
    encryptionOn: 'Eind-tot-eind-versleuteling ingeschakeld',
    notSignedIn: 'Je bent niet aangemeld',
    signInOrRegister: 'Meld je aan of registreer om je notities te synchroniseren',
    email: 'E-mail',
    password: 'Wachtwoord',
    confirmPassword: 'Wachtwoord bevestigen',
    syncNow: 'Nu synchroniseren',
    lastSynced: 'Laatst gesynchroniseerd',
    importData: 'Importeren',
    switchWorkspace: 'Werkruimte wisselen',
    lockApplication: 'Applicatie vergrendelen',
    helpAndFeedback: 'Help en feedback',
  },
  preferences: {
    title: 'Voorkeuren',
    general: 'Algemeen',
    account: 'Account',
    security: 'Beveiliging',
    appearance: 'Weergave',
    backups: 'Back-ups',
    listed: 'Listed',
    plugins: 'Plug-ins',
    whatsNew: 'Nieuw',
    helpAndFeedback: 'Help en feedback',
    language: 'Taal',
    languageTitle: 'Taal',
    languageDescription:
      'Kies de taal die in de hele app-interface wordt gebruikt. De app gebruikt Engels voor wat nog niet vertaald is.',
    languageChanged: 'Taal bijgewerkt',
    defaults: 'Standaardwaarden',
    tools: 'Hulpmiddelen',
    spellcheck: 'Spellingcontrole',
    labs: 'Labs',
  },
}

export default nl
