import type { LocaleResource } from './en'

const nl: LocaleResource = {
  common: {
    save: 'Opslaan',
    cancel: 'Annuleren',
    delete: 'Verwijderen',
    confirm: 'Bevestigen',
    close: 'Sluiten',
    edit: 'Bewerken',
    rename: 'Naam wijzigen',
    duplicate: 'Dupliceren',
    remove: 'Verwijderen',
    open: 'Openen',
    create: 'Aanmaken',
    add: 'Toevoegen',
    done: 'Klaar',
    back: 'Terug',
    next: 'Volgende',
    search: 'Zoeken',
    clear: 'Wissen',
    loading: 'Laden…',
    copy: 'Kopiëren',
    copied: 'Gekopieerd',
    download: 'Downloaden',
    upload: 'Uploaden',
    export: 'Exporteren',
    import: 'Importeren',
    yes: 'Ja',
    no: 'Nee',
    enabled: 'Ingeschakeld',
    disabled: 'Uitgeschakeld',
    on: 'Aan',
    off: 'Uit',
    learnMore: 'Meer informatie',
    options: 'Opties',
    settings: 'Instellingen',
    preferences: 'Voorkeuren',
    help: 'Help',
    pin: 'Vastmaken',
    unpin: 'Losmaken',
    star: 'Markeren',
    unstar: 'Markering verwijderen',
    archive: 'Archiveren',
    unarchive: 'Uit archief halen',
    restore: 'Herstellen',
    moveToTrash: 'Naar prullenbak verplaatsen',
    deletePermanently: 'Permanent verwijderen',
    protect: 'Beveiligen',
    unprotect: 'Beveiliging opheffen',
  },
  navigation: {
    notes: 'Notities',
    allNotes: 'Alle notities',
    files: 'Bestanden',
    starred: 'Gemarkeerd',
    archived: 'Gearchiveerd',
    trash: 'Prullenbak',
    untagged: 'Zonder onderwerp',
    conflicts: 'Conflicten',
    views: 'Weergaven',
    smartViews: 'Slimme weergaven',
    tags: 'Onderwerpen',
    folders: 'Mappen',
    favorites: 'Favorieten',
    dashboard: 'Dashboard',
    createNewNote: 'Een nieuwe notitie maken',
    createNewTag: 'Een nieuw onderwerp maken',
    createNewFolder: 'Een nieuwe map maken',
    createNewSmartView: 'Een nieuwe slimme weergave maken',
    searchTags: 'Onderwerpen zoeken…',
    noTagsFound: 'Geen onderwerpen gevonden. Probeer een andere zoekopdracht.',
    noSmartViewsFound: 'Geen slimme weergaven gevonden. Probeer een andere zoekopdracht.',
    collapseTagsPanel: 'Onderwerpenpaneel inklappen',
    expandTagsPanel: 'Onderwerpenpaneel uitklappen',
    goToItemsList: 'Ga naar itemlijst',
    goToAccountMenu: 'Ga naar accountmenu',
    openPreferences: 'Voorkeuren openen',
  },
  account: {
    account: 'Account',
    signIn: 'Aanmelden',
    signOut: 'Afmelden',
    signUp: 'Registreren',
    register: 'Registreren',
    you: 'Jij',
    encryptionOn: 'Eind-tot-eind-versleuteling ingeschakeld',
    notSignedIn: 'Je bent niet aangemeld',
    signInOrRegister: 'Meld je aan of registreer om je notities te synchroniseren',
    email: 'E-mail',
    password: 'Wachtwoord',
    confirmPassword: 'Wachtwoord bevestigen',
    syncNow: 'Nu synchroniseren',
    lastSynced: 'Laatst gesynchroniseerd',
    importData: 'Importeren',
    switchWorkspace: 'Werkruimte wisselen',
    lockApplication: 'Applicatie vergrendelen',
    helpAndFeedback: 'Help en feedback',
  },
  preferences: {
    title: 'Voorkeuren',
    general: 'Algemeen',
    account: 'Account',
    security: 'Beveiliging',
    appearance: 'Weergave',
    backups: 'Back-ups',
    listed: 'Listed',
    plugins: 'Plug-ins',
    whatsNew: 'Nieuw',
    helpAndFeedback: 'Help en feedback',
    language: 'Taal',
    languageTitle: 'Taal',
    languageDescription:
      'Kies de taal die in de hele app-interface wordt gebruikt. De app gebruikt Engels voor wat nog niet vertaald is.',
    languageChanged: 'Taal bijgewerkt',
    defaults: 'Standaardwaarden',
    tools: 'Hulpmiddelen',
    spellcheck: 'Spellingcontrole',
    labs: 'Labs',
  },
  editor: {
    cut: 'Knippen',
    copy: 'Kopiëren',
    paste: 'Plakken',
    moreCutOptions: 'Meer knipopties',
    moreCopyOptions: 'Meer kopieeropties',
    morePasteOptions: 'Meer plakopties',
    tableOfContents: 'Inhoudsopgave',
    selectAll: 'Alles selecteren',
    selectAllText: 'Alleen tekst selecteren',
    deselectAll: 'Selectie opheffen',
    search: 'Zoeken',
    undo: 'Ongedaan maken',
    redo: 'Opnieuw',
    undoHistory: 'Geschiedenis ongedaan maken',
    redoHistory: 'Geschiedenis opnieuw',
    undoHistoryEmpty: 'Ongedaan-geschiedenis — nog niets om ongedaan te maken',
    undoHistoryAvailable: 'Ongedaan-geschiedenis — ga meerdere stappen tegelijk terug',
    redoHistoryEmpty: 'Opnieuw-geschiedenis — niets om opnieuw te doen',
    redoHistoryAvailable: 'Opnieuw-geschiedenis — spring meerdere stappen tegelijk vooruit',
    formattingOptions: 'Opmaakopties',
    bold: 'Vet',
    italic: 'Cursief',
    underline: 'Onderstrepen',
    strikethrough: 'Doorhalen',
    inlineCode: 'Inline-code',
    link: 'Link',
    formatPainter: 'Opmaakkwast — opmaak kopiëren (dubbelklik om aan te houden)',
    textStyle: 'Tekststijl',
    textColor: 'Tekstkleur',
    highlightColor: 'Markeerkleur',
    typography: 'Typografie — nadruk, contour, letter- & woordafstand',
    typographyTitle: 'Typografie',
    fontSize: 'Tekengrootte',
    chooseFontSize: 'Tekengrootte kiezen',
    decreaseFontSize: 'Tekengrootte verkleinen',
    increaseFontSize: 'Tekengrootte vergroten',
    fontFamily: 'Lettertype',
    customFontFamily: 'Aangepast',
    bulletedList: 'Opsommingslijst',
    numberedList: 'Genummerde lijst',
    checkList: 'Checklijst',
    quote: 'Citaat',
    codeBlock: 'Codeblok',
    changeCase: 'Hoofdlettergebruik wijzigen',
    sortAndDedupeLines: 'Regels sorteren & ontdubbelen',
    alignment: 'Uitlijning',
    paragraphLayout: 'Alinea-indeling — regel- & alinea-afstand, inspringing, arcering',
    paragraphLayoutTitle: 'Alinea-indeling',
    listStyleMarker: 'Lijststijl — opsommings- & nummermarkering',
    formattingMarks: 'Opmaaktekens',
    insert: 'Invoegen',
    insertRowAbove: 'Rij hierboven invoegen',
    insertRowBelow: 'Rij hieronder invoegen',
    insertColumnLeft: 'Kolom links invoegen',
    insertColumnRight: 'Kolom rechts invoegen',
    deleteRow: 'Rij verwijderen',
    deleteColumn: 'Kolom verwijderen',
    toggleRowHeader: 'Rijkop in-/uitschakelen',
    toggleColumnHeader: 'Kolomkop in-/uitschakelen',
    deleteTable: 'Tabel verwijderen',
    rows: 'Rijen',
    columns: 'Kolommen',
    cells: 'Cellen',
    table: 'Tabel',
    block: 'Blok',
    alignLeft: 'Links uitlijnen',
    alignCenter: 'Centreren',
    alignRight: 'Rechts uitlijnen',
    editLink: 'Link bewerken',
    removeLink: 'Link verwijderen',
    zoomIntoBlock: 'Inzoomen op blok',
    blockStyle: 'Blokstijl',
    heading1: 'Kop 1',
    heading2: 'Kop 2',
    heading3: 'Kop 3',
    normalText: 'Normale tekst',
    moreFormatting: 'Meer opmaak',
    createNoteFromSelectionTitle: 'Nieuwe notitie maken van selectie',
    createNoteFromSelectionDescription:
      'Maakt een nieuwe notitie met de huidige selectie en vervangt de selectie door een link naar de nieuwe notitie.',
    dismissKeyboard: 'Toetsenbord verbergen',
    tableOfContentsLower: 'Inhoudsopgave',
    noHeadingsFound: 'Geen koppen gevonden',
    textFormattingOptions: 'Tekstopmaakopties',
    highlight: 'Markeren',
    subscript: 'Subscript',
    superscript: 'Superscript',
    clearFormatting: 'Opmaak wissen',
    normal: 'Normaal',
    smartChecklist: 'Slimme checklijst',
    restoreCompletedTasks: 'Voltooide taken herstellen',
    leftAlign: 'Links uitlijnen',
    centerAlign: 'Centreren',
    rightAlign: 'Rechts uitlijnen',
    justify: 'Uitvullen',
    searchBlocksPlaceholder: 'Blokken zoeken…',
    searchBlocksToInsert: 'Zoek blokken om in te voegen',
    clearSearch: 'Zoekopdracht wissen',
    noBlocksMatch: 'Geen blokken komen overeen met “{{query}}”',
    customizeToolbar: 'Werkbalk aanpassen',
    custom: 'Aangepast',
    clear: 'Wissen',
    textColorSwatch: 'Tekstkleur {{color}}',
    highlightColorSwatch: 'Markeerkleur {{color}}',
    textShadingSwatch: 'Tekstarcering {{color}}',
    noTextShading: 'Geen tekstarcering',
    uppercase: 'HOOFDLETTERS',
    lowercase: 'kleine letters',
    camelCase: 'camelCase',
    sortLines: 'Regels sorteren',
    deduplicate: 'Ontdubbelen',
    multiKeySort: 'Sorteren op meerdere sleutels (1e, 2e, 3e)…',
    sortAndDeduplicateLines: 'Regels sorteren en ontdubbelen',
    emphasisMarks: 'Nadruktekens',
    outlineTextStroke: 'Contour (tekstlijn)',
    letterSpacingKerning: 'Letterafstand (kerning)',
    wordSpacing: 'Woordafstand',
    clearTypography: 'Typografie wissen',
    spacingTight: 'Krap',
    spacingNormal: 'Normaal',
    spacingWide: 'Ruim',
    spacingWider: 'Ruimer',
    spacingWidest: 'Ruimst',
    undoMultipleSteps: 'Meerdere stappen ongedaan maken',
    redoMultipleSteps: 'Meerdere stappen opnieuw doen',
    emptyHistoryPreview: '(leeg)',
    pasteOptions: 'Plakopties',
    copyOptions: 'Kopieeropties',
    cutOptions: 'Knipopties',
    pasteWithoutFormatting: 'Plakken zonder opmaak',
    pasteClean: 'Schoon plakken (verborgen tekens verwijderen)',
    keepSourceFormatting: 'Bronopmaak behouden',
    matchDestinationFormatting: 'Opmaak van doel overnemen',
    pasteAsImage: 'Als afbeelding plakken',
    copyWithoutFormatting: 'Kopiëren zonder opmaak',
    copyTextOnly: 'Alleen tekst kopiëren',
    copyImagesOnly: 'Alleen afbeeldingen kopiëren',
    cutWithoutFormatting: 'Knippen zonder opmaak',
    cutTextOnly: 'Alleen tekst knippen',
    cutImagesOnly: 'Alleen afbeeldingen knippen',
    lineSpacing: 'Regelafstand',
    spaceBefore: 'Ruimte ervoor',
    spaceAfter: 'Ruimte erna',
    indentation: 'Inspringing',
    none: 'Geen',
    increaseLeft: 'Links vergroten',
    decreaseLeft: 'Links verkleinen',
    increaseRight: 'Rechts vergroten',
    decreaseRight: 'Rechts verkleinen',
    firstLine: 'Eerste regel',
    noFirstLine: 'Geen eerste regel',
    textShading: 'Tekstarcering',
    listStyle: 'Lijststijl',
    bulleted: 'Opsomming',
    numbered: 'Genummerd',
    bulletedListMarkers: 'Opsommingsmarkeringsstijl',
    numberedListMarkers: 'Nummeringsstijl',
    multilevelList: 'Lijst met meerdere niveaus',
    multilevelListHint: 'Kies een markering per nestniveau',
    multilevelLevelDefault: 'Standaard',
    level: 'Niveau',
    apply: 'Toepassen',
    insertTable: 'Tabel invoegen',
    insertImageFromUrl: 'Afbeelding invoegen vanaf URL',
    sortLinesModalTitle: 'Regels sorteren',
    blockPicker: 'Blokkiezer',
    blockParagraph: 'Alinea',
    blockCallout: 'Aandachtsblok',
    blockDivider: 'Scheidingslijn',
    blockCollapsible: 'Inklapbaar',
    blockImageFromUrl: 'Afbeelding vanaf URL',
    blockUploadFile: 'Bestand uploaden',
    blockDrawing: 'Tekening',
    blockQrCode: 'QR-code',
    blockTable: 'Tabel',
    blockKanbanBoard: 'Kanbanbord',
    blockCalendar: 'Kalender',
    blockTimeline: 'Tijdlijn',
    blockDataTable: 'Gegevenstabel',
    blockSqlQuery: 'SQL-query',
    blockMermaidDiagram: 'Mermaid-diagram',
    blockGanttChart: 'Gantt-grafiek',
    blockTimingDiagram: 'Timingdiagram',
    blockMusicStaff: 'Notenbalk',
    blockTradingViewChart: 'TradingView-grafiek',
    blockStockChart: 'Aandelengrafiek',
    blockEmbed: 'Insluiten',
    blockEmbedWebsite: 'Website insluiten',
    blockTweet: 'Tweet',
    blockEquation: 'Vergelijking',
    blockInlineEquation: 'Inline-vergelijking',
    blockFootnote: 'Voetnoot',
    blockBookmark: 'Bladwijzer',
    blockGeneratePassword: 'Cryptografisch veilig wachtwoord genereren',
    blockClock: 'Klok',
    blockCurrentDateTime: 'Huidige datum en tijd',
    blockCurrentTime: 'Huidige tijd',
    blockCurrentDate: 'Huidige datum',
    blockCategoryBasic: 'Basis',
    blockCategoryLists: 'Lijsten',
    blockCategoryMedia: 'Media',
    blockCategoryDataTables: 'Gegevens & tabellen',
    blockCategoryDiagramsCharts: 'Diagrammen & grafieken',
    blockCategoryFinance: 'Financiën',
    blockCategoryEmbeds: 'Insluitingen',
    blockCategoryAdvanced: 'Geavanceerd',
  },
  files: {
    dropToUploadTooltip: 'Sleep je bestanden hierheen om ze te uploaden en aan het huidige bestand te koppelen',
    fileAriaLabel: 'Bestand',
    fileReadonly: 'Dit bestand is alleen-lezen',
    fileInformationPanel: 'Bestandsinformatiepaneel',
    details: 'Details',
    selectedFilesCount: '{{count}} geselecteerde bestanden',
    actionsPerformedOnSelected: 'Acties worden uitgevoerd op alle geselecteerde bestanden.',
    cancelMultipleSelection: 'Meervoudige selectie annuleren',
    fileOptions: 'Bestandsopties',
    fileContextMenu: 'Bestandscontextmenu',
    fileOptionsMenu: 'Bestandsoptiemenu',
    fileOptionsPanel: 'Bestandsoptiepaneel',
    noFilesSelected: 'Geen bestanden geselecteerd',
    detachFromNote: 'Loskoppelen van notitie',
    attachToNote: 'Aan notitie koppelen',
    passwordProtect: 'Beveiligen met wachtwoord',
    downloadSeparately: 'Apart downloaden',
    downloadAsArchive: 'Downloaden als archief',
    failedToDownloadArchive: 'Bestanden konden niet als archief worden gedownload',
    fileId: 'Bestands-ID:',
    size: 'Grootte:',
    totalSize: 'Totale grootte:',
    backedUpOn: 'Geback-upt op {{date}}',
    configureFileBackups: 'Bestandsback-ups configureren',
    fileNotBackedUpLocally: 'Bestand niet lokaal geback-upt',
    noFoldersYet: 'Nog geen mappen',
    moveToFolder: 'Naar map verplaatsen',
    folderSelectionMenu: 'Mapselectiemenu',
    noFolder: 'Geen map',
    fileProtected: 'Dit bestand is beveiligd.',
    authenticateToView: 'Verifieer om dit bestand te bekijken.',
    addPasscodeToView:
      'Voeg een toegangscode toe of maak een account aan om verificatie te vereisen om dit bestand te bekijken.',
    openAccountMenu: 'Accountmenu openen',
    authenticate: 'Verifiëren',
    viewFile: 'Bestand bekijken',
    loading: 'Laden...',
    fileCannotBePreviewed: 'Dit bestand kan niet worden weergegeven.',
    errorLoadingFile:
      'Er is een fout opgetreden bij het laden van het bestand. Probeer het opnieuw of download het bestand en open het met een andere applicatie.',
    tryAgain: 'Opnieuw proberen',
    downloadToView: 'Download dit bestand en open het met een andere applicatie om het te bekijken.',
    fileInformation: 'Bestandsinformatie',
    type: 'Type:',
    decryptedSize: 'Ontsleutelde grootte:',
    encryptedSize: 'Versleutelde grootte:',
    created: 'Aangemaakt:',
    lastModified: 'Laatst gewijzigd:',
    done: 'Klaar',
    showFileOptions: 'Bestandsopties tonen',
    showFileInfo: 'Bestandsinfo tonen',
    hideFileInfo: 'Bestandsinfo verbergen',
    showLinksSection: 'Linksectie tonen',
    hideLinksSection: 'Linksectie verbergen',
    submit: 'Verzenden',
    renameFile: 'Bestandsnaam wijzigen',
    showLinkedItems: 'Gekoppelde items tonen',
    closeModal: 'Venster sluiten',
    filePreviewModal: 'Bestandsvoorbeeldvenster',
    leftAlign: 'Links uitlijnen',
    centerAlign: 'Centreren',
    rightAlign: 'Rechts uitlijnen',
    videoCannotBePreviewed: 'Deze video kan niet worden weergegeven.',
    audioCannotBePlayed: 'Deze audio kan niet worden afgespeeld.',
    downloadToListen: 'Download dit bestand en open het met een andere applicatie om ernaar te luisteren.',
    externalAppOnly: 'Dit bestand kan alleen in een externe app worden weergegeven',
    openFilePreview: 'Bestandsvoorbeeld openen',
    loadingPdfViewer: 'PDF-viewer laden...',
    zoomOut: 'Uitzoomen',
    zoomIn: 'Inzoomen',
    resetToActualSize: 'Terug naar werkelijke grootte',
    resetTo100: 'Terug naar 100%',
    fitToScreen: 'Aan scherm aanpassen',
    unableToRenderPdf: 'Kan deze PDF niet weergeven.',
    pdfCorruptedOrProtected: 'Het bestand is mogelijk beschadigd of met een wachtwoord beveiligd.',
    loadingPdf: 'PDF laden...',
    previousPage: 'Vorige pagina',
    pageNumber: 'Paginanummer',
    nextPage: 'Volgende pagina',
    fitWidth: 'Aan breedte aanpassen',
    searchInDocumentShortcut: 'Zoeken in document (Ctrl/Cmd+F)',
    searchInDocument: 'Zoeken in document',
    copyLinkToPage: 'Link naar pagina {{page}} kopiëren',
    copyLinkToThisPage: 'Link naar deze pagina kopiëren',
    copyLinkToSelectedText: 'Link naar geselecteerde tekst kopiëren',
    cancelOcr: 'OCR annuleren',
    preparingOcr: 'OCR voorbereiden...',
    ocrProgress: 'OCR pagina {{current}} / {{total}} ({{percent}}%)',
    ocrCachedReRunTooltip:
      'Tekst al geëxtraheerd (gecachet). OCR opnieuw uitvoeren in je browser (blijft op je apparaat).',
    ocrExtractedReRunTooltip: 'Tekst geëxtraheerd. OCR opnieuw uitvoeren in je browser (blijft op je apparaat).',
    ocrExtractTooltip:
      "Tekst uit gescande pagina's halen met OCR. Draait in je browser; niets verlaat je apparaat (traag; downloadt taalgegevens).",
    extractTextWithOcrBrowser: 'Tekst extraheren met OCR in je browser',
    reRunOcrBrowser: 'OCR opnieuw uitvoeren (browser)',
    extractTextOcr: 'Tekst extraheren (OCR)',
    serverOcrTooltip:
      'OCR op de SERVER uitvoeren. Hierbij worden de pagina-afbeeldingen van deze PDF naar de server verzonden en wordt eind-tot-eind-versleuteling VERLATEN — de server kan die inhoud lezen. Bij browser-OCR blijft alles op je apparaat.',
    runOcrOnServerAria:
      'OCR op de server uitvoeren (verzendt pagina-afbeeldingen naar de server; verlaat eind-tot-eind-versleuteling)',
    runOcrOnServer: 'OCR op server uitvoeren',
    copyAllExtractedText: 'Alle geëxtraheerde tekst kopiëren',
    copyExtractedTextAria: 'Geëxtraheerde tekst kopiëren',
    findInDocument: 'Zoeken in document',
    matchCase: 'Hoofdlettergevoelig',
    noResults: 'Geen resultaten',
    matchOfTotal: '{{current}} van {{total}}',
    previousMatch: 'Vorige overeenkomst',
    nextMatch: 'Volgende overeenkomst',
    closeSearch: 'Zoeken sluiten',
    serverOcrDisclosurePrefix:
      'Server-OCR is beschikbaar voor je account. Het verzendt de pagina-afbeeldingen van deze PDF naar de server en',
    serverOcrDisclosureBold: 'verlaat eind-tot-eind-versleuteling',
    serverOcrDisclosureSuffix:
      ' — de server (en iedereen die deze beheert) kan die inhoud lezen. Bij browser-OCR blijft alles op je apparaat. Standaard is browser-OCR.',
    ocrRunningServer:
      'Server-OCR: de pagina-afbeeldingen van deze PDF worden naar de server geüpload, wat eind-tot-eind-versleuteling VERLAAT — de server kan die inhoud lezen. (Bij browser-OCR blijft alles op je apparaat.)',
    ocrRunningBrowser:
      'OCR draait in je browser op dit apparaat (je bestanden blijven eind-tot-eind-versleuteld). Het is traag en downloadt bij het eerste gebruik taalgegevens.',
    ocrDoneServer:
      'Server-OCR voltooid. De pagina-afbeeldingen zijn naar de server verzonden (dit verliet eind-tot-eind-versleuteling). De nauwkeurigheid varieert met de scankwaliteit; geëxtraheerde tekst is nu doorzoekbaar en kopieerbaar en wordt op dit apparaat gecachet.',
    ocrDoneBrowser:
      'OCR voltooid. De nauwkeurigheid varieert met de scankwaliteit; geëxtraheerde tekst is nu doorzoekbaar en kopieerbaar en wordt op dit apparaat gecachet.',
    copiedExtractedText: 'Geëxtraheerde tekst gekopieerd',
    copiedLinkToPage: 'Link naar pagina {{page}} gekopieerd',
    copiedLinkToSelectedText: 'Link naar geselecteerde tekst gekopieerd',
    serverOcrFailed: 'Server-OCR mislukt: {{message}}',
    ocrUnknownError: 'onbekende fout',
    ocrFailed: 'OCR mislukt. Het downloaden van de taalgegevens is mogelijk mislukt.',
  },
  notes: {
    notesAndFiles: 'Notities & bestanden',
    selectAllItems: 'Alle items selecteren',
    selectedCount: '{{count}} geselecteerd',
    cancelMultipleSelection: 'Meervoudige selectie annuleren',
    noFilesInFolder: 'Geen bestanden in deze map.',
    noItems: 'Geen items.',
    loading: 'Laden...',
    uploadFileWithShortcut: 'Bestand uploaden {{shortcut}}',
    createNoteInTopicWithShortcut: 'Een nieuwe notitie maken in het geselecteerde onderwerp {{shortcut}}',
    dropFilesToUpload: 'Sleep je bestanden hierheen om ze te uploaden en aan onderwerp "{{title}}" te koppelen',
    noFilesYet: 'Je hebt nog geen bestanden',
    filesAttachedAppearHere:
      'Bestanden die aan je notities zijn gekoppeld, verschijnen hier. Je kunt ook rechtstreeks vanaf deze pagina bestanden uploaden.',
    uploadFiles: 'Bestanden uploaden',
    syncing: 'Synchroniseren...',
    loadingItemsProgress: '{{current}}/{{total}} items laden...',
    potentiallyOutOfSync: 'Mogelijk niet gesynchroniseerd',
    openDisplayOptionsMenu: 'Weergaveoptiemenu openen',
    displayOptionsMenu: 'Weergaveoptiemenu',
    displayOptions: 'Weergaveopties',
    expandTopicsPanel: 'Onderwerpenpaneel uitklappen',
    collapseNotesPanel: 'Notitiepaneel inklappen',
    addItem: 'Item toevoegen',
    uploadFolder: 'Map uploaden',
    takePhoto: 'Foto maken',
    recordVideo: 'Video opnemen',
    searchPlaceholder: 'Zoeken...',
    notesListOptionsMenu: 'Notitielijst-optiemenu',
    preferencesFor: 'Voorkeuren voor',
    global: 'Globaal',
    reset: 'Opnieuw instellen',
    upgradeForPerTopicPreferences: 'Upgraden voor voorkeuren per onderwerp',
    perTopicPreferencesMessageWithDaily:
      'Creëer krachtige workflows en organisatie-indelingen met weergavevoorkeuren per onderwerp en de gloednieuwe Daily Notebook-kalenderindeling.',
    perTopicPreferencesMessage:
      'Creëer krachtige workflows en organisatie-indelingen met weergavevoorkeuren per onderwerp.',
    sortBy: 'Sorteren op',
    relevanceBestMatch: 'Relevantie (beste overeenkomst)',
    dateModified: 'Wijzigingsdatum',
    creationDate: 'Aanmaakdatum',
    title: 'Titel',
    customDragToReorder: 'Aangepast (sleep om te herordenen)',
    view: 'Weergave',
    showNotePreview: 'Notitievoorbeeld tonen',
    showDate: 'Datum tonen',
    showTags: 'Onderwerpen tonen',
    showIcon: 'Pictogram tonen',
    other: 'Overige',
    showPinned: 'Vastgemaakte tonen',
    showProtected: 'Beveiligde tonen',
    showArchived: 'Gearchiveerde tonen',
    showTrashed: 'In prullenbak tonen',
    dailyNotebook: 'Daily Notebook',
    labs: 'Labs',
    dailyNotebookDescription: 'Leg dagelijks nieuwe notities vast met een kalendergebaseerde indeling',
    tableView: 'Tabelweergave',
    tableViewDescription: 'Toon de notities en bestanden in het huidige onderwerp in een tabelindeling',
    newNoteDefaults: 'Standaardwaarden nieuwe notitie',
    noteType: 'Notitietype',
    selectDefaultNoteType: 'Selecteer het standaard notitietype',
    titleFormat: 'Titelformaat',
    selectTitleFormat: 'Selecteer het formaat voor de notitietitel',
    customFormatPlaceholder: 'bijv. YYYY-MM-DD',
    preview: 'Voorbeeld: ',
    useBracketsToEscape: '. Gebruik ',
    toEscapeFormatting: ' om opmaak te ontwijken.',
    protected: 'Beveiligd',
    modified: 'Gewijzigd',
    now: 'Nu',
    editingDisabled: 'Bewerken uitgeschakeld',
    trashed: 'In prullenbak',
    archived: 'Gearchiveerd',
    files: 'Bestanden',
    starred: 'Gemarkeerd',
    fileBackedUpLocally: 'Bestand is lokaal geback-upt',
    conflictedCopy: 'Conflicterende kopie',
    allFiles: 'Alle bestanden',
    noFolder: 'Geen map',
    folderNamePlaceholder: 'Mapnaam',
    createNewFolder: 'Een nieuwe map maken',
    newFolder: 'Nieuwe map',
    currentStreak: 'Huidige reeks',
    dayWithCount_one: 'Dag',
    dayWithCount_other: 'Dagen',
  },
  auth: {
    unableToComputePrivateUsername: 'Kan privé-gebruikersnaam niet berekenen.',
    advancedOptions: 'Geavanceerde opties',
    privateUsernameMode: 'Privé-gebruikersnaammodus',
    username: 'Gebruikersnaam',
    useStrictSignIn: 'Strikte aanmelding gebruiken',
    useRecoveryCode: 'Herstelcode gebruiken',
    recoveryCode: 'Herstelcode',
    deleteLocalDataTitle: 'Lokale gegevens verwijderen?',
    noMergeWarning:
      'Je hebt ervoor gekozen om je lokale gegevens niet samen te voegen. Als je doorgaat, worden je lokale notities en onderwerpen permanent verwijderd en vervangen door gegevens van je account. Deze actie kan niet ongedaan worden gemaakt.',
    noMergeConfirmQuestion: 'Weet je zeker dat je wilt doorgaan zonder samen te voegen?',
    deleteLocalDataAndContinue: 'Lokale gegevens verwijderen en doorgaan',
    passwordResetWarningPart1: 'Omdat je notities zijn versleuteld met je wachtwoord,',
    passwordResetWarningHighlight: 'heeft Standard Red Notes geen optie om je wachtwoord opnieuw in te stellen',
    passwordResetWarningPart2: '. Als je je wachtwoord vergeet, verlies je permanent toegang tot je gegevens.',
    confirmPassword: 'Wachtwoord bevestigen',
    creatingAccount: 'Account aanmaken...',
    createAccountAndSignIn: 'Account aanmaken & aanmelden',
    staySignedIn: 'Aangemeld blijven',
    goBack: 'Teruggaan',
    humanVerification: 'Menselijke verificatie',
    confirmPasswordTitle: 'Wachtwoord bevestigen',
    createAccount: 'Account aanmaken',
    workspaceNameOptional: 'Werkruimtenaam (optioneel)',
    generalAccountMenuLabel: 'Algemeen accountmenu',
    signedInAs: 'Je bent aangemeld als:',
    syncing: 'Synchroniseren...',
    lastSynced: 'Laatst gesynchroniseerd:',
    offlineSignInPrompt:
      'Je bent offline. Meld je aan om je notities en voorkeuren op al je apparaten te synchroniseren en eind-tot-eind-versleuteling in te schakelen.',
    offline: 'Offline',
    accountSettings: 'Accountinstellingen',
    createFreeAccount: 'Gratis account aanmaken',
    documentation: 'Documentatie',
    keyboardShortcuts: 'Sneltoetsen',
    commandPalette: 'Opdrachtenpalet',
    signOutWorkspace: 'Werkruimte afmelden',
    mergeLocalData: 'Lokale gegevens samenvoegen ({{count}} notities en onderwerpen)',
    mergeLocalDataTooltip:
      'Als dit niet is aangevinkt, worden je lokale notities en onderwerpen permanent verwijderd en vervangen door gegevens van je account.',
    homeServerNotRunning:
      'De thuisserver draait niet. Open de voorkeuren en het tabblad thuisserver om deze te starten.',
    serverDefault: 'Standaard',
    serverCustom: 'Aangepast',
    serverHomeServer: 'Thuisserver',
    syncServer: 'Synchronisatieserver',
    signingIn: 'Aanmelden...',
    syncUnreachable: 'Synchronisatie onbereikbaar',
    syncUnreachableMessage: 'Hmm... we kunnen je account blijkbaar niet synchroniseren. De reden: {{reason}}',
    workspaceSwitcherMenuLabel: 'Werkruimtewisselmenu',
    signOutAllWorkspacesConfirm: 'Weet je zeker dat je je wilt afmelden bij alle werkruimtes op dit apparaat?',
    signOutAll: 'Alles afmelden',
    addAnotherWorkspace: 'Nog een werkruimte toevoegen',
    signOutAllWorkspaces: 'Alle werkruimtes afmelden',
    deleteAccountTitle: 'Account verwijderen?',
    deleteMyAccountForGood: 'Mijn account definitief verwijderen',
    dataNotBackedUp: 'Gegevens niet geback-upt',
    signInOrRegisterToSync:
      'Meld je aan of registreer om je notities met eind-tot-eind-versleuteling naar je andere apparaten te synchroniseren.',
    openAccountMenu: 'Accountmenu openen',
    ignoreWarning: 'Waarschuwing negeren',
    waitingForSecurityKey: 'Wachten op beveiligingssleutel...',
    authenticationSuccessful: 'Verificatie geslaagd!',
    insertSecurityKeyPrompt:
      'Steek je hardware-beveiligingssleutel in en druk op de onderstaande knop om te verifiëren.',
    authenticate: 'Verifiëren',
  },
  search: {
    placeholder: 'Zoeken...',
    protectedContents: 'Beveiligde inhoud',
    archived: 'Gearchiveerd',
    trashed: 'In prullenbak',
    aiUnavailable: 'AI-herrangschikking is niet beschikbaar of gaf geen resultaat.',
    aiUnavailableTooltip: 'Contextueel AI-zoeken is niet beschikbaar.',
    aiTypeQueryFirst: 'Typ eerst een zoekopdracht.',
    aiTooltip:
      'Herrangschik de beste resultaten op semantische relevantie met je geconfigureerde AI-provider. ' +
      'Verzendt de titels en korte fragmenten van die kandidaten, plus je zoekopdracht, naar de provider.',
    aiSearchWithAi: 'Zoeken met AI',
    aiRanking: 'Rangschikken…',
    aiRankedByRelevance: 'Gerangschikt op AI-relevantie',
    aiPrivacyNotice:
      'Verzendt de titels & fragmenten van de beste resultaten en je zoekopdracht naar je AI-provider. Cloudproviders zien ' +
      'ze — een lokaal model houdt het op je apparaat.',
    advancedFilters: 'Geavanceerde zoekfilters',
    filters: 'Filters',
    noteTypeAny: 'Elk type',
    noteTypePlainText: 'Platte tekst',
    noteTypeRichText: 'Opgemaakte tekst',
    noteTypeSuper: 'Super',
    noteTypeMarkdown: 'Markdown',
    noteTypeCode: 'Code',
    noteTypeTask: 'Taak',
    noteTypeSpreadsheet: 'Spreadsheet',
    flagProtected: 'Beveiligd',
    flagPinned: 'Vastgemaakt',
    flagArchived: 'Gearchiveerd',
    flagStarred: 'Gemarkeerd',
    flagTrashed: 'In prullenbak',
    topicsLabel: "Onderwerpen (door komma's gescheiden)",
    topicsPlaceholder: 'werk, persoonlijk',
    noteTypeLabel: 'Notitietype',
    searchInLabel: 'Zoeken in',
    searchInTitleAndContent: 'Titel & inhoud',
    modifiedWithinLabel: 'Gewijzigd binnen',
    datePreset: 'Afgelopen {{label}}',
    createdAfterLabel: 'Aangemaakt na',
    createdBeforeLabel: 'Aangemaakt vóór',
    updatedAfterLabel: 'Bijgewerkt na',
    updatedBeforeLabel: 'Bijgewerkt vóór',
    statusLabel: 'Status',
    hasAttachments: 'Heeft bijlagen',
    caseSensitive: 'Hoofdlettergevoelig',
    clearAllFilters: 'Alle filters wissen',
  },
  sharing: {
    vaultSelectionMenu: 'Kluisselectiemenu',
    vaultOptionsMenu: 'Kluisoptiemenu',
    vaultOptions: 'Kluisopties',
    noVaultsFound: 'Geen kluizen gevonden',
    moveToVault: 'Naar kluis verplaatsen',
    moveOutOfVault: 'Uit {{name}} verplaatsen',
    vaultsFallbackName: 'kluizen',
    editVault: 'Kluis bewerken',
    lockVault: 'Kluis vergrendelen',
    unlockVault: 'Kluis ontgrendelen',
    openVaultSettings: 'Kluisinstellingen openen',
    selectionModeMultiple: 'Meerdere',
    selectionModeOne: 'Eén',
    lastEditedBy: 'Laatst bewerkt door',
    sharedBy: 'Gedeeld door',
    sharedByContact: 'Gedeeld door contact',
    vaultName: 'Kluisnaam',
    sharedInVault: 'Gedeeld in kluis',
    copiedToClipboard: 'Gekopieerd naar klembord',
    failedToCopyToClipboard: 'Kopiëren naar klembord mislukt',
    copyExampleToClipboard: 'Voorbeeld naar klembord kopiëren',
    copiedExclaim: 'Gekopieerd!',
    shareUnavailableTitle: 'Delen niet beschikbaar',
    shareUnavailableMessage: 'Deze deellink is niet meer beschikbaar.',
    invalidLinkTitle: 'Ongeldige link',
    invalidLinkMessage: 'Deze deellink is ongeldig of de sleutel ontbreekt.',
    selfDestructTitle: 'Deze notitie vernietigt zichzelf na het bekijken',
    oneTimeViewConsumed: 'Je leest een eenmalige-weergavelink. Deze is nu verbruikt en kan niet opnieuw worden geopend',
    oneTimeViewExpiresClause_one: ', en verloopt volledig {{count}} minuut na de eerste opening',
    oneTimeViewExpiresClause_other: ', en verloopt volledig {{count}} minuten na de eerste opening',
    linkExpires_one: 'Deze link verloopt {{count}} minuut nadat deze voor het eerst is geopend.',
    linkExpires_other: 'Deze link verloopt {{count}} minuten nadat deze voor het eerst is geopend.',
    untitled: 'Naamloos',
    tagHasNoNotes: 'Dit onderwerp heeft geen notities.',
    publicReadOnlyFooter: 'Dit is een openbare, alleen-lezen gedeelde link. De inhoud is in je browser ontsleuteld.',
    confidentialWatermark: 'Vertrouwelijk · {{datetime}}',
    contentHiddenTitle: 'Inhoud verborgen',
    contentHiddenMessage: 'Zet de focus terug op dit venster om de gedeelde inhoud te bekijken.',
  },
}

export default nl
