import type { LocaleResource } from './en'

const pl: LocaleResource = {
  common: {
    save: 'Zapisz',
    cancel: 'Anuluj',
    delete: 'Usuń',
    confirm: 'Potwierdź',
    close: 'Zamknij',
    edit: 'Edytuj',
    rename: 'Zmień nazwę',
    duplicate: 'Duplikuj',
    remove: 'Usuń',
    open: 'Otwórz',
    create: 'Utwórz',
    add: 'Dodaj',
    done: 'Gotowe',
    back: 'Wstecz',
    next: 'Dalej',
    search: 'Szukaj',
    clear: 'Wyczyść',
    loading: 'Ładowanie…',
    copy: 'Kopiuj',
    copied: 'Skopiowano',
    download: 'Pobierz',
    upload: 'Prześlij',
    export: 'Eksportuj',
    import: 'Importuj',
    yes: 'Tak',
    no: 'Nie',
    enabled: 'Włączone',
    disabled: 'Wyłączone',
    on: 'Wł.',
    off: 'Wył.',
    learnMore: 'Dowiedz się więcej',
    options: 'Opcje',
    settings: 'Ustawienia',
    preferences: 'Preferencje',
    help: 'Pomoc',
    pin: 'Przypnij',
    unpin: 'Odepnij',
    star: 'Oznacz gwiazdką',
    unstar: 'Usuń gwiazdkę',
    archive: 'Archiwizuj',
    unarchive: 'Przywróć z archiwum',
    restore: 'Przywróć',
    moveToTrash: 'Przenieś do kosza',
    deletePermanently: 'Usuń trwale',
    protect: 'Chroń',
    unprotect: 'Usuń ochronę',
  },
  navigation: {
    notes: 'Notatki',
    allNotes: 'Wszystkie notatki',
    files: 'Pliki',
    starred: 'Oznaczone gwiazdką',
    archived: 'Zarchiwizowane',
    trash: 'Kosz',
    untagged: 'Bez tematu',
    conflicts: 'Konflikty',
    views: 'Widoki',
    smartViews: 'Widoki inteligentne',
    tags: 'Tematy',
    folders: 'Foldery',
    favorites: 'Ulubione',
    dashboard: 'Pulpit',
    createNewNote: 'Utwórz nową notatkę',
    createNewTag: 'Utwórz nowy temat',
    createNewFolder: 'Utwórz nowy folder',
    createNewSmartView: 'Utwórz nowy widok inteligentny',
    searchTags: 'Szukaj tematów…',
    noTagsFound: 'Nie znaleziono tematów. Spróbuj innego wyszukiwania.',
    noSmartViewsFound: 'Nie znaleziono widoków inteligentnych. Spróbuj innego wyszukiwania.',
    collapseTagsPanel: 'Zwiń panel tematów',
    expandTagsPanel: 'Rozwiń panel tematów',
    goToItemsList: 'Przejdź do listy elementów',
    goToAccountMenu: 'Przejdź do menu konta',
    openPreferences: 'Otwórz preferencje',
  },
  account: {
    account: 'Konto',
    signIn: 'Zaloguj się',
    signOut: 'Wyloguj się',
    signUp: 'Zarejestruj się',
    register: 'Zarejestruj się',
    you: 'Ty',
    encryptionOn: 'Szyfrowanie end-to-end włączone',
    notSignedIn: 'Nie jesteś zalogowany',
    signInOrRegister: 'Zaloguj się lub zarejestruj, aby synchronizować notatki',
    email: 'E-mail',
    password: 'Hasło',
    confirmPassword: 'Potwierdź hasło',
    syncNow: 'Synchronizuj teraz',
    lastSynced: 'Ostatnia synchronizacja',
    importData: 'Importuj',
    switchWorkspace: 'Przełącz obszar roboczy',
    lockApplication: 'Zablokuj aplikację',
    helpAndFeedback: 'Pomoc i opinie',
  },
  preferences: {
    title: 'Preferencje',
    general: 'Ogólne',
    account: 'Konto',
    security: 'Bezpieczeństwo',
    appearance: 'Wygląd',
    backups: 'Kopie zapasowe',
    listed: 'Listed',
    plugins: 'Wtyczki',
    whatsNew: 'Nowości',
    helpAndFeedback: 'Pomoc i opinie',
    language: 'Język',
    languageTitle: 'Język',
    languageDescription:
      'Wybierz język używany w całym interfejsie aplikacji. Aplikacja używa języka angielskiego dla treści jeszcze nieprzetłumaczonych.',
    languageChanged: 'Zaktualizowano język',
    defaults: 'Domyślne',
    tools: 'Narzędzia',
    spellcheck: 'Sprawdzanie pisowni',
    labs: 'Laboratoria',
  },
}

export default pl
