import type { LocaleResource } from './en'

const pl: LocaleResource = {
  common: {
    save: 'Zapisz',
    cancel: 'Anuluj',
    delete: 'Usuń',
    confirm: 'Potwierdź',
    close: 'Zamknij',
    edit: 'Edytuj',
    rename: 'Zmień nazwę',
    duplicate: 'Duplikuj',
    remove: 'Usuń',
    open: 'Otwórz',
    create: 'Utwórz',
    add: 'Dodaj',
    done: 'Gotowe',
    back: 'Wstecz',
    next: 'Dalej',
    search: 'Szukaj',
    clear: 'Wyczyść',
    loading: 'Ładowanie…',
    copy: 'Kopiuj',
    copied: 'Skopiowano',
    download: 'Pobierz',
    upload: 'Prześlij',
    export: 'Eksportuj',
    import: 'Importuj',
    yes: 'Tak',
    no: 'Nie',
    enabled: 'Włączone',
    disabled: 'Wyłączone',
    on: 'Wł.',
    off: 'Wył.',
    learnMore: 'Dowiedz się więcej',
    options: 'Opcje',
    settings: 'Ustawienia',
    preferences: 'Preferencje',
    help: 'Pomoc',
    pin: 'Przypnij',
    unpin: 'Odepnij',
    star: 'Oznacz gwiazdką',
    unstar: 'Usuń gwiazdkę',
    archive: 'Archiwizuj',
    unarchive: 'Przywróć z archiwum',
    restore: 'Przywróć',
    moveToTrash: 'Przenieś do kosza',
    deletePermanently: 'Usuń trwale',
    protect: 'Chroń',
    unprotect: 'Usuń ochronę',
  },
  navigation: {
    notes: 'Notatki',
    allNotes: 'Wszystkie notatki',
    files: 'Pliki',
    starred: 'Oznaczone gwiazdką',
    archived: 'Zarchiwizowane',
    trash: 'Kosz',
    untagged: 'Bez tematu',
    conflicts: 'Konflikty',
    views: 'Widoki',
    smartViews: 'Widoki inteligentne',
    tags: 'Tematy',
    folders: 'Foldery',
    favorites: 'Ulubione',
    dashboard: 'Pulpit',
    createNewNote: 'Utwórz nową notatkę',
    createNewTag: 'Utwórz nowy temat',
    createNewFolder: 'Utwórz nowy folder',
    createNewSmartView: 'Utwórz nowy widok inteligentny',
    searchTags: 'Szukaj tematów…',
    noTagsFound: 'Nie znaleziono tematów. Spróbuj innego wyszukiwania.',
    noSmartViewsFound: 'Nie znaleziono widoków inteligentnych. Spróbuj innego wyszukiwania.',
    collapseTagsPanel: 'Zwiń panel tematów',
    expandTagsPanel: 'Rozwiń panel tematów',
    goToItemsList: 'Przejdź do listy elementów',
    goToAccountMenu: 'Przejdź do menu konta',
    openPreferences: 'Otwórz preferencje',
  },
  account: {
    account: 'Konto',
    signIn: 'Zaloguj się',
    signOut: 'Wyloguj się',
    signUp: 'Zarejestruj się',
    register: 'Zarejestruj się',
    you: 'Ty',
    encryptionOn: 'Szyfrowanie end-to-end włączone',
    notSignedIn: 'Nie jesteś zalogowany',
    signInOrRegister: 'Zaloguj się lub zarejestruj, aby synchronizować notatki',
    email: 'E-mail',
    password: 'Hasło',
    confirmPassword: 'Potwierdź hasło',
    syncNow: 'Synchronizuj teraz',
    lastSynced: 'Ostatnia synchronizacja',
    importData: 'Importuj',
    switchWorkspace: 'Przełącz obszar roboczy',
    lockApplication: 'Zablokuj aplikację',
    helpAndFeedback: 'Pomoc i opinie',
  },
  preferences: {
    title: 'Preferencje',
    general: 'Ogólne',
    account: 'Konto',
    security: 'Bezpieczeństwo',
    appearance: 'Wygląd',
    backups: 'Kopie zapasowe',
    listed: 'Listed',
    plugins: 'Wtyczki',
    whatsNew: 'Nowości',
    helpAndFeedback: 'Pomoc i opinie',
    language: 'Język',
    languageTitle: 'Język',
    languageDescription:
      'Wybierz język używany w całym interfejsie aplikacji. Aplikacja używa języka angielskiego dla treści jeszcze nieprzetłumaczonych.',
    languageChanged: 'Zaktualizowano język',
    defaults: 'Domyślne',
    tools: 'Narzędzia',
    spellcheck: 'Sprawdzanie pisowni',
    labs: 'Laboratoria',
  },
  editor: {
    cut: 'Wytnij',
    copy: 'Kopiuj',
    paste: 'Wklej',
    moreCutOptions: 'Więcej opcji wycinania',
    moreCopyOptions: 'Więcej opcji kopiowania',
    morePasteOptions: 'Więcej opcji wklejania',
    tableOfContents: 'Spis treści',
    selectAll: 'Zaznacz wszystko',
    selectAllText: 'Zaznacz tylko tekst',
    deselectAll: 'Odznacz wszystko',
    search: 'Szukaj',
    undo: 'Cofnij',
    redo: 'Ponów',
    undoHistory: 'Historia cofania',
    redoHistory: 'Historia ponawiania',
    undoHistoryEmpty: 'Historia cofania — nie ma nic do cofnięcia',
    undoHistoryAvailable: 'Historia cofania — cofnij kilka kroków naraz',
    redoHistoryEmpty: 'Historia ponawiania — nie ma nic do ponowienia',
    redoHistoryAvailable: 'Historia ponawiania — przejdź naprzód o kilka kroków naraz',
    formattingOptions: 'Opcje formatowania',
    bold: 'Pogrubienie',
    italic: 'Kursywa',
    underline: 'Podkreślenie',
    strikethrough: 'Przekreślenie',
    inlineCode: 'Kod w wierszu',
    link: 'Odnośnik',
    formatPainter: 'Malarz formatów — kopiuj formatowanie (kliknij dwukrotnie, aby pozostawić włączone)',
    textStyle: 'Styl tekstu',
    textColor: 'Kolor tekstu',
    highlightColor: 'Kolor wyróżnienia',
    typography: 'Typografia — wyróżnienie, kontur, odstępy między literami i słowami',
    typographyTitle: 'Typografia',
    fontSize: 'Rozmiar czcionki',
    chooseFontSize: 'Wybierz rozmiar czcionki',
    decreaseFontSize: 'Zmniejsz rozmiar czcionki',
    increaseFontSize: 'Zwiększ rozmiar czcionki',
    fontFamily: 'Krój czcionki',
    customFontFamily: 'Niestandardowy',
    bulletedList: 'Lista punktowana',
    numberedList: 'Lista numerowana',
    checkList: 'Lista kontrolna',
    quote: 'Cytat',
    codeBlock: 'Blok kodu',
    changeCase: 'Zmień wielkość liter',
    sortAndDedupeLines: 'Sortuj i usuń duplikaty wierszy',
    alignment: 'Wyrównanie',
    paragraphLayout: 'Układ akapitu — odstępy między wierszami i akapitami, wcięcia, cieniowanie',
    paragraphLayoutTitle: 'Układ akapitu',
    listStyleMarker: 'Styl listy — znacznik punktu i numeru',
    formattingMarks: 'Znaki formatowania',
    insert: 'Wstaw',
    insertRowAbove: 'Wstaw wiersz powyżej',
    insertRowBelow: 'Wstaw wiersz poniżej',
    insertColumnLeft: 'Wstaw kolumnę z lewej',
    insertColumnRight: 'Wstaw kolumnę z prawej',
    deleteRow: 'Usuń wiersz',
    deleteColumn: 'Usuń kolumnę',
    toggleRowHeader: 'Przełącz nagłówek wiersza',
    toggleColumnHeader: 'Przełącz nagłówek kolumny',
    deleteTable: 'Usuń tabelę',
    rows: 'Wiersze',
    columns: 'Kolumny',
    cells: 'Komórki',
    table: 'Tabela',
    block: 'Blok',
    alignLeft: 'Wyrównaj do lewej',
    alignCenter: 'Wyśrodkuj',
    alignRight: 'Wyrównaj do prawej',
    editLink: 'Edytuj odnośnik',
    removeLink: 'Usuń odnośnik',
    zoomIntoBlock: 'Powiększ blok',
    blockStyle: 'Styl bloku',
    heading1: 'Nagłówek 1',
    heading2: 'Nagłówek 2',
    heading3: 'Nagłówek 3',
    normalText: 'Tekst zwykły',
    moreFormatting: 'Więcej formatowania',
    createNoteFromSelectionTitle: 'Utwórz nową notatkę z zaznaczenia',
    createNoteFromSelectionDescription:
      'Tworzy nową notatkę zawierającą bieżące zaznaczenie i zastępuje zaznaczenie odnośnikiem do nowej notatki.',
    dismissKeyboard: 'Ukryj klawiaturę',
    tableOfContentsLower: 'Spis treści',
    noHeadingsFound: 'Nie znaleziono nagłówków',
    textFormattingOptions: 'Opcje formatowania tekstu',
    highlight: 'Wyróżnienie',
    subscript: 'Indeks dolny',
    superscript: 'Indeks górny',
    clearFormatting: 'Wyczyść formatowanie',
    normal: 'Zwykły',
    smartChecklist: 'Inteligentna lista kontrolna',
    restoreCompletedTasks: 'Przywróć ukończone zadania',
    leftAlign: 'Wyrównaj do lewej',
    centerAlign: 'Wyśrodkuj',
    rightAlign: 'Wyrównaj do prawej',
    justify: 'Wyjustuj',
    searchBlocksPlaceholder: 'Szukaj bloków…',
    searchBlocksToInsert: 'Szukaj bloków do wstawienia',
    clearSearch: 'Wyczyść wyszukiwanie',
    noBlocksMatch: 'Żaden blok nie pasuje do „{{query}}”',
    customizeToolbar: 'Dostosuj pasek narzędzi',
    custom: 'Niestandardowy',
    clear: 'Wyczyść',
    textColorSwatch: 'Kolor tekstu {{color}}',
    highlightColorSwatch: 'Kolor wyróżnienia {{color}}',
    textShadingSwatch: 'Cieniowanie tekstu {{color}}',
    noTextShading: 'Brak cieniowania tekstu',
    uppercase: 'WIELKIE LITERY',
    lowercase: 'małe litery',
    camelCase: 'camelCase',
    sortLines: 'Sortuj wiersze',
    deduplicate: 'Usuń duplikaty',
    multiKeySort: 'Sortowanie wielokluczowe (1., 2., 3.)…',
    sortAndDeduplicateLines: 'Sortuj i usuń duplikaty wierszy',
    emphasisMarks: 'Znaki wyróżnienia',
    outlineTextStroke: 'Kontur (obrys tekstu)',
    letterSpacingKerning: 'Odstępy między literami (kerning)',
    wordSpacing: 'Odstępy między słowami',
    clearTypography: 'Wyczyść typografię',
    spacingTight: 'Ciasny',
    spacingNormal: 'Zwykły',
    spacingWide: 'Szeroki',
    spacingWider: 'Szerszy',
    spacingWidest: 'Najszerszy',
    undoMultipleSteps: 'Cofnij wiele kroków',
    redoMultipleSteps: 'Ponów wiele kroków',
    emptyHistoryPreview: '(pusto)',
    pasteOptions: 'Opcje wklejania',
    copyOptions: 'Opcje kopiowania',
    cutOptions: 'Opcje wycinania',
    pasteWithoutFormatting: 'Wklej bez formatowania',
    pasteClean: 'Wklej bez śmieci (usuń ukryte znaki)',
    keepSourceFormatting: 'Zachowaj formatowanie źródła',
    matchDestinationFormatting: 'Dopasuj do formatowania docelowego',
    pasteAsImage: 'Wklej jako obraz',
    copyWithoutFormatting: 'Kopiuj bez formatowania',
    copyTextOnly: 'Kopiuj tylko tekst',
    copyImagesOnly: 'Kopiuj tylko obrazy',
    cutWithoutFormatting: 'Wytnij bez formatowania',
    cutTextOnly: 'Wytnij tylko tekst',
    cutImagesOnly: 'Wytnij tylko obrazy',
    lineSpacing: 'Odstępy między wierszami',
    spaceBefore: 'Odstęp przed',
    spaceAfter: 'Odstęp po',
    indentation: 'Wcięcie',
    none: 'Brak',
    increaseLeft: 'Zwiększ z lewej',
    decreaseLeft: 'Zmniejsz z lewej',
    increaseRight: 'Zwiększ z prawej',
    decreaseRight: 'Zmniejsz z prawej',
    firstLine: 'Pierwszy wiersz',
    noFirstLine: 'Bez pierwszego wiersza',
    textShading: 'Cieniowanie tekstu',
    listStyle: 'Styl listy',
    bulleted: 'Punktowana',
    numbered: 'Numerowana',
    bulletedListMarkers: 'Styl znacznika punktu',
    numberedListMarkers: 'Styl numerowania',
    multilevelList: 'Lista wielopoziomowa',
    multilevelListHint: 'Wybierz znacznik dla każdego poziomu zagnieżdżenia',
    multilevelLevelDefault: 'Domyślny',
    level: 'Poziom',
    apply: 'Zastosuj',
    insertTable: 'Wstaw tabelę',
    insertImageFromUrl: 'Wstaw obraz z adresu URL',
    sortLinesModalTitle: 'Sortuj wiersze',
    blockPicker: 'Selektor bloków',
    blockParagraph: 'Akapit',
    blockCallout: 'Objaśnienie',
    blockDivider: 'Separator',
    blockCollapsible: 'Sekcja zwijana',
    blockImageFromUrl: 'Obraz z adresu URL',
    blockUploadFile: 'Prześlij plik',
    blockDrawing: 'Rysunek',
    blockQrCode: 'Kod QR',
    blockTable: 'Tabela',
    blockKanbanBoard: 'Tablica Kanban',
    blockCalendar: 'Kalendarz',
    blockTimeline: 'Oś czasu',
    blockDataTable: 'Tabela danych',
    blockSqlQuery: 'Zapytanie SQL',
    blockMermaidDiagram: 'Diagram Mermaid',
    blockGanttChart: 'Wykres Gantta',
    blockTimingDiagram: 'Diagram czasowy',
    blockMusicStaff: 'Pięciolinia',
    blockTradingViewChart: 'Wykres TradingView',
    blockStockChart: 'Wykres giełdowy',
    blockEmbed: 'Osadź',
    blockEmbedWebsite: 'Osadź witrynę',
    blockTweet: 'Tweet',
    blockEquation: 'Równanie',
    blockInlineEquation: 'Równanie w wierszu',
    blockFootnote: 'Przypis',
    blockBookmark: 'Zakładka',
    blockGeneratePassword: 'Wygeneruj kryptograficznie bezpieczne hasło',
    blockClock: 'Zegar',
    blockCurrentDateTime: 'Bieżąca data i godzina',
    blockCurrentTime: 'Bieżąca godzina',
    blockCurrentDate: 'Bieżąca data',
    blockCategoryBasic: 'Podstawowe',
    blockCategoryLists: 'Listy',
    blockCategoryMedia: 'Multimedia',
    blockCategoryDataTables: 'Dane i tabele',
    blockCategoryDiagramsCharts: 'Diagramy i wykresy',
    blockCategoryFinance: 'Finanse',
    blockCategoryEmbeds: 'Osadzenia',
    blockCategoryAdvanced: 'Zaawansowane',
  },
  files: {
    dropToUploadTooltip: 'Upuść pliki, aby przesłać je i połączyć z bieżącym plikiem',
    fileAriaLabel: 'Plik',
    fileReadonly: 'Ten plik jest tylko do odczytu',
    fileInformationPanel: 'Panel informacji o pliku',
    details: 'Szczegóły',
    selectedFilesCount: '{{count}} zaznaczonych plików',
    actionsPerformedOnSelected: 'Akcje zostaną wykonane na wszystkich zaznaczonych plikach.',
    cancelMultipleSelection: 'Anuluj zaznaczenie wielokrotne',
    fileOptions: 'Opcje pliku',
    fileContextMenu: 'Menu kontekstowe pliku',
    fileOptionsMenu: 'Menu opcji pliku',
    fileOptionsPanel: 'Panel opcji pliku',
    noFilesSelected: 'Nie zaznaczono plików',
    detachFromNote: 'Odłącz od notatki',
    attachToNote: 'Załącz do notatki',
    passwordProtect: 'Zabezpiecz hasłem',
    downloadSeparately: 'Pobierz osobno',
    downloadAsArchive: 'Pobierz jako archiwum',
    failedToDownloadArchive: 'Nie udało się pobrać plików jako archiwum',
    fileId: 'ID pliku:',
    size: 'Rozmiar:',
    totalSize: 'Rozmiar łączny:',
    backedUpOn: 'Utworzono kopię zapasową {{date}}',
    configureFileBackups: 'Skonfiguruj kopie zapasowe plików',
    fileNotBackedUpLocally: 'Plik nie ma lokalnej kopii zapasowej',
    noFoldersYet: 'Brak folderów',
    moveToFolder: 'Przenieś do folderu',
    folderSelectionMenu: 'Menu wyboru folderu',
    noFolder: 'Brak folderu',
    fileProtected: 'Ten plik jest chroniony.',
    authenticateToView: 'Uwierzytelnij się, aby wyświetlić ten plik.',
    addPasscodeToView: 'Dodaj kod dostępu lub utwórz konto, aby wymagać uwierzytelnienia do wyświetlenia tego pliku.',
    openAccountMenu: 'Otwórz menu konta',
    authenticate: 'Uwierzytelnij',
    viewFile: 'Wyświetl plik',
    loading: 'Ładowanie...',
    fileCannotBePreviewed: 'Nie można wyświetlić podglądu tego pliku.',
    errorLoadingFile:
      'Wystąpił błąd podczas ładowania pliku. Spróbuj ponownie lub pobierz plik i otwórz go w innej aplikacji.',
    tryAgain: 'Spróbuj ponownie',
    downloadToView: 'Aby wyświetlić ten plik, pobierz go i otwórz w innej aplikacji.',
    fileInformation: 'Informacje o pliku',
    type: 'Typ:',
    decryptedSize: 'Rozmiar odszyfrowany:',
    encryptedSize: 'Rozmiar zaszyfrowany:',
    created: 'Utworzono:',
    lastModified: 'Ostatnia modyfikacja:',
    done: 'Gotowe',
    showFileOptions: 'Pokaż opcje pliku',
    showFileInfo: 'Pokaż informacje o pliku',
    hideFileInfo: 'Ukryj informacje o pliku',
    showLinksSection: 'Pokaż sekcję odnośników',
    hideLinksSection: 'Ukryj sekcję odnośników',
    submit: 'Zatwierdź',
    renameFile: 'Zmień nazwę pliku',
    showLinkedItems: 'Pokaż połączone elementy',
    closeModal: 'Zamknij okno',
    filePreviewModal: 'Okno podglądu pliku',
    leftAlign: 'Wyrównaj do lewej',
    centerAlign: 'Wyśrodkuj',
    rightAlign: 'Wyrównaj do prawej',
    videoCannotBePreviewed: 'Nie można wyświetlić podglądu tego wideo.',
    audioCannotBePlayed: 'Nie można odtworzyć tego dźwięku.',
    downloadToListen: 'Aby odsłuchać ten plik, pobierz go i otwórz w innej aplikacji.',
    externalAppOnly: 'Podgląd tego pliku jest możliwy tylko w zewnętrznej aplikacji',
    openFilePreview: 'Otwórz podgląd pliku',
    loadingPdfViewer: 'Ładowanie przeglądarki PDF...',
    zoomOut: 'Pomniejsz',
    zoomIn: 'Powiększ',
    resetToActualSize: 'Przywróć rzeczywisty rozmiar',
    resetTo100: 'Przywróć do 100%',
    fitToScreen: 'Dopasuj do ekranu',
    unableToRenderPdf: 'Nie można wyrenderować tego pliku PDF.',
    pdfCorruptedOrProtected: 'Plik może być uszkodzony lub chroniony hasłem.',
    loadingPdf: 'Ładowanie PDF...',
    previousPage: 'Poprzednia strona',
    pageNumber: 'Numer strony',
    nextPage: 'Następna strona',
    fitWidth: 'Dopasuj szerokość',
    searchInDocumentShortcut: 'Szukaj w dokumencie (Ctrl/Cmd+F)',
    searchInDocument: 'Szukaj w dokumencie',
    copyLinkToPage: 'Kopiuj odnośnik do strony {{page}}',
    copyLinkToThisPage: 'Kopiuj odnośnik do tej strony',
    copyLinkToSelectedText: 'Kopiuj odnośnik do zaznaczonego tekstu',
    cancelOcr: 'Anuluj OCR',
    preparingOcr: 'Przygotowywanie OCR...',
    ocrProgress: 'OCR strona {{current}} / {{total}} ({{percent}}%)',
    ocrCachedReRunTooltip:
      'Tekst już wyodrębniony (z pamięci podręcznej). Uruchom OCR ponownie w przeglądarce (pozostaje na urządzeniu).',
    ocrExtractedReRunTooltip: 'Tekst wyodrębniony. Uruchom OCR ponownie w przeglądarce (pozostaje na urządzeniu).',
    ocrExtractTooltip:
      'Wyodrębnij tekst ze skanowanych stron za pomocą OCR. Działa w przeglądarce; nic nie opuszcza Twojego urządzenia (wolne; pobiera dane językowe).',
    extractTextWithOcrBrowser: 'Wyodrębnij tekst za pomocą OCR w przeglądarce',
    reRunOcrBrowser: 'Uruchom OCR ponownie (przeglądarka)',
    extractTextOcr: 'Wyodrębnij tekst (OCR)',
    serverOcrTooltip:
      'Uruchom OCR na SERWERZE. Powoduje to wysłanie obrazów stron tego pliku PDF na serwer i OPUSZCZA szyfrowanie end-to-end — serwer może odczytać tę treść. OCR w przeglądarce zachowuje wszystko na Twoim urządzeniu.',
    runOcrOnServerAria: 'Uruchom OCR na serwerze (wysyła obrazy stron na serwer; opuszcza szyfrowanie end-to-end)',
    runOcrOnServer: 'Uruchom OCR na serwerze',
    copyAllExtractedText: 'Kopiuj cały wyodrębniony tekst',
    copyExtractedTextAria: 'Kopiuj wyodrębniony tekst',
    findInDocument: 'Znajdź w dokumencie',
    matchCase: 'Uwzględnij wielkość liter',
    noResults: 'Brak wyników',
    matchOfTotal: '{{current}} z {{total}}',
    previousMatch: 'Poprzednie dopasowanie',
    nextMatch: 'Następne dopasowanie',
    closeSearch: 'Zamknij wyszukiwanie',
    serverOcrDisclosurePrefix:
      'OCR na serwerze jest dostępny dla Twojego konta. Wysyła obrazy stron tego pliku PDF na serwer i',
    serverOcrDisclosureBold: 'opuszcza szyfrowanie end-to-end',
    serverOcrDisclosureSuffix:
      ' — serwer (i każdy, kto go kontroluje) może odczytać tę treść. OCR w przeglądarce zachowuje wszystko na Twoim urządzeniu. Domyślnie używany jest OCR w przeglądarce.',
    ocrRunningServer:
      'OCR na serwerze: obrazy stron tego pliku PDF są przesyłane na serwer, co OPUSZCZA szyfrowanie end-to-end — serwer może odczytać tę treść. (OCR w przeglądarce zachowuje wszystko na Twoim urządzeniu.)',
    ocrRunningBrowser:
      'OCR działa w Twojej przeglądarce na tym urządzeniu (Twoje pliki pozostają zaszyfrowane end-to-end). Jest wolny i przy pierwszym użyciu pobiera dane językowe.',
    ocrDoneServer:
      'OCR na serwerze zakończony. Obrazy stron zostały wysłane na serwer (opuściło to szyfrowanie end-to-end). Dokładność zależy od jakości skanu; wyodrębniony tekst jest teraz przeszukiwalny i można go kopiować, a także jest buforowany na tym urządzeniu.',
    ocrDoneBrowser:
      'OCR zakończony. Dokładność zależy od jakości skanu; wyodrębniony tekst jest teraz przeszukiwalny i można go kopiować, a także jest buforowany na tym urządzeniu.',
    copiedExtractedText: 'Skopiowano wyodrębniony tekst',
    copiedLinkToPage: 'Skopiowano odnośnik do strony {{page}}',
    copiedLinkToSelectedText: 'Skopiowano odnośnik do zaznaczonego tekstu',
    serverOcrFailed: 'OCR na serwerze nie powiódł się: {{message}}',
    ocrUnknownError: 'nieznany błąd',
    ocrFailed: 'OCR nie powiódł się. Dane językowe mogły nie zostać pobrane.',
  },
  notes: {
    notesAndFiles: 'Notatki i pliki',
    selectAllItems: 'Zaznacz wszystkie elementy',
    selectedCount: 'Zaznaczono: {{count}}',
    cancelMultipleSelection: 'Anuluj zaznaczenie wielokrotne',
    noFilesInFolder: 'Brak plików w tym folderze.',
    noItems: 'Brak elementów.',
    loading: 'Ładowanie...',
    uploadFileWithShortcut: 'Prześlij plik {{shortcut}}',
    createNoteInTopicWithShortcut: 'Utwórz nową notatkę w wybranym temacie {{shortcut}}',
    dropFilesToUpload: 'Upuść pliki, aby przesłać je i połączyć z tematem „{{title}}”',
    noFilesYet: 'Nie masz jeszcze żadnych plików',
    filesAttachedAppearHere:
      'Pliki załączone do notatek pojawią się tutaj. Możesz też przesyłać pliki bezpośrednio z tej strony.',
    uploadFiles: 'Prześlij pliki',
    syncing: 'Synchronizowanie...',
    loadingItemsProgress: 'Ładowanie {{current}}/{{total}} elementów...',
    potentiallyOutOfSync: 'Prawdopodobnie niezsynchronizowane',
    openDisplayOptionsMenu: 'Otwórz menu opcji wyświetlania',
    displayOptionsMenu: 'Menu opcji wyświetlania',
    displayOptions: 'Opcje wyświetlania',
    expandTopicsPanel: 'Rozwiń panel tematów',
    collapseNotesPanel: 'Zwiń panel notatek',
    addItem: 'Dodaj element',
    uploadFolder: 'Prześlij folder',
    takePhoto: 'Zrób zdjęcie',
    recordVideo: 'Nagraj wideo',
    searchPlaceholder: 'Szukaj...',
    notesListOptionsMenu: 'Menu opcji listy notatek',
    preferencesFor: 'Preferencje dla',
    global: 'Globalne',
    reset: 'Resetuj',
    upgradeForPerTopicPreferences: 'Ulepsz, aby uzyskać preferencje dla każdego tematu',
    perTopicPreferencesMessageWithDaily:
      'Twórz zaawansowane procesy pracy i układy organizacyjne dzięki preferencjom wyświetlania dla każdego tematu oraz zupełnie nowemu układowi kalendarza Codzienny notatnik.',
    perTopicPreferencesMessage:
      'Twórz zaawansowane procesy pracy i układy organizacyjne dzięki preferencjom wyświetlania dla każdego tematu.',
    sortBy: 'Sortuj według',
    relevanceBestMatch: 'Trafność (najlepsze dopasowanie)',
    dateModified: 'Data modyfikacji',
    creationDate: 'Data utworzenia',
    title: 'Tytuł',
    customDragToReorder: 'Niestandardowe (przeciągnij, aby zmienić kolejność)',
    view: 'Widok',
    showNotePreview: 'Pokaż podgląd notatki',
    showDate: 'Pokaż datę',
    showTags: 'Pokaż tematy',
    showIcon: 'Pokaż ikonę',
    other: 'Inne',
    showPinned: 'Pokaż przypięte',
    showProtected: 'Pokaż chronione',
    showArchived: 'Pokaż zarchiwizowane',
    showTrashed: 'Pokaż w koszu',
    dailyNotebook: 'Codzienny notatnik',
    labs: 'Labs',
    dailyNotebookDescription: 'Twórz nowe notatki codziennie w układzie opartym na kalendarzu',
    tableView: 'Widok tabeli',
    tableViewDescription: 'Wyświetl notatki i pliki w bieżącym temacie w układzie tabeli',
    newNoteDefaults: 'Domyślne dla nowej notatki',
    noteType: 'Typ notatki',
    selectDefaultNoteType: 'Wybierz domyślny typ notatki',
    titleFormat: 'Format tytułu',
    selectTitleFormat: 'Wybierz format tytułu notatki',
    customFormatPlaceholder: 'np. RRRR-MM-DD',
    preview: 'Podgląd: ',
    useBracketsToEscape: '. Użyj ',
    toEscapeFormatting: ' aby pominąć formatowanie.',
    protected: 'Chronione',
    modified: 'Zmodyfikowano',
    now: 'Teraz',
    editingDisabled: 'Edycja wyłączona',
    trashed: 'W koszu',
    archived: 'Zarchiwizowane',
    files: 'Pliki',
    starred: 'Oznaczone gwiazdką',
    fileBackedUpLocally: 'Plik ma lokalną kopię zapasową',
    conflictedCopy: 'Kopia skonfliktowana',
    allFiles: 'Wszystkie pliki',
    noFolder: 'Brak folderu',
    folderNamePlaceholder: 'Nazwa folderu',
    createNewFolder: 'Utwórz nowy folder',
    newFolder: 'Nowy folder',
    currentStreak: 'Bieżąca passa',
    dayWithCount_one: 'dzień',
    dayWithCount_few: 'dni',
    dayWithCount_many: 'dni',
    dayWithCount_other: 'dnia',
  },
  auth: {
    unableToComputePrivateUsername: 'Nie można obliczyć prywatnej nazwy użytkownika.',
    advancedOptions: 'Opcje zaawansowane',
    privateUsernameMode: 'Tryb prywatnej nazwy użytkownika',
    username: 'Nazwa użytkownika',
    useStrictSignIn: 'Użyj ścisłego logowania',
    useRecoveryCode: 'Użyj kodu odzyskiwania',
    recoveryCode: 'Kod odzyskiwania',
    deleteLocalDataTitle: 'Usunąć dane lokalne?',
    noMergeWarning:
      'Zdecydowałeś się nie scalać danych lokalnych. Jeśli będziesz kontynuować, Twoje lokalne notatki i tematy zostaną trwale usunięte i zastąpione danymi z Twojego konta. Tej operacji nie można cofnąć.',
    noMergeConfirmQuestion: 'Czy na pewno chcesz kontynuować bez scalania?',
    deleteLocalDataAndContinue: 'Usuń dane lokalne i kontynuuj',
    passwordResetWarningPart1: 'Ponieważ Twoje notatki są szyfrowane przy użyciu hasła,',
    passwordResetWarningHighlight: 'Standard Red Notes nie oferuje opcji resetowania hasła',
    passwordResetWarningPart2: '. Jeśli zapomnisz hasła, na zawsze utracisz dostęp do swoich danych.',
    confirmPassword: 'Potwierdź hasło',
    creatingAccount: 'Tworzenie konta...',
    createAccountAndSignIn: 'Utwórz konto i zaloguj się',
    staySignedIn: 'Pozostań zalogowany',
    goBack: 'Wróć',
    humanVerification: 'Weryfikacja człowieka',
    confirmPasswordTitle: 'Potwierdź hasło',
    createAccount: 'Utwórz konto',
    workspaceNameOptional: 'Nazwa obszaru roboczego (opcjonalnie)',
    generalAccountMenuLabel: 'Ogólne menu konta',
    signedInAs: 'Jesteś zalogowany jako:',
    syncing: 'Synchronizowanie...',
    lastSynced: 'Ostatnia synchronizacja:',
    offlineSignInPrompt:
      'Jesteś offline. Zaloguj się, aby synchronizować notatki i preferencje na wszystkich urządzeniach oraz włączyć szyfrowanie end-to-end.',
    offline: 'Offline',
    accountSettings: 'Ustawienia konta',
    createFreeAccount: 'Utwórz darmowe konto',
    documentation: 'Dokumentacja',
    keyboardShortcuts: 'Skróty klawiszowe',
    commandPalette: 'Paleta poleceń',
    signOutWorkspace: 'Wyloguj z obszaru roboczego',
    mergeLocalData: 'Scal dane lokalne ({{count}} notatek i tematów)',
    mergeLocalDataTooltip:
      'Jeśli odznaczone, Twoje lokalne notatki i tematy zostaną trwale usunięte i zastąpione danymi z Twojego konta.',
    homeServerNotRunning:
      'Serwer domowy nie jest uruchomiony. Otwórz preferencje i kartę serwera domowego, aby go uruchomić.',
    serverDefault: 'Domyślny',
    serverCustom: 'Niestandardowy',
    serverHomeServer: 'Serwer domowy',
    syncServer: 'Serwer synchronizacji',
    signingIn: 'Logowanie...',
    syncUnreachable: 'Synchronizacja nieosiągalna',
    syncUnreachableMessage: 'Hmm... nie możemy zsynchronizować Twojego konta. Powód: {{reason}}',
    workspaceSwitcherMenuLabel: 'Menu przełączania obszarów roboczych',
    signOutAllWorkspacesConfirm:
      'Czy na pewno chcesz wylogować się ze wszystkich obszarów roboczych na tym urządzeniu?',
    signOutAll: 'Wyloguj ze wszystkich',
    addAnotherWorkspace: 'Dodaj kolejny obszar roboczy',
    signOutAllWorkspaces: 'Wyloguj ze wszystkich obszarów roboczych',
    deleteAccountTitle: 'Usunąć konto?',
    deleteMyAccountForGood: 'Usuń moje konto na zawsze',
    dataNotBackedUp: 'Dane bez kopii zapasowej',
    signInOrRegisterToSync:
      'Zaloguj się lub zarejestruj, aby synchronizować notatki na innych urządzeniach z szyfrowaniem end-to-end.',
    openAccountMenu: 'Otwórz menu konta',
    ignoreWarning: 'Zignoruj ostrzeżenie',
    waitingForSecurityKey: 'Oczekiwanie na klucz bezpieczeństwa...',
    authenticationSuccessful: 'Uwierzytelnianie powiodło się!',
    insertSecurityKeyPrompt:
      'Włóż sprzętowy klucz bezpieczeństwa, a następnie naciśnij poniższy przycisk, aby się uwierzytelnić.',
    authenticate: 'Uwierzytelnij',
  },
  search: {
    placeholder: 'Szukaj...',
    protectedContents: 'Chronione treści',
    archived: 'Zarchiwizowane',
    trashed: 'W koszu',
    aiUnavailable: 'Ponowne rankingowanie AI jest niedostępne lub nie zwróciło wyniku.',
    aiUnavailableTooltip: 'Kontekstowe wyszukiwanie AI jest niedostępne.',
    aiTypeQueryFirst: 'Najpierw wpisz zapytanie.',
    aiTooltip:
      'Zmień kolejność najlepszych wyników według trafności semantycznej, korzystając ze skonfigurowanego dostawcy AI. ' +
      'Wysyła tytuły i krótkie fragmenty tych kandydatów oraz Twoje zapytanie do dostawcy.',
    aiSearchWithAi: 'Szukaj z AI',
    aiRanking: 'Rankingowanie…',
    aiRankedByRelevance: 'Uszeregowano według trafności AI',
    aiPrivacyNotice:
      'Wysyła tytuły i fragmenty najlepszych wyników oraz Twoje zapytanie do dostawcy AI. Dostawcy w chmurze będą je widzieć — ' +
      'model lokalny zachowuje to na urządzeniu.',
    advancedFilters: 'Zaawansowane filtry wyszukiwania',
    filters: 'Filtry',
    noteTypeAny: 'Dowolny typ',
    noteTypePlainText: 'Zwykły tekst',
    noteTypeRichText: 'Tekst sformatowany',
    noteTypeSuper: 'Super',
    noteTypeMarkdown: 'Markdown',
    noteTypeCode: 'Kod',
    noteTypeTask: 'Zadanie',
    noteTypeSpreadsheet: 'Arkusz kalkulacyjny',
    flagProtected: 'Chronione',
    flagPinned: 'Przypięte',
    flagArchived: 'Zarchiwizowane',
    flagStarred: 'Oznaczone gwiazdką',
    flagTrashed: 'W koszu',
    topicsLabel: 'Tematy (oddzielone przecinkami)',
    topicsPlaceholder: 'praca, prywatne',
    noteTypeLabel: 'Typ notatki',
    searchInLabel: 'Szukaj w',
    searchInTitleAndContent: 'Tytuł i treść',
    modifiedWithinLabel: 'Zmodyfikowano w ciągu',
    datePreset: 'Ostatnie {{label}}',
    createdAfterLabel: 'Utworzono po',
    createdBeforeLabel: 'Utworzono przed',
    updatedAfterLabel: 'Zaktualizowano po',
    updatedBeforeLabel: 'Zaktualizowano przed',
    statusLabel: 'Status',
    hasAttachments: 'Ma załączniki',
    caseSensitive: 'Uwzględnij wielkość liter',
    clearAllFilters: 'Wyczyść wszystkie filtry',
  },
  sharing: {
    vaultSelectionMenu: 'Menu wyboru sejfu',
    vaultOptionsMenu: 'Menu opcji sejfu',
    vaultOptions: 'Opcje sejfu',
    noVaultsFound: 'Nie znaleziono sejfów',
    moveToVault: 'Przenieś do sejfu',
    moveOutOfVault: 'Przenieś poza {{name}}',
    vaultsFallbackName: 'sejfy',
    editVault: 'Edytuj sejf',
    lockVault: 'Zablokuj sejf',
    unlockVault: 'Odblokuj sejf',
    openVaultSettings: 'Otwórz ustawienia sejfu',
    selectionModeMultiple: 'Wiele',
    selectionModeOne: 'Jeden',
    lastEditedBy: 'Ostatnio edytowane przez',
    sharedBy: 'Udostępnione przez',
    sharedByContact: 'Udostępnione przez kontakt',
    vaultName: 'Nazwa sejfu',
    sharedInVault: 'Udostępnione w sejfie',
    copiedToClipboard: 'Skopiowano do schowka',
    failedToCopyToClipboard: 'Nie udało się skopiować do schowka',
    copyExampleToClipboard: 'Kopiuj przykład do schowka',
    copiedExclaim: 'Skopiowano!',
    shareUnavailableTitle: 'Udostępnianie niedostępne',
    shareUnavailableMessage: 'Ten link udostępniania nie jest już dostępny.',
    invalidLinkTitle: 'Nieprawidłowy link',
    invalidLinkMessage: 'Ten link udostępniania jest nieprawidłowy lub brakuje klucza.',
    selfDestructTitle: 'Ta notatka samoczynnie usuwa się po wyświetleniu',
    oneTimeViewConsumed:
      'Czytasz link jednorazowego wyświetlenia. Został on teraz wykorzystany i nie można go ponownie otworzyć',
    oneTimeViewExpiresClause_one: ', i całkowicie wygasa {{count}} minutę po pierwszym otwarciu',
    oneTimeViewExpiresClause_few: ', i całkowicie wygasa {{count}} minuty po pierwszym otwarciu',
    oneTimeViewExpiresClause_many: ', i całkowicie wygasa {{count}} minut po pierwszym otwarciu',
    oneTimeViewExpiresClause_other: ', i całkowicie wygasa {{count}} minuty po pierwszym otwarciu',
    linkExpires_one: 'Ten link wygasa {{count}} minutę po pierwszym otwarciu.',
    linkExpires_few: 'Ten link wygasa {{count}} minuty po pierwszym otwarciu.',
    linkExpires_many: 'Ten link wygasa {{count}} minut po pierwszym otwarciu.',
    linkExpires_other: 'Ten link wygasa {{count}} minuty po pierwszym otwarciu.',
    untitled: 'Bez tytułu',
    tagHasNoNotes: 'Ten temat nie ma notatek.',
    publicReadOnlyFooter:
      'To jest publiczny link udostępniania tylko do odczytu. Treść została odszyfrowana w Twojej przeglądarce.',
    confidentialWatermark: 'Poufne · {{datetime}}',
    contentHiddenTitle: 'Treść ukryta',
    contentHiddenMessage: 'Przywróć fokus do tego okna, aby wyświetlić udostępnioną treść.',
  },
}

export default pl
