import type { LocaleResource } from './en'

// Português brasileiro (pt-BR). Brazilian vocabulary/spelling
// (e.g. "arquivos", "cadastrar", "excluir", "senha").
const ptBR: LocaleResource = {
  common: {
    save: 'Salvar',
    cancel: 'Cancelar',
    delete: 'Excluir',
    confirm: 'Confirmar',
    close: 'Fechar',
    edit: 'Editar',
    rename: 'Renomear',
    duplicate: 'Duplicar',
    remove: 'Remover',
    open: 'Abrir',
    create: 'Criar',
    add: 'Adicionar',
    done: 'Concluído',
    back: 'Voltar',
    next: 'Próximo',
    search: 'Pesquisar',
    clear: 'Limpar',
    loading: 'Carregando…',
    copy: 'Copiar',
    copied: 'Copiado',
    download: 'Baixar',
    upload: 'Enviar',
    export: 'Exportar',
    import: 'Importar',
    yes: 'Sim',
    no: 'Não',
    enabled: 'Ativado',
    disabled: 'Desativado',
    on: 'Ligado',
    off: 'Desligado',
    learnMore: 'Saiba mais',
    options: 'Opções',
    settings: 'Configurações',
    preferences: 'Preferências',
    help: 'Ajuda',
    pin: 'Fixar',
    unpin: 'Desafixar',
    star: 'Marcar com estrela',
    unstar: 'Remover estrela',
    archive: 'Arquivar',
    unarchive: 'Desarquivar',
    restore: 'Restaurar',
    moveToTrash: 'Mover para a lixeira',
    deletePermanently: 'Excluir permanentemente',
    protect: 'Proteger',
    unprotect: 'Desproteger',
  },
  navigation: {
    notes: 'Notas',
    allNotes: 'Todas as notas',
    files: 'Arquivos',
    starred: 'Com estrela',
    archived: 'Arquivadas',
    trash: 'Lixeira',
    untagged: 'Sem tópico',
    conflicts: 'Conflitos',
    views: 'Visualizações',
    smartViews: 'Visualizações inteligentes',
    tags: 'Tópicos',
    folders: 'Pastas',
    favorites: 'Favoritos',
    dashboard: 'Painel',
    createNewNote: 'Criar uma nova nota',
    createNewTag: 'Criar um novo tópico',
    createNewFolder: 'Criar uma nova pasta',
    createNewSmartView: 'Criar uma nova visualização inteligente',
    searchTags: 'Pesquisar tópicos…',
    noTagsFound: 'Nenhum tópico encontrado. Tente outra pesquisa.',
    noSmartViewsFound: 'Nenhuma visualização inteligente encontrada. Tente outra pesquisa.',
    collapseTagsPanel: 'Recolher painel de tópicos',
    expandTagsPanel: 'Expandir painel de tópicos',
    goToItemsList: 'Ir para a lista de itens',
    goToAccountMenu: 'Ir para o menu da conta',
    openPreferences: 'Abrir preferências',
  },
  account: {
    account: 'Conta',
    signIn: 'Entrar',
    signOut: 'Sair',
    signUp: 'Cadastrar',
    register: 'Cadastrar',
    you: 'Você',
    encryptionOn: 'Criptografia de ponta a ponta ativada',
    notSignedIn: 'Você não está conectado',
    signInOrRegister: 'Entre ou cadastre-se para sincronizar suas notas',
    email: 'E-mail',
    password: 'Senha',
    confirmPassword: 'Confirmar senha',
    syncNow: 'Sincronizar agora',
    lastSynced: 'Última sincronização',
    importData: 'Importar',
    switchWorkspace: 'Trocar de espaço de trabalho',
    lockApplication: 'Bloquear o aplicativo',
    helpAndFeedback: 'Ajuda e feedback',
  },
  preferences: {
    title: 'Preferências',
    general: 'Geral',
    account: 'Conta',
    security: 'Segurança',
    appearance: 'Aparência',
    backups: 'Backups',
    listed: 'Listed',
    plugins: 'Plugins',
    whatsNew: 'Novidades',
    helpAndFeedback: 'Ajuda e feedback',
    language: 'Idioma',
    languageTitle: 'Idioma',
    languageDescription:
      'Escolha o idioma usado em toda a interface do aplicativo. O aplicativo usa o inglês para o que ainda não foi traduzido.',
    languageChanged: 'Idioma atualizado',
    defaults: 'Padrões',
    tools: 'Ferramentas',
    spellcheck: 'Verificação ortográfica',
    labs: 'Laboratórios',
  },
  editor: {
    cut: 'Recortar',
    copy: 'Copiar',
    paste: 'Colar',
    moreCutOptions: 'Mais opções de recortar',
    moreCopyOptions: 'Mais opções de copiar',
    morePasteOptions: 'Mais opções de colar',
    tableOfContents: 'Sumário',
    selectAll: 'Selecionar tudo',
    selectAllText: 'Selecionar apenas o texto',
    deselectAll: 'Desmarcar tudo',
    search: 'Pesquisar',
    undo: 'Desfazer',
    redo: 'Refazer',
    undoHistory: 'Histórico de desfazer',
    redoHistory: 'Histórico de refazer',
    undoHistoryEmpty: 'Histórico de desfazer — nada para desfazer ainda',
    undoHistoryAvailable: 'Histórico de desfazer — volte várias etapas de uma vez',
    redoHistoryEmpty: 'Histórico de refazer — nada para refazer',
    redoHistoryAvailable: 'Histórico de refazer — avance várias etapas de uma vez',
    formattingOptions: 'Opções de formatação',
    bold: 'Negrito',
    italic: 'Itálico',
    underline: 'Sublinhado',
    strikethrough: 'Tachado',
    inlineCode: 'Código em linha',
    link: 'Link',
    formatPainter: 'Pincel de formatação — copiar formatação (clique duplo para manter ativado)',
    textStyle: 'Estilo de texto',
    textColor: 'Cor do texto',
    highlightColor: 'Cor do realce',
    typography: 'Tipografia — ênfase, contorno, espaçamento entre letras e palavras',
    typographyTitle: 'Tipografia',
    fontSize: 'Tamanho da fonte',
    chooseFontSize: 'Escolher tamanho da fonte',
    decreaseFontSize: 'Diminuir tamanho da fonte',
    increaseFontSize: 'Aumentar tamanho da fonte',
    fontFamily: 'Família da fonte',
    customFontFamily: 'Personalizada',
    bulletedList: 'Lista com marcadores',
    numberedList: 'Lista numerada',
    checkList: 'Lista de tarefas',
    quote: 'Citação',
    codeBlock: 'Bloco de código',
    changeCase: 'Alterar maiúsculas/minúsculas',
    sortAndDedupeLines: 'Ordenar e remover linhas duplicadas',
    alignment: 'Alinhamento',
    paragraphLayout: 'Layout do parágrafo — espaçamento entre linhas e parágrafos, recuo, sombreamento',
    paragraphLayoutTitle: 'Layout do parágrafo',
    listStyleMarker: 'Estilo de lista — marcador e numeração',
    formattingMarks: 'Marcas de formatação',
    insert: 'Inserir',
    insertRowAbove: 'Inserir linha acima',
    insertRowBelow: 'Inserir linha abaixo',
    insertColumnLeft: 'Inserir coluna à esquerda',
    insertColumnRight: 'Inserir coluna à direita',
    deleteRow: 'Excluir linha',
    deleteColumn: 'Excluir coluna',
    toggleRowHeader: 'Alternar cabeçalho de linha',
    toggleColumnHeader: 'Alternar cabeçalho de coluna',
    deleteTable: 'Excluir tabela',
    rows: 'Linhas',
    columns: 'Colunas',
    cells: 'Células',
    table: 'Tabela',
    block: 'Bloco',
    alignLeft: 'Alinhar à esquerda',
    alignCenter: 'Centralizar',
    alignRight: 'Alinhar à direita',
    editLink: 'Editar link',
    removeLink: 'Remover link',
    zoomIntoBlock: 'Ampliar bloco',
    blockStyle: 'Estilo de bloco',
    heading1: 'Título 1',
    heading2: 'Título 2',
    heading3: 'Título 3',
    normalText: 'Texto normal',
    moreFormatting: 'Mais formatação',
    createNoteFromSelectionTitle: 'Criar nova nota a partir da seleção',
    createNoteFromSelectionDescription:
      'Cria uma nova nota contendo a seleção atual e substitui a seleção por um link para a nova nota.',
    dismissKeyboard: 'Ocultar teclado',
    tableOfContentsLower: 'Sumário',
    noHeadingsFound: 'Nenhum título encontrado',
    textFormattingOptions: 'Opções de formatação de texto',
    highlight: 'Realce',
    subscript: 'Subscrito',
    superscript: 'Sobrescrito',
    clearFormatting: 'Limpar formatação',
    normal: 'Normal',
    smartChecklist: 'Lista de tarefas inteligente',
    restoreCompletedTasks: 'Restaurar tarefas concluídas',
    leftAlign: 'Alinhar à esquerda',
    centerAlign: 'Centralizar',
    rightAlign: 'Alinhar à direita',
    justify: 'Justificar',
    searchBlocksPlaceholder: 'Pesquisar blocos…',
    searchBlocksToInsert: 'Pesquisar blocos para inserir',
    clearSearch: 'Limpar pesquisa',
    noBlocksMatch: 'Nenhum bloco corresponde a “{{query}}”',
    customizeToolbar: 'Personalizar barra de ferramentas',
    custom: 'Personalizado',
    clear: 'Limpar',
    textColorSwatch: 'Cor do texto {{color}}',
    highlightColorSwatch: 'Cor do realce {{color}}',
    textShadingSwatch: 'Sombreamento do texto {{color}}',
    noTextShading: 'Sem sombreamento de texto',
    uppercase: 'MAIÚSCULAS',
    lowercase: 'minúsculas',
    camelCase: 'camelCase',
    sortLines: 'Ordenar linhas',
    deduplicate: 'Remover duplicadas',
    multiKeySort: 'Ordenação por várias chaves (1ª, 2ª, 3ª)…',
    sortAndDeduplicateLines: 'Ordenar e remover linhas duplicadas',
    emphasisMarks: 'Marcas de ênfase',
    outlineTextStroke: 'Contorno (traço do texto)',
    letterSpacingKerning: 'Espaçamento entre letras (kerning)',
    wordSpacing: 'Espaçamento entre palavras',
    clearTypography: 'Limpar tipografia',
    spacingTight: 'Estreito',
    spacingNormal: 'Normal',
    spacingWide: 'Largo',
    spacingWider: 'Mais largo',
    spacingWidest: 'Máximo',
    undoMultipleSteps: 'Desfazer várias etapas',
    redoMultipleSteps: 'Refazer várias etapas',
    emptyHistoryPreview: '(vazio)',
    pasteOptions: 'Opções de colar',
    copyOptions: 'Opções de copiar',
    cutOptions: 'Opções de recortar',
    pasteWithoutFormatting: 'Colar sem formatação',
    pasteClean: 'Colar limpo (remover caracteres ocultos)',
    keepSourceFormatting: 'Manter formatação de origem',
    matchDestinationFormatting: 'Usar formatação de destino',
    pasteAsImage: 'Colar como imagem',
    copyWithoutFormatting: 'Copiar sem formatação',
    copyTextOnly: 'Copiar apenas o texto',
    copyImagesOnly: 'Copiar apenas as imagens',
    cutWithoutFormatting: 'Recortar sem formatação',
    cutTextOnly: 'Recortar apenas o texto',
    cutImagesOnly: 'Recortar apenas as imagens',
    lineSpacing: 'Espaçamento entre linhas',
    spaceBefore: 'Espaço antes',
    spaceAfter: 'Espaço depois',
    indentation: 'Recuo',
    none: 'Nenhum',
    increaseLeft: 'Aumentar à esquerda',
    decreaseLeft: 'Diminuir à esquerda',
    increaseRight: 'Aumentar à direita',
    decreaseRight: 'Diminuir à direita',
    firstLine: 'Primeira linha',
    noFirstLine: 'Sem primeira linha',
    textShading: 'Sombreamento do texto',
    listStyle: 'Estilo de lista',
    bulleted: 'Com marcadores',
    numbered: 'Numerada',
    bulletedListMarkers: 'Estilo do marcador',
    numberedListMarkers: 'Estilo de numeração',
    multilevelList: 'Lista de vários níveis',
    multilevelListHint: 'Escolha um marcador para cada nível de aninhamento',
    multilevelLevelDefault: 'Padrão',
    level: 'Nível',
    apply: 'Aplicar',
    insertTable: 'Inserir tabela',
    insertImageFromUrl: 'Inserir imagem a partir de URL',
    sortLinesModalTitle: 'Ordenar linhas',
    blockPicker: 'Seletor de blocos',
    blockParagraph: 'Parágrafo',
    blockCallout: 'Destaque',
    blockDivider: 'Divisor',
    blockCollapsible: 'Recolhível',
    blockImageFromUrl: 'Imagem a partir de URL',
    blockUploadFile: 'Enviar arquivo',
    blockDrawing: 'Desenho',
    blockQrCode: 'QR Code',
    blockTable: 'Tabela',
    blockKanbanBoard: 'Quadro Kanban',
    blockCalendar: 'Calendário',
    blockTimeline: 'Linha do tempo',
    blockDataTable: 'Tabela de dados',
    blockSqlQuery: 'Consulta SQL',
    blockMermaidDiagram: 'Diagrama Mermaid',
    blockGanttChart: 'Gráfico de Gantt',
    blockTimingDiagram: 'Diagrama de temporização',
    blockMusicStaff: 'Pauta musical',
    blockTradingViewChart: 'Gráfico TradingView',
    blockStockChart: 'Gráfico de ações',
    blockEmbed: 'Incorporar',
    blockEmbedWebsite: 'Incorporar site',
    blockTweet: 'Tweet',
    blockEquation: 'Equação',
    blockInlineEquation: 'Equação em linha',
    blockFootnote: 'Nota de rodapé',
    blockBookmark: 'Favorito',
    blockGeneratePassword: 'Gerar senha criptograficamente segura',
    blockClock: 'Relógio',
    blockCurrentDateTime: 'Data e hora atuais',
    blockCurrentTime: 'Hora atual',
    blockCurrentDate: 'Data atual',
    blockCategoryBasic: 'Básico',
    blockCategoryLists: 'Listas',
    blockCategoryMedia: 'Mídia',
    blockCategoryDataTables: 'Dados e tabelas',
    blockCategoryDiagramsCharts: 'Diagramas e gráficos',
    blockCategoryFinance: 'Finanças',
    blockCategoryEmbeds: 'Incorporações',
    blockCategoryAdvanced: 'Avançado',
  },
  files: {
    dropToUploadTooltip: 'Solte seus arquivos para enviá-los e vinculá-los ao arquivo atual',
    fileAriaLabel: 'Arquivo',
    fileReadonly: 'Este arquivo é somente leitura',
    fileInformationPanel: 'Painel de informações do arquivo',
    details: 'Detalhes',
    selectedFilesCount: '{{count}} arquivos selecionados',
    actionsPerformedOnSelected: 'As ações serão realizadas em todos os arquivos selecionados.',
    cancelMultipleSelection: 'Cancelar seleção múltipla',
    fileOptions: 'Opções do arquivo',
    fileContextMenu: 'Menu de contexto do arquivo',
    fileOptionsMenu: 'Menu de opções do arquivo',
    fileOptionsPanel: 'Painel de opções do arquivo',
    noFilesSelected: 'Nenhum arquivo selecionado',
    detachFromNote: 'Desvincular da nota',
    attachToNote: 'Anexar à nota',
    passwordProtect: 'Proteger com senha',
    downloadSeparately: 'Baixar separadamente',
    downloadAsArchive: 'Baixar como arquivo compactado',
    failedToDownloadArchive: 'Falha ao baixar os arquivos como arquivo compactado',
    fileId: 'ID do arquivo:',
    size: 'Tamanho:',
    totalSize: 'Tamanho total:',
    backedUpOn: 'Backup feito em {{date}}',
    configureFileBackups: 'Configurar backups de arquivos',
    fileNotBackedUpLocally: 'Arquivo sem backup local',
    noFoldersYet: 'Nenhuma pasta ainda',
    moveToFolder: 'Mover para pasta',
    folderSelectionMenu: 'Menu de seleção de pasta',
    noFolder: 'Sem pasta',
    fileProtected: 'Este arquivo está protegido.',
    authenticateToView: 'Autentique-se para visualizar este arquivo.',
    addPasscodeToView: 'Adicione uma senha de acesso ou crie uma conta para exigir autenticação para visualizar este arquivo.',
    openAccountMenu: 'Abrir menu da conta',
    authenticate: 'Autenticar',
    viewFile: 'Visualizar arquivo',
    loading: 'Carregando...',
    fileCannotBePreviewed: 'Não é possível pré-visualizar este arquivo.',
    errorLoadingFile: 'Ocorreu um erro ao carregar o arquivo. Tente novamente ou baixe o arquivo e abra-o usando outro aplicativo.',
    tryAgain: 'Tentar novamente',
    downloadToView: 'Para visualizar este arquivo, baixe-o e abra-o usando outro aplicativo.',
    fileInformation: 'Informações do arquivo',
    type: 'Tipo:',
    decryptedSize: 'Tamanho descriptografado:',
    encryptedSize: 'Tamanho criptografado:',
    created: 'Criado:',
    lastModified: 'Última modificação:',
    done: 'Concluído',
    showFileOptions: 'Mostrar opções do arquivo',
    showFileInfo: 'Mostrar informações do arquivo',
    hideFileInfo: 'Ocultar informações do arquivo',
    showLinksSection: 'Mostrar seção de links',
    hideLinksSection: 'Ocultar seção de links',
    submit: 'Enviar',
    renameFile: 'Renomear arquivo',
    showLinkedItems: 'Mostrar itens vinculados',
    closeModal: 'Fechar janela',
    filePreviewModal: 'Janela de pré-visualização do arquivo',
    leftAlign: 'Alinhar à esquerda',
    centerAlign: 'Centralizar',
    rightAlign: 'Alinhar à direita',
    videoCannotBePreviewed: 'Não é possível pré-visualizar este vídeo.',
    audioCannotBePlayed: 'Não é possível reproduzir este áudio.',
    downloadToListen: 'Para ouvir este arquivo, baixe-o e abra-o usando outro aplicativo.',
    externalAppOnly: 'Este arquivo só pode ser pré-visualizado em um aplicativo externo',
    openFilePreview: 'Abrir pré-visualização do arquivo',
    loadingPdfViewer: 'Carregando visualizador de PDF...',
    zoomOut: 'Reduzir',
    zoomIn: 'Ampliar',
    resetToActualSize: 'Redefinir para o tamanho real',
    resetTo100: 'Redefinir para 100%',
    fitToScreen: 'Ajustar à tela',
    unableToRenderPdf: 'Não foi possível renderizar este PDF.',
    pdfCorruptedOrProtected: 'O arquivo pode estar corrompido ou protegido por senha.',
    loadingPdf: 'Carregando PDF...',
    previousPage: 'Página anterior',
    pageNumber: 'Número da página',
    nextPage: 'Próxima página',
    fitWidth: 'Ajustar à largura',
    searchInDocumentShortcut: 'Pesquisar no documento (Ctrl/Cmd+F)',
    searchInDocument: 'Pesquisar no documento',
    copyLinkToPage: 'Copiar link para a página {{page}}',
    copyLinkToThisPage: 'Copiar link para esta página',
    copyLinkToSelectedText: 'Copiar link para o texto selecionado',
    cancelOcr: 'Cancelar OCR',
    preparingOcr: 'Preparando OCR...',
    ocrProgress: 'OCR página {{current}} / {{total}} ({{percent}}%)',
    ocrCachedReRunTooltip: 'Texto já extraído (em cache). Execute o OCR novamente no seu navegador (permanece no seu dispositivo).',
    ocrExtractedReRunTooltip: 'Texto extraído. Execute o OCR novamente no seu navegador (permanece no seu dispositivo).',
    ocrExtractTooltip: 'Extraia texto de páginas digitalizadas com OCR. É executado no seu navegador; nada sai do seu dispositivo (lento; baixa dados de idioma).',
    extractTextWithOcrBrowser: 'Extrair texto com OCR no seu navegador',
    reRunOcrBrowser: 'Executar OCR novamente (navegador)',
    extractTextOcr: 'Extrair texto (OCR)',
    serverOcrTooltip:
      'Execute o OCR no SERVIDOR. Isso envia as imagens das páginas deste PDF para o servidor e ABANDONA a criptografia de ponta a ponta — o servidor pode ler esse conteúdo. O OCR no navegador mantém tudo no seu dispositivo.',
    runOcrOnServerAria: 'Executar OCR no servidor (envia imagens das páginas para o servidor; abandona a criptografia de ponta a ponta)',
    runOcrOnServer: 'Executar OCR no servidor',
    copyAllExtractedText: 'Copiar todo o texto extraído',
    copyExtractedTextAria: 'Copiar texto extraído',
    findInDocument: 'Localizar no documento',
    matchCase: 'Diferenciar maiúsculas de minúsculas',
    noResults: 'Nenhum resultado',
    matchOfTotal: '{{current}} de {{total}}',
    previousMatch: 'Ocorrência anterior',
    nextMatch: 'Próxima ocorrência',
    closeSearch: 'Fechar pesquisa',
    serverOcrDisclosurePrefix: 'O OCR no servidor está disponível para sua conta. Ele envia as imagens das páginas deste PDF para o servidor e',
    serverOcrDisclosureBold: 'abandona a criptografia de ponta a ponta',
    serverOcrDisclosureSuffix:
      ' — o servidor (e qualquer pessoa que o controle) pode ler esse conteúdo. O OCR no navegador mantém tudo no seu dispositivo. O padrão é o OCR no navegador.',
    ocrRunningServer:
      'OCR no servidor: as imagens das páginas deste PDF estão sendo enviadas para o servidor, o que ABANDONA a criptografia de ponta a ponta — o servidor pode ler esse conteúdo. (O OCR no navegador mantém tudo no seu dispositivo.)',
    ocrRunningBrowser:
      'O OCR é executado no seu navegador neste dispositivo (seus arquivos permanecem criptografados de ponta a ponta). É lento e baixa dados de idioma na primeira utilização.',
    ocrDoneServer:
      'OCR no servidor concluído. As imagens das páginas foram enviadas para o servidor (isso abandonou a criptografia de ponta a ponta). A precisão varia conforme a qualidade da digitalização; o texto extraído agora pode ser pesquisado e copiado, e fica em cache neste dispositivo.',
    ocrDoneBrowser:
      'OCR concluído. A precisão varia conforme a qualidade da digitalização; o texto extraído agora pode ser pesquisado e copiado, e fica em cache neste dispositivo.',
    copiedExtractedText: 'Texto extraído copiado',
    copiedLinkToPage: 'Link para a página {{page}} copiado',
    copiedLinkToSelectedText: 'Link para o texto selecionado copiado',
    serverOcrFailed: 'Falha no OCR do servidor: {{message}}',
    ocrUnknownError: 'erro desconhecido',
    ocrFailed: 'Falha no OCR. Pode ter havido falha ao baixar os dados de idioma.',
  },
  notes: {
    notesAndFiles: 'Notas e arquivos',
    selectAllItems: 'Selecionar todos os itens',
    selectedCount: '{{count}} selecionados',
    cancelMultipleSelection: 'Cancelar seleção múltipla',
    noFilesInFolder: 'Nenhum arquivo nesta pasta.',
    noItems: 'Nenhum item.',
    loading: 'Carregando...',
    uploadFileWithShortcut: 'Enviar arquivo {{shortcut}}',
    createNoteInTopicWithShortcut: 'Criar uma nova nota no tópico selecionado {{shortcut}}',
    dropFilesToUpload: 'Solte seus arquivos para enviá-los e vinculá-los ao tópico "{{title}}"',
    noFilesYet: 'Você ainda não tem nenhum arquivo',
    filesAttachedAppearHere:
      'Os arquivos anexados às suas notas aparecem aqui. Você também pode enviar arquivos diretamente desta página.',
    uploadFiles: 'Enviar arquivos',
    syncing: 'Sincronizando...',
    loadingItemsProgress: 'Carregando {{current}}/{{total}} itens...',
    potentiallyOutOfSync: 'Possivelmente fora de sincronia',
    openDisplayOptionsMenu: 'Abrir menu de opções de exibição',
    displayOptionsMenu: 'Menu de opções de exibição',
    displayOptions: 'Opções de exibição',
    expandTopicsPanel: 'Expandir painel de tópicos',
    collapseNotesPanel: 'Recolher painel de notas',
    addItem: 'Adicionar item',
    uploadFolder: 'Enviar pasta',
    takePhoto: 'Tirar foto',
    recordVideo: 'Gravar vídeo',
    searchPlaceholder: 'Pesquisar...',
    notesListOptionsMenu: 'Menu de opções da lista de notas',
    preferencesFor: 'Preferências para',
    global: 'Global',
    reset: 'Redefinir',
    upgradeForPerTopicPreferences: 'Faça upgrade para preferências por tópico',
    perTopicPreferencesMessageWithDaily:
      'Crie fluxos de trabalho poderosos e layouts organizacionais com preferências de exibição por tópico e o novíssimo layout de calendário do Caderno Diário.',
    perTopicPreferencesMessage:
      'Crie fluxos de trabalho poderosos e layouts organizacionais com preferências de exibição por tópico.',
    sortBy: 'Ordenar por',
    relevanceBestMatch: 'Relevância (melhor correspondência)',
    dateModified: 'Data de modificação',
    creationDate: 'Data de criação',
    title: 'Título',
    customDragToReorder: 'Personalizado (arraste para reordenar)',
    view: 'Exibição',
    showNotePreview: 'Mostrar pré-visualização da nota',
    showDate: 'Mostrar data',
    showTags: 'Mostrar tópicos',
    showIcon: 'Mostrar ícone',
    other: 'Outros',
    showPinned: 'Mostrar fixadas',
    showProtected: 'Mostrar protegidas',
    showArchived: 'Mostrar arquivadas',
    showTrashed: 'Mostrar na lixeira',
    dailyNotebook: 'Caderno Diário',
    labs: 'Labs',
    dailyNotebookDescription: 'Capture novas notas diariamente com um layout baseado em calendário',
    tableView: 'Visualização em tabela',
    tableViewDescription: 'Exiba as notas e arquivos do tópico atual em um layout de tabela',
    newNoteDefaults: 'Padrões de nova nota',
    noteType: 'Tipo de nota',
    selectDefaultNoteType: 'Selecione o tipo de nota padrão',
    titleFormat: 'Formato do título',
    selectTitleFormat: 'Selecione o formato do título da nota',
    customFormatPlaceholder: 'ex.: AAAA-MM-DD',
    preview: 'Pré-visualização: ',
    useBracketsToEscape: '. Use ',
    toEscapeFormatting: ' para escapar da formatação.',
    protected: 'Protegida',
    modified: 'Modificada',
    now: 'Agora',
    editingDisabled: 'Edição desativada',
    trashed: 'Na lixeira',
    archived: 'Arquivada',
    files: 'Arquivos',
    starred: 'Com estrela',
    fileBackedUpLocally: 'O arquivo tem backup local',
    conflictedCopy: 'Cópia com conflito',
    allFiles: 'Todos os arquivos',
    noFolder: 'Sem pasta',
    folderNamePlaceholder: 'Nome da pasta',
    createNewFolder: 'Criar uma nova pasta',
    newFolder: 'Nova pasta',
    currentStreak: 'Sequência atual',
    dayWithCount_one: 'Dia',
    dayWithCount_many: 'Dias',
    dayWithCount_other: 'Dias',
  },
  auth: {
    unableToComputePrivateUsername: 'Não foi possível calcular o nome de usuário privado.',
    advancedOptions: 'Opções avançadas',
    privateUsernameMode: 'Modo de nome de usuário privado',
    username: 'Nome de usuário',
    useStrictSignIn: 'Usar login restrito',
    useRecoveryCode: 'Usar código de recuperação',
    recoveryCode: 'Código de recuperação',
    deleteLocalDataTitle: 'Excluir dados locais?',
    noMergeWarning:
      'Você optou por não mesclar seus dados locais. Se continuar, suas notas e tópicos locais serão excluídos permanentemente e substituídos pelos dados da sua conta. Esta ação não pode ser desfeita.',
    noMergeConfirmQuestion: 'Tem certeza de que deseja continuar sem mesclar?',
    deleteLocalDataAndContinue: 'Excluir dados locais e continuar',
    passwordResetWarningPart1: 'Como suas notas são criptografadas usando sua senha,',
    passwordResetWarningHighlight: 'o Standard Red Notes não tem opção de redefinição de senha',
    passwordResetWarningPart2: '. Se você esquecer sua senha, perderá permanentemente o acesso aos seus dados.',
    confirmPassword: 'Confirmar senha',
    creatingAccount: 'Criando conta...',
    createAccountAndSignIn: 'Criar conta e entrar',
    staySignedIn: 'Permanecer conectado',
    goBack: 'Voltar',
    humanVerification: 'Verificação humana',
    confirmPasswordTitle: 'Confirmar senha',
    createAccount: 'Criar conta',
    workspaceNameOptional: 'Nome do espaço de trabalho (opcional)',
    generalAccountMenuLabel: 'Menu geral da conta',
    signedInAs: 'Você está conectado como:',
    syncing: 'Sincronizando...',
    lastSynced: 'Última sincronização:',
    offlineSignInPrompt:
      'Você está offline. Entre para sincronizar suas notas e preferências em todos os seus dispositivos e habilitar a criptografia de ponta a ponta.',
    offline: 'Offline',
    accountSettings: 'Configurações da conta',
    createFreeAccount: 'Criar conta gratuita',
    documentation: 'Documentação',
    keyboardShortcuts: 'Atalhos de teclado',
    commandPalette: 'Paleta de comandos',
    signOutWorkspace: 'Sair do espaço de trabalho',
    mergeLocalData: 'Mesclar dados locais ({{count}} notas e tópicos)',
    mergeLocalDataTooltip:
      'Se desmarcado, suas notas e tópicos locais serão excluídos permanentemente e substituídos pelos dados da sua conta.',
    homeServerNotRunning:
      'O servidor local não está em execução. Abra as preferências e a aba do servidor local para iniciá-lo.',
    serverDefault: 'Padrão',
    serverCustom: 'Personalizado',
    serverHomeServer: 'Servidor local',
    syncServer: 'Servidor de sincronização',
    signingIn: 'Entrando...',
    syncUnreachable: 'Sincronização inacessível',
    syncUnreachableMessage: 'Hmm... não conseguimos sincronizar sua conta. O motivo: {{reason}}',
    workspaceSwitcherMenuLabel: 'Menu de alternância de espaços de trabalho',
    signOutAllWorkspacesConfirm: 'Tem certeza de que deseja sair de todos os espaços de trabalho neste dispositivo?',
    signOutAll: 'Sair de todos',
    addAnotherWorkspace: 'Adicionar outro espaço de trabalho',
    signOutAllWorkspaces: 'Sair de todos os espaços de trabalho',
    deleteAccountTitle: 'Excluir conta?',
    deleteMyAccountForGood: 'Excluir minha conta definitivamente',
    dataNotBackedUp: 'Dados sem backup',
    signInOrRegisterToSync:
      'Entre ou cadastre-se para sincronizar suas notas com seus outros dispositivos com criptografia de ponta a ponta.',
    openAccountMenu: 'Abrir menu da conta',
    ignoreWarning: 'Ignorar aviso',
    waitingForSecurityKey: 'Aguardando a chave de segurança...',
    authenticationSuccessful: 'Autenticação bem-sucedida!',
    insertSecurityKeyPrompt: 'Insira sua chave de segurança de hardware e pressione o botão abaixo para autenticar.',
    authenticate: 'Autenticar',
  },
  search: {
    placeholder: 'Pesquisar...',
    protectedContents: 'Conteúdos protegidos',
    archived: 'Arquivadas',
    trashed: 'Na lixeira',
    aiUnavailable: 'A reclassificação por IA está indisponível ou não retornou resultados.',
    aiUnavailableTooltip: 'A pesquisa contextual por IA está indisponível.',
    aiTypeQueryFirst: 'Digite uma consulta de pesquisa primeiro.',
    aiTooltip:
      'Reclassifique os principais resultados por relevância semântica usando o provedor de IA configurado. ' +
      'Envia os títulos e trechos curtos desses candidatos, além da sua consulta, para o provedor.',
    aiSearchWithAi: 'Pesquisar com IA',
    aiRanking: 'Classificando…',
    aiRankedByRelevance: 'Classificado por relevância da IA',
    aiPrivacyNotice:
      'Envia os títulos e trechos dos principais resultados e sua consulta ao seu provedor de IA. Provedores em nuvem os verão ' +
      '— um modelo local mantém tudo no dispositivo.',
    advancedFilters: 'Filtros de pesquisa avançados',
    filters: 'Filtros',
    noteTypeAny: 'Qualquer tipo',
    noteTypePlainText: 'Texto simples',
    noteTypeRichText: 'Texto formatado',
    noteTypeSuper: 'Super',
    noteTypeMarkdown: 'Markdown',
    noteTypeCode: 'Código',
    noteTypeTask: 'Tarefa',
    noteTypeSpreadsheet: 'Planilha',
    flagProtected: 'Protegida',
    flagPinned: 'Fixada',
    flagArchived: 'Arquivada',
    flagStarred: 'Com estrela',
    flagTrashed: 'Na lixeira',
    topicsLabel: 'Tópicos (separados por vírgula)',
    topicsPlaceholder: 'trabalho, pessoal',
    noteTypeLabel: 'Tipo de nota',
    searchInLabel: 'Pesquisar em',
    searchInTitleAndContent: 'Título e conteúdo',
    modifiedWithinLabel: 'Modificado dentro de',
    datePreset: 'Últimos {{label}}',
    createdAfterLabel: 'Criado após',
    createdBeforeLabel: 'Criado antes de',
    updatedAfterLabel: 'Atualizado após',
    updatedBeforeLabel: 'Atualizado antes de',
    statusLabel: 'Status',
    hasAttachments: 'Tem anexos',
    caseSensitive: 'Diferenciar maiúsculas de minúsculas',
    clearAllFilters: 'Limpar todos os filtros',
  },
  sharing: {
    vaultSelectionMenu: 'Menu de seleção de cofre',
    vaultOptionsMenu: 'Menu de opções do cofre',
    vaultOptions: 'Opções do cofre',
    noVaultsFound: 'Nenhum cofre encontrado',
    moveToVault: 'Mover para o cofre',
    moveOutOfVault: 'Mover para fora de {{name}}',
    vaultsFallbackName: 'cofres',
    editVault: 'Editar cofre',
    lockVault: 'Bloquear cofre',
    unlockVault: 'Desbloquear cofre',
    openVaultSettings: 'Abrir configurações do cofre',
    selectionModeMultiple: 'Múltiplos',
    selectionModeOne: 'Um',
    lastEditedBy: 'Última edição por',
    sharedBy: 'Compartilhado por',
    sharedByContact: 'Compartilhado pelo contato',
    vaultName: 'Nome do cofre',
    sharedInVault: 'Compartilhado no cofre',
    copiedToClipboard: 'Copiado para a área de transferência',
    failedToCopyToClipboard: 'Falha ao copiar para a área de transferência',
    copyExampleToClipboard: 'Copiar exemplo para a área de transferência',
    copiedExclaim: 'Copiado!',
    shareUnavailableTitle: 'Compartilhamento indisponível',
    shareUnavailableMessage: 'Este link de compartilhamento não está mais disponível.',
    invalidLinkTitle: 'Link inválido',
    invalidLinkMessage: 'Este link de compartilhamento é inválido ou a chave está ausente.',
    selfDestructTitle: 'Esta nota se autodestrói após a visualização',
    oneTimeViewConsumed: 'Você está lendo um link de visualização única. Ele já foi consumido e não pode ser reaberto',
    oneTimeViewExpiresClause_one: ', e expira totalmente {{count}} minuto após a primeira abertura',
    oneTimeViewExpiresClause_many: ', e expira totalmente {{count}} minutos após a primeira abertura',
    oneTimeViewExpiresClause_other: ', e expira totalmente {{count}} minutos após a primeira abertura',
    linkExpires_one: 'Este link expira {{count}} minuto após ser aberto pela primeira vez.',
    linkExpires_many: 'Este link expira {{count}} minutos após ser aberto pela primeira vez.',
    linkExpires_other: 'Este link expira {{count}} minutos após ser aberto pela primeira vez.',
    untitled: 'Sem título',
    tagHasNoNotes: 'Este tópico não tem notas.',
    publicReadOnlyFooter: 'Este é um link compartilhado público e somente leitura. O conteúdo foi descriptografado no seu navegador.',
    confidentialWatermark: 'Confidencial · {{datetime}}',
    contentHiddenTitle: 'Conteúdo oculto',
    contentHiddenMessage: 'Retorne o foco para esta janela para visualizar o conteúdo compartilhado.',
  },
}

export default ptBR
