import type { LocaleResource } from './en'

// Português brasileiro (pt-BR). Brazilian vocabulary/spelling
// (e.g. "arquivos", "cadastrar", "excluir", "senha").
const ptBR: LocaleResource = {
  common: {
    save: 'Salvar',
    cancel: 'Cancelar',
    delete: 'Excluir',
    confirm: 'Confirmar',
    close: 'Fechar',
    edit: 'Editar',
    rename: 'Renomear',
    duplicate: 'Duplicar',
    remove: 'Remover',
    open: 'Abrir',
    create: 'Criar',
    add: 'Adicionar',
    done: 'Concluído',
    back: 'Voltar',
    next: 'Próximo',
    search: 'Pesquisar',
    clear: 'Limpar',
    loading: 'Carregando…',
    copy: 'Copiar',
    copied: 'Copiado',
    download: 'Baixar',
    upload: 'Enviar',
    export: 'Exportar',
    import: 'Importar',
    yes: 'Sim',
    no: 'Não',
    enabled: 'Ativado',
    disabled: 'Desativado',
    on: 'Ligado',
    off: 'Desligado',
    learnMore: 'Saiba mais',
    options: 'Opções',
    settings: 'Configurações',
    preferences: 'Preferências',
    help: 'Ajuda',
    pin: 'Fixar',
    unpin: 'Desafixar',
    star: 'Marcar com estrela',
    unstar: 'Remover estrela',
    archive: 'Arquivar',
    unarchive: 'Desarquivar',
    restore: 'Restaurar',
    moveToTrash: 'Mover para a lixeira',
    deletePermanently: 'Excluir permanentemente',
    protect: 'Proteger',
    unprotect: 'Desproteger',
  },
  navigation: {
    notes: 'Notas',
    allNotes: 'Todas as notas',
    files: 'Arquivos',
    starred: 'Com estrela',
    archived: 'Arquivadas',
    trash: 'Lixeira',
    untagged: 'Sem etiqueta',
    conflicts: 'Conflitos',
    views: 'Visualizações',
    smartViews: 'Visualizações inteligentes',
    tags: 'Etiquetas',
    folders: 'Pastas',
    favorites: 'Favoritos',
    dashboard: 'Painel',
    createNewNote: 'Criar uma nova nota',
    createNewTag: 'Criar uma nova etiqueta',
    createNewFolder: 'Criar uma nova pasta',
    createNewSmartView: 'Criar uma nova visualização inteligente',
    searchTags: 'Pesquisar etiquetas…',
    noTagsFound: 'Nenhuma etiqueta encontrada. Tente outra pesquisa.',
    noSmartViewsFound: 'Nenhuma visualização inteligente encontrada. Tente outra pesquisa.',
    collapseTagsPanel: 'Recolher painel de etiquetas',
    expandTagsPanel: 'Expandir painel de etiquetas',
    goToItemsList: 'Ir para a lista de itens',
    goToAccountMenu: 'Ir para o menu da conta',
    openPreferences: 'Abrir preferências',
  },
  account: {
    account: 'Conta',
    signIn: 'Entrar',
    signOut: 'Sair',
    signUp: 'Cadastrar',
    register: 'Cadastrar',
    you: 'Você',
    encryptionOn: 'Criptografia de ponta a ponta ativada',
    notSignedIn: 'Você não está conectado',
    signInOrRegister: 'Entre ou cadastre-se para sincronizar suas notas',
    email: 'E-mail',
    password: 'Senha',
    confirmPassword: 'Confirmar senha',
    syncNow: 'Sincronizar agora',
    lastSynced: 'Última sincronização',
    importData: 'Importar',
    switchWorkspace: 'Trocar de espaço de trabalho',
    lockApplication: 'Bloquear o aplicativo',
    helpAndFeedback: 'Ajuda e feedback',
  },
  preferences: {
    title: 'Preferências',
    general: 'Geral',
    account: 'Conta',
    security: 'Segurança',
    appearance: 'Aparência',
    backups: 'Backups',
    listed: 'Listed',
    plugins: 'Plugins',
    whatsNew: 'Novidades',
    helpAndFeedback: 'Ajuda e feedback',
    language: 'Idioma',
    languageTitle: 'Idioma',
    languageDescription:
      'Escolha o idioma usado em toda a interface do aplicativo. O aplicativo usa o inglês para o que ainda não foi traduzido.',
    languageChanged: 'Idioma atualizado',
    defaults: 'Padrões',
    tools: 'Ferramentas',
    spellcheck: 'Verificação ortográfica',
    labs: 'Laboratórios',
  },
}

export default ptBR
