import type { LocaleResource } from './en'

// Português europeu (pt-PT). Uses European Portuguese vocabulary and spelling
// (e.g. "ficheiros" not "arquivos", "registar" not "cadastrar", "eliminar").
const ptPT: LocaleResource = {
  common: {
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    confirm: 'Confirmar',
    close: 'Fechar',
    edit: 'Editar',
    rename: 'Mudar o nome',
    duplicate: 'Duplicar',
    remove: 'Remover',
    open: 'Abrir',
    create: 'Criar',
    add: 'Adicionar',
    done: 'Concluído',
    back: 'Voltar',
    next: 'Seguinte',
    search: 'Pesquisar',
    clear: 'Limpar',
    loading: 'A carregar…',
    copy: 'Copiar',
    copied: 'Copiado',
    download: 'Transferir',
    upload: 'Carregar',
    export: 'Exportar',
    import: 'Importar',
    yes: 'Sim',
    no: 'Não',
    enabled: 'Ativado',
    disabled: 'Desativado',
    on: 'Ligado',
    off: 'Desligado',
    learnMore: 'Saber mais',
    options: 'Opções',
    settings: 'Definições',
    preferences: 'Preferências',
    help: 'Ajuda',
    pin: 'Fixar',
    unpin: 'Desafixar',
    star: 'Marcar com estrela',
    unstar: 'Retirar estrela',
    archive: 'Arquivar',
    unarchive: 'Desarquivar',
    restore: 'Restaurar',
    moveToTrash: 'Mover para o lixo',
    deletePermanently: 'Eliminar definitivamente',
    protect: 'Proteger',
    unprotect: 'Desproteger',
  },
  navigation: {
    notes: 'Notas',
    allNotes: 'Todas as notas',
    files: 'Ficheiros',
    starred: 'Com estrela',
    archived: 'Arquivadas',
    trash: 'Lixo',
    untagged: 'Sem tópico',
    conflicts: 'Conflitos',
    views: 'Vistas',
    smartViews: 'Vistas inteligentes',
    tags: 'Tópicos',
    folders: 'Pastas',
    favorites: 'Favoritos',
    dashboard: 'Painel',
    createNewNote: 'Criar uma nova nota',
    createNewTag: 'Criar um novo tópico',
    createNewFolder: 'Criar uma nova pasta',
    createNewSmartView: 'Criar uma nova vista inteligente',
    searchTags: 'Pesquisar tópicos…',
    noTagsFound: 'Nenhum tópico encontrado. Tente outra pesquisa.',
    noSmartViewsFound: 'Nenhuma vista inteligente encontrada. Tente outra pesquisa.',
    collapseTagsPanel: 'Recolher painel de tópicos',
    expandTagsPanel: 'Expandir painel de tópicos',
    goToItemsList: 'Ir para a lista de itens',
    goToAccountMenu: 'Ir para o menu da conta',
    openPreferences: 'Abrir preferências',
  },
  account: {
    account: 'Conta',
    signIn: 'Iniciar sessão',
    signOut: 'Terminar sessão',
    signUp: 'Registar',
    register: 'Registar',
    you: 'Você',
    encryptionOn: 'Encriptação ponta a ponta ativada',
    notSignedIn: 'Sessão não iniciada',
    signInOrRegister: 'Inicie sessão ou registe-se para sincronizar as suas notas',
    email: 'Correio eletrónico',
    password: 'Palavra-passe',
    confirmPassword: 'Confirmar palavra-passe',
    syncNow: 'Sincronizar agora',
    lastSynced: 'Última sincronização',
    importData: 'Importar',
    switchWorkspace: 'Mudar de espaço de trabalho',
    lockApplication: 'Bloquear a aplicação',
    helpAndFeedback: 'Ajuda e comentários',
  },
  preferences: {
    title: 'Preferências',
    general: 'Geral',
    account: 'Conta',
    security: 'Segurança',
    appearance: 'Aparência',
    backups: 'Cópias de segurança',
    listed: 'Listed',
    plugins: 'Extensões',
    whatsNew: 'Novidades',
    helpAndFeedback: 'Ajuda e comentários',
    language: 'Idioma',
    languageTitle: 'Idioma',
    languageDescription:
      'Escolha o idioma utilizado em toda a interface da aplicação. A aplicação recorre ao inglês para o que ainda não estiver traduzido.',
    languageChanged: 'Idioma atualizado',
    defaults: 'Predefinições',
    tools: 'Ferramentas',
    spellcheck: 'Verificação ortográfica',
    labs: 'Laboratórios',
  },
}

export default ptPT
