import type { LocaleResource } from './en'

const ru: LocaleResource = {
  common: {
    save: 'Сохранить',
    cancel: 'Отмена',
    delete: 'Удалить',
    confirm: 'Подтвердить',
    close: 'Закрыть',
    edit: 'Изменить',
    rename: 'Переименовать',
    duplicate: 'Дублировать',
    remove: 'Убрать',
    open: 'Открыть',
    create: 'Создать',
    add: 'Добавить',
    done: 'Готово',
    back: 'Назад',
    next: 'Далее',
    search: 'Поиск',
    clear: 'Очистить',
    loading: 'Загрузка…',
    copy: 'Копировать',
    copied: 'Скопировано',
    download: 'Скачать',
    upload: 'Загрузить',
    export: 'Экспорт',
    import: 'Импорт',
    yes: 'Да',
    no: 'Нет',
    enabled: 'Включено',
    disabled: 'Выключено',
    on: 'Вкл.',
    off: 'Выкл.',
    learnMore: 'Подробнее',
    options: 'Параметры',
    settings: 'Настройки',
    preferences: 'Настройки',
    help: 'Справка',
    pin: 'Закрепить',
    unpin: 'Открепить',
    star: 'Отметить',
    unstar: 'Снять отметку',
    archive: 'В архив',
    unarchive: 'Из архива',
    restore: 'Восстановить',
    moveToTrash: 'Переместить в корзину',
    deletePermanently: 'Удалить навсегда',
    protect: 'Защитить',
    unprotect: 'Снять защиту',
  },
  navigation: {
    notes: 'Заметки',
    allNotes: 'Все заметки',
    files: 'Файлы',
    starred: 'Отмеченные',
    archived: 'Архив',
    trash: 'Корзина',
    untagged: 'Без метки',
    conflicts: 'Конфликты',
    views: 'Представления',
    smartViews: 'Умные представления',
    tags: 'Метки',
    folders: 'Папки',
    favorites: 'Избранное',
    dashboard: 'Панель',
    createNewNote: 'Создать новую заметку',
    createNewTag: 'Создать новую метку',
    createNewFolder: 'Создать новую папку',
    createNewSmartView: 'Создать новое умное представление',
    searchTags: 'Поиск меток…',
    noTagsFound: 'Метки не найдены. Попробуйте другой запрос.',
    noSmartViewsFound: 'Умные представления не найдены. Попробуйте другой запрос.',
    collapseTagsPanel: 'Свернуть панель меток',
    expandTagsPanel: 'Развернуть панель меток',
    goToItemsList: 'Перейти к списку элементов',
    goToAccountMenu: 'Перейти в меню учётной записи',
    openPreferences: 'Открыть настройки',
  },
  account: {
    account: 'Учётная запись',
    signIn: 'Войти',
    signOut: 'Выйти',
    signUp: 'Зарегистрироваться',
    register: 'Зарегистрироваться',
    you: 'Вы',
    encryptionOn: 'Сквозное шифрование включено',
    notSignedIn: 'Вы не вошли в систему',
    signInOrRegister: 'Войдите или зарегистрируйтесь, чтобы синхронизировать заметки',
    email: 'Эл. почта',
    password: 'Пароль',
    confirmPassword: 'Подтвердите пароль',
    syncNow: 'Синхронизировать',
    lastSynced: 'Последняя синхронизация',
    importData: 'Импорт',
    switchWorkspace: 'Сменить рабочую область',
    lockApplication: 'Заблокировать приложение',
    helpAndFeedback: 'Справка и отзывы',
  },
  preferences: {
    title: 'Настройки',
    general: 'Общие',
    account: 'Учётная запись',
    security: 'Безопасность',
    appearance: 'Оформление',
    backups: 'Резервные копии',
    listed: 'Listed',
    plugins: 'Плагины',
    whatsNew: 'Что нового',
    helpAndFeedback: 'Справка и отзывы',
    language: 'Язык',
    languageTitle: 'Язык',
    languageDescription:
      'Выберите язык интерфейса приложения. Для непереведённого содержимого используется английский язык.',
    languageChanged: 'Язык обновлён',
    defaults: 'Значения по умолчанию',
    tools: 'Инструменты',
    spellcheck: 'Проверка орфографии',
    labs: 'Лаборатория',
  },
}

export default ru
