import type { LocaleResource } from './en'

const tr: LocaleResource = {
  common: {
    save: 'Kaydet',
    cancel: 'İptal',
    delete: 'Sil',
    confirm: 'Onayla',
    close: 'Kapat',
    edit: 'Düzenle',
    rename: 'Yeniden adlandır',
    duplicate: 'Çoğalt',
    remove: 'Kaldır',
    open: 'Aç',
    create: 'Oluştur',
    add: 'Ekle',
    done: 'Tamam',
    back: 'Geri',
    next: 'İleri',
    search: 'Ara',
    clear: 'Temizle',
    loading: 'Yükleniyor…',
    copy: 'Kopyala',
    copied: 'Kopyalandı',
    download: 'İndir',
    upload: 'Yükle',
    export: 'Dışa aktar',
    import: 'İçe aktar',
    yes: 'Evet',
    no: 'Hayır',
    enabled: 'Etkin',
    disabled: 'Devre dışı',
    on: 'Açık',
    off: 'Kapalı',
    learnMore: 'Daha fazla bilgi',
    options: 'Seçenekler',
    settings: 'Ayarlar',
    preferences: 'Tercihler',
    help: 'Yardım',
    pin: 'Sabitle',
    unpin: 'Sabitlemeyi kaldır',
    star: 'Yıldızla',
    unstar: 'Yıldızı kaldır',
    archive: 'Arşivle',
    unarchive: 'Arşivden çıkar',
    restore: 'Geri yükle',
    moveToTrash: 'Çöp kutusuna taşı',
    deletePermanently: 'Kalıcı olarak sil',
    protect: 'Koru',
    unprotect: 'Korumayı kaldır',
  },
  navigation: {
    notes: 'Notlar',
    allNotes: 'Tüm notlar',
    files: 'Dosyalar',
    starred: 'Yıldızlı',
    archived: 'Arşivlenmiş',
    trash: 'Çöp Kutusu',
    untagged: 'Konusuz',
    conflicts: 'Çakışmalar',
    views: 'Görünümler',
    smartViews: 'Akıllı Görünümler',
    tags: 'Konular',
    folders: 'Klasörler',
    favorites: 'Sık kullanılanlar',
    dashboard: 'Panel',
    createNewNote: 'Yeni bir not oluştur',
    createNewTag: 'Yeni bir konu oluştur',
    createNewFolder: 'Yeni bir klasör oluştur',
    createNewSmartView: 'Yeni bir akıllı görünüm oluştur',
    searchTags: 'Konularda ara…',
    noTagsFound: 'Konu bulunamadı. Farklı bir arama deneyin.',
    noSmartViewsFound: 'Akıllı görünüm bulunamadı. Farklı bir arama deneyin.',
    collapseTagsPanel: 'Konu panelini daralt',
    expandTagsPanel: 'Konu panelini genişlet',
    goToItemsList: 'Öğe listesine git',
    goToAccountMenu: 'Hesap menüsüne git',
    openPreferences: 'Tercihleri aç',
  },
  account: {
    account: 'Hesap',
    signIn: 'Giriş yap',
    signOut: 'Çıkış yap',
    signUp: 'Kaydol',
    register: 'Kaydol',
    you: 'Siz',
    encryptionOn: 'Uçtan uca şifreleme açık',
    notSignedIn: 'Giriş yapmadınız',
    signInOrRegister: 'Notlarınızı senkronize etmek için giriş yapın veya kaydolun',
    email: 'E-posta',
    password: 'Parola',
    confirmPassword: 'Parolayı onayla',
    syncNow: 'Şimdi senkronize et',
    lastSynced: 'Son senkronizasyon',
    importData: 'İçe aktar',
    switchWorkspace: 'Çalışma alanını değiştir',
    lockApplication: 'Uygulamayı kilitle',
    helpAndFeedback: 'Yardım ve geri bildirim',
  },
  preferences: {
    title: 'Tercihler',
    general: 'Genel',
    account: 'Hesap',
    security: 'Güvenlik',
    appearance: 'Görünüm',
    backups: 'Yedeklemeler',
    listed: 'Listed',
    plugins: 'Eklentiler',
    whatsNew: 'Yenilikler',
    helpAndFeedback: 'Yardım ve geri bildirim',
    language: 'Dil',
    languageTitle: 'Dil',
    languageDescription:
      'Uygulama arayüzünde kullanılan dili seçin. Henüz çevrilmemiş içerikler için uygulama İngilizceye döner.',
    languageChanged: 'Dil güncellendi',
    defaults: 'Varsayılanlar',
    tools: 'Araçlar',
    spellcheck: 'Yazım denetimi',
    labs: 'Laboratuvarlar',
  },
  editor: {
    cut: 'Kes',
    copy: 'Kopyala',
    paste: 'Yapıştır',
    moreCutOptions: 'Daha fazla kesme seçeneği',
    moreCopyOptions: 'Daha fazla kopyalama seçeneği',
    morePasteOptions: 'Daha fazla yapıştırma seçeneği',
    tableOfContents: 'İçindekiler',
    selectAll: 'Tümünü seç',
    selectAllText: 'Yalnızca tüm metni seç',
    deselectAll: 'Seçimi kaldır',
    search: 'Ara',
    undo: 'Geri al',
    redo: 'Yinele',
    undoHistory: 'Geri alma geçmişi',
    redoHistory: 'Yineleme geçmişi',
    undoHistoryEmpty: 'Geri alma geçmişi — henüz geri alınacak bir şey yok',
    undoHistoryAvailable: 'Geri alma geçmişi — birkaç adımı birden geri gidin',
    redoHistoryEmpty: 'Yineleme geçmişi — yinelenecek bir şey yok',
    redoHistoryAvailable: 'Yineleme geçmişi — birkaç adımı birden ileri atlayın',
    formattingOptions: 'Biçimlendirme seçenekleri',
    bold: 'Kalın',
    italic: 'İtalik',
    underline: 'Altı çizili',
    strikethrough: 'Üstü çizili',
    inlineCode: 'Satır içi kod',
    link: 'Bağlantı',
    formatPainter: 'Biçim boyacısı — biçimlendirmeyi kopyala (açık tutmak için çift tıklayın)',
    textStyle: 'Metin stili',
    textColor: 'Metin rengi',
    highlightColor: 'Vurgu rengi',
    typography: 'Tipografi — vurgu, dış çizgi, harf ve kelime aralığı',
    typographyTitle: 'Tipografi',
    fontSize: 'Yazı tipi boyutu',
    chooseFontSize: 'Yazı tipi boyutunu seç',
    decreaseFontSize: 'Yazı tipi boyutunu küçült',
    increaseFontSize: 'Yazı tipi boyutunu büyüt',
    fontFamily: 'Yazı tipi ailesi',
    customFontFamily: 'Özel',
    bulletedList: 'Madde işaretli liste',
    numberedList: 'Numaralı liste',
    checkList: 'Onay listesi',
    quote: 'Alıntı',
    codeBlock: 'Kod bloğu',
    changeCase: 'Büyük/küçük harf değiştir',
    sortAndDedupeLines: 'Satırları sırala ve yinelenenleri kaldır',
    alignment: 'Hizalama',
    paragraphLayout: 'Paragraf düzeni — satır ve paragraf aralığı, girinti, gölgeleme',
    paragraphLayoutTitle: 'Paragraf düzeni',
    listStyleMarker: 'Liste stili — madde ve numara işareti',
    formattingMarks: 'Biçimlendirme işaretleri',
    insert: 'Ekle',
    insertRowAbove: 'Üste satır ekle',
    insertRowBelow: 'Alta satır ekle',
    insertColumnLeft: 'Sola sütun ekle',
    insertColumnRight: 'Sağa sütun ekle',
    deleteRow: 'Satırı sil',
    deleteColumn: 'Sütunu sil',
    toggleRowHeader: 'Satır başlığını aç/kapat',
    toggleColumnHeader: 'Sütun başlığını aç/kapat',
    deleteTable: 'Tabloyu sil',
    rows: 'Satırlar',
    columns: 'Sütunlar',
    cells: 'Hücreler',
    table: 'Tablo',
    block: 'Blok',
    alignLeft: 'Sola hizala',
    alignCenter: 'Ortala',
    alignRight: 'Sağa hizala',
    editLink: 'Bağlantıyı düzenle',
    removeLink: 'Bağlantıyı kaldır',
    zoomIntoBlock: 'Bloğa yakınlaş',
    blockStyle: 'Blok stili',
    heading1: 'Başlık 1',
    heading2: 'Başlık 2',
    heading3: 'Başlık 3',
    normalText: 'Normal metin',
    moreFormatting: 'Daha fazla biçimlendirme',
    createNoteFromSelectionTitle: 'Seçimden yeni not oluştur',
    createNoteFromSelectionDescription:
      'Geçerli seçimi içeren yeni bir not oluşturur ve seçimi yeni nota bir bağlantıyla değiştirir.',
    dismissKeyboard: 'Klavyeyi kapat',
    tableOfContentsLower: 'İçindekiler',
    noHeadingsFound: 'Başlık bulunamadı',
    textFormattingOptions: 'Metin biçimlendirme seçenekleri',
    highlight: 'Vurgu',
    subscript: 'Alt simge',
    superscript: 'Üst simge',
    clearFormatting: 'Biçimlendirmeyi temizle',
    normal: 'Normal',
    smartChecklist: 'Akıllı onay listesi',
    restoreCompletedTasks: 'Tamamlanan görevleri geri yükle',
    leftAlign: 'Sola hizala',
    centerAlign: 'Ortala',
    rightAlign: 'Sağa hizala',
    justify: 'İki yana yasla',
    searchBlocksPlaceholder: 'Bloklarda ara…',
    searchBlocksToInsert: 'Eklenecek blokları ara',
    clearSearch: 'Aramayı temizle',
    noBlocksMatch: '“{{query}}” ile eşleşen blok yok',
    customizeToolbar: 'Araç çubuğunu özelleştir',
    custom: 'Özel',
    clear: 'Temizle',
    textColorSwatch: 'Metin rengi {{color}}',
    highlightColorSwatch: 'Vurgu rengi {{color}}',
    textShadingSwatch: 'Metin gölgelemesi {{color}}',
    noTextShading: 'Metin gölgelemesi yok',
    uppercase: 'BÜYÜK HARF',
    lowercase: 'küçük harf',
    camelCase: 'camelCase',
    sortLines: 'Satırları sırala',
    deduplicate: 'Yinelenenleri kaldır',
    multiKeySort: 'Çok anahtarlı sıralama (1., 2., 3.)…',
    sortAndDeduplicateLines: 'Satırları sırala ve yinelenenleri kaldır',
    emphasisMarks: 'Vurgu işaretleri',
    outlineTextStroke: 'Dış çizgi (metin konturu)',
    letterSpacingKerning: 'Harf aralığı (kerning)',
    wordSpacing: 'Kelime aralığı',
    clearTypography: 'Tipografiyi temizle',
    spacingTight: 'Dar',
    spacingNormal: 'Normal',
    spacingWide: 'Geniş',
    spacingWider: 'Daha geniş',
    spacingWidest: 'En geniş',
    undoMultipleSteps: 'Birden fazla adımı geri al',
    redoMultipleSteps: 'Birden fazla adımı yinele',
    emptyHistoryPreview: '(boş)',
    pasteOptions: 'Yapıştırma seçenekleri',
    copyOptions: 'Kopyalama seçenekleri',
    cutOptions: 'Kesme seçenekleri',
    pasteWithoutFormatting: 'Biçimlendirmeden yapıştır',
    pasteClean: 'Temiz yapıştır (gizli karakterleri kaldır)',
    keepSourceFormatting: 'Kaynak biçimlendirmesini koru',
    matchDestinationFormatting: 'Hedef biçimlendirmesine uydur',
    pasteAsImage: 'Görüntü olarak yapıştır',
    copyWithoutFormatting: 'Biçimlendirmeden kopyala',
    copyTextOnly: 'Yalnızca metni kopyala',
    copyImagesOnly: 'Yalnızca görüntüleri kopyala',
    cutWithoutFormatting: 'Biçimlendirmeden kes',
    cutTextOnly: 'Yalnızca metni kes',
    cutImagesOnly: 'Yalnızca görüntüleri kes',
    lineSpacing: 'Satır aralığı',
    spaceBefore: 'Öncesinde boşluk',
    spaceAfter: 'Sonrasında boşluk',
    indentation: 'Girinti',
    none: 'Yok',
    increaseLeft: 'Soldan artır',
    decreaseLeft: 'Soldan azalt',
    increaseRight: 'Sağdan artır',
    decreaseRight: 'Sağdan azalt',
    firstLine: 'İlk satır',
    noFirstLine: 'İlk satır yok',
    textShading: 'Metin gölgelemesi',
    listStyle: 'Liste stili',
    bulleted: 'Madde işaretli',
    numbered: 'Numaralı',
    bulletedListMarkers: 'Madde işareti stili',
    numberedListMarkers: 'Numaralandırma stili',
    multilevelList: 'Çok düzeyli liste',
    multilevelListHint: 'Her yuvalama düzeyi için bir işaret seçin',
    multilevelLevelDefault: 'Varsayılan',
    level: 'Düzey',
    apply: 'Uygula',
    insertTable: 'Tablo Ekle',
    insertImageFromUrl: 'URL’den görüntü ekle',
    sortLinesModalTitle: 'Satırları sırala',
    blockPicker: 'Blok seçici',
    blockParagraph: 'Paragraf',
    blockCallout: 'Bilgi kutusu',
    blockDivider: 'Ayırıcı',
    blockCollapsible: 'Daraltılabilir',
    blockImageFromUrl: 'URL’den görüntü',
    blockUploadFile: 'Dosya yükle',
    blockDrawing: 'Çizim',
    blockQrCode: 'QR Kodu',
    blockTable: 'Tablo',
    blockKanbanBoard: 'Kanban Panosu',
    blockCalendar: 'Takvim',
    blockTimeline: 'Zaman Çizelgesi',
    blockDataTable: 'Veri Tablosu',
    blockSqlQuery: 'SQL Sorgusu',
    blockMermaidDiagram: 'Mermaid Diyagramı',
    blockGanttChart: 'Gantt Şeması',
    blockTimingDiagram: 'Zamanlama Diyagramı',
    blockMusicStaff: 'Nota Portesi',
    blockTradingViewChart: 'TradingView Grafiği',
    blockStockChart: 'Hisse Senedi Grafiği',
    blockEmbed: 'Yerleştir',
    blockEmbedWebsite: 'Web sitesi yerleştir',
    blockTweet: 'Tweet',
    blockEquation: 'Denklem',
    blockInlineEquation: 'Satır içi denklem',
    blockFootnote: 'Dipnot',
    blockBookmark: 'Yer imi',
    blockGeneratePassword: 'Kriptografik olarak güvenli parola oluştur',
    blockClock: 'Saat',
    blockCurrentDateTime: 'Geçerli tarih ve saat',
    blockCurrentTime: 'Geçerli saat',
    blockCurrentDate: 'Geçerli tarih',
    blockCategoryBasic: 'Temel',
    blockCategoryLists: 'Listeler',
    blockCategoryMedia: 'Medya',
    blockCategoryDataTables: 'Veri ve tablolar',
    blockCategoryDiagramsCharts: 'Diyagramlar ve grafikler',
    blockCategoryFinance: 'Finans',
    blockCategoryEmbeds: 'Yerleştirmeler',
    blockCategoryAdvanced: 'Gelişmiş',
  },
  files: {
    dropToUploadTooltip: 'Yüklemek ve geçerli dosyaya bağlamak için dosyalarınızı buraya bırakın',
    fileAriaLabel: 'Dosya',
    fileReadonly: 'Bu dosya salt okunurdur',
    fileInformationPanel: 'Dosya bilgi paneli',
    details: 'Ayrıntılar',
    selectedFilesCount: '{{count}} seçili dosya',
    actionsPerformedOnSelected: 'İşlemler seçili tüm dosyalara uygulanacaktır.',
    cancelMultipleSelection: 'Çoklu seçimi iptal et',
    fileOptions: 'Dosya seçenekleri',
    fileContextMenu: 'Dosya bağlam menüsü',
    fileOptionsMenu: 'Dosya seçenekleri menüsü',
    fileOptionsPanel: 'Dosya seçenekleri paneli',
    noFilesSelected: 'Dosya seçilmedi',
    detachFromNote: 'Nottan ayır',
    attachToNote: 'Nota ekle',
    passwordProtect: 'Parolayla koru',
    downloadSeparately: 'Ayrı ayrı indir',
    downloadAsArchive: 'Arşiv olarak indir',
    failedToDownloadArchive: 'Dosyalar arşiv olarak indirilemedi',
    fileId: 'Dosya kimliği:',
    size: 'Boyut:',
    totalSize: 'Toplam Boyut:',
    backedUpOn: '{{date}} tarihinde yedeklendi',
    configureFileBackups: 'Dosya yedeklemelerini yapılandır',
    fileNotBackedUpLocally: 'Dosya yerel olarak yedeklenmedi',
    noFoldersYet: 'Henüz klasör yok',
    moveToFolder: 'Klasöre taşı',
    folderSelectionMenu: 'Klasör seçim menüsü',
    noFolder: 'Klasör yok',
    fileProtected: 'Bu dosya korumalıdır.',
    authenticateToView: 'Bu dosyayı görüntülemek için kimlik doğrulayın.',
    addPasscodeToView: 'Bu dosyayı görüntülemek için kimlik doğrulama gerektirmek üzere bir parola kodu ekleyin veya bir hesap oluşturun.',
    openAccountMenu: 'Hesap menüsünü aç',
    authenticate: 'Kimlik doğrula',
    viewFile: 'Dosyayı görüntüle',
    loading: 'Yükleniyor...',
    fileCannotBePreviewed: 'Bu dosya önizlenemiyor.',
    errorLoadingFile: 'Dosya yüklenirken bir hata oluştu. Tekrar deneyin veya dosyayı indirip başka bir uygulamayla açın.',
    tryAgain: 'Tekrar dene',
    downloadToView: 'Bu dosyayı görüntülemek için indirin ve başka bir uygulamayla açın.',
    fileInformation: 'Dosya bilgileri',
    type: 'Tür:',
    decryptedSize: 'Şifresi Çözülmüş Boyut:',
    encryptedSize: 'Şifrelenmiş Boyut:',
    created: 'Oluşturuldu:',
    lastModified: 'Son Değiştirilme:',
    done: 'Tamam',
    showFileOptions: 'Dosya seçeneklerini göster',
    showFileInfo: 'Dosya bilgilerini göster',
    hideFileInfo: 'Dosya bilgilerini gizle',
    showLinksSection: 'Bağlantılar bölümünü göster',
    hideLinksSection: 'Bağlantılar bölümünü gizle',
    submit: 'Gönder',
    renameFile: 'Dosyayı yeniden adlandır',
    showLinkedItems: 'Bağlantılı öğeleri göster',
    closeModal: 'Pencereyi kapat',
    filePreviewModal: 'Dosya önizleme penceresi',
    leftAlign: 'Sola hizala',
    centerAlign: 'Ortala',
    rightAlign: 'Sağa hizala',
    videoCannotBePreviewed: 'Bu video önizlenemiyor.',
    audioCannotBePlayed: 'Bu ses çalınamıyor.',
    downloadToListen: 'Bu dosyayı dinlemek için indirin ve başka bir uygulamayla açın.',
    externalAppOnly: 'Bu dosya yalnızca harici bir uygulamada önizlenebilir',
    openFilePreview: 'Dosya önizlemesini aç',
    loadingPdfViewer: 'PDF görüntüleyici yükleniyor...',
    zoomOut: 'Uzaklaş',
    zoomIn: 'Yakınlaş',
    resetToActualSize: 'Gerçek boyuta sıfırla',
    resetTo100: '%100’e sıfırla',
    fitToScreen: 'Ekrana sığdır',
    unableToRenderPdf: 'Bu PDF işlenemiyor.',
    pdfCorruptedOrProtected: 'Dosya bozuk veya parola korumalı olabilir.',
    loadingPdf: 'PDF yükleniyor...',
    previousPage: 'Önceki sayfa',
    pageNumber: 'Sayfa numarası',
    nextPage: 'Sonraki sayfa',
    fitWidth: 'Genişliğe sığdır',
    searchInDocumentShortcut: 'Belgede ara (Ctrl/Cmd+F)',
    searchInDocument: 'Belgede ara',
    copyLinkToPage: '{{page}}. sayfaya bağlantı kopyala',
    copyLinkToThisPage: 'Bu sayfaya bağlantı kopyala',
    copyLinkToSelectedText: 'Seçili metne bağlantı kopyala',
    cancelOcr: 'OCR’yi iptal et',
    preparingOcr: 'OCR hazırlanıyor...',
    ocrProgress: 'OCR sayfa {{current}} / {{total}} (%{{percent}})',
    ocrCachedReRunTooltip: 'Metin zaten çıkarıldı (önbelleğe alındı). OCR’yi tarayıcınızda yeniden çalıştırın (cihazınızda kalır).',
    ocrExtractedReRunTooltip: 'Metin çıkarıldı. OCR’yi tarayıcınızda yeniden çalıştırın (cihazınızda kalır).',
    ocrExtractTooltip: 'Taranan sayfalardan OCR ile metin çıkarın. Tarayıcınızda çalışır; hiçbir şey cihazınızdan ayrılmaz (yavaş; dil verilerini indirir).',
    extractTextWithOcrBrowser: 'Tarayıcınızda OCR ile metin çıkar',
    reRunOcrBrowser: 'OCR’yi yeniden çalıştır (tarayıcı)',
    extractTextOcr: 'Metin çıkar (OCR)',
    serverOcrTooltip:
      'OCR’yi SUNUCUDA çalıştırın. Bu, bu PDF’nin sayfa görüntülerini sunucuya gönderir ve uçtan uca şifrelemeden ÇIKAR — sunucu bu içeriği okuyabilir. Tarayıcı OCR’si her şeyi cihazınızda tutar.',
    runOcrOnServerAria: 'OCR’yi sunucuda çalıştır (sayfa görüntülerini sunucuya gönderir; uçtan uca şifrelemeden çıkar)',
    runOcrOnServer: 'OCR’yi sunucuda çalıştır',
    copyAllExtractedText: 'Çıkarılan tüm metni kopyala',
    copyExtractedTextAria: 'Çıkarılan metni kopyala',
    findInDocument: 'Belgede bul',
    matchCase: 'Büyük/küçük harf eşleştir',
    noResults: 'Sonuç yok',
    matchOfTotal: '{{total}} içinden {{current}}',
    previousMatch: 'Önceki eşleşme',
    nextMatch: 'Sonraki eşleşme',
    closeSearch: 'Aramayı kapat',
    serverOcrDisclosurePrefix: 'Hesabınız için Sunucu OCR’si kullanılabilir. Bu PDF’nin sayfa görüntülerini sunucuya gönderir ve',
    serverOcrDisclosureBold: 'uçtan uca şifrelemeden çıkar',
    serverOcrDisclosureSuffix:
      ' — sunucu (ve onu kontrol eden herkes) bu içeriği okuyabilir. Tarayıcı OCR’si her şeyi cihazınızda tutar. Varsayılan tarayıcı OCR’sidir.',
    ocrRunningServer:
      'Sunucu OCR’si: bu PDF’nin sayfa görüntüleri sunucuya yükleniyor, bu da uçtan uca şifrelemeden ÇIKAR — sunucu bu içeriği okuyabilir. (Tarayıcı OCR’si her şeyi cihazınızda tutar.)',
    ocrRunningBrowser:
      'OCR bu cihazda tarayıcınızda çalışır (dosyalarınız uçtan uca şifreli kalır). Yavaştır ve ilk kullanımda dil verilerini indirir.',
    ocrDoneServer:
      'Sunucu OCR’si tamamlandı. Sayfa görüntüleri sunucuya gönderildi (bu, uçtan uca şifrelemeden çıktı). Doğruluk tarama kalitesine göre değişir; çıkarılan metin artık aranabilir ve kopyalanabilir ve bu cihazda önbelleğe alınmıştır.',
    ocrDoneBrowser:
      'OCR tamamlandı. Doğruluk tarama kalitesine göre değişir; çıkarılan metin artık aranabilir ve kopyalanabilir ve bu cihazda önbelleğe alınmıştır.',
    copiedExtractedText: 'Çıkarılan metin kopyalandı',
    copiedLinkToPage: '{{page}}. sayfaya bağlantı kopyalandı',
    copiedLinkToSelectedText: 'Seçili metne bağlantı kopyalandı',
    serverOcrFailed: 'Sunucu OCR’si başarısız oldu: {{message}}',
    ocrUnknownError: 'bilinmeyen hata',
    ocrFailed: 'OCR başarısız oldu. Dil verileri indirilememiş olabilir.',
  },
  notes: {
    notesAndFiles: 'Notlar ve Dosyalar',
    selectAllItems: 'Tüm öğeleri seç',
    selectedCount: '{{count}} seçili',
    cancelMultipleSelection: 'Çoklu seçimi iptal et',
    noFilesInFolder: 'Bu klasörde dosya yok.',
    noItems: 'Öğe yok.',
    loading: 'Yükleniyor...',
    uploadFileWithShortcut: 'Dosya yükle {{shortcut}}',
    createNoteInTopicWithShortcut: 'Seçili konuda yeni bir not oluştur {{shortcut}}',
    dropFilesToUpload: 'Yüklemek ve "{{title}}" konusuna bağlamak için dosyalarınızı buraya bırakın',
    noFilesYet: 'Henüz hiç dosyanız yok',
    filesAttachedAppearHere:
      'Notlarınıza eklenen dosyalar burada görünür. Ayrıca doğrudan bu sayfadan da dosya yükleyebilirsiniz.',
    uploadFiles: 'Dosya yükle',
    syncing: 'Senkronize ediliyor...',
    loadingItemsProgress: '{{current}}/{{total}} öğe yükleniyor...',
    potentiallyOutOfSync: 'Senkronizasyon Dışı Olabilir',
    openDisplayOptionsMenu: 'Görüntüleme seçenekleri menüsünü aç',
    displayOptionsMenu: 'Görüntüleme seçenekleri menüsü',
    displayOptions: 'Görüntüleme seçenekleri',
    expandTopicsPanel: 'Konu panelini genişlet',
    collapseNotesPanel: 'Not panelini daralt',
    addItem: 'Öğe ekle',
    uploadFolder: 'Klasör yükle',
    takePhoto: 'Fotoğraf çek',
    recordVideo: 'Video kaydet',
    searchPlaceholder: 'Ara...',
    notesListOptionsMenu: 'Not listesi seçenekleri menüsü',
    preferencesFor: 'Şunun için tercihler',
    global: 'Genel',
    reset: 'Sıfırla',
    upgradeForPerTopicPreferences: 'Konu bazlı tercihler için yükseltin',
    perTopicPreferencesMessageWithDaily:
      'Konu bazlı görüntüleme tercihleri ve yepyeni Günlük Defter takvim düzeniyle güçlü iş akışları ve organizasyon düzenleri oluşturun.',
    perTopicPreferencesMessage:
      'Konu bazlı görüntüleme tercihleriyle güçlü iş akışları ve organizasyon düzenleri oluşturun.',
    sortBy: 'Sıralama ölçütü',
    relevanceBestMatch: 'İlgililik (en iyi eşleşme)',
    dateModified: 'Değiştirilme tarihi',
    creationDate: 'Oluşturulma tarihi',
    title: 'Başlık',
    customDragToReorder: 'Özel (sürükleyerek yeniden sırala)',
    view: 'Görünüm',
    showNotePreview: 'Not önizlemesini göster',
    showDate: 'Tarihi göster',
    showTags: 'Konuları göster',
    showIcon: 'Simgeyi göster',
    other: 'Diğer',
    showPinned: 'Sabitlenenleri göster',
    showProtected: 'Korumalıları göster',
    showArchived: 'Arşivlenenleri göster',
    showTrashed: 'Çöptekileri göster',
    dailyNotebook: 'Günlük Defter',
    labs: 'Labs',
    dailyNotebookDescription: 'Takvim tabanlı bir düzenle her gün yeni notlar yakalayın',
    tableView: 'Tablo görünümü',
    tableViewDescription: 'Geçerli konudaki notları ve dosyaları tablo düzeninde göster',
    newNoteDefaults: 'Yeni not varsayılanları',
    noteType: 'Not Türü',
    selectDefaultNoteType: 'Varsayılan not türünü seç',
    titleFormat: 'Başlık Biçimi',
    selectTitleFormat: 'Not başlığı için biçimi seç',
    customFormatPlaceholder: 'örn. YYYY-AA-GG',
    preview: 'Önizleme: ',
    useBracketsToEscape: '. Biçimlendirmeden kaçmak için ',
    toEscapeFormatting: ' kullanın.',
    protected: 'Korumalı',
    modified: 'Değiştirildi',
    now: 'Şimdi',
    editingDisabled: 'Düzenleme Devre Dışı',
    trashed: 'Çöpe Atıldı',
    archived: 'Arşivlendi',
    files: 'Dosyalar',
    starred: 'Yıldızlı',
    fileBackedUpLocally: 'Dosya yerel olarak yedeklendi',
    conflictedCopy: 'Çakışan Kopya',
    allFiles: 'Tüm Dosyalar',
    noFolder: 'Klasör yok',
    folderNamePlaceholder: 'Klasör adı',
    createNewFolder: 'Yeni bir klasör oluştur',
    newFolder: 'Yeni klasör',
    currentStreak: 'Mevcut Seri',
    dayWithCount_one: 'Gün',
    dayWithCount_other: 'Gün',
  },
  auth: {
    unableToComputePrivateUsername: 'Özel kullanıcı adı hesaplanamıyor.',
    advancedOptions: 'Gelişmiş seçenekler',
    privateUsernameMode: 'Özel kullanıcı adı modu',
    username: 'Kullanıcı adı',
    useStrictSignIn: 'Katı oturum açmayı kullan',
    useRecoveryCode: 'Kurtarma kodu kullan',
    recoveryCode: 'Kurtarma kodu',
    deleteLocalDataTitle: 'Yerel veriler silinsin mi?',
    noMergeWarning:
      'Yerel verilerinizi birleştirmemeyi seçtiniz. Devam ederseniz, yerel notlarınız ve konularınız kalıcı olarak silinecek ve hesabınızdaki verilerle değiştirilecektir. Bu işlem geri alınamaz.',
    noMergeConfirmQuestion: 'Birleştirmeden devam etmek istediğinizden emin misiniz?',
    deleteLocalDataAndContinue: 'Yerel Verileri Sil ve Devam Et',
    passwordResetWarningPart1: 'Notlarınız parolanız kullanılarak şifrelendiğinden,',
    passwordResetWarningHighlight: 'Standard Red Notes bir parola sıfırlama seçeneğine sahip değildir',
    passwordResetWarningPart2: '. Parolanızı unutursanız, verilerinize erişimi kalıcı olarak kaybedersiniz.',
    confirmPassword: 'Parolayı onayla',
    creatingAccount: 'Hesap oluşturuluyor...',
    createAccountAndSignIn: 'Hesap oluştur ve giriş yap',
    staySignedIn: 'Oturumu açık tut',
    goBack: 'Geri dön',
    humanVerification: 'İnsan doğrulaması',
    confirmPasswordTitle: 'Parolayı onayla',
    createAccount: 'Hesap oluştur',
    workspaceNameOptional: 'Çalışma alanı adı (isteğe bağlı)',
    generalAccountMenuLabel: 'Genel hesap menüsü',
    signedInAs: 'Şu hesapla giriş yaptınız:',
    syncing: 'Senkronize ediliyor...',
    lastSynced: 'Son senkronizasyon:',
    offlineSignInPrompt:
      'Çevrimdışısınız. Notlarınızı ve tercihlerinizi tüm cihazlarınızda senkronize etmek ve uçtan uca şifrelemeyi etkinleştirmek için giriş yapın.',
    offline: 'Çevrimdışı',
    accountSettings: 'Hesap ayarları',
    createFreeAccount: 'Ücretsiz hesap oluştur',
    documentation: 'Belgeler',
    keyboardShortcuts: 'Klavye kısayolları',
    commandPalette: 'Komut paleti',
    signOutWorkspace: 'Çalışma alanından çıkış yap',
    mergeLocalData: 'Yerel verileri birleştir ({{count}} not ve konu)',
    mergeLocalDataTooltip:
      'İşaretlenmezse, yerel notlarınız ve konularınız kalıcı olarak silinecek ve hesabınızdaki verilerle değiştirilecektir.',
    homeServerNotRunning:
      'Ana sunucu çalışmıyor. Başlatmak için lütfen tercihleri ve ana sunucu sekmesini açın.',
    serverDefault: 'Varsayılan',
    serverCustom: 'Özel',
    serverHomeServer: 'Ana Sunucu',
    syncServer: 'Senkronizasyon Sunucusu',
    signingIn: 'Giriş yapılıyor...',
    syncUnreachable: 'Senkronizasyona Ulaşılamıyor',
    syncUnreachableMessage: 'Hmm...hesabınızı senkronize edemiyoruz gibi görünüyor. Nedeni: {{reason}}',
    workspaceSwitcherMenuLabel: 'Çalışma alanı değiştirici menüsü',
    signOutAllWorkspacesConfirm: 'Bu cihazdaki tüm çalışma alanlarından çıkış yapmak istediğinizden emin misiniz?',
    signOutAll: 'Tümünden çıkış yap',
    addAnotherWorkspace: 'Başka bir çalışma alanı ekle',
    signOutAllWorkspaces: 'Tüm çalışma alanlarından çıkış yap',
    deleteAccountTitle: 'Hesap silinsin mi?',
    deleteMyAccountForGood: 'Hesabımı kalıcı olarak sil',
    dataNotBackedUp: 'Veriler yedeklenmedi',
    signInOrRegisterToSync:
      'Notlarınızı diğer cihazlarınıza uçtan uca şifrelemeyle senkronize etmek için giriş yapın veya kaydolun.',
    openAccountMenu: 'Hesap menüsünü aç',
    ignoreWarning: 'Uyarıyı yoksay',
    waitingForSecurityKey: 'Güvenlik anahtarı bekleniyor...',
    authenticationSuccessful: 'Kimlik doğrulama başarılı!',
    insertSecurityKeyPrompt: 'Donanım güvenlik anahtarınızı takın, ardından kimlik doğrulamak için aşağıdaki düğmeye basın.',
    authenticate: 'Kimlik doğrula',
  },
  search: {
    placeholder: 'Ara...',
    protectedContents: 'Korumalı İçerikler',
    archived: 'Arşivlenmiş',
    trashed: 'Çöpe Atılmış',
    aiUnavailable: 'AI yeniden sıralaması kullanılamıyor veya sonuç döndürmedi.',
    aiUnavailableTooltip: 'AI bağlamsal araması kullanılamıyor.',
    aiTypeQueryFirst: 'Önce bir arama sorgusu yazın.',
    aiTooltip:
      'Yapılandırılmış AI sağlayıcınızı kullanarak en iyi sonuçları anlamsal ilgililiğe göre yeniden sıralar. ' +
      'Bu adayların başlıklarını ve kısa parçacıklarını, sorgunuzla birlikte sağlayıcıya gönderir.',
    aiSearchWithAi: 'AI ile ara',
    aiRanking: 'Sıralanıyor…',
    aiRankedByRelevance: 'AI ilgililiğine göre sıralandı',
    aiPrivacyNotice:
      'En iyi sonuçların başlıklarını ve parçacıklarını ve sorgunuzu AI sağlayıcınıza gönderir. Bulut sağlayıcıları ' +
      'bunları görebilir — yerel bir model bunu cihazda tutar.',
    advancedFilters: 'Gelişmiş arama filtreleri',
    filters: 'Filtreler',
    noteTypeAny: 'Herhangi bir tür',
    noteTypePlainText: 'Düz metin',
    noteTypeRichText: 'Zengin metin',
    noteTypeSuper: 'Super',
    noteTypeMarkdown: 'Markdown',
    noteTypeCode: 'Kod',
    noteTypeTask: 'Görev',
    noteTypeSpreadsheet: 'Elektronik tablo',
    flagProtected: 'Korumalı',
    flagPinned: 'Sabitlenmiş',
    flagArchived: 'Arşivlenmiş',
    flagStarred: 'Yıldızlı',
    flagTrashed: 'Çöpe Atılmış',
    topicsLabel: 'Konular (virgülle ayrılmış)',
    topicsPlaceholder: 'iş, kişisel',
    noteTypeLabel: 'Not türü',
    searchInLabel: 'Şurada ara',
    searchInTitleAndContent: 'Başlık ve içerik',
    modifiedWithinLabel: 'Şu süre içinde değiştirilenler',
    datePreset: 'Son {{label}}',
    createdAfterLabel: 'Şu tarihten sonra oluşturulan',
    createdBeforeLabel: 'Şu tarihten önce oluşturulan',
    updatedAfterLabel: 'Şu tarihten sonra güncellenen',
    updatedBeforeLabel: 'Şu tarihten önce güncellenen',
    statusLabel: 'Durum',
    hasAttachments: 'Eki var',
    caseSensitive: 'Büyük/küçük harfe duyarlı',
    clearAllFilters: 'Tüm filtreleri temizle',
  },
  sharing: {
    vaultSelectionMenu: 'Kasa seçim menüsü',
    vaultOptionsMenu: 'Kasa seçenekleri menüsü',
    vaultOptions: 'Kasa seçenekleri',
    noVaultsFound: 'Kasa bulunamadı',
    moveToVault: 'Kasaya taşı',
    moveOutOfVault: '{{name}} dışına taşı',
    vaultsFallbackName: 'kasalar',
    editVault: 'Kasayı düzenle',
    lockVault: 'Kasayı kilitle',
    unlockVault: 'Kasa kilidini aç',
    openVaultSettings: 'Kasa ayarlarını aç',
    selectionModeMultiple: 'Birden fazla',
    selectionModeOne: 'Bir',
    lastEditedBy: 'Son düzenleyen',
    sharedBy: 'Paylaşan',
    sharedByContact: 'Kişi tarafından paylaşıldı',
    vaultName: 'Kasa adı',
    sharedInVault: 'Kasada paylaşıldı',
    copiedToClipboard: 'Panoya kopyalandı',
    failedToCopyToClipboard: 'Panoya kopyalanamadı',
    copyExampleToClipboard: 'Örneği panoya kopyala',
    copiedExclaim: 'Kopyalandı!',
    shareUnavailableTitle: 'Paylaşım kullanılamıyor',
    shareUnavailableMessage: 'Bu paylaşım bağlantısı artık kullanılamıyor.',
    invalidLinkTitle: 'Geçersiz bağlantı',
    invalidLinkMessage: 'Bu paylaşım bağlantısı geçersiz veya anahtar eksik.',
    selfDestructTitle: 'Bu not görüntülendikten sonra kendini imha eder',
    oneTimeViewConsumed: 'Tek seferlik görüntüleme bağlantısı okuyorsunuz. Artık kullanıldı ve yeniden açılamaz',
    oneTimeViewExpiresClause_one: ' ve ilk açılıştan {{count}} dakika sonra tamamen sona erer',
    oneTimeViewExpiresClause_other: ' ve ilk açılıştan {{count}} dakika sonra tamamen sona erer',
    linkExpires_one: 'Bu bağlantı ilk açıldıktan {{count}} dakika sonra sona erer.',
    linkExpires_other: 'Bu bağlantı ilk açıldıktan {{count}} dakika sonra sona erer.',
    untitled: 'Başlıksız',
    tagHasNoNotes: 'Bu konunun notu yok.',
    publicReadOnlyFooter: 'Bu, herkese açık, salt okunur bir paylaşım bağlantısıdır. İçerik tarayıcınızda şifresi çözülmüştür.',
    confidentialWatermark: 'Gizli · {{datetime}}',
    contentHiddenTitle: 'İçerik gizli',
    contentHiddenMessage: 'Paylaşılan içeriği görüntülemek için bu pencereye geri dönün.',
  },
}

export default tr
