import type { LocaleResource } from './en'

const tr: LocaleResource = {
  common: {
    save: 'Kaydet',
    cancel: 'İptal',
    delete: 'Sil',
    confirm: 'Onayla',
    close: 'Kapat',
    edit: 'Düzenle',
    rename: 'Yeniden adlandır',
    duplicate: 'Çoğalt',
    remove: 'Kaldır',
    open: 'Aç',
    create: 'Oluştur',
    add: 'Ekle',
    done: 'Tamam',
    back: 'Geri',
    next: 'İleri',
    search: 'Ara',
    clear: 'Temizle',
    loading: 'Yükleniyor…',
    copy: 'Kopyala',
    copied: 'Kopyalandı',
    download: 'İndir',
    upload: 'Yükle',
    export: 'Dışa aktar',
    import: 'İçe aktar',
    yes: 'Evet',
    no: 'Hayır',
    enabled: 'Etkin',
    disabled: 'Devre dışı',
    on: 'Açık',
    off: 'Kapalı',
    learnMore: 'Daha fazla bilgi',
    options: 'Seçenekler',
    settings: 'Ayarlar',
    preferences: 'Tercihler',
    help: 'Yardım',
    pin: 'Sabitle',
    unpin: 'Sabitlemeyi kaldır',
    star: 'Yıldızla',
    unstar: 'Yıldızı kaldır',
    archive: 'Arşivle',
    unarchive: 'Arşivden çıkar',
    restore: 'Geri yükle',
    moveToTrash: 'Çöp kutusuna taşı',
    deletePermanently: 'Kalıcı olarak sil',
    protect: 'Koru',
    unprotect: 'Korumayı kaldır',
  },
  navigation: {
    notes: 'Notlar',
    allNotes: 'Tüm notlar',
    files: 'Dosyalar',
    starred: 'Yıldızlı',
    archived: 'Arşivlenmiş',
    trash: 'Çöp Kutusu',
    untagged: 'Etiketsiz',
    conflicts: 'Çakışmalar',
    views: 'Görünümler',
    smartViews: 'Akıllı Görünümler',
    tags: 'Etiketler',
    folders: 'Klasörler',
    favorites: 'Sık kullanılanlar',
    dashboard: 'Panel',
    createNewNote: 'Yeni bir not oluştur',
    createNewTag: 'Yeni bir etiket oluştur',
    createNewFolder: 'Yeni bir klasör oluştur',
    createNewSmartView: 'Yeni bir akıllı görünüm oluştur',
    searchTags: 'Etiketleri ara…',
    noTagsFound: 'Etiket bulunamadı. Farklı bir arama deneyin.',
    noSmartViewsFound: 'Akıllı görünüm bulunamadı. Farklı bir arama deneyin.',
    collapseTagsPanel: 'Etiket panelini daralt',
    expandTagsPanel: 'Etiket panelini genişlet',
    goToItemsList: 'Öğe listesine git',
    goToAccountMenu: 'Hesap menüsüne git',
    openPreferences: 'Tercihleri aç',
  },
  account: {
    account: 'Hesap',
    signIn: 'Giriş yap',
    signOut: 'Çıkış yap',
    signUp: 'Kaydol',
    register: 'Kaydol',
    you: 'Siz',
    encryptionOn: 'Uçtan uca şifreleme açık',
    notSignedIn: 'Giriş yapmadınız',
    signInOrRegister: 'Notlarınızı senkronize etmek için giriş yapın veya kaydolun',
    email: 'E-posta',
    password: 'Parola',
    confirmPassword: 'Parolayı onayla',
    syncNow: 'Şimdi senkronize et',
    lastSynced: 'Son senkronizasyon',
    importData: 'İçe aktar',
    switchWorkspace: 'Çalışma alanını değiştir',
    lockApplication: 'Uygulamayı kilitle',
    helpAndFeedback: 'Yardım ve geri bildirim',
  },
  preferences: {
    title: 'Tercihler',
    general: 'Genel',
    account: 'Hesap',
    security: 'Güvenlik',
    appearance: 'Görünüm',
    backups: 'Yedeklemeler',
    listed: 'Listed',
    plugins: 'Eklentiler',
    whatsNew: 'Yenilikler',
    helpAndFeedback: 'Yardım ve geri bildirim',
    language: 'Dil',
    languageTitle: 'Dil',
    languageDescription:
      'Uygulama arayüzünde kullanılan dili seçin. Henüz çevrilmemiş içerikler için uygulama İngilizceye döner.',
    languageChanged: 'Dil güncellendi',
    defaults: 'Varsayılanlar',
    tools: 'Araçlar',
    spellcheck: 'Yazım denetimi',
    labs: 'Laboratuvarlar',
  },
}

export default tr
