import type { LocaleResource } from './en'

const uk: LocaleResource = {
  common: {
    save: 'Зберегти',
    cancel: 'Скасувати',
    delete: 'Видалити',
    confirm: 'Підтвердити',
    close: 'Закрити',
    edit: 'Редагувати',
    rename: 'Перейменувати',
    duplicate: 'Дублювати',
    remove: 'Прибрати',
    open: 'Відкрити',
    create: 'Створити',
    add: 'Додати',
    done: 'Готово',
    back: 'Назад',
    next: 'Далі',
    search: 'Пошук',
    clear: 'Очистити',
    loading: 'Завантаження…',
    copy: 'Копіювати',
    copied: 'Скопійовано',
    download: 'Завантажити',
    upload: 'Вивантажити',
    export: 'Експорт',
    import: 'Імпорт',
    yes: 'Так',
    no: 'Ні',
    enabled: 'Увімкнено',
    disabled: 'Вимкнено',
    on: 'Увімк.',
    off: 'Вимк.',
    learnMore: 'Докладніше',
    options: 'Параметри',
    settings: 'Налаштування',
    preferences: 'Налаштування',
    help: 'Довідка',
    pin: 'Закріпити',
    unpin: 'Відкріпити',
    star: 'Позначити',
    unstar: 'Зняти позначку',
    archive: 'До архіву',
    unarchive: 'З архіву',
    restore: 'Відновити',
    moveToTrash: 'Перемістити в кошик',
    deletePermanently: 'Видалити назавжди',
    protect: 'Захистити',
    unprotect: 'Зняти захист',
  },
  navigation: {
    notes: 'Нотатки',
    allNotes: 'Усі нотатки',
    files: 'Файли',
    starred: 'Позначені',
    archived: 'Архів',
    trash: 'Кошик',
    untagged: 'Без теми',
    conflicts: 'Конфлікти',
    views: 'Подання',
    smartViews: 'Розумні подання',
    tags: 'Теми',
    folders: 'Теки',
    favorites: 'Вибране',
    dashboard: 'Панель',
    createNewNote: 'Створити нову нотатку',
    createNewTag: 'Створити нову тему',
    createNewFolder: 'Створити нову теку',
    createNewSmartView: 'Створити нове розумне подання',
    searchTags: 'Пошук тем…',
    noTagsFound: 'Тем не знайдено. Спробуйте інший запит.',
    noSmartViewsFound: 'Розумних подань не знайдено. Спробуйте інший запит.',
    collapseTagsPanel: 'Згорнути панель тем',
    expandTagsPanel: 'Розгорнути панель тем',
    goToItemsList: 'Перейти до списку елементів',
    goToAccountMenu: 'Перейти до меню облікового запису',
    openPreferences: 'Відкрити налаштування',
  },
  account: {
    account: 'Обліковий запис',
    signIn: 'Увійти',
    signOut: 'Вийти',
    signUp: 'Зареєструватися',
    register: 'Зареєструватися',
    you: 'Ви',
    encryptionOn: 'Наскрізне шифрування ввімкнено',
    notSignedIn: 'Ви не ввійшли',
    signInOrRegister: 'Увійдіть або зареєструйтеся, щоб синхронізувати нотатки',
    email: 'Ел. пошта',
    password: 'Пароль',
    confirmPassword: 'Підтвердьте пароль',
    syncNow: 'Синхронізувати',
    lastSynced: 'Остання синхронізація',
    importData: 'Імпорт',
    switchWorkspace: 'Змінити робочу область',
    lockApplication: 'Заблокувати застосунок',
    helpAndFeedback: 'Довідка та відгуки',
  },
  preferences: {
    title: 'Налаштування',
    general: 'Загальні',
    account: 'Обліковий запис',
    security: 'Безпека',
    appearance: 'Оформлення',
    backups: 'Резервні копії',
    listed: 'Listed',
    plugins: 'Плагіни',
    whatsNew: 'Що нового',
    helpAndFeedback: 'Довідка та відгуки',
    language: 'Мова',
    languageTitle: 'Мова',
    languageDescription: 'Виберіть мову інтерфейсу застосунку. Для неперекладеного вмісту використовується англійська.',
    languageChanged: 'Мову оновлено',
    defaults: 'Значення за замовчуванням',
    tools: 'Інструменти',
    spellcheck: 'Перевірка орфографії',
    labs: 'Лабораторія',
  },
  editor: {
    cut: 'Вирізати',
    copy: 'Копіювати',
    paste: 'Вставити',
    moreCutOptions: 'Більше параметрів вирізання',
    moreCopyOptions: 'Більше параметрів копіювання',
    morePasteOptions: 'Більше параметрів вставлення',
    tableOfContents: 'Зміст',
    selectAll: 'Виділити все',
    selectAllText: 'Виділити лише текст',
    deselectAll: 'Зняти виділення',
    search: 'Пошук',
    undo: 'Скасувати',
    redo: 'Повторити',
    undoHistory: 'Історія скасувань',
    redoHistory: 'Історія повторень',
    undoHistoryEmpty: 'Історія скасувань — скасовувати поки нічого',
    undoHistoryAvailable: 'Історія скасувань — поверніться на кілька кроків назад одразу',
    redoHistoryEmpty: 'Історія повторень — повторювати нічого',
    redoHistoryAvailable: 'Історія повторень — перейдіть на кілька кроків уперед одразу',
    formattingOptions: 'Параметри форматування',
    bold: 'Жирний',
    italic: 'Курсив',
    underline: 'Підкреслений',
    strikethrough: 'Закреслений',
    inlineCode: 'Вбудований код',
    link: 'Посилання',
    formatPainter: 'Пензлик форматування — копіювати форматування (подвійний клік, щоб залишити ввімкненим)',
    textStyle: 'Стиль тексту',
    textColor: 'Колір тексту',
    highlightColor: 'Колір виділення',
    typography: 'Типографіка — акценти, контур, міжлітерний та міжсловний інтервал',
    typographyTitle: 'Типографіка',
    fontSize: 'Розмір шрифту',
    chooseFontSize: 'Виберіть розмір шрифту',
    decreaseFontSize: 'Зменшити розмір шрифту',
    increaseFontSize: 'Збільшити розмір шрифту',
    fontFamily: 'Гарнітура шрифту',
    customFontFamily: 'Власна',
    bulletedList: 'Маркований список',
    numberedList: 'Нумерований список',
    checkList: 'Список завдань',
    quote: 'Цитата',
    codeBlock: 'Блок коду',
    changeCase: 'Змінити регістр',
    sortAndDedupeLines: 'Сортувати та видалити дублікати рядків',
    alignment: 'Вирівнювання',
    paragraphLayout: 'Макет абзацу — міжрядковий та міжабзацний інтервал, відступи, заливка',
    paragraphLayoutTitle: 'Макет абзацу',
    listStyleMarker: 'Стиль списку — маркер та нумерація',
    formattingMarks: 'Знаки форматування',
    insert: 'Вставити',
    insertRowAbove: 'Вставити рядок вище',
    insertRowBelow: 'Вставити рядок нижче',
    insertColumnLeft: 'Вставити стовпець ліворуч',
    insertColumnRight: 'Вставити стовпець праворуч',
    deleteRow: 'Видалити рядок',
    deleteColumn: 'Видалити стовпець',
    toggleRowHeader: 'Перемкнути заголовок рядка',
    toggleColumnHeader: 'Перемкнути заголовок стовпця',
    deleteTable: 'Видалити таблицю',
    rows: 'Рядки',
    columns: 'Стовпці',
    cells: 'Комірки',
    table: 'Таблиця',
    block: 'Блок',
    alignLeft: 'Вирівняти ліворуч',
    alignCenter: 'Вирівняти по центру',
    alignRight: 'Вирівняти праворуч',
    editLink: 'Редагувати посилання',
    removeLink: 'Видалити посилання',
    zoomIntoBlock: 'Збільшити блок',
    blockStyle: 'Стиль блоку',
    heading1: 'Заголовок 1',
    heading2: 'Заголовок 2',
    heading3: 'Заголовок 3',
    normalText: 'Звичайний текст',
    moreFormatting: 'Більше форматування',
    createNoteFromSelectionTitle: 'Створити нову нотатку з виділення',
    createNoteFromSelectionDescription:
      'Створює нову нотатку з поточним виділенням і замінює виділення посиланням на нову нотатку.',
    dismissKeyboard: 'Сховати клавіатуру',
    tableOfContentsLower: 'Зміст',
    noHeadingsFound: 'Заголовків не знайдено',
    textFormattingOptions: 'Параметри форматування тексту',
    highlight: 'Виділення',
    subscript: 'Нижній індекс',
    superscript: 'Верхній індекс',
    clearFormatting: 'Очистити форматування',
    normal: 'Звичайний',
    smartChecklist: 'Розумний список завдань',
    restoreCompletedTasks: 'Відновити виконані завдання',
    completeAllChecklistItems: 'Позначити всі як виконані',
    completeAllChecklistItemsDescription:
      'Позначає виконаними всі елементи списку завдань, у якому перебуває курсор або виділення.',
    completeSelectedChecklistItems: 'Позначити виділені як виконані',
    uncompleteSelectedChecklistItems: 'Позначити виділені як невиконані',
    noChecklistItemsSelected: 'Помістіть курсор у список завдань або виділіть елементи, щоб скористатися цією дією.',
    leftAlign: 'Вирівняти ліворуч',
    centerAlign: 'Вирівняти по центру',
    rightAlign: 'Вирівняти праворуч',
    justify: 'За шириною',
    searchBlocksPlaceholder: 'Пошук блоків…',
    searchBlocksToInsert: 'Шукати блоки для вставлення',
    clearSearch: 'Очистити пошук',
    noBlocksMatch: 'Немає блоків, що відповідають «{{query}}»',
    customizeToolbar: 'Налаштувати панель інструментів',
    custom: 'Власний',
    clear: 'Очистити',
    textColorSwatch: 'Колір тексту {{color}}',
    highlightColorSwatch: 'Колір виділення {{color}}',
    textShadingSwatch: 'Заливка тексту {{color}}',
    noTextShading: 'Без заливки тексту',
    uppercase: 'ВЕРХНІЙ РЕГІСТР',
    lowercase: 'нижній регістр',
    camelCase: 'camelCase',
    sortLines: 'Сортувати рядки',
    deduplicate: 'Видалити дублікати',
    multiKeySort: 'Багатоключове сортування (1-й, 2-й, 3-й)…',
    sortAndDeduplicateLines: 'Сортувати та видалити дублікати рядків',
    emphasisMarks: 'Знаки акценту',
    outlineTextStroke: 'Контур (обведення тексту)',
    letterSpacingKerning: 'Міжлітерний інтервал (кернінг)',
    wordSpacing: 'Міжсловний інтервал',
    clearTypography: 'Очистити типографіку',
    spacingTight: 'Щільний',
    spacingNormal: 'Звичайний',
    spacingWide: 'Широкий',
    spacingWider: 'Ширший',
    spacingWidest: 'Найширший',
    undoMultipleSteps: 'Скасувати кілька кроків',
    redoMultipleSteps: 'Повторити кілька кроків',
    emptyHistoryPreview: '(порожньо)',
    pasteOptions: 'Параметри вставлення',
    copyOptions: 'Параметри копіювання',
    cutOptions: 'Параметри вирізання',
    pasteWithoutFormatting: 'Вставити без форматування',
    pasteClean: 'Вставити очищене (прибрати приховані символи)',
    keepSourceFormatting: 'Зберегти вихідне форматування',
    matchDestinationFormatting: 'Застосувати форматування місця вставлення',
    pasteAsImage: 'Вставити як зображення',
    copyWithoutFormatting: 'Копіювати без форматування',
    copyTextOnly: 'Копіювати лише текст',
    copyImagesOnly: 'Копіювати лише зображення',
    cutWithoutFormatting: 'Вирізати без форматування',
    cutTextOnly: 'Вирізати лише текст',
    cutImagesOnly: 'Вирізати лише зображення',
    lineSpacing: 'Міжрядковий інтервал',
    spaceBefore: 'Інтервал перед',
    spaceAfter: 'Інтервал після',
    indentation: 'Відступ',
    none: 'Немає',
    increaseLeft: 'Збільшити ліворуч',
    decreaseLeft: 'Зменшити ліворуч',
    increaseRight: 'Збільшити праворуч',
    decreaseRight: 'Зменшити праворуч',
    firstLine: 'Перший рядок',
    noFirstLine: 'Без першого рядка',
    textShading: 'Заливка тексту',
    listStyle: 'Стиль списку',
    bulleted: 'Маркований',
    numbered: 'Нумерований',
    bulletedListMarkers: 'Стиль маркера',
    numberedListMarkers: 'Стиль нумерації',
    multilevelList: 'Багаторівневий список',
    multilevelListHint: 'Виберіть маркер для кожного рівня вкладеності',
    multilevelLevelDefault: 'За замовчуванням',
    level: 'Рівень',
    apply: 'Застосувати',
    insertTable: 'Вставити таблицю',
    insertImageFromUrl: 'Вставити зображення за URL',
    sortLinesModalTitle: 'Сортувати рядки',
    blockPicker: 'Вибір блоку',
    blockParagraph: 'Абзац',
    blockCallout: 'Виноска',
    blockDivider: 'Роздільник',
    blockCollapsible: 'Згортуваний блок',
    blockImageFromUrl: 'Зображення за URL',
    blockUploadFile: 'Вивантажити файл',
    blockDrawing: 'Малюнок',
    blockQrCode: 'QR-код',
    blockTable: 'Таблиця',
    blockKanbanBoard: 'Канбан-дошка',
    blockCalendar: 'Календар',
    blockTimeline: 'Часова шкала',
    blockDataTable: 'Таблиця даних',
    blockSqlQuery: 'SQL-запит',
    blockMermaidDiagram: 'Діаграма Mermaid',
    blockGanttChart: 'Діаграма Ганта',
    blockTimingDiagram: 'Часова діаграма',
    blockMusicStaff: 'Нотний стан',
    blockTradingViewChart: 'Графік TradingView',
    blockStockChart: 'Біржовий графік',
    blockEmbed: 'Вбудовування',
    blockEmbedWebsite: 'Вбудувати вебсайт',
    blockTweet: 'Твіт',
    blockEquation: 'Рівняння',
    blockInlineEquation: 'Вбудоване рівняння',
    blockFootnote: 'Примітка',
    blockBookmark: 'Закладка',
    blockGeneratePassword: 'Згенерувати криптографічно надійний пароль',
    blockClock: 'Годинник',
    blockCurrentDateTime: 'Поточна дата й час',
    blockCurrentTime: 'Поточний час',
    blockCurrentDate: 'Поточна дата',
    blockCategoryBasic: 'Основне',
    blockCategoryLists: 'Списки',
    blockCategoryMedia: 'Медіа',
    blockCategoryDataTables: 'Дані й таблиці',
    blockCategoryDiagramsCharts: 'Діаграми й графіки',
    blockCategoryFinance: 'Фінанси',
    blockCategoryEmbeds: 'Вбудовування',
    blockCategoryAdvanced: 'Додатково',
  },
  files: {
    dropToUploadTooltip: 'Перетягніть файли, щоб вивантажити та прив’язати їх до поточного файлу',
    fileAriaLabel: 'Файл',
    fileReadonly: 'Цей файл доступний лише для читання',
    fileInformationPanel: 'Панель інформації про файл',
    details: 'Деталі',
    selectedFilesCount: '{{count}} вибраних файлів',
    actionsPerformedOnSelected: 'Дії буде виконано для всіх вибраних файлів.',
    cancelMultipleSelection: 'Скасувати множинний вибір',
    fileOptions: 'Параметри файлу',
    fileContextMenu: 'Контекстне меню файлу',
    fileOptionsMenu: 'Меню параметрів файлу',
    fileOptionsPanel: 'Панель параметрів файлу',
    noFilesSelected: 'Файли не вибрано',
    detachFromNote: 'Від’єднати від нотатки',
    attachToNote: 'Прикріпити до нотатки',
    passwordProtect: 'Захистити паролем',
    downloadSeparately: 'Завантажити окремо',
    downloadAsArchive: 'Завантажити як архів',
    failedToDownloadArchive: 'Не вдалося завантажити файли як архів',
    fileId: 'ID файлу:',
    size: 'Розмір:',
    totalSize: 'Загальний розмір:',
    backedUpOn: 'Резервну копію створено {{date}}',
    configureFileBackups: 'Налаштувати резервне копіювання файлів',
    fileNotBackedUpLocally: 'Файл не має локальної резервної копії',
    noFoldersYet: 'Тек поки немає',
    moveToFolder: 'Перемістити до теки',
    folderSelectionMenu: 'Меню вибору теки',
    noFolder: 'Без теки',
    fileProtected: 'Цей файл захищено.',
    authenticateToView: 'Пройдіть автентифікацію, щоб переглянути цей файл.',
    addPasscodeToView:
      'Додайте код доступу або створіть обліковий запис, щоб вимагати автентифікацію для перегляду цього файлу.',
    openAccountMenu: 'Відкрити меню облікового запису',
    authenticate: 'Автентифікувати',
    viewFile: 'Переглянути файл',
    loading: 'Завантаження...',
    fileCannotBePreviewed: 'Цей файл не можна попередньо переглянути.',
    errorLoadingFile:
      'Під час завантаження файлу сталася помилка. Спробуйте ще раз або завантажте файл і відкрийте його в іншій програмі.',
    tryAgain: 'Спробувати ще раз',
    downloadToView: 'Щоб переглянути цей файл, завантажте його та відкрийте в іншій програмі.',
    fileInformation: 'Інформація про файл',
    type: 'Тип:',
    decryptedSize: 'Розмір після розшифрування:',
    encryptedSize: 'Зашифрований розмір:',
    created: 'Створено:',
    lastModified: 'Востаннє змінено:',
    done: 'Готово',
    showFileOptions: 'Показати параметри файлу',
    showFileInfo: 'Показати інформацію про файл',
    hideFileInfo: 'Сховати інформацію про файл',
    showLinksSection: 'Показати розділ посилань',
    hideLinksSection: 'Сховати розділ посилань',
    submit: 'Надіслати',
    renameFile: 'Перейменувати файл',
    showLinkedItems: 'Показати пов’язані елементи',
    closeModal: 'Закрити вікно',
    filePreviewModal: 'Вікно попереднього перегляду файлу',
    leftAlign: 'Вирівняти ліворуч',
    centerAlign: 'Вирівняти по центру',
    rightAlign: 'Вирівняти праворуч',
    videoCannotBePreviewed: 'Це відео не можна попередньо переглянути.',
    audioCannotBePlayed: 'Це аудіо не можна відтворити.',
    downloadToListen: 'Щоб прослухати цей файл, завантажте його та відкрийте в іншій програмі.',
    externalAppOnly: 'Цей файл можна переглянути лише у зовнішній програмі',
    openFilePreview: 'Відкрити попередній перегляд файлу',
    loadingPdfViewer: 'Завантаження засобу перегляду PDF...',
    zoomOut: 'Зменшити',
    zoomIn: 'Збільшити',
    resetToActualSize: 'Скинути до фактичного розміру',
    resetTo100: 'Скинути до 100%',
    fitToScreen: 'За розміром екрана',
    unableToRenderPdf: 'Не вдалося відобразити цей PDF.',
    pdfCorruptedOrProtected: 'Файл може бути пошкоджений або захищений паролем.',
    loadingPdf: 'Завантаження PDF...',
    previousPage: 'Попередня сторінка',
    pageNumber: 'Номер сторінки',
    nextPage: 'Наступна сторінка',
    fitWidth: 'За шириною',
    searchInDocumentShortcut: 'Пошук у документі (Ctrl/Cmd+F)',
    searchInDocument: 'Пошук у документі',
    copyLinkToPage: 'Копіювати посилання на сторінку {{page}}',
    copyLinkToThisPage: 'Копіювати посилання на цю сторінку',
    copyLinkToSelectedText: 'Копіювати посилання на виділений текст',
    cancelOcr: 'Скасувати OCR',
    preparingOcr: 'Підготовка OCR...',
    ocrProgress: 'OCR сторінка {{current}} / {{total}} ({{percent}}%)',
    ocrCachedReRunTooltip:
      'Текст уже видобуто (кешовано). Повторно запустити OCR у браузері (залишається на вашому пристрої).',
    ocrExtractedReRunTooltip: 'Текст видобуто. Повторно запустити OCR у браузері (залишається на вашому пристрої).',
    ocrExtractTooltip:
      'Видобути текст зі сканованих сторінок за допомогою OCR. Виконується у вашому браузері; нічого не залишає ваш пристрій (повільно; завантажує мовні дані).',
    extractTextWithOcrBrowser: 'Видобути текст за допомогою OCR у браузері',
    reRunOcrBrowser: 'Повторно запустити OCR (браузер)',
    extractTextOcr: 'Видобути текст (OCR)',
    serverOcrTooltip:
      'Запустити OCR на СЕРВЕРІ. Це надсилає зображення сторінок цього PDF на сервер і ВИХОДИТЬ за межі наскрізного шифрування — сервер може прочитати цей вміст. Браузерний OCR зберігає все на вашому пристрої.',
    runOcrOnServerAria:
      'Запустити OCR на сервері (надсилає зображення сторінок на сервер; виходить за межі наскрізного шифрування)',
    runOcrOnServer: 'Запустити OCR на сервері',
    copyAllExtractedText: 'Копіювати весь видобутий текст',
    copyExtractedTextAria: 'Копіювати видобутий текст',
    findInDocument: 'Знайти в документі',
    matchCase: 'Враховувати регістр',
    noResults: 'Немає результатів',
    matchOfTotal: '{{current}} з {{total}}',
    previousMatch: 'Попередній збіг',
    nextMatch: 'Наступний збіг',
    closeSearch: 'Закрити пошук',
    serverOcrDisclosurePrefix:
      'Серверний OCR доступний для вашого облікового запису. Він надсилає зображення сторінок цього PDF на сервер і',
    serverOcrDisclosureBold: 'виходить за межі наскрізного шифрування',
    serverOcrDisclosureSuffix:
      ' — сервер (і будь-хто, хто ним керує) може прочитати цей вміст. Браузерний OCR зберігає все на вашому пристрої. За замовчуванням використовується браузерний OCR.',
    ocrRunningServer:
      'Серверний OCR: зображення сторінок цього PDF вивантажуються на сервер, що ВИХОДИТЬ за межі наскрізного шифрування — сервер може прочитати цей вміст. (Браузерний OCR зберігає все на вашому пристрої.)',
    ocrRunningBrowser:
      'OCR виконується у вашому браузері на цьому пристрої (ваші файли залишаються наскрізно зашифрованими). Це повільно і завантажує мовні дані під час першого використання.',
    ocrDoneServer:
      'Серверний OCR завершено. Зображення сторінок було надіслано на сервер (це вийшло за межі наскрізного шифрування). Точність залежить від якості сканування; видобутий текст тепер доступний для пошуку та копіювання і кешується на цьому пристрої.',
    ocrDoneBrowser:
      'OCR завершено. Точність залежить від якості сканування; видобутий текст тепер доступний для пошуку та копіювання і кешується на цьому пристрої.',
    copiedExtractedText: 'Видобутий текст скопійовано',
    copiedLinkToPage: 'Посилання на сторінку {{page}} скопійовано',
    copiedLinkToSelectedText: 'Посилання на виділений текст скопійовано',
    serverOcrFailed: 'Серверний OCR не вдався: {{message}}',
    ocrUnknownError: 'невідома помилка',
    ocrFailed: 'OCR не вдався. Можливо, не вдалося завантажити мовні дані.',
  },
  notes: {
    notesAndFiles: 'Нотатки й файли',
    selectAllItems: 'Виділити всі елементи',
    selectedCount: '{{count}} вибрано',
    cancelMultipleSelection: 'Скасувати множинний вибір',
    noFilesInFolder: 'У цій теці немає файлів.',
    noItems: 'Немає елементів.',
    loading: 'Завантаження...',
    uploadFileWithShortcut: 'Вивантажити файл {{shortcut}}',
    createNoteInTopicWithShortcut: 'Створити нову нотатку у вибраній темі {{shortcut}}',
    dropFilesToUpload: 'Перетягніть файли, щоб вивантажити та прив’язати їх до теми «{{title}}»',
    noFilesYet: 'У вас поки немає файлів',
    filesAttachedAppearHere:
      'Файли, прикріплені до ваших нотаток, з’являються тут. Ви також можете вивантажувати файли безпосередньо з цієї сторінки.',
    uploadFiles: 'Вивантажити файли',
    syncing: 'Синхронізація...',
    loadingItemsProgress: 'Завантаження {{current}}/{{total}} елементів...',
    potentiallyOutOfSync: 'Можливо, не синхронізовано',
    openDisplayOptionsMenu: 'Відкрити меню параметрів відображення',
    displayOptionsMenu: 'Меню параметрів відображення',
    displayOptions: 'Параметри відображення',
    expandTopicsPanel: 'Розгорнути панель тем',
    collapseNotesPanel: 'Згорнути панель нотаток',
    addItem: 'Додати елемент',
    uploadFolder: 'Вивантажити теку',
    takePhoto: 'Зробити фото',
    recordVideo: 'Записати відео',
    searchPlaceholder: 'Пошук...',
    notesListOptionsMenu: 'Меню параметрів списку нотаток',
    preferencesFor: 'Налаштування для',
    global: 'Глобальні',
    reset: 'Скинути',
    upgradeForPerTopicPreferences: 'Оновіть для налаштувань за темами',
    perTopicPreferencesMessageWithDaily:
      'Створюйте потужні робочі процеси та організаційні макети за допомогою налаштувань відображення для кожної теми та абсолютно нового календарного макета «Щоденний записник».',
    perTopicPreferencesMessage:
      'Створюйте потужні робочі процеси та організаційні макети за допомогою налаштувань відображення для кожної теми.',
    sortBy: 'Сортувати за',
    relevanceBestMatch: 'Релевантність (найкращий збіг)',
    dateModified: 'Дата зміни',
    creationDate: 'Дата створення',
    title: 'Назва',
    customDragToReorder: 'Власне (перетягніть для впорядкування)',
    view: 'Вигляд',
    showNotePreview: 'Показувати попередній перегляд нотатки',
    showDate: 'Показувати дату',
    showTags: 'Показувати теми',
    showIcon: 'Показувати піктограму',
    other: 'Інше',
    showPinned: 'Показувати закріплені',
    showProtected: 'Показувати захищені',
    showArchived: 'Показувати архівовані',
    showTrashed: 'Показувати у кошику',
    dailyNotebook: 'Щоденний записник',
    labs: 'Labs',
    dailyNotebookDescription: 'Створюйте нові нотатки щодня за допомогою макета на основі календаря',
    tableView: 'Табличний вигляд',
    tableViewDescription: 'Відображати нотатки та файли поточної теми в табличному макеті',
    newNoteDefaults: 'Значення за замовчуванням для нових нотаток',
    noteType: 'Тип нотатки',
    selectDefaultNoteType: 'Виберіть тип нотатки за замовчуванням',
    titleFormat: 'Формат назви',
    selectTitleFormat: 'Виберіть формат назви нотатки',
    customFormatPlaceholder: 'напр. YYYY-MM-DD',
    preview: 'Попередній перегляд: ',
    useBracketsToEscape: '. Використовуйте ',
    toEscapeFormatting: ' для екранування форматування.',
    protected: 'Захищено',
    modified: 'Змінено',
    now: 'Зараз',
    editingDisabled: 'Редагування вимкнено',
    trashed: 'У кошику',
    archived: 'Архівовано',
    files: 'Файли',
    starred: 'Позначені',
    fileBackedUpLocally: 'Файл має локальну резервну копію',
    conflictedCopy: 'Конфліктна копія',
    allFiles: 'Усі файли',
    noFolder: 'Без теки',
    folderNamePlaceholder: 'Назва теки',
    createNewFolder: 'Створити нову теку',
    newFolder: 'Нова тека',
    currentStreak: 'Поточна серія',
    dayWithCount_one: 'День',
    dayWithCount_few: 'Дні',
    dayWithCount_many: 'Днів',
    dayWithCount_other: 'Дня',
  },
  auth: {
    unableToComputePrivateUsername: 'Не вдалося обчислити приватне ім’я користувача.',
    advancedOptions: 'Додаткові параметри',
    privateUsernameMode: 'Режим приватного імені користувача',
    username: 'Ім’я користувача',
    useStrictSignIn: 'Використовувати суворий вхід',
    useRecoveryCode: 'Використати код відновлення',
    recoveryCode: 'Код відновлення',
    deleteLocalDataTitle: 'Видалити локальні дані?',
    noMergeWarning:
      'Ви вибрали не об’єднувати свої локальні дані. Якщо ви продовжите, ваші локальні нотатки та теми будуть остаточно видалені та замінені даними з вашого облікового запису. Цю дію не можна скасувати.',
    noMergeConfirmQuestion: 'Ви впевнені, що хочете продовжити без об’єднання?',
    deleteLocalDataAndContinue: 'Видалити локальні дані та продовжити',
    passwordResetWarningPart1: 'Оскільки ваші нотатки зашифровано за допомогою вашого пароля,',
    passwordResetWarningHighlight: 'Standard Red Notes не має можливості скидання пароля',
    passwordResetWarningPart2: '. Якщо ви забудете свій пароль, ви назавжди втратите доступ до своїх даних.',
    confirmPassword: 'Підтвердьте пароль',
    creatingAccount: 'Створення облікового запису...',
    createAccountAndSignIn: 'Створити обліковий запис і ввійти',
    staySignedIn: 'Залишатися у системі',
    goBack: 'Назад',
    humanVerification: 'Перевірка на людину',
    confirmPasswordTitle: 'Підтвердьте пароль',
    createAccount: 'Створити обліковий запис',
    workspaceNameOptional: 'Назва робочої області (необов’язково)',
    generalAccountMenuLabel: 'Загальне меню облікового запису',
    signedInAs: 'Ви ввійшли як:',
    syncing: 'Синхронізація...',
    lastSynced: 'Остання синхронізація:',
    offlineSignInPrompt:
      'Ви офлайн. Увійдіть, щоб синхронізувати нотатки та налаштування на всіх ваших пристроях і ввімкнути наскрізне шифрування.',
    offline: 'Офлайн',
    accountSettings: 'Налаштування облікового запису',
    createFreeAccount: 'Створити безкоштовний обліковий запис',
    documentation: 'Документація',
    keyboardShortcuts: 'Комбінації клавіш',
    commandPalette: 'Палітра команд',
    signOutWorkspace: 'Вийти з робочої області',
    mergeLocalData: 'Об’єднати локальні дані ({{count}} нотаток і тем)',
    mergeLocalDataTooltip:
      'Якщо не позначено, ваші локальні нотатки та теми будуть остаточно видалені та замінені даними з вашого облікового запису.',
    homeServerNotRunning:
      'Домашній сервер не запущено. Будь ласка, відкрийте налаштування та вкладку домашнього сервера, щоб запустити його.',
    serverDefault: 'За замовчуванням',
    serverCustom: 'Власний',
    serverHomeServer: 'Домашній сервер',
    syncServer: 'Сервер синхронізації',
    signingIn: 'Вхід...',
    syncUnreachable: 'Синхронізація недоступна',
    syncUnreachableMessage: 'Хм... схоже, ми не можемо синхронізувати ваш обліковий запис. Причина: {{reason}}',
    workspaceSwitcherMenuLabel: 'Меню перемикання робочих областей',
    signOutAllWorkspacesConfirm: 'Ви впевнені, що хочете вийти з усіх робочих областей на цьому пристрої?',
    signOutAll: 'Вийти з усіх',
    addAnotherWorkspace: 'Додати ще одну робочу область',
    signOutAllWorkspaces: 'Вийти з усіх робочих областей',
    deleteAccountTitle: 'Видалити обліковий запис?',
    deleteMyAccountForGood: 'Видалити мій обліковий запис назавжди',
    dataNotBackedUp: 'Дані не мають резервної копії',
    signInOrRegisterToSync:
      'Увійдіть або зареєструйтеся, щоб синхронізувати ваші нотатки на інших пристроях із наскрізним шифруванням.',
    openAccountMenu: 'Відкрити меню облікового запису',
    ignoreWarning: 'Ігнорувати попередження',
    waitingForSecurityKey: 'Очікування апаратного ключа безпеки...',
    authenticationSuccessful: 'Автентифікацію успішно виконано!',
    insertSecurityKeyPrompt: 'Вставте ваш апаратний ключ безпеки, потім натисніть кнопку нижче для автентифікації.',
    authenticate: 'Автентифікувати',
  },
  search: {
    placeholder: 'Пошук...',
    protectedContents: 'Захищений вміст',
    archived: 'Архівовані',
    trashed: 'У кошику',
    aiUnavailable: 'Перевпорядкування за допомогою ШІ недоступне або не повернуло результату.',
    aiUnavailableTooltip: 'Контекстний пошук за допомогою ШІ недоступний.',
    aiTypeQueryFirst: 'Спочатку введіть пошуковий запит.',
    aiTooltip:
      'Перевпорядкуйте найкращі результати за семантичною релевантністю за допомогою налаштованого постачальника ШІ. ' +
      'Надсилає постачальнику заголовки та короткі фрагменти цих кандидатів, а також ваш запит.',
    aiSearchWithAi: 'Шукати за допомогою ШІ',
    aiRanking: 'Ранжування…',
    aiRankedByRelevance: 'Ранжовано за релевантністю ШІ',
    aiPrivacyNotice:
      'Надсилає заголовки та фрагменти найкращих результатів і ваш запит вашому постачальнику ШІ. Хмарні постачальники побачать ' +
      'їх — локальна модель зберігає це на пристрої.',
    advancedFilters: 'Розширені фільтри пошуку',
    filters: 'Фільтри',
    noteTypeAny: 'Будь-який тип',
    noteTypePlainText: 'Звичайний текст',
    noteTypeRichText: 'Форматований текст',
    noteTypeSuper: 'Super',
    noteTypeMarkdown: 'Markdown',
    noteTypeCode: 'Код',
    noteTypeTask: 'Завдання',
    noteTypeSpreadsheet: 'Електронна таблиця',
    flagProtected: 'Захищені',
    flagPinned: 'Закріплені',
    flagArchived: 'Архівовані',
    flagStarred: 'Позначені',
    flagTrashed: 'У кошику',
    topicsLabel: 'Теми (через кому)',
    topicsPlaceholder: 'робота, особисте',
    noteTypeLabel: 'Тип нотатки',
    searchInLabel: 'Шукати в',
    searchInTitleAndContent: 'Назва та вміст',
    modifiedWithinLabel: 'Змінено протягом',
    datePreset: 'Останні {{label}}',
    createdAfterLabel: 'Створено після',
    createdBeforeLabel: 'Створено до',
    updatedAfterLabel: 'Оновлено після',
    updatedBeforeLabel: 'Оновлено до',
    statusLabel: 'Статус',
    hasAttachments: 'Має вкладення',
    caseSensitive: 'З урахуванням регістру',
    clearAllFilters: 'Очистити всі фільтри',
  },
  sharing: {
    vaultSelectionMenu: 'Меню вибору сховища',
    vaultOptionsMenu: 'Меню параметрів сховища',
    vaultOptions: 'Параметри сховища',
    noVaultsFound: 'Сховищ не знайдено',
    moveToVault: 'Перемістити до сховища',
    moveOutOfVault: 'Перемістити з {{name}}',
    vaultsFallbackName: 'сховища',
    editVault: 'Редагувати сховище',
    lockVault: 'Заблокувати сховище',
    unlockVault: 'Розблокувати сховище',
    openVaultSettings: 'Відкрити налаштування сховища',
    selectionModeMultiple: 'Кілька',
    selectionModeOne: 'Одне',
    lastEditedBy: 'Востаннє відредаговано',
    sharedBy: 'Поділився',
    sharedByContact: 'Поділився контакт',
    vaultName: 'Назва сховища',
    sharedInVault: 'Спільний доступ у сховищі',
    copiedToClipboard: 'Скопійовано до буфера обміну',
    failedToCopyToClipboard: 'Не вдалося скопіювати до буфера обміну',
    copyExampleToClipboard: 'Копіювати приклад до буфера обміну',
    copiedExclaim: 'Скопійовано!',
    shareUnavailableTitle: 'Спільний доступ недоступний',
    shareUnavailableMessage: 'Це посилання спільного доступу більше недоступне.',
    invalidLinkTitle: 'Недійсне посилання',
    invalidLinkMessage: 'Це посилання спільного доступу недійсне або відсутній ключ.',
    selfDestructTitle: 'Ця нотатка самознищується після перегляду',
    oneTimeViewConsumed:
      'Ви читаєте посилання одноразового перегляду. Тепер його використано, і його не можна відкрити знову',
    oneTimeViewExpiresClause_one: ', і повністю закінчується через {{count}} хвилину від першого відкриття',
    oneTimeViewExpiresClause_few: ', і повністю закінчується через {{count}} хвилини від першого відкриття',
    oneTimeViewExpiresClause_many: ', і повністю закінчується через {{count}} хвилин від першого відкриття',
    oneTimeViewExpiresClause_other: ', і повністю закінчується через {{count}} хвилини від першого відкриття',
    linkExpires_one: 'Це посилання закінчується через {{count}} хвилину після першого відкриття.',
    linkExpires_few: 'Це посилання закінчується через {{count}} хвилини після першого відкриття.',
    linkExpires_many: 'Це посилання закінчується через {{count}} хвилин після першого відкриття.',
    linkExpires_other: 'Це посилання закінчується через {{count}} хвилини після першого відкриття.',
    untitled: 'Без назви',
    tagHasNoNotes: 'У цієї теми немає нотаток.',
    publicReadOnlyFooter:
      'Це публічне посилання спільного доступу лише для читання. Вміст було розшифровано у вашому браузері.',
    confidentialWatermark: 'Конфіденційно · {{datetime}}',
    contentHiddenTitle: 'Вміст приховано',
    contentHiddenMessage: 'Поверніть фокус на це вікно, щоб переглянути спільний вміст.',
  },
}

export default uk
