import type { LocaleResource } from './en'

const uk: LocaleResource = {
  common: {
    save: 'Зберегти',
    cancel: 'Скасувати',
    delete: 'Видалити',
    confirm: 'Підтвердити',
    close: 'Закрити',
    edit: 'Редагувати',
    rename: 'Перейменувати',
    duplicate: 'Дублювати',
    remove: 'Прибрати',
    open: 'Відкрити',
    create: 'Створити',
    add: 'Додати',
    done: 'Готово',
    back: 'Назад',
    next: 'Далі',
    search: 'Пошук',
    clear: 'Очистити',
    loading: 'Завантаження…',
    copy: 'Копіювати',
    copied: 'Скопійовано',
    download: 'Завантажити',
    upload: 'Вивантажити',
    export: 'Експорт',
    import: 'Імпорт',
    yes: 'Так',
    no: 'Ні',
    enabled: 'Увімкнено',
    disabled: 'Вимкнено',
    on: 'Увімк.',
    off: 'Вимк.',
    learnMore: 'Докладніше',
    options: 'Параметри',
    settings: 'Налаштування',
    preferences: 'Налаштування',
    help: 'Довідка',
    pin: 'Закріпити',
    unpin: 'Відкріпити',
    star: 'Позначити',
    unstar: 'Зняти позначку',
    archive: 'До архіву',
    unarchive: 'З архіву',
    restore: 'Відновити',
    moveToTrash: 'Перемістити в кошик',
    deletePermanently: 'Видалити назавжди',
    protect: 'Захистити',
    unprotect: 'Зняти захист',
  },
  navigation: {
    notes: 'Нотатки',
    allNotes: 'Усі нотатки',
    files: 'Файли',
    starred: 'Позначені',
    archived: 'Архів',
    trash: 'Кошик',
    untagged: 'Без теми',
    conflicts: 'Конфлікти',
    views: 'Подання',
    smartViews: 'Розумні подання',
    tags: 'Теми',
    folders: 'Теки',
    favorites: 'Вибране',
    dashboard: 'Панель',
    createNewNote: 'Створити нову нотатку',
    createNewTag: 'Створити нову тему',
    createNewFolder: 'Створити нову теку',
    createNewSmartView: 'Створити нове розумне подання',
    searchTags: 'Пошук тем…',
    noTagsFound: 'Тем не знайдено. Спробуйте інший запит.',
    noSmartViewsFound: 'Розумних подань не знайдено. Спробуйте інший запит.',
    collapseTagsPanel: 'Згорнути панель тем',
    expandTagsPanel: 'Розгорнути панель тем',
    goToItemsList: 'Перейти до списку елементів',
    goToAccountMenu: 'Перейти до меню облікового запису',
    openPreferences: 'Відкрити налаштування',
  },
  account: {
    account: 'Обліковий запис',
    signIn: 'Увійти',
    signOut: 'Вийти',
    signUp: 'Зареєструватися',
    register: 'Зареєструватися',
    you: 'Ви',
    encryptionOn: 'Наскрізне шифрування ввімкнено',
    notSignedIn: 'Ви не ввійшли',
    signInOrRegister: 'Увійдіть або зареєструйтеся, щоб синхронізувати нотатки',
    email: 'Ел. пошта',
    password: 'Пароль',
    confirmPassword: 'Підтвердьте пароль',
    syncNow: 'Синхронізувати',
    lastSynced: 'Остання синхронізація',
    importData: 'Імпорт',
    switchWorkspace: 'Змінити робочу область',
    lockApplication: 'Заблокувати застосунок',
    helpAndFeedback: 'Довідка та відгуки',
  },
  preferences: {
    title: 'Налаштування',
    general: 'Загальні',
    account: 'Обліковий запис',
    security: 'Безпека',
    appearance: 'Оформлення',
    backups: 'Резервні копії',
    listed: 'Listed',
    plugins: 'Плагіни',
    whatsNew: 'Що нового',
    helpAndFeedback: 'Довідка та відгуки',
    language: 'Мова',
    languageTitle: 'Мова',
    languageDescription:
      'Виберіть мову інтерфейсу застосунку. Для неперекладеного вмісту використовується англійська.',
    languageChanged: 'Мову оновлено',
    defaults: 'Значення за замовчуванням',
    tools: 'Інструменти',
    spellcheck: 'Перевірка орфографії',
    labs: 'Лабораторія',
  },
}

export default uk
