export * from './AuthMiddleware'
export * from './RequiredCrossServiceTokenMiddleware'
export * from './CorsOriginResolver'
export * from './FallbackController'
export * from './HealthCheckController'
export * from './RateLimitMiddleware'
export * from './IpAccessList'
export * from './ClientIp'
export * from './RateLimitMetrics'
export * from './SharedServerAccessKeyMiddleware'
export * from './TrustProxy'
export * from './SubscriptionTokenAuthMiddleware'
export * from './TokenAuthenticationMethod'
export * from './WebSocketAuthMiddleware'
export * from './v1/ActionsController'
export * from './v1/AdminController'
export * from './v1/MessagesController'
export * from './v1/AuthenticatorsController'
export * from './v1/AppPasswordsController'
export * from './v1/MeInviteLinksController'
export * from './v1/McpTokensController'
export * from './v1/CaldavTokensController'
export * from './v1/ReminderDeliveryController'
export * from './v1/WebhooksController'
export * from './v1/SharesController'
export * from './v1/DeadManSwitchesController'
export * from './v1/EmailRemindersController'
export * from './v1/TrustedDevicesController'
export * from './v1/PendingMfaApprovalsController'
export * from './v1/MagicLinkController'
export * from './v1/FilesController'
export * from './v1/InvoicesController'
export * from './v1/ItemsController'
export * from './v1/OfflineController'
export * from './v1/PaymentsController'
export * from './v1/RevisionsController'
export * from './v1/SessionsController'
export * from './v1/SharedVaultInvitesController'
export * from './v1/SharedVaultUsersController'
export * from './v1/SharedVaultsController'
export * from './v1/SubscriptionInvitesController'
export * from './v1/TokensController'
export * from './v1/UsersController'
export * from './v1/WebSocketsController'
export * from './v1/WorkflowsController'
export { createAdminEmailDeliveryRouter } from './v1/createAdminEmailDeliveryRouter'
// Standard Red Notes: these controllers were imported in bin/server.ts (standalone
// gateway) but omitted from this barrel, so they registered on the standalone
// gateway yet 404'd on the home-server bootstrap path (which imports the package
// root => `export * from './Controller'`). Keep the two lists in sync — see
// ControllerRegistration.spec.ts which now asserts equality in BOTH directions.
export * from './v1/AssistantController'
export * from './v1/OcrController'
export * from './v1/CollaborationController'
export * from './v1/WebController'
export * from './v1/IntegrationsController'
export * from './v1/UpdatesController'
export * from './v1/PluginsController'
export * from './v1/SyncWebSocketController'
export * from './v2/ActionsControllerV2'
export * from './v2/PaymentsControllerV2'
export * from './v2/RevisionsControllerV2'
