import { chmodSync, mkdtempSync, rmSync, symlinkSync, writeFileSync } from 'fs'
import { tmpdir } from 'os'
import path from 'path'

import { readDeploymentMarker, verifiedDeploymentIdentity } from './DeploymentIdentity'

describe('DeploymentIdentity', () => {
  let directory: string
  const fixtureUid = process.getuid?.() ?? 0

  beforeEach(() => {
    directory = mkdtempSync(path.join(tmpdir(), 'srn-deployment-identity-'))
  })

  afterEach(() => {
    rmSync(directory, { recursive: true, force: true })
  })

  const writeMarker = (content: string): string => {
    const markerPath = path.join(directory, 'deployment.json')
    writeFileSync(markerPath, content)
    chmodSync(markerPath, 0o444)

    return markerPath
  }

  it('reads the exact bounded marker generated by a release image', () => {
    const markerPath = writeMarker(
      JSON.stringify({
        revision: '0123456789abcdef0123456789abcdef01234567',
        version: 'v26.8.11-rc.1+linux.x64',
      }),
    )

    expect(readDeploymentMarker(markerPath, fixtureUid)).toEqual({
      revision: '0123456789abcdef0123456789abcdef01234567',
      version: 'v26.8.11-rc.1+linux.x64',
    })
  })

  it.each([
    ['missing marker', undefined],
    ['malformed JSON', '{'],
    ['extra fields', '{"revision":"","version":"","other":true}'],
    ['uppercase revision', '{"revision":"0123456789ABCDEF0123456789abcdef01234567","version":""}'],
    ['unsafe version', '{"revision":"0123456789abcdef0123456789abcdef01234567","version":"bad value"}'],
    ['oversized marker', `{"revision":"","version":"${'v'.repeat(513)}"}`],
  ])('rejects %s', (_case, content) => {
    const markerPath = content === undefined ? path.join(directory, 'missing.json') : writeMarker(content)

    expect(readDeploymentMarker(markerPath, fixtureUid)).toBeUndefined()
  })

  it('requires the runtime expectation and immutable marker to match atomically', () => {
    const marker = {
      revision: '0123456789abcdef0123456789abcdef01234567',
      version: 'v26.8.11',
    }

    expect(verifiedDeploymentIdentity(marker.revision, marker.version, marker)).toEqual(marker)
    expect(verifiedDeploymentIdentity('fedcba9876543210fedcba9876543210fedcba98', marker.version, marker)).toEqual({
      revision: null,
      version: null,
    })
    expect(verifiedDeploymentIdentity(marker.revision, 'v26.8.12', marker)).toEqual({
      revision: null,
      version: null,
    })
    expect(verifiedDeploymentIdentity(marker.revision, marker.version, undefined)).toEqual({
      revision: null,
      version: null,
    })
  })

  it('rejects writable marker files', () => {
    const markerPath = writeMarker('{"revision":"","version":""}')
    chmodSync(markerPath, 0o644)
    expect(readDeploymentMarker(markerPath, fixtureUid)).toBeUndefined()
  })

  it('rejects symbolic-link marker files', () => {
    if (process.platform === 'win32') {
      return
    }
    const targetPath = path.join(directory, 'target.json')
    writeFileSync(targetPath, '{"revision":"","version":""}')
    chmodSync(targetPath, 0o444)
    const linkPath = path.join(directory, 'link.json')
    symlinkSync(targetPath, linkPath)
    expect(readDeploymentMarker(linkPath, fixtureUid)).toBeUndefined()
  })

  it('uses root as the production trust owner by default', () => {
    if (fixtureUid === 0) {
      return
    }
    expect(readDeploymentMarker(writeMarker('{"revision":"","version":""}'))).toBeUndefined()
  })

  it('keeps the empty local-source mode anonymous', () => {
    expect(verifiedDeploymentIdentity(undefined, undefined, undefined)).toEqual({ revision: null, version: null })
    expect(verifiedDeploymentIdentity('', '', { revision: null, version: null })).toEqual({
      revision: null,
      version: null,
    })
  })
})
